JIT: Remove remaining SVE references from emitarm64.cpp
dotnet/runtime pull request #100100
Opened 2024-03-21 19:59 UTC by amanasifkhalid

This changes finishes transitioning SVE-specific code from `emitarm64.cpp` to `emitarm64sve.cpp` by splitting out SVE cases in `emitInsSanityCheck`, `emitDispInsHelp`, and `getInsExecutionCharacteristics`. A quick search for `IF_SVE_*` or `INS_sve_*` in `emitarm64.cpp` yields no results.

cc @dotnet/arm64-contrib this will probably conflict with #100081 and #100078; I'd rather merge this first.

2024-03-22 10:59 UTC, a74nh approved these changes
Changes in `emitarm64.cpp` are too big for github to show a diff!

I'm going to assume the code is an exact copy/paste with the only diffs being the start and end of the functions.

Reviewing the changed parts, LGTM.

2024-03-22 11:01 UTC, a74nh commented
Looks like the CI got stuck before scheduling the main block of tests. (Same thing happened to one of my PRs)

2024-03-22 15:13 UTC, amanasifkhalid commented
> I'm going to assume the code is an exact copy/paste with the only diffs being the start and end of the functions.

That's correct. Some of the SVE method signatures don't match their non-SVE counterparts exactly, though I did this for the sake of convenience/avoiding code duplication. For example, `getInsSveExecutionCharacteristics` takes a reference to the `insExecutionCharacteristics` struct already created in `getInsExecutionCharacteristics` so that we don't have to re-initialize all of its fields. Other than that, everything else was just copying and pasting.

> Looks like the CI got stuck before scheduling the main block of tests. (Same thing happened to one of my PRs)

Yeah, looks like I have some merge conflicts to resolve (sorry for pinging you prematurely). At this rate, I'll let my other cleanup PRs go first, and update here when this is ready.

2024-03-22 16:18 UTC, kunalspathak requested changes
Changes looks good. One minor change suggested.

2024-03-22 16:18 UTC, kunalspathak commented on src/coreclr/jit/emit.h
> +    void getInsSveExecutionCharacteristics(instrDesc* id, insExecutionCharacteristics& result);
can you move this in `emitarm64.h` file?

2024-03-22 16:18 UTC, kunalspathak commented on src/coreclr/jit/emit.h
> +    void emitInsSveSanityCheck(instrDesc* id);
and this one too?

2024-03-22 16:59 UTC, amanasifkhalid commented on src/coreclr/jit/emit.h
> +    void emitInsSveSanityCheck(instrDesc* id);
Sure thing

2024-03-25 18:00 UTC, kunalspathak approved these changes
LGTM

2024-03-25 21:49 UTC, amanasifkhalid commented
[No diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=617094&view=ms.vss-build-web.run-extensions-tab) (or TP impact).

2024-03-25 21:49 UTC, merged