Enable control flow guard for mono on windows
dotnet/runtime pull request #101293
Opened 2024-04-19 14:18 UTC by steveisok

Resolves binskim warnings for the runtime and aot compilers on windows.

2024-04-19 15:00 UTC, lewing approved these changes

2024-04-19 15:15 UTC, lambdageek approved these changes

2024-04-19 16:23 UTC, jkotas commented on src/mono/CMakeLists.txt
>      add_compile_options($<$<COMPILE_LANGUAGE:C,CXX>:/GF>) # enable string pooling
Nit: Control flow guard is not an optimization. I would enable it for all build flavors, not just for Release.

2024-04-20 00:33 UTC, jkotas approved these changes

2024-04-20 00:35 UTC, jkotas requested changes
Build breaks:
```
2024-04-19T19:57:55.6709922Z   MASM : fatal error A1000:cannot open file : $<0:/GUARD:cf
2024-04-19T19:57:55.6712646Z   [24/359] Building C object mono\eglib\CMakeFiles\eglib_objects.dir\D_\a\_work\1\s\src\native\minipal\utf8.c.obj
2024-04-19T19:57:55.8142203Z   cl : Command line warning D9024 : unrecognized source file type '$<1:/GUARD:cf', object file assumed
2024-04-19T19:57:55.8145990Z   cl : Command line warning D9027 : source file '$<1:/GUARD:cf' ignored
```

2024-04-20 15:43 UTC, akoeplinger commented on src/mono/CMakeLists.txt
> +  append("/guard:cf" CMAKE_C_FLAGS CMAKE_CXX_FLAGS)          # Enable control flow guard
the reason why it didn't work was because you were missing the closing `>`, please change it back.

2024-04-20 16:35 UTC, jkotas approved these changes

2024-04-22 13:55 UTC, steveisok commented
/ba-g The failure is similar to https://github.com/dotnet/runtime/issues/98578 except it's not appearing in the console log and so BA can't capture and relate the failure.

2024-04-22 13:56 UTC, merged