[release/6.0-staging] Allow setting ZipArchiveEntry general-purpose flag bits
dotnet/runtime pull request #102096
Opened 2024-05-10 18:27 UTC by carlossanlop

Backport of #98278 to release/6.0-staging

/cc @carlossanlop @edwardneal

## Customer Impact

- [ ] Customer reported
- [ ] Found internally

## Regression

- [ ] Yes
- [ ] No

## Testing

## Risk

2024-05-11 14:46 UTC, edwardneal requested changes
Thanks @carlossanlop. .NET 6.0 doesn't have the `ZipArchiveEntry.Comment` property, which complicates the backport slightly. I've added a change which should hopefully allow the test to keep on testing the specification behaviour regardless of this.

The simpler alternative is just to remove the reference to `entry.Comment` on line 39 of ReflectionTests.cs. It depends whether we need to test for behaviour when it's in the spec, but not in the public API surface.

2024-05-11 14:46 UTC, edwardneal commented on src/libraries/System.IO.Packaging/tests/ReflectionTests.cs
> +            foreach (ZipArchiveEntry entry in archive.Entries)
```suggestion
            FieldInfo archiveEncodingFieldInfo = typeof(ZipArchive).GetField("_entryNameAndCommentEncoding", BindingFlags.Instance | BindingFlags.NonPublic);
            System.Text.Encoding archiveEncoding = (archiveEncodingFieldInfo.GetValue(archive) as System.Text.Encoding?) ?? System.Text.Encoding.UTF8;
            
            foreach (ZipArchiveEntry entry in archive.Entries)
```

2024-05-11 14:46 UTC, edwardneal commented on src/libraries/System.IO.Packaging/tests/ReflectionTests.cs
> +                CheckCharacters(entry.Comment); // Unavailable in .NET Framework
```suggestion
                fieldInfo = typeof(ZipArchiveEntry).GetField("_fileComment", BindingFlags.Instance | BindingFlags.NonPublic);
                byte[]? commentBytes = (byte[]?)fieldInfo.GetValue(archiveEntry);
                
                CheckCharacters(archiveEncoding.GetString(commentBytes)); // Unavailable in .NET Framework
```

2024-05-14 05:10 UTC, carlossanlop commented on src/libraries/System.IO.Packaging/tests/ReflectionTests.cs
> +            System.Text.Encoding archiveEncoding = (archiveEncodingFieldInfo.GetValue(archive) as System.Text.Encoding?) ?? System.Text.Encoding.UTF8;
```suggestion
            System.Text.Encoding archiveEncoding = (archiveEncodingFieldInfo.GetValue(archive) as System.Text.Encoding) ?? System.Text.Encoding.UTF8;
```

2024-05-14 05:11 UTC, carlossanlop commented on src/libraries/System.IO.Packaging/tests/ReflectionTests.cs
> +                byte[]? commentBytes = (byte[]?)fieldInfo.GetValue(archiveEntry);
```suggestion
                byte[]? commentBytes = (byte[]?)fieldInfo.GetValue(entry);
```

2024-05-15 18:38 UTC, edwardneal commented
Thanks @carlossanlop - I see what you mean about the variable names and test errors. Apologies for those!

The test errors appear to be because the general purpose bit flag has the Unicode encoding bit (bit 11) set in the general purpose bit flags. The test is simply to make sure the compression levels roundtrip, so arguably this could be masked away and the test would pass. I'll check the tests over the next few days and submit another review with corrections.

2024-05-15 19:44 UTC, edwardneal commented on src/libraries/System.IO.Packaging/tests/ReflectionTests.cs
> +            FieldInfo archiveEncodingFieldInfo = typeof(ZipArchive).GetField("_entryNameAndCommentEncoding", BindingFlags.Instance | BindingFlags.NonPublic);
```suggestion
            FieldInfo archiveEncodingFieldInfo = typeof(ZipArchive).GetField("_entryNameEncoding", BindingFlags.Instance | BindingFlags.NonPublic);
```

2024-05-15 20:12 UTC, edwardneal reviewed
Finding the cause took less time than I thought.

By default, .NET 6.0 creates the ZipArchive with UTF8 encoding, which eventually feeds through to setting bit 11 in the general purpose bitflag for each archive entry. PR #87883 corrects this for .NET 8.0, and hasn't been backported to .NET 6.0 - so the values of the general purpose bit flags for a ZIP archive entry will be different between .NET 6.0 and .NET 8.0.

The purpose of the `Roundtrip_Compression_Option` test only requires us to validate bits 1 & 2, so I've just decided to mask the other bits out. The exception should never be triggered in the .NET 8.0 test because we don't create any files which need the extended encoding support, but I can update it to keep it in sync with the .NET 6.0 test if needed.

The other two review comments are just the result of me checking the tests in Visual Studio rather than eyeballing the code in GitHub...

2024-05-29 02:36 UTC, carlossanlop commented
@ViktorHofer @ericstj can I get a review and a sign-off for this servicing fix, please?

2024-05-31 20:56 UTC, carlossanlop commented
Closing while we get clarity on whether this bug's impact is severe enough to justify a backport.

2024-05-31 20:56 UTC, closed without merging