Fix 2 issues when triggering a garbage collection via EventPipe
dotnet/runtime pull request #102612
Opened 2024-05-23 15:36 UTC by chrisnas

Fix the following issues:
- https://github.com/dotnet/runtime/issues/99487: avoid double GC
- https://github.com/dotnet/runtime/issues/102572: handle client sequence number

2024-06-17 13:27 UTC, tommcdon commented
@noahfalk @brianrob ptal

2024-06-17 21:51 UTC, brianrob commented
Thanks @chrisnas!  One question - can you also test this with ETW?  I suspect that the ETW runtime is going to set `FilterData` differently.  I'll also have to defer to @noahfalk on the EventPipe specific file.

2024-06-24 16:37 UTC, chrisnas commented
> Thanks @chrisnas! One question - can you also test this with ETW? I suspect that the ETW runtime is going to set `FilterData` differently. 

I did not try @brianrob...
Do you know the command line I should use with perfview?

2024-06-24 22:42 UTC, noahfalk requested changes
I'm happy to take a PR to fix this, but we need to modify the approach. Suggestions inline. Thanks!

2024-06-24 22:42 UTC, noahfalk commented on src/native/eventpipe/ep.c
> +			provider_callback_data.enabled = false;
Lets not modify enabled here. EventPipe is following a convention established by ETW. Modifying when we emit the PROVIDER_ENABLED control code makes ETW/EventPipe behave differently which makes it more difficult for anyone to write logic in a provider callback that works correctly for both.

2024-08-12 20:34 UTC, tommcdon commented
Hi @chrisnas! I am moving this PR to "draft" mode - please let us know if you plan on addressing feedback in this PR.

2024-08-13 07:13 UTC, chrisnas commented
> Hi @chrisnas! I am moving this PR to "draft" mode - please let us know if you plan on addressing feedback in this PR.

Sorry for the delay @tommcdon!
It's good to move it to draft because it seems that I underestimate the impact of the change for ETW.
When @noahfalk will have time, I will need to validate what should be done (especially defining the convention of exchanges between a tool and the runtime)

2024-09-12 09:03 UTC, closed without merging