Don't trim members called by TypeDescriptor's use of reflection
dotnet/runtime pull request #102780
Opened 2024-05-28 20:36 UTC by steveharter

[verifying]

2024-06-11 05:18 UTC, MichalStrehovsky requested changes
This doesn't look like the right fix. https://github.com/dotnet/runtime/issues/102244#issuecomment-2138184386 and the subsequent discussion discuss why.

I think this should use ILLink.LibraryBuild file like the original issue was suggesting so that these get preserved when we build the repo. After repo build it can be trimmed like anything else. ILLink.LibraryBuild is designed for these cases.

These DynamicDependency will keep things unconditionally in trimmed apps even if nobody uses TypeDescriptor/Json.NET/etc. It's a global fix for a local problem. It will regress the size for everyone, including the well behaved apps that don't use trim unsafe code this tries to fix. Everything that could need this should already be marked as trim unsafe. We don't need trim unsafe code to work in trimmed apps, it is okay and expected that trim unsafe code will be broken after trimming. It is the responsibility of whoever is turning on trimming on trim unsafe code to author XML descriptors if they wish to take the hard path.

> The `TypeDescriptor` reflection-based model and the XML and Json.NET serializers use these conventions.

These are also trim unsafe and not expected to work after trimming. The issue this PR tries to address is a drop in the bucket, there are more fundamental trimming problems with these serializers.

2024-06-11 15:43 UTC, steveharter commented
> This doesn't look like the right fix. https://github.com/dotnet/runtime/issues/102244#issuecomment-2138184386 and the subsequent discussion discuss why.This doesn't look like the right fix. https://github.com/dotnet/runtime/issues/102244#issuecomment-2138184386 and the subsequent discussion discuss why.

I assume the change requested here is to move the DynamicDependency from source to XML like this:
```xml
    <type fullname="System.Data.DataSet">
      <method signature="System.Void .ctor()">
        <attribute fullname="System.Diagnostics.CodeAnalysis.DynamicDependencyAttribute">
          <argument>ResetRelations</argument>
        </attribute>
```

however, when I do that it appears trimming already occurred, meaning in the example above I'll get this error when building:
```
C:\git\ComponentModel\src\libraries\System.Data.Common\src\System\Data\DataSet.cs(47,9): error IL2037: System.Data.DataSet.DataSet(): No members were resolved for 'ResetRelations' on type 'System.Data.DataSet'. [C:\git\ComponentModel\src\libraries\sfx.proj]
```

2024-06-11 15:59 UTC, jkotas commented
> I assume the change requested here is to move the DynamicDependency from source to XML like this:

Yes, it should be in `ILLink.Descriptors.LibraryBuild.xml`.

> however, when I do that it appears trimming already occurred, meaning in the example above I'll get this error when building:

I am not sure where this error is coming from. Could you please apply the change so that we can see it?

2024-06-11 16:03 UTC, steveharter commented
> Yes, it should be in ILLink.Descriptors.LibraryBuild.xml.

I saw that right after I posted; I was using the wrong xml file. I added `src\libraries\System.Data.Common\src\ILLink` which is working.

2024-06-12 04:47 UTC, MichalStrehovsky approved these changes
I'm not reviewing whether this list is complete, but the approach looks good to me! Thanks!

2024-06-12 04:47 UTC, MichalStrehovsky commented on src/libraries/System.Data.Common/src/ILLink/ILLink.Descriptors.LibraryBuild.xml
> +  <assembly fullname="System.Data.Common, PublicKeyToken=b03f5f7f11d50a3a">
Nit: we don't put the public key token in any of our descriptor files.

```suggestion
  <assembly fullname="System.Data.Common">
```

2024-06-12 17:46 UTC, merged

2024-06-12 18:13 UTC, steveharter commented
This should be considered for servicing one verified.

2024-06-12 20:15 UTC, SamMonoRT commented
@roji @AndriySvyryd fyi --