Use LTO for linux as well
dotnet/runtime pull request #103058
Opened 2024-06-05 00:49 UTC by kunalspathak

2024-06-05 12:54 UTC, kunalspathak commented
Expected [TP diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=697803&view=ms.vss-build-web.run-extensions-tab) :)

![image](https://github.com/dotnet/runtime/assets/12488060/457f6f3a-ffef-4626-b96d-807b21722256)

2024-06-05 16:01 UTC, a74nh approved these changes
LGTM

2024-06-05 19:15 UTC, KennethHoff commented
> Seeing the expected [TP diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=697803&view=ms.vss-build-web.run-extensions-tab) :)
> 
> ![image](https://private-user-images.githubusercontent.com/12488060/336844009-457f6f3a-ffef-4626-b96d-807b21722256.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2MTQ5NjksIm5iZiI6MTcxNzYxNDY2OSwicGF0aCI6Ii8xMjQ4ODA2MC8zMzY4NDQwMDktNDU3ZjZmM2EtZmZlZi00NjI2LWI5NmQtODA3YjIxNzIyMjU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA1VDE5MTEwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlMDk5YWNmMzY3MGU1MjZmYzQ2OWZiY2JlZjEzYWUyZGQ5Y2U0MTJiYTFhOTE1NjBkYmRmNjJiOTExZjkxZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hK3vNlkD8LZL5a8i0tm4-_Yl3lhbsTkK3onGx7_XtCM)

What does this mean? I'm guessing it's not a 10-21% performance lift on Linux platforms.

2024-06-05 20:12 UTC, tannergooding commented
> What does this mean? I'm guessing it's not a 10-21% performance lift on Linux platforms.

This isn't for code that RyuJIT produces, but rather the code generated by `clang`/`gcc` for `RyuJIT` itself. So RyuJIT executes about 15-20% less instructions in order to compile IL to the target platform

2024-06-05 21:37 UTC, EgorBo commented
We might expect some improvements for performance as well since it also enables LTO for VM and GC

2024-06-10 17:30 UTC, jkoritzinsky commented on eng/native/configurecompiler.cmake
> +  add_link_options($<$<BOOL:$<TARGET_PROPERTY:INTERPROCEDURAL_OPTIMIZATION>>:LINKER:object_path_lto,lto.o>)
I'm not sure why CMake isn't parsing out the `LINKER:` correctly. Let's try passing the argument in a more straightforward manner.

```suggestion
  add_link_options($<$<BOOL:$<TARGET_PROPERTY:INTERPROCEDURAL_OPTIMIZATION>>:-Wl,object_path_lto,lto.o>)
```

2024-06-12 15:39 UTC, jkoritzinsky approved these changes
LGTM! Let's add a few comments though so we know why certain decisions were made/are required when we look at this in the future.

2024-06-12 15:39 UTC, jkoritzinsky commented on eng/native/configurecompiler.cmake
> +if(result AND NOT CLR_CMAKE_TARGET_APPLE)
Add a comment about why IPO is disabled on apple platforms?

2024-06-12 15:39 UTC, jkoritzinsky commented on src/coreclr/debug/runtimeinfo/CMakeLists.txt
> +  set_target_properties(cdac_data_descriptor  PROPERTIES INTERPROCEDURAL_OPTIMIZATION OFF)
Add a comment about why we're disabling IPO here?

2024-06-12 20:42 UTC, jkoritzinsky approved these changes

2024-06-13 04:21 UTC, MichalStrehovsky commented
If this is only adding `-flto=thin` like https://github.com/dotnet/runtime/pull/103058#discussion_r1628047207 says, does this interact with the `-flto` we set here?

https://github.com/dotnet/runtime/blob/bfb028b80f97ce853ff8c4ea0f98e596af5da0cc/src/coreclr/pgosupport.cmake#L57

> Seeing the expected [TP diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=697803&view=ms.vss-build-web.run-extensions-tab) :)

SPMI jobs seem to explicitly pass `/p:NoPgoOptimize=true` so the RyuJIT binary they use is not the RyuJIT binary we ship. Passing `NoPgoOptimize` would explicitly skip the `-flto` line in pgosupport.cmake since we currently condition LTO on PGO.

> runtime (Build linux-x64 Release NativeAOT) Failing after 39m

We should not use LTO on native AOT runtime binaries. LTO would place LLVM bitcode (instead of machine code) into the object files that we ship. Such object files can only be linked with a matching LLVM linker plugin. We don't have LLVM or LLVM version requirements for PublishAot.

2024-06-13 19:56 UTC, jkotas requested changes
>  does this interact with the -flto we set here?

@kunalspathak Could you please shed some light on this?

If we are specifying both `-flto` and `-flto=thin` on the command line when building the shipping binaries, there is a chance that `-flto=thin` is specified second, overrides the full `-flto` and we will see large scale perf regression.

It would be best to avoid specifying both `-flto` and `-flto=thin` on the command line when building the shipping binaries to avoid the problems with command line options overriding each other.

2024-06-14 05:02 UTC, kunalspathak commented
> @kunalspathak Could you please shed some light on this?

So my impression was that `LTO` was not passed at all even for shipped binaries, but the fact that it is passed in `pgosupport.cmake` confirms that we do use LTO for shipped binaries. 

> If we are specifying both `-flto` and `-flto=thin` on the command line when building the shipping binaries, there is a chance that `-flto=thin` is specified second, overrides the full `-flto` and we will see large scale perf regression.
> 
> It would be best to avoid specifying both `-flto` and `-flto=thin` on the command line when building the shipping binaries to avoid the problems with command line options overriding each other.

Agree that we should not pessimize the flags to get regression on shipped binaries.

> SPMI jobs seem to explicitly pass /p:NoPgoOptimize=true so the RyuJIT binary they use is not the RyuJIT binary we ship

So I am trying to understand how this is working currently. If I compare the TP difference with and without the `NoPgoOptimize` flag using superpmi, I don't see much improvements (see data below).  

```
[21:57:52] Total instructions executed by base: 34565002901
[21:57:52] Total instructions executed by diff: 34564841018
[21:57:52] Total instructions executed delta: -161883 (-0.00% of base)
```

However, with this PR, even when compiled with `NoPgoOptimize`, I see the improvements I shared earlier. So what should be the right model here? In long term, I just want to use `-flto` (and probably I should update this PR to do that) like the way we do in `pgosupport.cmake`. Thoughts?

2024-06-14 05:19 UTC, jkotas commented
> If I compare the TP difference with and without the NoPgoOptimize flag using superpmi, I don't see much improvements (see data below).

Do you see [packages with PGO optimization data being downloaded](https://github.com/dotnet/runtime/blob/5508f791239fd51b1624cc50d7c96e395a7d9fd5/eng/nativepgo.targets#L13-L27) and the data being successfully applied by the compiler?

2024-06-14 05:20 UTC, jkotas commented
> I just want to use -flto (and probably I should update this PR to do that) like the way we do in pgosupport.cmake. Thoughts?

Yes, that would make sense. If nothing else, it should reduce the gap between the shipping config and what you are measuring.

2024-06-14 05:40 UTC, jkoritzinsky commented
If you set the `CMAKE_CXX_LINK_OPTIONS_IPO` and `CMAKE_C_LINK_OPTIONS_IPO` variables to `"-flto"` when targeting Linux, we'll get behavior consistent with today and still be able to use the CMake IPO support (which is useful for being able to turn it on/off for select targets, not enabling it on platforms where it's not supported, and getting target-specific required options added for us).

2024-06-14 05:43 UTC, jkoritzinsky commented
https://gitlab.kitware.com/cmake/cmake/-/issues/23136 tracks being able to specify the flavor of LTO in CMake.

2026-05-22 00:25 UTC, closed without merging