Add support for Sve.ReverseBits() and Sve.Splice()
dotnet/runtime pull request #103567
Opened 2024-06-17 11:19 UTC by SwapnilGaikwad

Contribute towards https://github.com/dotnet/runtime/issues/99957.

This PR contains `Sve.Splice()`. It's the first one with an explicit mask and RMW semantics.

2024-06-17 11:19 UTC, SwapnilGaikwad commented
@a74nh @kunalspathak @dotnet/arm64-contrib @arch-arm64-sve

2024-06-17 13:05 UTC, SwapnilGaikwad commented
Some of the stress tests are failing when it fails read mask correctly that may lead to loading an Op2 using a mask incorrectly (with all zeros) or mask itself is incorrect. It seems like a known issue, happy to debug it further if you think otherwise.

<details>
<summary> Stress test results</summary>

```
===================Running default===================
------------------- {} -------------------
Passed test: _Sve_ro::JIT.HardwareIntrinsics.Arm._Sve._Sve.Program.SveSplice_float() : 16
Passed test: _Sve_ro::JIT.HardwareIntrinsics.Arm._Sve._Sve.Program.SveSplice_double() : 16
Passed test: _Sve_ro::JIT.HardwareIntrinsics.Arm._Sve._Sve.Program.SveSplice_sbyte() : 16
Passed test: _Sve_ro::JIT.HardwareIntrinsics.Arm._Sve._Sve.Program.SveSplice_short() : 16
Passed test: _Sve_ro::JIT.HardwareIntrinsics.Arm._Sve._Sve.Program.SveSplice_int() : 16
Passed test: _Sve_ro::JIT.HardwareIntrinsics.Arm._Sve._Sve.Program.SveSplice_long() : 16
Passed test: _Sve_ro::JIT.HardwareIntrinsics.Arm._Sve._Sve.Program.SveSplice_byte() : 16
Passed test: _Sve_ro::JIT.HardwareIntrinsics.Arm._Sve._Sve.Program.SveSplice_ushort() : 16
Passed test: _Sve_ro::JIT.HardwareIntrinsics.Arm._Sve._Sve.Program.SveSplice_uint() : 16
Passed test: _Sve_ro::JIT.HardwareIntrinsics.Arm._Sve._Sve.Program.SveSplice_ulong() : 16
===================Running jitstress===================
------------------- {'JitMinOpts': '1'} -------------------
------------------- {'JitStress': '1'} -------------------
Test failed:
..........................................
Sve.Splice<UInt32>(Vector<UInt32>, Vector<UInt32>, Vector<UInt32>): RunBasicScenario_Load failed:
   first: (579443, 991223, 48410, 7347)
  second: (772588, 159164, 581600, 551421)
    mask: (0, 1, 0, 0)
  result: (0, 0, 0, 0)
..........................................
System.Exception: One or more scenarios did not complete as expected.
   at JIT.HardwareIntrinsics.Arm._Sve._Sve.Program.SveSplice_uint() in /home/user/dotnet/runtime/artifacts/tests/coreclr/obj/linux.arm64.Checked/Managed/JIT/HardwareIntrinsics/Arm/Sve/Sve_ro/Sve_ro/gen/SveSplice.uint.cs:line 72
   at Program.<<Main>$>g__TestExecutor3554|0_3555(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&) in /home/user/dotnet/runtime/artifacts/tests/coreclr/obj/linux.arm64.Checked/Managed/JIT/HardwareIntrinsics/HardwareIntrinsics_Arm_ro/generated/XUnitWrapperGenerator/XUnitWrapperGenerator.XUnitWrapperGenerator/FullRunner.g.cs:line 88902
------------------- {'JitStress': '2'} -------------------
Test failed:
..........................................
Sve.Splice<Single>(Vector<Single>, Vector<Single>, Vector<Single>): RunBasicScenario_UnsafeRead failed:
   first: (0.7862908, 0.7901114, 0.28765604, 0.74686563)
  second: (0.5965609, 0.049051978, 0.79936534, 0.96844226)
    mask: (1E-45, 1E-45, 1E-45, 1E-45)
  result: (0.5965609, 0.049051978, 0.79936534, 0.96844226)
..........................................
System.Exception: One or more scenarios did not complete as expected.
   at JIT.HardwareIntrinsics.Arm._Sve._Sve.Program.SveSplice_float() in /home/user/dotnet/runtime/artifacts/tests/coreclr/obj/linux.arm64.Checked/Managed/JIT/HardwareIntrinsics/Arm/Sve/Sve_ro/Sve_ro/gen/SveSplice.float.cs:line 72
   at Program.<<Main>$>g__TestExecutor3546|0_3547(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&) in /home/user/dotnet/runtime/artifacts/tests/coreclr/obj/linux.arm64.Checked/Managed/JIT/HardwareIntrinsics/HardwareIntrinsics_Arm_ro/generated/XUnitWrapperGenerator/XUnitWrapperGenerator.XUnitWrapperGenerator/FullRunner.g.cs:line 88710
..........................................
Sve.Splice<Double>(Vector<Double>, Vector<Double>, Vector<Double>): RunBasicScenario_Load failed:
   first: (0.46858944778456424, 0.0999621186960985)
  second: (0.09344251435870388, 0.151148643963522)
    mask: (0, 0)
  result: (0, 0)
..........................................
System.Exception: One or more scenarios did not complete as expected.
   at JIT.HardwareIntrinsics.Arm._Sve._Sve.Program.SveSplice_double() in /home/user/dotnet/runtime/artifacts/tests/coreclr/obj/linux.arm64.Checked/Managed/JIT/HardwareIntrinsics/Arm/Sve/Sve_ro/Sve_ro/gen/SveSplice.double.cs:line 72
   at Program.<<Main>$>g__TestExecutor3547|0_3548(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&) in /home/user/dotnet/runtime/artifacts/tests/coreclr/obj/linux.arm64.Checked/Managed/JIT/HardwareIntrinsics/HardwareIntrinsics_Arm_ro/generated/XUnitWrapperGenerator/XUnitWrapperGenerator.XUnitWrapperGenerator/FullRunner.g.cs:line 88734
..........................................
Sve.Splice<SByte>(Vector<SByte>, Vector<SByte>, Vector<SByte>): RunBasicScenario_UnsafeRead failed:
   first: (3, 28, 25, 89, 47, 102, 1, 25, 6, 107, 6, 36, 113, 98, 83, 49)
  second: (27, 41, 103, 39, 38, 81, 26, 15, 22, 78, 64, 54, 80, 59, 31, 94)
    mask: (0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0)
  result: (27, 41, 103, 39, 38, 81, 26, 15, 22, 78, 64, 54, 80, 59, 31, 94)
..........................................
System.Exception: One or more scenarios did not complete as expected.
   at JIT.HardwareIntrinsics.Arm._Sve._Sve.Program.SveSplice_sbyte() in /home/user/dotnet/runtime/artifacts/tests/coreclr/obj/linux.arm64.Checked/Managed/JIT/HardwareIntrinsics/Arm/Sve/Sve_ro/Sve_ro/gen/SveSplice.sbyte.cs:line 72
   at Program.<<Main>$>g__TestExecutor3548|0_3549(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&) in /home/user/dotnet/runtime/artifacts/tests/coreclr/obj/linux.arm64.Checked/Managed/JIT/HardwareIntrinsics/HardwareIntrinsics_Arm_ro/generated/XUnitWrapperGenerator/XUnitWrapperGenerator.XUnitWrapperGenerator/FullRunner.g.cs:line 88758
..........................................
Sve.Splice<Int16>(Vector<Int16>, Vector<Int16>, Vector<Int16>): RunBasicScenario_Load failed:
   first: (22905, 27406, 1092, 27906, 8152, 12299, 26225, 7098)
  second: (6072, 1949, 24938, 3180, 11516, 6047, 31385, 5641)
    mask: (1, 1, 0, 0, 1, 1, 0, 0)
  result: (6072, 1949, 24938, 3180, 11516, 6047, 31385, 5641)
..........................................
System.Exception: One or more scenarios did not complete as expected.
   at JIT.HardwareIntrinsics.Arm._Sve._Sve.Program.SveSplice_short() in /home/user/dotnet/runtime/artifacts/tests/coreclr/obj/linux.arm64.Checked/Managed/JIT/HardwareIntrinsics/Arm/Sve/Sve_ro/Sve_ro/gen/SveSplice.short.cs:line 72
   at Program.<<Main>$>g__TestExecutor3549|0_3550(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&) in /home/user/dotnet/runtime/artifacts/tests/coreclr/obj/linux.arm64.Checked/Managed/JIT/HardwareIntrinsics/HardwareIntrinsics_Arm_ro/generated/XUnitWrapperGenerator/XUnitWrapperGenerator.XUnitWrapperGenerator/FullRunner.g.cs:line 88782
..........................................
Sve.Splice<UInt64>(Vector<UInt64>, Vector<UInt64>, Vector<UInt64>): RunBasicScenario_UnsafeRead failed:
   first: (1132024568253399371, 3418240130782517830)
  second: (16411807881777427699, 147021453806186895)
    mask: (1, 1)
  result: (16411807881777427699, 147021453806186895)
..........................................
System.Exception: One or more scenarios did not complete as expected.
   at JIT.HardwareIntrinsics.Arm._Sve._Sve.Program.SveSplice_ulong() in /home/user/dotnet/runtime/artifacts/tests/coreclr/obj/linux.arm64.Checked/Managed/JIT/HardwareIntrinsics/Arm/Sve/Sve_ro/Sve_ro/gen/SveSplice.ulong.cs:line 72
   at Program.<<Main>$>g__TestExecutor3555|0_3556(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&) in /home/user/dotnet/runtime/artifacts/tests/coreclr/obj/linux.arm64.Checked/Managed/JIT/HardwareIntrinsics/HardwareIntrinsics_Arm_ro/generated/XUnitWrapperGenerator/XUnitWrapperGenerator.XUnitWrapperGenerator/FullRunner.g.cs:line 88926
------------------- {'JitStress': '1', 'TieredCompilation': '1'} -------------------
------------------- {'JitStress': '2', 'TieredCompilation': '1'} -------------------
------------------- {'TailcallStres [...]

2024-06-17 18:22 UTC, kunalspathak requested changes
Just to confirm, changed related to `ReverseBits` are straight forward and just need an entry in `hwintrinsiclistarm64sve.h` table. The other changes are to support `Splice` whose `op2` is the preferred target, yes?

Probably worth sending a separate PR for `ReveseBits` and `Splice` because the logic on how they are handled are very different.

2024-06-21 10:47 UTC, SwapnilGaikwad commented
> Probably worth sending a separate PR for `ReveseBits`

Put ReverseBits in #103806

2024-06-21 15:41 UTC, SwapnilGaikwad commented on src/coreclr/jit/lsraarm64.cpp
> +        if ((isRMW || simdRegToSimdRegMove) && !HWIntrinsicInfo::IsExplicitMaskedOperation(intrin.id))
Added a comment.

2024-06-21 15:42 UTC, SwapnilGaikwad commented on src/coreclr/jit/lsraarm64.cpp
> +                tgtPrefUse = BuildUse(intrin.op2);
Just asserted that tgtPref is not set as one of them would only be set, cannot `assert(tgtPrefUse != nullptr);`

2024-06-21 15:43 UTC, SwapnilGaikwad commented on src/coreclr/jit/lsraarm64.cpp
> +            if (op2IsTarget)
Changed it to use `tgtPrefOp2`.

2024-06-21 15:48 UTC, SwapnilGaikwad commented on src/coreclr/jit/lsraarm64.cpp
> +                    srcCount += BuildDelayFreeUses(intrin.op1, intrin.op2, predMask);
I don't fully understand working of lsra here but I'll look into this for correctness.

2024-06-21 15:52 UTC, SwapnilGaikwad commented
Regarding using a constructive variant. Not sure how to mark explicit op2 and op3 as needing consecutive registers. The current intrinsics with consecutive registers have a tuple in a single op. Here we have two separate args in the API.

2024-06-21 16:00 UTC, kunalspathak commented
> Regarding using a constructive variant. Not sure how to mark explicit op2 and op3 as needing consecutive registers. The current intrinsics with consecutive registers have a tuple in a single op. Here we have two separate args in the API.

I might have to spend some time in figuring out how to make sure that when `op2` gets register `Zn`, force `op3` to get `Zn+1` given that they are 2 different operands. I think for simplicity, lets add just the destructive version of `SPLICE` and open an issue to add constructive version post .NET 9.

2024-06-24 12:26 UTC, SwapnilGaikwad commented on src/coreclr/jit/hwintrinsiccodegenarm64.cpp
> +                            if (targetReg != op2Reg)
Following the suggestion, switching to destructive variant only.

2024-06-24 12:27 UTC, SwapnilGaikwad commented on src/coreclr/jit/lsraarm64.cpp
> +                    srcCount += BuildDelayFreeUses(intrin.op1, intrin.op2, predMask);
You're right, op1 can't be delayed-free. Fix it now.

2024-06-24 13:07 UTC, kunalspathak commented
@SwapnilGaikwad - can you confirm if all the stress test passes with your recent change? Also, can you please share disassembly for one of the test? I will look deeply, but are we making sure that we are never generating constructive form?

2024-06-24 13:51 UTC, SwapnilGaikwad commented
> can you confirm if all the stress test passes with your recent change

Some of the stress tests failed as before. They are loading the mask incorrectly as all zeros that is then leading to a wrong results.

<details>
<summary> Stress test results </summary>

```

===================Running default===================
------------------- {} -------------------
Passed test: _Sve_ro::JIT.HardwareIntrinsics.Arm._Sve._Sve.Program.Sve_Splice_float() : 16
Passed test: _Sve_ro::JIT.HardwareIntrinsics.Arm._Sve._Sve.Program.Sve_Splice_double() : 16
Passed test: _Sve_ro::JIT.HardwareIntrinsics.Arm._Sve._Sve.Program.Sve_Splice_sbyte() : 16
Passed test: _Sve_ro::JIT.HardwareIntrinsics.Arm._Sve._Sve.Program.Sve_Splice_short() : 16
Passed test: _Sve_ro::JIT.HardwareIntrinsics.Arm._Sve._Sve.Program.Sve_Splice_int() : 16
Passed test: _Sve_ro::JIT.HardwareIntrinsics.Arm._Sve._Sve.Program.Sve_Splice_long() : 16
Passed test: _Sve_ro::JIT.HardwareIntrinsics.Arm._Sve._Sve.Program.Sve_Splice_byte() : 16
Passed test: _Sve_ro::JIT.HardwareIntrinsics.Arm._Sve._Sve.Program.Sve_Splice_ushort() : 16
Passed test: _Sve_ro::JIT.HardwareIntrinsics.Arm._Sve._Sve.Program.Sve_Splice_uint() : 16
Passed test: _Sve_ro::JIT.HardwareIntrinsics.Arm._Sve._Sve.Program.Sve_Splice_ulong() : 16
===================Running jitstress===================
------------------- {'JitMinOpts': '1'} -------------------
------------------- {'JitStress': '1'} -------------------
Test failed:
..........................................
Sve.Splice<Single>(Vector<Single>, Vector<Single>, Vector<Single>): RunBasicScenario_Load failed:
   first: (0.76844823, 0.28580046, 0.9643689, 0.004709583)
  second: (0.36862698, 0.30574182, 0.6652912, 0.6942193)
    mask: (0, 0, 0, 1E-45)
  result: (0, 0, 0, 0)
..........................................
System.Exception: One or more scenarios did not complete as expected.
   at JIT.HardwareIntrinsics.Arm._Sve._Sve.Program.Sve_Splice_float() in /home/swagai01/dotnet/runtime/artifacts/tests/coreclr/obj/linux.arm64.Checked/Managed/JIT/HardwareIntrinsics/Arm/Sve/Sve_ro/Sve_ro/gen/Sve.Splice.float.cs:line 72
   at Program.<<Main>$>g__TestExecutor3595|0_3596(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&) in /home/swagai01/dotnet/runtime/artifacts/tests/coreclr/obj/linux.arm64.Checked/Managed/JIT/HardwareIntrinsics/HardwareIntrinsics_Arm_ro/generated/XUnitWrapperGenerator/XUnitWrapperGenerator.XUnitWrapperGenerator/FullRunner.g.cs:line 89935
..........................................
Sve.Splice<Byte>(Vector<Byte>, Vector<Byte>, Vector<Byte>): RunBasicScenario_Load failed:
   first: (126, 179, 163, 251, 76, 9, 72, 180, 202, 244, 64, 207, 67, 85, 231, 85)
  second: (178, 20, 134, 117, 208, 17, 166, 182, 88, 186, 163, 136, 170, 7, 67, 50)
    mask: (1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1)
  result: (0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
..........................................
..........................................
Sve.Splice<Byte>(Vector<Byte>, Vector<Byte>, Vector<Byte>): ConditionalSelectScenario failed:
    mask: (255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255)
    left: (126, 179, 163, 251, 76, 9, 72, 180, 202, 244, 64, 207, 67, 85, 231, 85)
   right: (178, 20, 134, 117, 208, 17, 166, 182, 88, 186, 163, 136, 170, 7, 67, 50)
 falseOp: (126, 179, 163, 251, 76, 9, 72, 180, 202, 244, 64, 207, 67, 85, 231, 85)
  result: (178, 20, 134, 117, 208, 17, 166, 182, 88, 186, 163, 136, 170, 7, 67, 50)
..........................................
..........................................
Sve.Splice<Byte>(Vector<Byte>, Vector<Byte>, Vector<Byte>): ConditionalSelectScenario failed:
    mask: (255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255)
    left: (126, 179, 163, 251, 76, 9, 72, 180, 202, 244, 64, 207, 67, 85, 231, 85)
   right: (178, 20, 134, 117, 208, 17, 166, 182, 88, 186, 163, 136, 170, 7, 67, 50)
 falseOp: (0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
  result: (178, 20, 134, 117, 208, 17, 166, 182, 88, 186, 163, 136, 170, 7, 67, 50)
..........................................
System.Exception: One or more scenarios did not complete as expected.
   at JIT.HardwareIntrinsics.Arm._Sve._Sve.Program.Sve_Splice_byte() in /home/swagai01/dotnet/runtime/artifacts/tests/coreclr/obj/linux.arm64.Checked/Managed/JIT/HardwareIntrinsics/Arm/Sve/Sve_ro/Sve_ro/gen/Sve.Splice.byte.cs:line 72
   at Program.<<Main>$>g__TestExecutor3601|0_3602(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&) in /home/swagai01/dotnet/runtime/artifacts/tests/coreclr/obj/linux.arm64.Checked/Managed/JIT/HardwareIntrinsics/HardwareIntrinsics_Arm_ro/generated/XUnitWrapperGenerator/XUnitWrapperGenerator.XUnitWrapperGenerator/FullRunner.g.cs:line 90079
..........................................
Sve.Splice<UInt16>(Vector<UInt16>, Vector<UInt16>, Vector<UInt16>): RunBasicScenario_UnsafeRead failed:
   first: (49444, 34630, 11472, 42333, 39372, 61345, 61268, 44312)
  second: (29682, 39452, 60490, 55509, 39546, 7392, 45898, 52287)
    mask: (1, 1, 1, 1, 0, 0, 0, 0)
  result: (29682, 39452, 60490, 55509, 39546, 7392, 45898, 52287)
..........................................
System.Exception: One or more scenarios did not complete as expected.
   at JIT.HardwareIntrinsics.Arm._Sve._Sve.Program.Sve_Splice_ushort() in /home/swagai01/dotnet/runtime/artifacts/tests/coreclr/obj/linux.arm64.Checked/Managed/JIT/HardwareIntrinsics/Arm/Sve/Sve_ro/Sve_ro/gen/Sve.Splice.ushort.cs:line 72
   at Program.<<Main>$>g__TestExecutor3602|0_3603(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&) in /home/swagai01/dotnet/runtime/artifacts/tests/coreclr/obj/linux.arm64.Checked/Managed/JIT/HardwareIntrinsics/HardwareIntrinsics_Arm_ro/generated/XUnitWrapperGenerator/XUnitWrapperGenerator.XUnitWrapperGenerator/FullRunner.g.cs:line 90103
------------------- {'JitStress': '2'} -------------------
Test failed:
..........................................
Sve.Splice<SByte>(Vector<SByte>, Vector<SByte>, Vector<SByte>): RunBasicScenario_UnsafeRead failed:
   first: (100, 73, 124, 52, 58, 113, 5, 46, 114, 5, 37, 68, 27, 1, 93, 86)
  second: (12, 124, 56, 99, 99, 62, 127, 105, 35, 75, 46, 58, 71, 83, 36, 67)
    mask: (1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0)
  result: (12, 124, 56, 99, 99, 62, 127, 105, 35, 75, 46, 58, 71, 83, 36, 67)
..........................................
System.Exception: One or more scenarios did not complete as expected.
   at JIT.HardwareIntrinsics.Arm._Sve._Sve.Program.Sve_Splice_sbyte() in /home/swagai01/dotnet/runtime/artifacts/tests/coreclr/obj/linux.arm64.Checked/Managed/JIT/HardwareIntrinsics/Arm/Sve/Sve_ro/Sve_ro/gen/Sve.Splice.sbyte.cs:line 72
   at Program.<<Main>$>g__TestExecutor3597|0_3598(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&) in /home/swagai01/dotnet/runtime/artifacts/tests/coreclr/obj/linux.arm64.Checked/Managed/JIT/HardwareIntrinsics/HardwareIntrinsics_Arm_ro/generated/XUnitWrapperGenerator/XUnitWrapperGenerator.XUnitWrapperGenerator/FullRunner.g.cs:line 89983
..........................................
Sve.Splice<Byte>(Vector<Byte>, Vector<Byte>, Vector<Byte>): RunBasicScenario_UnsafeRead failed:
   first: (59, 60, 61, 105, 10, 128, 231, 150, 246, 225, 4, 178, 199, 110, 117, 237)
  second: (86, 147, 63, 50, 139, 53, 165, 110, 117, 75, 229, 253, 45, 21, 86, 87)
    mask: (0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0)
  result: (86, 147, 63, 50, 139, 53, 165, 110, 117, 75, 229, 253, 45, 21, 86, 87)
..........................................
..........................................
Sve.Splice<Byte>(Vector<Byte>, Vector<Byte>, Vector<Byte>): ConditionalSelectScenario failed:
    mask: (255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255)
    left: (59, 60, 61, 105, 10, 128, 231, 150, 246, 225, 4, 178, 199, 110, 117, 237)
   right: (86, 147, 63, 50, 139, 53, 165, 110, 117, 75, 229, 253, 45, 21, 86, 87)
 falseOp: ( [...]

2024-06-24 14:17 UTC, kunalspathak commented
> However, we don't have an explicit assert to ensure that we are emitting an instruction of group IF_SVE_CV_3B (destructively) and not IF_SVE_CV_3A (constructively).

Is it possible to add it?

2024-06-24 14:28 UTC, SwapnilGaikwad commented
> > However, we don't have an explicit assert to ensure that we are emitting an instruction of group IF_SVE_CV_3B (destructively) and not IF_SVE_CV_3A (constructively).
> 
> Is it possible to add it?

Well, we kind of do it indirectly. We emit a constructive variant when `sopt == INS_SCALABLE_OPTS_WITH_VECTOR_PAIR`, otherwise emit a destructive one.
[Here](https://github.com/dotnet/runtime/pull/103567/files#diff-45c9473f1b1d031652a13186a211c1aef1406a74f576d5f04e3a65766b0f5050R853), we don't pass sopt in `emitIns_R_R_R` that makes it `INS_SCALABLE_OPTS_NONE`. This ensures we emit a destructive variant.
Do you think this should suffice or we should have an additional check somewhere? 🤔

2024-06-24 15:00 UTC, kunalspathak commented
> Do you think this should suffice or we should have an additional check somewhere?

May be `unreached()` where we set the format `IF_SVE_CV_3A` should be good enough.

2024-06-24 15:04 UTC, kunalspathak commented
> > Do you think this should suffice or we should have an additional check somewhere?
> 
> May be `unreached()` where we set the format `IF_SVE_CV_3A` should be good enough.

Add a link to https://github.com/dotnet/runtime/issues/103850 in comment

2024-06-24 16:00 UTC, a74nh commented
> > Do you think this should suffice or we should have an additional check somewhere?
> 
> May be `unreached()` where we set the format `IF_SVE_CV_3A` should be good enough.

That would have to be inside the `emitIns_R_R_R()` which feels wrong. And it would break the codegen testing.

> [Here](https://github.com/dotnet/runtime/pull/103567/files#diff-45c9473f1b1d031652a13186a211c1aef1406a74f576d5f04e3a65766b0f5050R853), we don't pass sopt in `emitIns_R_R_R` that makes it `INS_SCALABLE_OPTS_NONE`. This ensures we emit a destructive variant.

In addition, all of this is done in common codegen code.

We could forcibly set `sopt` to `INS_SCALABLE_OPTS_NONE` in codegen. But then that would then force the use of the SpecialCodeGen flag, bypassing all the common code.

2024-06-24 17:05 UTC, kunalspathak commented
> That would have to be inside the `emitIns_R_R_R()` which feels wrong. 

It will be still inside the individual case like https://github.com/dotnet/runtime/blob/e1efa6b633d01c00ec019a8e222b2ebdfa593bcb/src/coreclr/jit/emitarm64sve.cpp#L3861C28-L3861C62 and not in common code path.

`INS_SCALABLE_OPTS_WITH_VECTOR_PAIR` is only used for 4 isntructions: `ext`, `splice`, `tbl`, `luti4`. For `tbl`, we can leave it as-is, `luti4` is SME/Sve2, which we are not implementing currently. That leaves us with `ext` and `splice` and both should support constructive form, but for now, we can assert that we are not producing that form currently.

> And it would break the codegen testing.

I am ok to comment out the relevant unit test, because we are not supporting it currently.

2024-06-24 17:06 UTC, kunalspathak commented
> It will be still inside the individual case like https://github.com/dotnet/runtime/blob/e1efa6b633d01c00ec019a8e222b2ebdfa593bcb/src/coreclr/jit/emitarm64sve.cpp#L3861C28-L3861C62 and not in common code path.

So perhaps something like `assert(sopt != INS_SCALABLE_OPTS_WITH_VECTOR_PAIR)` would work. And same assert will go in `ext`. cc: @TIHan

2024-06-25 10:59 UTC, SwapnilGaikwad commented
`jit-format` shows the changes to `src/coreclr/jit/gcencode.cpp` that are unrelated to the patch.

2024-06-25 12:57 UTC, kunalspathak approved these changes
LGTM

2024-06-25 15:47 UTC, merged