Arm64/SVE: Implemented `ReciprocalEstimate`, `ReciprocalExponent`, `ReciprocalSqrtEstimate`, `ReciprocalSqrtStep`, and `ReciprocalStep`
dotnet/runtime pull request #103673
Opened 2024-06-18 22:36 UTC by ebepho

Contributes to https://github.com/dotnet/runtime/issues/99957

Note: Currently `ReciprocalExponent` tests are not correctly written.

2024-06-18 23:18 UTC, kunalspathak commented
> Currently Blocked on ReciprocalExponent for testing

@a74nh - can you clarify this, if possible?

2024-06-19 00:51 UTC, kunalspathak reviewed
Changes looks good, apart from missing `LowMaskedOperation` flag. Let's wait for @a74nh to confirm the test failure.

2024-06-19 11:11 UTC, a74nh commented
> Currently Blocked on `ReciprocalExponent` for testing.

It's a little more complicated than raising to the power -1.
I'm not an fp expert, but easiest way I can see of doing this was via some bitwise manipulation.
This worked when I tried it:

```
        public static double RecipExpo(double op1)
        {
            ulong bits = (ulong)BitConverter.DoubleToUInt64Bits(op1);

            // Invert the exponent
            bits ^= 0x7FF0000000000000;
            // Zero the fraction
            bits &= 0xFFF0000000000000;

            return BitConverter.UInt64BitsToDouble(bits);
        }

        public static float RecipExpo(float op1)
        {
            uint bits = BitConverter.SingleToUInt32Bits(op1);

            // Invert the exponent
            bits ^= 0x7F800000;
            // Zero the fraction
            bits &= 0xFF800000;

            return BitConverter.UInt32BitsToSingle(bits);
        }
```

2024-06-19 17:47 UTC, kunalspathak commented on src/tests/Common/GenerateHWIntrinsicTests/GenerateHWIntrinsicTests_Arm.cs
> +    ("SveSimpleVecOpTest.template",      new Dictionary<string, string> { ["TestName"] = "Sve_ReciprocalExponent_float",                                                                           ["Is
The helper names need to change.

2024-06-20 04:36 UTC, kunalspathak approved these changes
LGTM. Thanks!

2024-06-20 04:43 UTC, kunalspathak commented on src/tests/Common/GenerateHWIntrinsicTests/GenerateHWIntrinsicTests_Arm.cs
> +    ("VecBinOpTest.template",             new Dictionary<string, string> { ["TestName"] = "ReciprocalStep_Vector64_Single",                                                                        ["Is
This and line below should be `FPReciprocalStepFused`. That is the reason CI tests are failing. https://dev.azure.com/dnceng-public/public/_build/results?buildId=713553&view=ms.vss-test-web.build-test-results-tab&runId=17847992&resultId=108403&paneView=debug

2024-06-20 04:45 UTC, kunalspathak requested changes
please fix the AdvSimd test

2024-06-21 06:07 UTC, kunalspathak requested changes
2 tests are still failing.

2024-06-21 06:07 UTC, kunalspathak commented on src/tests/Common/GenerateHWIntrinsicTests/GenerateHWIntrinsicTests_Arm.cs
> +    ("VecBinOpTest.template",             new Dictionary<string, string> { ["TestName"] = "ReciprocalSquareRootStep_Vector128_Single",                                                             ["Is
Same here - this should be `Helpers.FPReciprocalSqrtStepFused()`

2024-06-21 06:07 UTC, kunalspathak commented on src/tests/Common/GenerateHWIntrinsicTests/GenerateHWIntrinsicTests_Arm.cs
> +    ("VecBinOpTest.template",             new Dictionary<string, string> { ["TestName"] = "ReciprocalStep_Vector64_Single",                                                                        ["Is
This should be `Helpers.FPReciprocalSqrtStepFused()`

2024-06-21 23:41 UTC, kunalspathak approved these changes
LGTM

2024-06-21 23:41 UTC, kunalspathak commented
/ba-g timeout issues

2024-06-21 23:41 UTC, merged