Fix field accessor for RVA field
dotnet/runtime pull request #103705
Opened 2024-06-19 16:15 UTC by huoyaoyuan

Fixes #103207

2024-06-19 20:45 UTC, steveharter commented on src/libraries/System.Runtime/tests/System.Reflection.Tests/FieldInfoTests.cs
> +            // Roslyn uses SHA256 of raw data as data field name
Interesting; this is likely why the original RVA tests added with the fast field feature didn't fail.

2024-06-19 20:45 UTC, steveharter approved these changes
Thanks!

2024-06-19 20:47 UTC, steveharter requested changes
There is a test failure on macOS-12.7.2. Does Mono do things differently?
```
[FAIL] System.Reflection.Tests.FieldInfoTests.GetValueFromRvaField
System.NotSupportedException : This object cannot be invoked because no code was generated for it: '<PrivateImplementationDetails>.74F81FE167D99B4CB41D6D0CCDA82278CAEE9F3E2F25D5E5A3936FF3DCEC60D0'.
   at System.Reflection.Runtime.FieldInfos.RuntimeFieldInfo.get_FieldAccessor() + 0xe8
   at System.Reflection.Runtime.FieldInfos.RuntimeFieldInfo.GetValue(Object) + 0x14
   at System.Reflection.Tests.FieldInfoTests.GetValueFromRvaField() + 0x120
   at System.Reflection!<BaseAddress>+0xb29b40
   at System.Reflection.DynamicInvokeInfo.Invoke(Object, IntPtr, Object[], BinderBundle, Boolean) + 0x10c
```

2024-06-20 03:28 UTC, huoyaoyuan commented
It's NativeAOT. Seems that NativeAOT doesn't support reflection on RVA field. Let's see if it can easily be added or just disable the test.

@dotnet/ilc-contrib

2024-06-20 04:23 UTC, jkotas commented
> Seems that NativeAOT doesn't support reflection on RVA field. Let's see if it can easily be added or just disable the test.

I do not think that it is something we want enable. Could you please disable the test for NAOT?

2024-06-20 04:52 UTC, MichalStrehovsky commented
> It's NativeAOT. Seems that NativeAOT doesn't support reflection on RVA field. Let's see if it can easily be added or just disable the test.

Agreed with Jan. This would only be useful for two things: C++/CLI support and support for (non-intrinsic) RuntimeHelpers.InitializeArray. Native AOT has both listed as unplanned in https://github.com/dotnet/runtime/issues/69919.

The whole reflection with RVA static field business would ideally be just blocked everywhere, it has always been buggy - calling SetValue on RVA statics on .NET Framework crashes the runtime badly, and accessing RVA statics in the TLS range doesn't work as expected (accessing fields marked `thread_local` in C++/CLI will read the template default value instead of the current value of the threadstatic).

2024-06-21 02:54 UTC, huoyaoyuan commented
The failures look unrelated now.

2024-06-21 05:09 UTC, jkotas approved these changes

2024-06-24 03:58 UTC, AaronRobinsonMSFT approved these changes

2024-06-24 18:17 UTC, steveharter approved these changes

2024-06-24 21:07 UTC, merged