Don't dispose timers if we're in our UnhandledException handler.
dotnet/runtime pull request #104828
Opened 2024-07-12 20:25 UTC by StephenMolloy

- **Description** - 
Timer was updated in 5.0 to improve performance, but is prone to deadlocks when manipulated in an unhandled exception handler. Which MemoryCache does. And MemoryCache is probably more likely to witness unhandled exceptions like OOM than typical code.
- **Customer Impact** - The deadlock is preventing a first-party team (Exchange/Substrate) from migrating to .Net 6 and 8.
- **Regression?** - From NetFx, yes.
- **Risk** Low.

Original Issue: #64115 (and #102666)
.Net 9.0 PR: #103937

System.Runtime.Caching is an OOB package that ships alongside the runtime.

2024-07-15 22:19 UTC, carlossanlop commented
@StephenMolloy This needs to target the release/8.0-staging branch, not the release/8.0 branch directly. Can you please make the change? Make sure the branch switch doesn't accidentally bring in unrelated commits.

2024-07-15 22:21 UTC, carlossanlop commented
Because this change affects an OOB package: https://github.com/dotnet/runtime/blob/2e4661c32daaa43e8bdd927339c0adbc461a6e32/src/libraries/System.Runtime.Caching/src/System.Runtime.Caching.csproj#L5

You'll also have to follow these instructions to enable building the package: https://github.com/dotnet/runtime/blob/main/docs/project/library-servicing.md#check-if-a-package-is-generated

OOB assemblies don't get built by default in servicing branches.

2024-07-15 22:22 UTC, carlossanlop requested changes
OOB

2024-07-16 18:24 UTC, carlossanlop reviewed
Thanks. OOB changes look good.

2024-08-10 04:11 UTC, StephenMolloy commented
Closed in favor of #106221

2024-08-10 04:11 UTC, closed without merging