Issue 104700: Clarify error message for collection property with no getter
dotnet/runtime pull request #104861
Opened 2024-07-13 19:57 UTC by julien98Qc

- Added verification to distinguish between different error types.
- Renamed existing test to more accurately reflect that it tests required properties without a setter.
- Added a new test to ensure that a collection property without a getter throws an InvalidOperationException.

2024-07-13 19:59 UTC, julien98Qc commented
> @julien98Qc please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @dotnet-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @dotnet-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @dotnet-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@dotnet-policy-service agree

2024-07-26 09:44 UTC, eiriktsarpalis commented on src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/JsonPropertyInfo.cs
> -                if (!CanDeserialize &&
Could you keep the logic inlined please? Extracting into a separate method makes the diff harder to review and IMHO it shouldn't make a big difference from a readability perspective. Thanks.

2024-07-26 09:54 UTC, eiriktsarpalis commented on src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/JsonPropertyInfo.cs
> +                if (isCollectionProperty)
Is this really only improving the error message or is it expanding failures for more types? It seems to me that if we have a collection property and `RespectRequiredConstructorParameters` is set to false this is failing when it wasn't before this change.

2024-07-26 09:55 UTC, eiriktsarpalis commented on src/libraries/System.Text.Json/tests/Common/RequiredKeywordTests.cs
> +        public async Task RequiredPropertyWithoutSetterThrows()
Please don't rename existing unit tests as it breaks historical tracking in CI.

2024-07-26 10:00 UTC, eiriktsarpalis commented on src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Metadata/JsonPropertyInfo.cs
> +                bool isRequiredParameterRespected = AssociatedParameter?.IsRequiredParameter is true && Options.RespectRequiredConstructorParameters;
Nit: this expression is being evaluated even for branches that won't use it.

2024-07-26 10:02 UTC, eiriktsarpalis commented on src/libraries/System.Text.Json/tests/Common/RequiredKeywordTests.cs
> +        public class ClassWithRequiredCollectionPropertyWithoutGetter
Just to make sure we're not regressing things here, could you also add a test for class like so:
```C#
class ClassWithCollectionCtorParam(Dictionary<string, JsonElement> value)
{
    public Dictionary<string, JsonElement> Value { get; } = value;
}
```
And then try to deserialize it using an `options` instance with `RespectRequiredConstructorParameters` set to `true`.

2024-07-26 10:11 UTC, eiriktsarpalis commented on src/libraries/System.Text.Json/tests/Common/RequiredKeywordTests.cs
> +            InvalidOperationException exception = await Assert.ThrowsAsync<InvalidOperationException>(
I don't think this is the correct way to address the problem. A fix should instead try to make the scenario work as expected. If you remove `JsonRequired` from the repro in #104700 then deserialization works as expected and this should too.

2024-07-29 11:35 UTC, eiriktsarpalis requested changes
Per https://github.com/dotnet/runtime/pull/104861/files#r1692841347 I don't believe clarifying the error message is the correct way to address the issue. We should instead make the impact scenario work similar to how it does when `[JsonRequired]` isn't being specified.

2024-07-30 00:36 UTC, closed without merging

2024-07-30 10:32 UTC, eiriktsarpalis commented
@julien98Qc Thank you for taking the time to contribute a fix!

2024-07-30 10:34 UTC, julien98Qc commented
@eiriktsarpalis Thank you for reviewing :D