Update RedHat 7 -> 8
dotnet/runtime pull request #105063
Opened 2024-07-18 05:08 UTC by richlander

Red Hat no longer supports .NET 6 on RHEL 7.

Also resolving https://github.com/dotnet/runtime/pull/103380#discussion_r1680782274

2024-07-18 14:53 UTC, omajid approved these changes
I don't know the format of these files too well, but the general change from 7 to 8 makes sense to me.

2024-07-19 12:34 UTC, akoeplinger approved these changes

2024-07-26 18:35 UTC, carlossanlop commented
No equivalent PR for `release/8.0-staging`?

2024-07-26 18:38 UTC, carlossanlop requested changes
@richlander this is failing:
```
.packages/microsoft.dotnet.helix.sdk/6.0.0-beta.24360.7/tools/Microsoft.DotNet.Helix.Sdk.MonoQueue.targets(59,5): error : (NETCORE_ENGINEERING_TELEMETRY=Build) Helix API does not contain an entry for RedHat.8.Amd64.Open
```

Here: https://dev.azure.com/dnceng-public/public/_build/results?buildId=745875&view=logs&j=1f44e919-17d8-5098-631c-31ef11f9e57b&t=d617d884-da52-5b82-bd49-f7613b408af4&l=92

and here: https://dev.azure.com/dnceng-public/public/_build/results?buildId=745875&view=logs&j=bc8f69e2-91b3-518c-84f8-466a04c1af40&t=0864dbdb-cb3f-5f82-b0b6-057b78db53e2&l=92

2024-07-26 18:38 UTC, carlossanlop commented on eng/pipelines/coreclr/templates/helix-queues-setup.yml
> +        - RedHat.8.Amd64.Open
@richlander this is failing:
```
.packages/microsoft.dotnet.helix.sdk/6.0.0-beta.24360.7/tools/Microsoft.DotNet.Helix.Sdk.MonoQueue.targets(59,5): error : (NETCORE_ENGINEERING_TELEMETRY=Build) Helix API does not contain an entry for RedHat.8.Amd64.Open
```

Here: https://dev.azure.com/dnceng-public/public/_build/results?buildId=745875&view=logs&j=1f44e919-17d8-5098-631c-31ef11f9e57b&t=d617d884-da52-5b82-bd49-f7613b408af4&l=92

and here: https://dev.azure.com/dnceng-public/public/_build/results?buildId=745875&view=logs&j=bc8f69e2-91b3-518c-84f8-466a04c1af40&t=0864dbdb-cb3f-5f82-b0b6-057b78db53e2&l=92

2024-08-14 21:13 UTC, carlossanlop commented
Approving for servicing as tell-mode. You can merge anytime if the CI looks good.

2024-08-19 21:35 UTC, carlossanlop approved these changes

2024-08-23 15:33 UTC, richlander commented
Silly me. I didn't realize that we didn't have a RHEL 8 queue. Tracking issue: https://github.com/dotnet/dnceng/issues/3867.

I also didn't realize that they list was available: https://helix.dot.net/

2024-09-04 21:44 UTC, carlossanlop commented
@richlander any updates on this? Is it ready to merge?

2024-09-05 16:11 UTC, richlander commented
Thanks for checking in. The tracking issue is still open.

2024-09-05 17:27 UTC, carlossanlop commented
BTW friendly reminder: Code Complete for the October Release is September 9. If we want this fix to be included in that release, please merge this PR _before_ that date. Otherwise, it will have to wait until November.

2024-09-19 18:17 UTC, carlossanlop commented
Removing `servicing-approved` to prevent accidental merge. @richlander feel free to add the label again when you're ready to merge (it will unblock the check-service-labels required CI leg).

2024-10-01 23:20 UTC, carlossanlop commented
@richlander we are going to need this PR merged soon as all existing PRs in the release/6.0-staging are now failing with the following error:

```
❌SENDHELIXJOB(0,0): error : Helix queue redhat.7.amd64.open is set for estimated removal date of 2024-10-01. 
In most cases the queue will be removed permanently due to end-of-life; please contact dnceng for any questions 
or concerns, and we can help you decide how to proceed and discuss other options.
```

2024-10-02 03:40 UTC, richlander commented
I'll raise this with the right folks.

2024-10-03 00:49 UTC, richlander commented
My thinking is:

- Replace RHEL7 with CentOS 7 to preserve validating min glibc.
- Add CentOS Stream 9 for outer loop testing.

2024-10-03 22:25 UTC, carlossanlop commented
/ba-g The wasm "connection refused" and "Chrome was unable to start" failures that did not get linked to an issue are unrelated to this PR. One of them is https://github.com/dotnet/runtime/issues/104349

2024-10-03 22:26 UTC, carlossanlop approved these changes

2024-10-03 22:26 UTC, merged