[RISC-V][LoongArch64] Pass FP struct fields at arbitrary offsets in ArgIterator and CallDescrWorker
dotnet/runtime pull request #105800
Opened 2024-08-01 12:10 UTC by tomeksowi

Use new info calculated in #103945 on the VM side (shuffling thunks will be handled in a separate PR).

Stems from #101796, part of #84834, cc @dotnet/samsung @shushanhf @LuckyXu-HF

2024-08-01 12:47 UTC, tomeksowi commented on src/coreclr/vm/loongarch64/calldescrworkerloongarch64.S
@shushanhf @LuckyXu-HF PTAL, I don't really know LA asm and I had no way to test it..

2024-08-05 06:33 UTC, tomeksowi commented
@MichalStrehovsky @jkotas can anyone review please?

2024-08-05 11:16 UTC, jkotas commented
@dotnet/samsung @shushanhf @LuckyXu-HF Could you please review and sign-off?

2024-08-08 12:56 UTC, risc-vv commented
<details><summary>8d8e705dis being scheduled for building and testing</summary>

GIT:: `8d8e705de3908f6138e7d691563776f8dc4e0ed5`
REPO: [dotnet/runtime](https://github.com/dotnet/runtime)
BRANCH: main</details>

2024-08-08 13:23 UTC, risc-vv commented
<details><summary>8d8e705dis being scheduled for building and testing</summary>

GIT: `8d8e705de3908f6138e7d691563776f8dc4e0ed5`
REPO: [dotnet/runtime](https://github.com/dotnet/runtime)
BRANCH: main</details>

2024-08-08 13:49 UTC, risc-vv commented
<details><summary>8d8e705d is being scheduled for building and testing</summary>

GIT: `8d8e705de3908f6138e7d691563776f8dc4e0ed5`
REPO: [dotnet/runtime](https://github.com/dotnet/runtime)
BRANCH: main</details>

2024-08-08 14:49 UTC, sirntar approved these changes
I left review of the LA64 parts for @shushanhf  and/or @LuckyXu-HF, but as for the RV64, everything looks good to me.

@tomeksowi I saw that the EmptyStructs test fails, but I'm not sure if this pr was supposed to solve this problem (?).

2024-08-09 00:50 UTC, shushanhf commented
OK, Thanks very much.
I will test it based on the latest patch right now.

2024-08-09 03:03 UTC, shushanhf requested changes

2024-08-09 03:03 UTC, shushanhf commented on src/coreclr/vm/callingconvention.h
> +#if defined(TARGET_RISCV64) || defined(TARGET_RISCV64)
```suggestion
#if defined(TARGET_RISCV64) || defined(TARGET_LOONGARCH64)
```

2024-08-09 03:05 UTC, shushanhf commented on src/coreclr/vm/loongarch64/calldescrworkerloongarch64.S
> +    j  LOCAL_LABEL(ReturnDone)
```suggestion
    b  LOCAL_LABEL(ReturnDone)
```

2024-08-09 03:05 UTC, shushanhf commented on src/coreclr/vm/loongarch64/calldescrworkerloongarch64.S
> +    j  LOCAL_LABEL(ReturnDone)
```suggestion
    b  LOCAL_LABEL(ReturnDone)
```

2024-08-09 06:36 UTC, risc-vv commented
<details><summary>3985f11e is being scheduled for building and testing</summary>

GIT: `3985f11e825beafbc9fd591d97942c4d69753333`
REPO: [dotnet/runtime](https://github.com/dotnet/runtime)
BRANCH: main</details>

2024-08-09 06:41 UTC, shushanhf approved these changes
LGTM
Thanks

2024-08-09 07:07 UTC, tomeksowi commented
> @tomeksowi I saw that the EmptyStructs test fails, but I'm not sure if this pr was supposed to solve this problem (?).

This no, but #106112 disables them where not supported.

2024-08-09 11:41 UTC, risc-vv commented
<details><summary>3985f11e is being scheduled for building and testing</summary>

GIT: `3985f11e825beafbc9fd591d97942c4d69753333`
REPO: [dotnet/runtime](https://github.com/dotnet/runtime)
BRANCH: main</details>

2024-08-09 14:49 UTC, risc-vv commented
<details><summary>3985f11e is being scheduled for building and testing</summary>

GIT: `3985f11e825beafbc9fd591d97942c4d69753333`
REPO: [dotnet/runtime](https://github.com/dotnet/runtime)
BRANCH: main</details>

2024-08-09 17:51 UTC, risc-vv commented
<details><summary>88815d2d is being scheduled for building and testing</summary>

GIT: `88815d2db74d1ac9039fe09874b81af9cdd9e47b`
REPO: [dotnet/runtime](https://github.com/dotnet/runtime)
BRANCH: main</details>

2024-08-10 02:49 UTC, jkotas approved these changes

2024-08-10 02:49 UTC, merged