[wasm] Allow to build browser in library mode
dotnet/runtime pull request #106388
Opened 2024-08-14 11:24 UTC by mkhamoyan

2024-08-14 12:13 UTC, mkhamoyan commented
/azp run runtime-wasm

2024-08-14 12:28 UTC, mkhamoyan commented on src/tools/illink/src/ILLink.Tasks/build/Microsoft.NET.ILLink.targets
> +    </ItemGroup>
Not sure this is the right place.

2024-08-15 06:59 UTC, mkhamoyan commented on src/tasks/WasmAppBuilder/PInvokeTableGenerator.cs
> +#if TARGET_WASI
I couldn't find RID passed to the task https://github.com/dotnet/runtime/blob/67df47e1abb45b08f32063737e1e0f6eecb083e7/src/mono/wasi/wasi.proj#L65-L72  that's why decided to check  `TARGET_WASI`.

2024-08-15 15:33 UTC, maraf commented on src/tasks/WasmAppBuilder/PInvokeTableGenerator.cs
> +#if TARGET_WASI
Yeah, we need to pass-in RID. `TARGET_WASI` wouldn't solve the problem

2024-09-10 00:12 UTC, lewing requested changes
Needs follow up on existing comments

2024-09-11 12:44 UTC, mkhamoyan commented
/azp run runtime-wasm

2024-09-16 08:32 UTC, maraf approved these changes
Looks good to me 👍

2024-09-16 08:32 UTC, maraf commented on src/tasks/WasmAppBuilder/PInvokeTableGenerator.cs
> +    public PInvokeTableGenerator(Func<string, string> fixupSymbolName, LogAdapter log, bool isLibraryMode = false, string runtimeIdentifier = "browser-wasm")
nit: Please don't fallback to browser, make the argument "required"

2024-09-16 09:11 UTC, mkhamoyan commented
/azp run runtime-wasm

2024-09-16 09:18 UTC, ilonatommy approved these changes

2024-09-16 09:41 UTC, mkhamoyan commented on src/tasks/WasmAppBuilder/ManagedToNativeGenerator.cs
> +    public string RuntimeIdentifier { get; set; } = string.Empty;
Thanks, updated.

2024-09-16 09:42 UTC, mkhamoyan commented
/azp run runtime-wasm

2024-09-16 11:34 UTC, mkhamoyan commented
/azp run runtime-wasm

2024-09-24 00:21 UTC, lewing commented
This feels wrong, we're plumbing the rid down to the generator rather than dealing with runtime init ordering in the browser case.  I'd rather we unconditionally emit the intiialize_runtime call and have it assert when it can't actually do the initialization.

2024-09-25 10:59 UTC, maraf commented
> This feels wrong, we're plumbing the rid down to the generator rather than dealing with runtime init ordering in the browser case. I'd rather we unconditionally emit the intiialize_runtime call and have it assert when it can't actually do the initialization.

We are initializing runtime for browser in the place™️ manually. I guess we can have wrap the `mono_wasm_load_runtime` in `initialize_runtime` for browser case, still call it manually and leave the generator untouched

2024-09-30 19:22 UTC, lewing approved these changes

2024-10-03 07:35 UTC, merged