[release/9.0] [browser] Make boot json file name configurable
dotnet/runtime pull request #108708
Opened 2024-10-09 13:05 UTC by maraf

Backport of https://github.com/dotnet/runtime/pull/108281 to release/9.0

/cc @lewing @maraf

## Customer Impact

- [x] Customer reported
- [ ] Found internally

A late customer (Uno) "feature" request. The default value of "blazor.boot.json" is a relic from SDK migration but changing it or having it configurable was no priority until Uno started to use our build system. 

## Regression

- [ ] Yes
- [x] No

## Testing

Automated. We have a lot of tests in runtime repository and SDK repository to cover correct placement and content of boot config.

## Risk

Low. Based on amount of test we have and the fact that default values remain unchanged.

2024-10-09 13:09 UTC, ilonatommy approved these changes

2024-10-09 16:22 UTC, lewing approved these changes

2024-10-09 23:18 UTC, lewing requested changes
in the current form this will break the sdk tests, please stage a fix for that.  I would still like to take this but lets have everything ready first.

2024-10-10 14:42 UTC, lewing approved these changes

2024-10-10 17:45 UTC, jeffschwMSFT commented
@maraf can you take a look at the pr failures?

2024-10-11 05:33 UTC, maraf commented
All green now

2024-10-11 16:15 UTC, merged