[release/9.0] Stable branding for GA
dotnet/runtime pull request #108899
Opened 2024-10-15 17:49 UTC by carlossanlop

2024-10-15 17:53 UTC, carlossanlop commented
The emsdk stable branding deps flow PR is https://github.com/dotnet/runtime/pull/108898

2024-10-15 18:49 UTC, ViktorHofer approved these changes

2024-10-15 22:12 UTC, mmitche commented
@carlossanlop @akoeplinger Test is failing on check a stable branding string. emsdk is merged but I don't see any failrues here that are a result of not flowing emsdk bits yet. Test failure is here:

```
#if STABILIZE_PACKAGE_VERSION
            // a stabilized version looks like 8.0.0
            Assert.DoesNotContain("-", version);
            Assert.True(Version.TryParse(version, out Version _));
#else
            // a non-stabilized version looks like 8.0.0-preview.5.23280.8 or 8.0.0-dev
            Assert.Contains("-", version);
            var versionNumber = version.Substring(0, version.IndexOf("-"));
            Assert.True(Version.TryParse(versionNumber, out Version _));
#endif
```

2024-10-15 22:38 UTC, carlossanlop commented
The test is expecting to _not_ see the `"-"` character in the version, but PR CI results are (AFAIK) always expected to have the `"-ci"` suffix added to them:

```
[19:03:40] info: [FAIL] System.Runtime.InteropServices.RuntimeInformationTests.DescriptionNameTests.VerifyFrameworkDescriptionContainsCorrectVersion
[19:03:40] info: Assert.DoesNotContain() Failure: Sub-string found
[19:03:40] info:               ↓ (pos 5)
[19:03:40] info: String: "9.0.0-ci"
[19:03:40] info: Found:  "-"
[19:03:40] info:    at System.Runtime.InteropServices.RuntimeInformationTests.DescriptionNameTests.VerifyFrameworkDescriptionContainsCorrectVersion()
[19:03:40] info:    at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args)
[19:03:40] info:    at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
[19:03:40] info: Finished:    System.Runtime.InteropServices.RuntimeInformation.Tests.dll
```

I suspect the test will pass in rolling builds where `"-ci"` is not added.

2024-10-16 00:18 UTC, mmitche commented
> The test is expecting to _not_ see the `"-"` character in the version, but PR CI results are (AFAIK) always expected to have the `"-ci"` suffix added to them, and local builds are expected to have the `"-dev"` suffix.
> 
> ```
> [19:03:40] info: [FAIL] System.Runtime.InteropServices.RuntimeInformationTests.DescriptionNameTests.VerifyFrameworkDescriptionContainsCorrectVersion
> [19:03:40] info: Assert.DoesNotContain() Failure: Sub-string found
> [19:03:40] info:               ↓ (pos 5)
> [19:03:40] info: String: "9.0.0-ci"
> [19:03:40] info: Found:  "-"
> [19:03:40] info:    at System.Runtime.InteropServices.RuntimeInformationTests.DescriptionNameTests.VerifyFrameworkDescriptionContainsCorrectVersion()
> [19:03:40] info:    at System.Reflection.MethodBaseInvoker.InterpretedInvoke_Method(Object obj, IntPtr* args)
> [19:03:40] info:    at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
> [19:03:40] info: Finished:    System.Runtime.InteropServices.RuntimeInformation.Tests.dll
> ```
> 
> I suspect the test will pass in rolling builds where `"-ci"` or `"-dev"` is not added.
> 
> Fixing the test by making it more specific.

Hmm, the shipping assets maybe should not have -ci. At least, when i build winforms stable with -ci, shipping packages are 9.0.0. Maybe this is just specific to the framework description? We def need to verify on an official build.

2024-10-16 07:20 UTC, dkurepa approved these changes

2024-10-16 07:30 UTC, dkurepa commented
We didn't see any `-ci` suffix in 9.0.0 test build https://dev.azure.com/dnceng/internal/_build/results?buildId=2531164&view=results. So I guess it's just a PR build?

2024-10-16 08:53 UTC, akoeplinger requested changes

2024-10-16 08:53 UTC, akoeplinger commented on src/libraries/System.Runtime/tests/System.Runtime.InteropServices.RuntimeInformation.Tests/DescriptionNameTests.cs
> +            if (!version.Contains("-dev") && !version.Contains("-ci"))
This is not correct. The FrameworkDescription should always contain the stabilized version irrespective of the build environment.

This is a regression caused by https://github.com/dotnet/runtime/pull/102164. Before it was reading the AssemblyInformationalVersion from System.Private.CoreLib.dll which is `9.0.0`, now it's reading it from the generators assembly and that contains `9.0.0-dev` (basically what Stephen noticed in https://github.com/dotnet/runtime/pull/102164#discussion_r1601772016)

2024-10-16 09:07 UTC, akoeplinger commented on src/libraries/System.Runtime/tests/System.Runtime.InteropServices.RuntimeInformation.Tests/DescriptionNameTests.cs
> +            if (!version.Contains("-dev") && !version.Contains("-ci"))
I pushed a fix. There is potential to clean up overriding the version in SPC.dll now I think but that can be done separately.

2024-10-16 09:07 UTC, akoeplinger approved these changes

2024-10-16 09:17 UTC, ViktorHofer commented
Should these lines now get removed (at least in main when we forward port this change)?

- https://github.com/dotnet/runtime/blob/ee99d7c50bed644bbb53c30b73cd21c7fe6c9fc2/src/coreclr/System.Private.CoreLib/System.Private.CoreLib.csproj#L47-L49
- https://github.com/dotnet/runtime/blob/ee99d7c50bed644bbb53c30b73cd21c7fe6c9fc2/src/mono/System.Private.CoreLib/System.Private.CoreLib.csproj#L34-L36
- https://github.com/dotnet/runtime/blob/ee99d7c50bed644bbb53c30b73cd21c7fe6c9fc2/src/coreclr/nativeaot/Directory.Build.props#L28-L30

2024-10-16 09:18 UTC, akoeplinger commented
Yeah I mentioned it above.

2024-10-16 14:13 UTC, mmitche commented
Looks like some additional test failures that may be test issues rather than product issues

2024-10-16 16:29 UTC, carlossanlop commented
Build Analysis says most failures are known. There is one in Installer Host Activation that I have not seen before. @NikolaMilosavljevic does this look familiar? https://dev.azure.com/dnceng-public/public/_build/results?buildId=844459&view=logs&j=34fcf1e9-20e8-52c9-c21d-1ed3608ac124&t=3f5386ba-6526-5d7f-4342-42281a824185&l=489

2024-10-16 16:42 UTC, mmitche commented
![image](https://github.com/user-attachments/assets/1e037dd7-8552-4f6d-97a5-28c674ba1f65)

Those are the ones i think are interesting.

2024-10-16 17:08 UTC, carlossanlop commented
> Those are the ones i think are interesting.

The failure is coming from the build output argument passed to this method: https://github.com/dotnet/runtime/blob/9305d7f71d73c1d1edeb2a06478c998e40deda8d/src/mono/wasi/Wasi.Build.Tests/BuildTestBase.cs#L345-L355

2024-10-16 17:14 UTC, carlossanlop commented
We generate the build out of this portion of the code, which we then pass to AssertRuntimePackPath. I wonder if we need to pass an environment variable to indicate that we are using a stabilizing build.

https://github.com/dotnet/runtime/blob/9305d7f71d73c1d1edeb2a06478c998e40deda8d/src/mono/wasi/Wasi.Build.Tests/BuildTestBase.cs#L243-L253

2024-10-16 18:45 UTC, merged

2024-10-17 03:55 UTC, carlossanlop commented
Good news: The release/9.0 rolling build that included this change did _not_ hit the failures reported above: https://dev.azure.com/dnceng/internal/_build/results?buildId=2562281&view=results

So they indeed are only happening in PRs.