Reference net10.0 path for ILLink.Tasks assembly
dotnet/runtime pull request #109619
Opened 2024-11-07 18:44 UTC by mthalman

ILLink.Tasks targets the net10.0 TFM and it needs the assembly reference for the MSBuild props file to match that TFM.

Related to https://github.com/dotnet/sdk/pull/44685

2024-11-07 18:48 UTC, sbomer approved these changes

2024-11-08 08:25 UTC, ViktorHofer commented
This change can't be made as is. Illink in this repo still targets net9.0. I think it would be better to avoid the TFM version in the folder path entirely.

2024-11-08 08:28 UTC, am11 commented
> This change can't be made as is. Illink in this repo still targets net9.0. I think it would be better to avoid the TFM version in the folder path entirely.

+1 (assuming that for a given task package, there's always only a single implementation assembly).

2024-11-08 10:32 UTC, ViktorHofer commented
For this package, yes.

2024-11-08 10:33 UTC, ViktorHofer requested changes
This change can't be made because runtime still targets net9.0.

2024-11-08 10:53 UTC, ViktorHofer commented
Submitted https://github.com/dotnet/runtime/pull/109634

2024-11-08 14:49 UTC, mthalman commented
Closing in favor of https://github.com/dotnet/runtime/pull/109634.

2024-11-08 14:49 UTC, closed without merging