Fix calling convention mismatch in GC callouts
dotnet/runtime pull request #110685
Opened 2024-12-13 09:16 UTC by MichalStrehovsky

Fixes #110607.

The native side expects fastcall.

Filed #110684 on the test hole. We would have caught it during native AOT x86 bringup if this had any tests since this is a guaranteed stack corruption and crash.

Cc @dotnet/interop-contrib

2024-12-13 13:31 UTC, AaronRobinsonMSFT approved these changes

2024-12-13 15:57 UTC, jkoritzinsky requested changes
Does the JIT support fastcall here? I'm pretty sure this will just fail with another exception. I don't think we ever brought Fastcall support online.

Can we add a test or run some existing test suite on the PR?

2024-12-13 22:37 UTC, jkoritzinsky approved these changes
Okay I went looking through the code and found something very interesting. It looks like when I did the unmanaged calling-convention support rewrite in the JIT, I implemented fastcall correctly.

However, as we have never supported it for P/Invokes, our exceptions that block fastcall are P/Invoke-only. Additionally, the exceptions are only thrown in CoreCLR (NativeAOT likely fails in a more inscrutible way).

In any case, looks like `Fastcall` + `UnmanagedCallersOnly` should work here just fine.

2024-12-13 23:32 UTC, jkotas commented on src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/TrackerObjectManager.NativeAot.cs
> +            delegate* unmanaged[Fastcall]<int, void> gcStartCallback = &GCStartCollection;
Can we change the unmanaged side to use the default calling convention instead?

x86 custom calling conventions are pain. It is best to stick to the default calling convention where possible.

2024-12-13 23:35 UTC, jkotas commented on src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/TrackerObjectManager.NativeAot.cs
> +            delegate* unmanaged[Fastcall]<int, void> gcStartCallback = &GCStartCollection;
We have two different callouts https://`github.com/dotnet/runtime/blob/90dfc04d8f863e053e42edf0992c1b63398b12fb/src/coreclr/nativeaot/Runtime/RestrictedCallouts.h#L100-L101 . One of them is FastCall and the other one is default. I would make both of them default.

2024-12-16 06:10 UTC, MichalStrehovsky commented
> Does the JIT support fastcall here? I'm pretty sure this will just fail with another exception. I don't think we ever brought Fastcall support online.

I did test this and it worked.

Looking through our test tree, I don't see any test exercising Fastcall though. Do we have any testing for this? Should we have testing? It doesn't look like CoreCLR VM blocks UnmanagedCallersOnly with fastcall either.

Either way, I made this use not-fastcall per Jan's request.

2024-12-16 06:20 UTC, am11 commented
FCall callbacks probably are implicitly tested assuming tests exercise this code:

```
src/coreclr/nativeaot/Runtime/interoplibinterface.h:    using TryGetCallback = void*(F_CALL_CONV *)(void);
src/coreclr/nativeaot/Runtime/interoplibinterface.h:    using TryGetTaggedMemoryCallback = CLR_BOOL(F_CALL_CONV *)(_In_ Object *, _Out_ void **);
src/coreclr/nativeaot/Runtime/interoplibinterface.h:    using BeginEndCallback = void(F_CALL_CONV *)(void);
src/coreclr/nativeaot/Runtime/interoplibinterface.h:    using IsReferencedCallback = int(F_CALL_CONV *)(_In_ void*);
src/coreclr/nativeaot/Runtime/interoplibinterface.h:    using EnteredFinalizationCallback = void(F_CALL_CONV *)(_In_ void*);
```
(math functions are also using F_CALL_CONV on x86/arm32 but they are not callbacks)

2024-12-16 06:26 UTC, MichalStrehovsky commented
> FCall callbacks probably are implicitly tested assuming tests exercise this code:

Do any of those call into managed code? We're not discussing test coverage of fastcall in the Visual C++ compiler but `UnmanagedCallersOnly` methods with `CallConvs = typeof(CallConvFastcall)`.

2024-12-16 08:04 UTC, jkotas approved these changes

2024-12-16 08:37 UTC, merged

2024-12-16 08:42 UTC, MichalStrehovsky commented
This is fixed in main. I consider backport to 9.0 blocked on #110684 - I don't want to be laughed out of the shiproom when I say "no we don't have test coverage, but we do have a concept of a plan for it".

2024-12-17 17:35 UTC, Sergio0694 commented
Would it be sufficient to validate this on both x86 and x64 with the Store? We won't be able to ship to x86 with Native AOT otherwise. In theory we could keep that target on .NET Native, but it'd be simpler for us if we could migrate all 3 targets. And would the fact x86 right now is flat out broken on NAOT in XAML scenario help make the case for servicing?

2024-12-17 18:10 UTC, jkotas commented
If you can validate the fix with Store, it should be good enough test coverage for servicing backport.

2024-12-19 12:48 UTC, Sergio0694 commented
I tested this on x64 and it works fine (except for #110823, but that's unrelated). Currently blocked by other dependencies on testing with x86, but I hope to get that resolved by end of this week, hopefully. Will report back as soon as I can also validate on x86 and confirm that things work correctly, and then hopefully we can backport this too 🙂

2024-12-19 13:24 UTC, MichalStrehovsky commented
> I tested this on x64 and it works fine (except for #110823, but that's unrelated).

The bug can only be observed on x86. There's no fastcall or stdcall on x64, there's only one calling convention. This PR is essentially no-op on x64 or arm64.

2024-12-19 13:39 UTC, Sergio0694 commented
Oh I know, but I figured it wouldn't hurt to validate everything end to end too just in case, to make things a bit simpler for tactics to backport this. Also until we unblock x86 in the Store it was the only thing I could do 😅

2025-01-05 23:03 UTC, Sergio0694 commented
Didn't want to delay this any further, so I ended up just yeeting all problematic code from the Store for testing 😆

Followed similar steps as https://github.com/dotnet/runtime/pull/110762#pullrequestreview-2508994178:
Tested with the Microsoft Store and could not repro any hangs:
- Checked out `release/9.0-staging` (f58036422045bc89fa2e70536be5a857614cfee8)
- Cherry-pick 1033fb317ce195658237f0f8453b792aa864d1af (#110762)
- Cherry-pick c69ac7c63494ba7c6307c054846a100a6b7fb836 (this merged PR)
- Build with `.\build.cmd clr.aot -c Release -arch x86`
- Set `IlcSdkPath` in the Store .csproj to `runtime\artifacts\bin\coreclr\windows.x86.Release\aotsdk\`
- Set `GenerateAppxPackageOnBuild`
- Switch to Release x86
- Deploy

I could run the Store just fine. Didn't notice hangs, also I guess the fact the app didn't just explode as soon as the GC triggered should be enough to show the fix for the specific issue for this PR should be working fine. Can we backport this? 😅

Thank you!

2025-01-06 03:28 UTC, AaronRobinsonMSFT commented
/backport to release/9.0

2025-01-06 03:49 UTC, AaronRobinsonMSFT commented
/backport to release/9.0-staging