exclude obj/cmake from codeql.
dotnet/runtime pull request #110630
Opened 2024-12-11 22:19 UTC by mangod9

There are duplicate issues being created due to random directory names generated by cmake in obj/cmake

2024-12-11 22:39 UTC, GrabYourPitchforks requested changes
These are not duplicate issues in the sense that there's no "primary" issue (outside the CMakeFiles folder) that they're duplicates of.

Instead, what should probably be done here is to suppress the specific files that we know are generating false positives. The pattern would presumably look something like:

```txt
artifacts/obj/**/CMakeFiles/**/CheckFunctionExists.c
```

2024-12-11 22:59 UTC, GrabYourPitchforks requested changes
The comment justifying this suppression is inaccurate. The comment doesn't describe why _this file specifically_ is targeted.

2024-12-11 23:47 UTC, GrabYourPitchforks approved these changes

2024-12-17 16:40 UTC, jkoritzinsky commented on .CodeQL.yml
> +    # is build time only and shouldnt affect the product binares.
```suggestion
    # related to obsolete encryption algorithm used. Note that CheckFuntionExists 
    # files are generated as part of build-time checks in CMake and are not compiled
    # or linked into any product binaries.
```

2024-12-17 16:40 UTC, jkoritzinsky approved these changes

2024-12-17 16:43 UTC, merged