Observe any exception on HTTP connection scavenge.
dotnet/runtime pull request #110982
Opened 2024-12-29 14:58 UTC by salvois

Fixes #110951

2024-12-29 15:18 UTC, MihaZupan requested changes
Thank you for filing the issue and looking to fix it.

We don't want to unconditionally suppress the error here as it's meaningful for the request.
Instead, we'll have to figure out in what case it's possible that no thread would observe the exception.

It's not immediately obvious to me how that could happen with .NET 9.0.
Do you mind double-checking that you were indeed running on 9.0 and not 8.0?

2024-12-29 15:18 UTC, MihaZupan commented on src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnection.cs
> +                catch (Exception error)
`TransitionToCompletedAndTryOwnCompletion` controls who is responsible for observing the exception.
If a thread has already flipped `_readAheadTaskStatus` to `CompletionReserved`, it's also responsible for observing any exceptions thrown by this method.
The exact exception is meaningful as the request may fail with it as the inner exception.

If it has not (task status is still `Started`), the method itself will observe and suppress the exception. In that case we don't necessarily care that/which exception occured, just that the read completed before a request attempted to use the connection.

2024-12-30 11:48 UTC, salvois commented
> Thank you for filing the issue and looking to fix it.

Thank you for taking time to review and being so fast in it! I drafted the PR mainly to understand how much I went off road with my interpretation. I'm still trying to create a repro under Functional.Tests but have been unsuccessful so far.

> We don't want to unconditionally suppress the error here as it's meaningful for the request. Instead, we'll have to figure out in what case it's possible that no thread would observe the exception.

Long shot here: what if CheckUsabilityOnScavenge got an exception while the read-ahead task is CompletionReserved, because PrepareForReuse ran just at the "right" time, and then the connection is disposed? It looks to me nobody may be observing the read-ahead task in this case.
But I'm still biased by the hope of a "false positive" error here.

> It's not immediately obvious to me how that could happen with .NET 9.0. Do you mind double-checking that you were indeed running on 9.0 and not 8.0?

I'm afraid we are: I double checked the content of our self-contained deployed package, and it contains, among the others, System.Net.Http.dll 9.0.24.52809 (2024-10-29) and runtimeconfig.json specifying Microsoft.NETCore.App and Microsoft.AspNetCore.App 9.0.0.

2024-12-30 17:27 UTC, MihaZupan commented
If `PrepareForReuse` returns `true`, the caller is expected to always follow up with a call into [`HttpConnection.SendAsync`](https://github.com/dotnet/runtime/blob/756e62050722c168cd3b753be73b7cbcd93f06d6/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnection.cs#L532), which should always observe the `_readAheadTask` result.
Either when doing the initial read here
https://github.com/dotnet/runtime/blob/756e62050722c168cd3b753be73b7cbcd93f06d6/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnection.cs#L618-L634
or if an exception occurs here
https://github.com/dotnet/runtime/blob/756e62050722c168cd3b753be73b7cbcd93f06d6/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnection.cs#L854-L859

If there's a case where we could throw between `PrepareForReuse` and the `try` block in `HttpConnection.SendAsync`, we would indeed leak unobserved faulted tasks, but I don't know how that'd happen.

2024-12-30 18:38 UTC, salvois commented
> If `PrepareForReuse` returns `true`, the caller is expected to always follow up with a call into `HttpConnection.SendAsync`

Makes sense to me, and confirms my understanding, thanks.
I was looking at the code path where `PrepareForReuse` returns `false` but the `Exchange` should indeed protect us.

What about the code paths that check for a read-ahead task not yet started, though?

In my understanding, there could be a case where both `PrepareForReuse` and `CheckUsabilityOnScavenge` see `ReadAheadTaskHasStarted == false`, because they set `_readAheadTaskStatus` later, not atomically.
If this is the case, they'd both start a read-ahead task (which doesn't sound good to me), moreover `TransitionToCompletedAndTryOwnCompletion` could well see `ReadAheadTask_CompletionReserved` as set here:

https://github.com/dotnet/runtime/blob/756e62050722c168cd3b753be73b7cbcd93f06d6/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnection.cs#L162

Of course, apologies if I misunderstood the implementation!

2024-12-30 20:34 UTC, MihaZupan commented
> a case where both PrepareForReuse and `CheckUsabilityOnScavenge` see `ReadAheadTaskHasStarted == false`

While not obvious from the methods themselves, for both of those, the caller first removes the connection from the pool such that only 1 thread has access to the connection at any given point, hence why they use non-synchronized checks.

Note how both are called after popping the connection from the stack:
https://github.com/dotnet/runtime/blob/1613dd360914841b0dc1976a8499fce54a47f6a6/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/ConnectionPool/HttpConnectionPool.Http1.cs#L441-L443
https://github.com/dotnet/runtime/blob/1613dd360914841b0dc1976a8499fce54a47f6a6/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/ConnectionPool/HttpConnectionPool.Http1.cs#L37-L46

2025-01-03 06:41 UTC, MihaZupan commented
I'll close this PR for now while we try to find the root cause in #110951.

2025-01-03 06:41 UTC, closed without merging