JIT: check that constant handles are not OK2_CONST_LONGs
dotnet/runtime pull request #1831
Opened 2020-01-16 20:18 UTC by AndyAyersMS

Follow-up from #1788.

Also remove an arm-only handle block that should now be redundant.

2020-01-16 20:18 UTC, AndyAyersMS commented
@briansull PTAL
cc @dotnet/jit-contrib

2020-01-16 21:14 UTC, AndyAyersMS commented
The newly added assert is firing. Will dig in and see why.

2020-01-16 21:58 UTC, briansull commented
There is a strange code sequence here, that may be relevant:

Assertionprop.cpp line 1341:
```

                /* iconFlags should only contain bits in GTF_ICON_HDL_MASK */
                assert((iconFlags & ~GTF_ICON_HDL_MASK) == 0);
                assertion.op2.u1.iconFlags = iconFlags;
#ifdef _TARGET_64BIT_
                if (op2->TypeGet() == TYP_LONG)
                {
                    assertion.op2.u1.iconFlags |= 1; // Signify that this is really TYP_LONG
                }
#endif // _TARGET_64BIT_
```

2020-01-17 00:23 UTC, AndyAyersMS commented
Hmm, I should have checked the assertion unions more carefully -- the iconFlags overlay the top part of the long value, so once an assertion is created, there's no easy way to check if somebody has inadvertently set the icon flags.

I suppose in a debug build we could keep some extra state?

2020-01-17 00:29 UTC, AndyAyersMS commented
> I suppose in a debug build we could keep some extra state?

Or perhaps just add padding to `IntVal` on 32 bits, so the icon flags aren't overlaying anything.

2020-01-17 00:40 UTC, briansull commented
These flags should not overlap.  I would suggest that we fix that.

2020-01-17 03:28 UTC, AndyAyersMS commented
/AZP run runtime-coreclr outerloop

2020-01-17 08:22 UTC, AndyAyersMS commented
After adding padding, no hits from the new assert in inner or outer loop testing. The padding should not increase the size of the assertion records.

The one remaining failure is in the flaky-seeming trace event test.

2020-01-17 18:50 UTC, briansull approved these changes
Looks Good

2020-01-17 18:50 UTC, briansull commented on src/coreclr/src/jit/assertionprop.cpp
> +        {
Don't really need the braces { } here.

2020-01-17 18:50 UTC, briansull requested changes
I would add a break.

2020-01-17 18:50 UTC, briansull commented on src/coreclr/src/jit/assertionprop.cpp
> +
Should have a break here

2020-01-17 21:28 UTC, briansull approved these changes
LGTM

2020-01-21 16:06 UTC, AndyAyersMS commented
Remaining failures are in the tracevent tests.

2020-01-21 16:08 UTC, merged