Fix GC.GetGCMemoryInfo.TotalAvailableMemoryBytes
dotnet/runtime pull request #31691
Opened 2020-02-03 23:06 UTC by naricc

The current status is that Fix GC.GetGCMemoryInfo.TotalAvailableMemoryBytes (if no limit is set) indicates the total physical memory in the machine, not the physical memory available (after subtracting used memory). This fixes it.

2020-02-04 08:46 UTC, akoeplinger commented
I assume this fixes https://github.com/dotnet/runtime/issues/2280 ?

2020-02-04 10:57 UTC, BrzVlad commented on src/mono/mono/sgen/sgen-memory-governor.c
> +		sgen_gc_info.total_available_memory_bytes = mono_determine_physical_ram_available_size ();
the available ram is ever changing

2020-02-04 10:59 UTC, BrzVlad requested changes
If we are at it, we should also fix the memory load stats which are incorrect.

I'm not sure what the high memory threshold should be, I suggest leaving it 0 for now, rather than have random confusing value.

2020-02-04 16:46 UTC, naricc commented
> I assume this fixes #2280 ?

@akoeplinger   Actually its unrelated. I am still trying to repro that one.

2020-02-04 18:01 UTC, CoffeeFlux reviewed
I find the `ifdef` spam here very difficult to read. If there are enough other functions with platform-specific behavior in here, I'd consider platform-specific source files (maybe Vlad has an opinion here?). Otherwise, I think it's worth at least commenting the endifs with the corresponding if to help make it easier to follow. We don't require that in the codebase as a whole, but for functions like this I think it adds a lot of value.

Also, I realize the code is copy-pasted, but I included some style nits anyway since they're easy to fix :)

2020-02-04 18:01 UTC, CoffeeFlux commented on src/mono/mono/utils/memfuncs.c
> +	host_page_size(host, &page_size);
```suggestion
	host_page_size (host, &page_size);
```

2020-02-05 08:44 UTC, BrzVlad commented
@CoffeeFlux I have no strong opinion on splitting this method up in other source files. I think it would be nice, but I wouldn't consider it as part of this PR.

2020-02-05 18:40 UTC, naricc commented
> If we are at it, we should also fix the memory load stats which are incorrect.
> 
> I'm not sure what the high memory threshold should be, I suggest leaving it 0 for now, rather than have random confusing value.

Currently we are using the major_collection_trigger_size, and updating hte value every time we do a major GC. I didn't realize this was incorrect? I can make it zero.

2020-02-05 21:29 UTC, naricc commented on src/mono/mono/sgen/sgen-memory-governor.c
> +		sgen_gc_info.total_available_memory_bytes = mono_determine_physical_ram_available_size ();
Ah, yeah, that was dumb of me.

2020-02-07 19:58 UTC, naricc commented
I am abandoing this to do a PR that fixes all the stats at once.

2020-02-07 19:58 UTC, closed without merging