Prefer Darwin to OSX
dotnet/runtime pull request #31933
Opened 2020-02-07 18:55 UTC by sdmaclea

Rename TARGET_OSX -> TARGET_DARWIN
Rename TargetsOSX -> TargetsDarwin

2020-02-07 19:03 UTC, CoffeeFlux commented
What is the motivation for this? I suspect it would require more changes on the Mono side in files that aren't mirrored.

2020-02-07 19:07 UTC, BruceForstall commented
Seems like [Darwin](https://en.wikipedia.org/wiki/Darwin_(operating_system)) isn't a name for the "whole" OS, just the core. Could that be more confusing?

IMO, we should just use macOS / MACOS and if Apple changes it again, we can do a big rename again. If that's too disruptive, maybe just leave OSX. After all, we still use "Windows_NT" which drives me bonkers since we haven't used that term for 20 years...

2020-02-07 19:07 UTC, lambdageek requested changes
Mono `TARGET_OSX` define is used to distinguish it from iOS and watchOS; renaming it to `TARGET_DARWIN` is a semantic change.

2020-02-07 19:09 UTC, lambdageek commented on src/mono/configure.ac
> +          CFLAGS_FOR_LIBGC="$CFLAGS_FOR_LIBGC -DTARGET_DARWIN"
The nearby code here is distinguishing the Darwin flavor: ios/watchos/macos

2020-02-07 19:20 UTC, am11 commented
`DARWIN` (like `LINUX` and `ILLUMOS`) is the base system name. `macOS`, `iOS`, `watchOS`, `tvOS` are the OS names. `OSX` is obsolete name. IMO, we can define `DARWIN` and `MACOS` macros, and in (most) cases where we do not need to specialize macos and ios etc., `DARWIN` can be used (as we use `LINUX` and not `DEBIAN` etc.).

2020-02-07 20:05 UTC, sdmaclea commented
> What is the motivation for this?

There was a discussion with @jkotas @am11 and @BruceForstall  where the MACOS, Darwin, OSX inconsistency was noted in coreclr.  This rename was suggested to be more immune to marketing whims.

I have no time invested in this...
I certainly can: 
+ abandon the patch...
+ revise to not touch mono (except mono/System.Private.Corlib)
+ revise to not touch mono or System.Private.CoreLib
+ revise to limit this to the coreclr/jit and rename to MACOS or Darwin.

2020-02-07 20:17 UTC, sdmaclea commented
Abandoning patch until further feedback suggests a better course...

2020-02-07 20:17 UTC, closed without merging

2020-06-26 00:22 UTC, BruceForstall commented
FWIW, the "OSX" name is now even more obsolete than it was before, now that Apple has renumbered the new "Big Sur" OS as macOS 11 (since the "X" was a Roman numeral for version 10).

2020-06-26 08:05 UTC, am11 commented
Sure, it is either `Mac OS X`, `Mac OS 9` (with numbers), or `macOS` without. While working on https://github.com/dotnet/runtime/issues/37923, I found that `/System/Library/CoreServices/SystemVersion.plist` file and `sw_vers` utility (which reads that plist file) tell us `ProductName: Mac OS X` on Mojave and Catalina (although the name was changed to `macOS` in 2016), and Bug Sur (beta) gives us: `ProductName: macOS`. Unless there are backward compatibility concerns, we can start using `macOS` (at least in new code). #naming-is-hard