[mono] Fix msvc mono build
dotnet/runtime pull request #32130
Opened 2020-02-11 19:25 UTC by EgorBo

Fixes
```
fatal error C1083: Cannot open include file: '../../support/libm/complex.c': No such file or directory
```
when `mono-netcore.sln` is opened in vs2019

2020-02-11 19:43 UTC, akoeplinger requested changes
We can't do that since this file is mirrored with mono/mono.

2020-02-11 19:45 UTC, akoeplinger commented
Maybe one way would be to check whether `../mono.proj` exists (or some other file that only exists in dotnet/runtime) and default the property to true in that case?

2020-02-11 22:04 UTC, akoeplinger approved these changes

2020-02-17 08:57 UTC, lateralusX approved these changes

2020-02-17 09:03 UTC, merged