[mono] Include filename in Invalid image error messages
dotnet/runtime pull request #32560
Opened 2020-02-19 20:56 UTC by mdh1418

Fixes #31649 and #31650 

**Testing**:
Reproduced Error via
`<Runtime Repo Root>/build.sh /p:RuntimeFlavor=mono`
Removing `[ActiveIssue("https://github.com/dotnet/runtime/issues/31650", TestRuntimes.Mono)]` in AssemblyTests.cs
Running `dotnet msbuild /t:RebuildAndTest /p:XunitMethodName=System.Reflection.Tests.AssemblyTests.LoadFile_NoSuchPath_ThrowsFileNotFoundException`

Fixing issue resulted in no errors.

2020-02-19 21:15 UTC, CoffeeFlux requested changes
I think we should use `mono_error_set_simple_file_not_found` for some of these FileNotFoundExceptions. It seems to already include the file name in its error message and includes a nicer error message.

Additionally, we should make the change to include the filename with the error message in more than just the function calls failing the tests. There are some cases where it doesn't make sense to do so because we have an in-memory assembly (e.g. `mono_error_set_bad_image_by_name (error, "In memory assembly", "0x%p", assembly_data);`) but otherwise we should try and include it across the board. For FileNotFound, the main candidates are the two calls in icall.c, but we have a bunch of invalid image calls in metadata.c and aot-runtime.c that seem like they would benefit from this.

2020-02-22 19:00 UTC, danmosemsft commented
Please add exactly one area label if the bot doesn't. It trains the bot

2020-02-28 21:00 UTC, CoffeeFlux reviewed
Mostly looks good, just a few little things to fix up.

2020-03-02 19:15 UTC, mdh1418 commented on src/mono/mono/metadata/icall.c
> +	g_assert (!MONO_HANDLE_IS_NULL (name));
Reverted these changes and kept the original code.

2020-03-02 19:25 UTC, CoffeeFlux commented on src/mono/mono/metadata/icall.c
> +	filename = mono_string_handle_to_utf8 (name, error);
Never mind, the access changed because of the macro. It's fine.

2020-03-02 19:27 UTC, mdh1418 commented on src/mono/mono/metadata/metadata.c
> +	const char *image_name = meta && meta->name ? meta->name : "unknown image";
Done

2020-03-02 19:27 UTC, mdh1418 commented on src/mono/mono/metadata/metadata.c
> +	const char *image_name = meta && meta->name ? meta->name : "unknown image";
Done

2020-03-02 19:27 UTC, mdh1418 commented on src/mono/mono/metadata/icall.c
> +				mono_error_set_file_not_found (error, filename, "Assembly %d referenced from assembly %s not found ", i - 1, assembly->image->name);
Reverted the change to keep original code

2020-03-02 19:36 UTC, CoffeeFlux requested changes
So close! Watch out for whitespace changes.

2020-03-02 19:36 UTC, CoffeeFlux commented on src/mono/mono/metadata/metadata.c
> +
Unrelated whitespace change.

2020-03-02 19:36 UTC, CoffeeFlux commented on src/mono/mono/metadata/metadata.c
> +
Unrelated whitespace change.

2020-03-02 19:50 UTC, mdh1418 commented on src/mono/mono/metadata/metadata.c
> +
Thanks for the catch!

2020-03-02 19:51 UTC, mdh1418 commented on src/mono/mono/metadata/metadata.c
> +
Thanks for the catch!

2020-03-02 21:08 UTC, CoffeeFlux approved these changes
Looks good, thanks!

2020-03-03 16:14 UTC, merged