[mono] Reintroduce MERP API
dotnet/runtime pull request #32761
Opened 2020-02-24 20:45 UTC by alexischr

Bring back Mono.Runtime methods used for telemetry by VS4Mac.

/cc @lambdageek @marek-safar

2020-02-24 22:35 UTC, marek-safar requested changes

2020-02-24 22:35 UTC, marek-safar commented on src/mono/netcore/System.Private.CoreLib/src/Mono/Runtime.cs
> +#if MOBILE || XAMMAC_4_5
These defines make no sense here

2020-02-24 22:35 UTC, marek-safar commented on src/mono/netcore/System.Private.CoreLib/src/Mono/Runtime.cs
> +#if !MOBILE
Please remove as well

2020-02-24 22:46 UTC, lambdageek commented
Is `Mono.Runtime` one of those class names that third party code uses to figure out if they're running on Mono?  Maybe we should put this in some less mono-ish namespace.

2020-02-24 23:17 UTC, akoeplinger commented
Yeah I was told removing the `Mono.Runtime` class was intentional so old checks that assumed classic Mono aren't firing on netcore Mono.

2020-02-25 05:33 UTC, jkotas commented on src/mono/netcore/System.Private.CoreLib/src/Mono/Runtime.cs
> +//
Nit: The file should start with the license header.

2020-03-03 15:42 UTC, lambdageek commented
This is not going in in the current form right now. Will open a new PR when needed.

2020-03-03 15:42 UTC, closed without merging