Add System.Type converter for JsonSerializer
dotnet/runtime pull request #34249
Opened 2020-03-29 01:48 UTC by layomia

Fixes https://github.com/dotnet/runtime/issues/31567. Per the conversation in this issue & following triage, this PR adds a new converter for `System.Type` with the following behavior:

- serialization: writes the [`AssemblyQualifiedName`](https://docs.microsoft.com/dotnet/api/system.type.assemblyqualifiedname?view=netcore-3.1) of the `Type` instance. This is compatible with Newtonsoft.Json.

- deserialization: throws `NotSupportedException`, as deserializing `Type` instances from arbitrary user input is a security vulnerability. Relevant path and reader position information is added to the exception message, as applicable.

The behavior before this PR was a `JsonException` (max depth exceeded) on serialization, and `JsonException` on deserialization (most commonly due to the current token being `JsonTokenType.String` rather than `JsonTokenType.StartObject` as the reader expects when parsing object types),

2020-03-29 02:35 UTC, jkotas commented
What's the point of writing `AssemblyQualifiedName` when you cannot deserialize it?

2020-03-29 02:46 UTC, jkotas commented
IMHO, we should throw exception for both serialization and deserialization.

2020-03-29 03:41 UTC, GrabYourPitchforks requested changes
I don't think we can say _A workaround is to use a custom converter_ and leave it at that. What is the implementation of this theoretical custom converter?

If we believe there's a secure way to implement this, the exception text should point to documentation which shows clearly how to do this safely.

2020-03-30 16:50 UTC, jkotas commented on src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Converters/Value/TypeConverter.cs
> +            throw ThrowHelper.GetNotSupportedException_SerializeTypeInstanceNotSupported();
These are not performance sensitive methods by any means. You can just throw from here, no need to factor it out into a helper.

2020-03-30 17:07 UTC, layomia commented
> IMHO, we should throw exception for both serialization and deserialization.

Makes sense to throw since we won't round-trip otherwise.

2020-03-30 17:10 UTC, jkotas approved these changes

2020-03-30 17:14 UTC, layomia commented
> I don't think we can say _A workaround is to use a custom converter_ and leave it at that. What is the implementation of this theoretical custom converter?
> 
> If we believe there's a secure way to implement this, the exception text should point to documentation which shows clearly how to do this safely.

I've removed the note about using a custom converter - users already know they can write one. 

Not sure of a way to implement this safely for arbitrary user input. There doesn't seem to be much appetite to (de)serialize `Type` instances at the moment. If there is in the future, we can add some examples to the JSON docs and extend the exception message to link to them.

2020-03-30 17:51 UTC, bartonjs approved these changes

2020-03-30 18:26 UTC, GrabYourPitchforks commented
> Not sure of a way to implement this safely for arbitrary user input.

It's not safe for arbitrary input, but it can be made safe for known-good inputs. For example, maybe your custom converter maintains a static `Dictionary<string, Type>` of known-allowed inputs. When an arbitrary user-provided string comes in, you look up the entry in that static dictionary, either returning the matched `Type` or throwing due to disallowed input. This mechanism could also be used to perform polymorphic deserialization safely.

It really depends on the application's specific scenario.

2020-03-30 20:22 UTC, layomia commented
Test failure unrelated - https://github.com/dotnet/runtime/issues/28553.

2020-03-30 20:34 UTC, GrabYourPitchforks approved these changes

2020-03-30 20:37 UTC, layomia commented
Test failure unrelated - https://github.com/dotnet/runtime/issues/28553.

2020-03-30 20:37 UTC, merged