Rename ThirdPartyNotices.txt to THIRD-PARTY-NOTICES.txt
dotnet/runtime pull request #34554
Opened 2020-04-05 01:59 UTC by jkredzvr

Renamed instances where ThirdPartyNotices.txt was referenced to upper case naming.

Fixes https://github.com/dotnet/runtime/issues/2243

Please let me know if I've renamed something incorrectly, or if additional files need to be modified as well. 

Thank you

2020-04-05 02:00 UTC, dnfclas commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=34554) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=34554) before we can accept your contribution.<br/><br/>:x: jkredzvr [sign now](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=34554)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/runtime?pullRequest=34554) it.</sub>

2020-04-05 02:05 UTC, jkredzvr commented
There was also a reference to ThirdPartyNotices.txt in the .gitnore but I didnt think it was necessary to change that as well.

2020-04-06 13:20 UTC, MichaelSimons approved these changes

2020-04-12 17:43 UTC, stephentoub commented
@MichaelSimons, should/can this be merged?

2020-04-13 13:11 UTC, MichaelSimons commented
@NikolaMilosavljevic - Can you take a quick look?

2020-04-13 15:32 UTC, NikolaMilosavljevic commented
Taking a look...

2020-04-13 19:15 UTC, NikolaMilosavljevic requested changes
This should not be merged.

@jkredzvr - my apologies for marking the original issue as "up-for-grabs" - my testing of your changes exposed some issues that are blockers for merging the PR.

This file ships with a shared component in .NET Host MSI. Renaming the file without doing more changes in .NET Core 3.1 and .NET 5.0 would result in 2 files installed next to each other, old (ThirdPartNotices.txt) and new (THIRD-PARTY-NOTICES.txt). Further analysis of 3.1 and 5.0 installers is required to solve that problem - tracked as https://github.com/dotnet/runtime/issues/34913

Rejecting this PR to avoid introducing the other issue.

2020-04-27 00:53 UTC, stephentoub commented
Closing per the above comments.  Thanks for the PR, regardless!

2020-04-27 00:53 UTC, closed without merging