Test build target agnostic separately from target specific tests
dotnet/runtime pull request #34658
Opened 2020-04-07 21:22 UTC by sdmaclea

Part of #33066

Modifies build-test to add options to allow building target agnostic tests separately from target specific tests.

+ Audited the `TraitTag`s found a few cases where `TraitTag`s were missed in #637.  Also added `ArchSpecific`
+ @VSadov is working on a generic filtering mechanism.  While waiting for it this PR add an extra property `CLRTestNeedTarget` to indicate a test which is not target agnostic.
+ I had originally tried to build the agnostic tests with `AnyOS` and `AnyCPU`, but I ran into lots of issues.  So I reverted that.

2020-04-07 21:25 UTC, sdmaclea commented
I tested manually building on Linux.  It looks good to me.
I will try building tests on Windows too now.

2020-04-07 21:27 UTC, sdmaclea commented
The simple filtering used in this PR is relatively slow.  It takes a while for MSBuild to find the tests to build.

Generic filtering may be slower.  

It is possible we may need to build test lists to make this faster....

2020-04-07 22:36 UTC, jkoritzinsky requested changes
Can we do a string for `CLRTestNeedTargetToBuild`s value instead of an opaque number that has to be documented somewhere else?

2020-04-07 23:11 UTC, sdmaclea commented
> Can we do a string for `CLRTestNeedTargetToBuild`s 

Your going to make me do the hard work of naming the states.

Effectively right now the states are
 + `CLRTestNeedTargetToBuild == 0` : `False` 
 + `CLRTestNeedTargetToBuild == 1`: `True`
 + `CLRTestNeedTargetToBuild == ''` `BuildAll`

@jkoritzinsky How does `BuildTargetGenericTests` and `BuildTargetSpecificTests` sound for strings. Keeping an empty string for the default behavior.

2020-04-07 23:16 UTC, jkoritzinsky commented
Those work. We could also shorten them to "TargetGeneric" and "TargetSpecific" if you would like.

2020-04-07 23:19 UTC, sdmaclea commented
What about the script option?  Sounds like they should change to 
+ `-buildTargetSpecific`
+ `-buildTargetGeneric`

2020-04-07 23:22 UTC, ivdiazsa commented
I agree with @jkoritzinsky's suggestions. Other than that, LGTM! I'm assuming the test lists building would be done in a separate PR?

2020-04-07 23:22 UTC, ivdiazsa approved these changes

2020-04-07 23:30 UTC, ivdiazsa commented
> What about the script option?  Sounds like they should change to
> 
> -buildTargetSpecific
> -buildTargetGeneric
> 
> or
> 
> -targetSpecific
> -targetGeneric

Both are fine by me. I would vote for the latter choices. Since the script is already called `build-test`, the former ones are a bit redundant.

2020-04-08 00:13 UTC, sdmaclea commented
> I'm assuming the test lists building would be done in a separate PR?

@VSadov Is working on generic filtering.  I was assuming we would wait and see what he comes up with before engineering another solution,

2020-04-08 16:58 UTC, sdmaclea commented
I made the renames per feedback.

I also did a quick benchmark of test building on my local Hyper-V Ubuntu machine. It took `10 minutes` to build `all the tests`.  When using `testSpecific`, the build time dropped to `3 minutes`.

2020-04-08 17:00 UTC, jkoritzinsky approved these changes

2020-04-09 00:08 UTC, sdmaclea commented
quick benchmark - Windows results were about the same as Linux Hyper-V on the same machine.

2020-04-09 00:09 UTC, merged