Fix runtime.native.System.IO.Ports package baseline
dotnet/runtime pull request #34716
Opened 2020-04-08 22:05 UTC by mmitche

This version is not produced in 5.0 and appears it should be baselined at 4.7.0

2020-04-08 22:05 UTC, mmitche commented
I'm not sure about this fix.  It doesn't follow the same pattern as the Windows.Compatibility fixes.

2020-04-08 22:06 UTC, mmitche commented
Shoudl fix https://github.com/dotnet/runtime/issues/34715

2020-04-08 23:22 UTC, Anipik approved these changes

2020-04-09 03:16 UTC, ericstj requested changes
This is incorrect. This is still part of the product and should be built.

2020-04-09 05:48 UTC, closed without merging