Prefix protected fields with underscore for the internal XmlRawWriter
dotnet/runtime pull request #35759
Opened 2020-05-02 22:09 UTC by Marusyk

Add underscore prefix to protected fields for the internal `XmlRawWriter` and its descendant classes 

Issue #35320

Please review
Thank you in advance

2020-05-12 17:46 UTC, stephentoub approved these changes

2020-05-12 22:49 UTC, buyaa-n requested changes
@Marusyk thank you for working on this, added couple of comments for template files, overall looks good to me

2020-05-12 22:49 UTC, buyaa-n commented on src/libraries/System.Private.Xml/src/System/Xml/Core/XmlRawTextWriterGenerator.ttinclude
> +                    RawText("\" _encoding=\"");
This is string output, believe shouldn't have `_`

2020-05-12 22:49 UTC, buyaa-n commented on src/libraries/System.Private.Xml/src/System/Xml/Core/XmlRawTextWriterGenerator.ttinclude
> +            <#= BufferName #> = new <#= BufferType #>[_bufLen + OVERFLOW];
seems `<#= BufferName #>` need to be updated here https://github.com/dotnet/runtime/blob/b0721f1f8415bc5064f898a1e94747ca8965f009/src/libraries/System.Private.Xml/src/System/Xml/Core/RawTextWriterEncoded.ttinclude#L8

2020-05-12 22:49 UTC, buyaa-n commented on src/libraries/System.Private.Xml/src/System/Xml/Core/XmlRawTextWriterGenerator.ttinclude
> +            <#= BufferName #> = new <#= BufferType #>[_bufLen + OVERFLOW];
might be worth run all template for all generated files and build

2020-05-13 23:32 UTC, buyaa-n approved these changes
Thank you @Marusyk LGTM, please merge conflicts

2020-05-18 16:37 UTC, krwq commented
(restarting CI)

2020-05-18 23:52 UTC, merged