Preserve fields of AssemblyLoadContext since its accessed by runtime code through the MonoManagedAssemblyLoadContext structure.
dotnet/runtime pull request #35792
Opened 2020-05-04 14:14 UTC by vargaz

2020-05-04 14:41 UTC, marek-safar approved these changes

2020-05-04 14:52 UTC, CoffeeFlux approved these changes

2020-05-04 14:55 UTC, CoffeeFlux commented
I feel bad about continually missing the LinkerDescriptor changes :(

I know you said CI for it will exist once the wasm lane is up and running, but in the meantime is there anywhere I can see what sorts of changes require me to update it? Is it just direct field accesses and calling managed methods from the runtime?

2020-05-04 15:25 UTC, vargaz commented
Basically, if the runtime needs some types/methods/fields to be preserved to function, those should be added to the linker descriptor. The linker sometimes keeps these things anyway, so its hard to notice when something is missed.

2020-05-05 09:01 UTC, akoeplinger requested changes

2020-05-05 09:01 UTC, akoeplinger commented on src/mono/netcore/System.Private.CoreLib/src/LinkerDescriptor/System.Private.CoreLib.xml
> +		<-- object-internals.h: MonoManagedAssemblyLoadContext -->
This XML comment is wrong (doesn't start with `<!--`) which likely is the reason for the test failures.

It's a bit worrying that this doesn't cause a build error.

2020-05-05 11:16 UTC, akoeplinger approved these changes

2020-05-05 11:33 UTC, merged