Interpret DOTNET_BUNDLE_EXTRACT_BASE_DIR without dir separator as relative path
dotnet/runtime pull request #39331
Opened 2020-07-14 23:03 UTC by mateoatr

Should fix #36804

2020-07-14 23:44 UTC, vitek-karas approved these changes

2020-07-14 23:44 UTC, vitek-karas commented on src/installer/tests/Microsoft.NET.HostModel.Tests/AppHost.Bundle.Tests/BundleExtractToSpecificPath.cs
> +                .HaveStdOutContaining("Hello World");
Nit: If it's not hard, you may also validate that it created the right folder and ran from there.

2020-07-15 15:17 UTC, vitek-karas requested changes
I ran it just out of curiosity - and to be honest I don't understand why we're fixing it here...

The failure happens in `dir_utils_t::create_directory_tree` which ends up in an endless recursion. I think we should fix it there.

2020-07-15 16:14 UTC, vitek-karas commented
Actually the root cause is here: https://github.com/dotnet/runtime/blob/master/src/installer/corehost/cli/hostmisc/utils.cpp#L143

This code doesn't handle relative paths well. Basically if I call `get_directory("name")` it returns `"name/"` and the caller (`create_direcotry_tree` in this case) expects to get back an empty string.

We should either make the utils work with relate paths (which might be pretty tricky) or we should turn the env. variable into an absolute path before we do anything else. So your fix sort of works in that regard, but it's still relatively fragile I think. I think a better solution would be to call `pal::realpath` - based on some docs it should work on just "name" input (and understand it as a "./name" basically).

2020-07-15 16:29 UTC, mateoatr commented
The reason I did not use `realpath` originally was because it fails and returns null whenever the path does not exist (as in this case, since we're just about to create the dir), although we can do `realpath(".")` and then append the relative path...

I think the failures in Windows are due to cases when the path start with a volume, e.g., `C:\\foo` will become `.\\C:\\foo`, which fails.

2020-07-15 18:58 UTC, vitek-karas commented
Good point about `realpath`. I think using the `realpath(".")` feels better - mainly because we can then declare a clear contract of the other methods - pass in absolute paths, always.

2020-07-15 19:20 UTC, vitek-karas approved these changes
Looks good

2020-07-16 03:48 UTC, merged