Fix the condition that determines if initReg was used during function…
dotnet/runtime pull request #39822
Opened 2020-07-23 07:04 UTC by kunalspathak

… prolog generation

2020-07-23 19:47 UTC, kunalspathak commented
@dotnet/jit-contrib

2020-07-23 20:17 UTC, echesakovMSFT commented
Is it possible to reproduce the issue in a regression without requiring JitStress?

2020-07-23 21:12 UTC, kunalspathak commented
> Is it possible to reproduce the issue in a regression without requiring JitStress?

It doesn't repro without JitStressRegs. In fact, the original repro in #39247 didn't require `GCStress` but I had to use `GCStress` and `JitStressRegs` to repro it. I also verified the JIT assembly code without JitStress flag, and in that case, we did generate the needed "zero-init" of initReg.

![image](https://user-images.githubusercontent.com/12488060/88339212-7e366c00-ccee-11ea-8a4e-40b454966c6e.png)

2020-07-23 21:58 UTC, BruceForstall commented
It looks like one of the stress modes caused us to create a very large frame. Note that the failure only occurred with sufficiently large frames that arm64 frame type 3 was required. So it might be possible to construct a test case that already requires such a large frame without JitStress. (It might not be worth the effort.)

2020-07-23 22:09 UTC, kunalspathak commented
> It looks like one of the stress modes caused us to create a very large frame. Note that the failure only occurred with sufficiently large frames that arm64 frame type 3 was required. So it might be possible to construct a test case that already requires such a large frame without JitStress. (It might not be worth the effort.)

I am curious what is frame type 3?

2020-07-23 22:21 UTC, BruceForstall commented
Check the comments in `CodeGen::genPushCalleeSavedRegisters`. Also https://github.com/dotnet/runtime/blob/master/docs/design/coreclr/jit/arm64-jit-frame-layout.md (the numbers in that document don't necessarily correspond to the numbers in the code)

2020-07-24 00:18 UTC, BruceForstall commented
> I did pmi after my change 

Can you clarify what you mean by this?

2020-07-24 00:20 UTC, kunalspathak commented
> > I did pmi after my change
> 
> Can you clarify what you mean by this?

I meant I did `jit-diff diff --pmi` before and after my changes and I don't see any diffs.

2020-07-24 00:48 UTC, BruceForstall commented
Over what set of assemblies did you run diffs? (S.P.C? frameworks? benchmarks? tests?)

Also, I presume this was diffs run on arm64? Or was it with arm64 altjit on x64?

2020-07-24 00:51 UTC, kunalspathak commented
> Over what set of assemblies did you run diffs? (S.P.C? frameworks? benchmarks? tests?)
> 
> Also, I presume this was diffs run on arm64? Or was it with arm64 altjit on x64?

Sorry for not clarifying. It was ran on framework libraries and SPC. I ran it on x64 with `-altjit`.

2020-07-25 19:52 UTC, BruceForstall requested changes
There's still a problem, where arm64 `genPushCalleeSaveRegisters` calls `genPrologSaveRegPair` and `genStackPointerAdjustment`, passing in `pInitRegModified`, where those called functions expect `pTmpRegIsZero` instead -- which has the opposite sense.

2020-07-25 19:52 UTC, BruceForstall commented on src/coreclr/src/jit/codegencommon.cpp
> +//                       'true' if this method sets initReg to non-zero value. Else 'false'.
It's slightly different than this. `*pInitRegModified` is set to `true` if `initReg` is set to a non-zero value, `false` if it is set to zero, and not changed if `initReg` is unused.

2020-07-25 19:52 UTC, BruceForstall commented on src/coreclr/src/jit/codegenarmarch.cpp
> +//     pInitRegModified - OUT parameter. *pInitRegModified is set to 'true' since
I think the original wording is clearer.

2020-07-30 17:12 UTC, kunalspathak commented
Replaced by https://github.com/dotnet/runtime/pull/40148

2020-07-30 17:12 UTC, closed without merging