Fix covariant returns validation
dotnet/runtime pull request #41874
Opened 2020-09-04 16:06 UTC by janvorli

Recent fix to a problem with covariant returns validation has introduced
another problem related to code versioning. The validation method is now
called too late in the type load process which causes problem in
crossgening or in case code versioning is disabled.

This change fixes it by splitting the return type verification and
mutating changes like vtable slot updates into two separate phases, each
called at a proper time.

Close #41853

2020-09-04 17:20 UTC, davidwrighton requested changes
You need to avoid setting RequiresCovariantTypeChecking so often. Covariant type checking is expensive, and while setting the bit extra times isn't a correctness problem it will show up in a profile of the application.

Also, last night I said the assert that was firing looked like there may be a concern caused by misbehavior of MethodTableBuilder::ChangesImplementationOfVirtualSlot in the presence of this feature. However, that assert is pretty fragile and incomplete. These changes make it so that the assert will not fire, but I do not have confidence that the vtable chunk sharing logic may be misbehaving. Have you had a chance to look into that?

2020-09-04 17:20 UTC, davidwrighton commented on src/coreclr/src/vm/class.cpp
> +                pMD->SetRequiresCovariantReturnTypeChecking();
This is setting RequiresCovariantReturnTypeChecking too often. In particular, we should only force set the bit here if the parenteMD RequiresCovariantReturnTypeChecking.

2020-09-04 17:41 UTC, janvorli commented
> Have you had a chance to look into that?

I did and it seems to me there is really a problem there and that the MethodTableBuilder::ChangesImplementationOfVirtualSlot needs to be modified to consider the attribute. However, I'd leave that for another PR since for now, this issue is blocking outerloop, so it needs to be fixed asap.

2020-09-04 17:46 UTC, janvorli commented
> You need to avoid setting RequiresCovariantTypeChecking so often.

Right, the check for the parent MD has somehow fallen out of my latest version by mistake.

2020-09-04 21:19 UTC, davidwrighton approved these changes

2020-09-04 23:23 UTC, merged

2020-09-14 15:46 UTC, janvorli commented
/backport to release/5.0-rc2