Fix vtable chunk sharing with covariant returns
dotnet/runtime pull request #42077
Opened 2020-09-10 16:46 UTC by janvorli

There is an issue causing invalid sharing of a vtable chunk when a
method is overridden using method impl in a class and its parent class
and the slot in the parent class is in a previous vtable chunk. The
algorithm in `MethodTableBuilder::ChangesImplementationOfVirtualSlot` that
detects whether a slot in a vtable chunk was changed doesn't know that
the override will be propagated to all slots occupied by the method
being overridden. In the test attached to this fix, it leads to a stack
overflow due to an infinite recursion in the type system code. It could
also result in an overwrite of the method in the parent class, so when
another class derives from it, it would get a method from its sibling.

This change fixes it by checking if the parent method of a current slot
was overridden in some previous slot in the vtable.

Close #42047

2020-09-10 17:31 UTC, janvorli commented on src/coreclr/src/vm/methodtablebuilder.cpp
> +            for (SLOT_INDEX i = 0; i < idx; i++)
@davidwrighton one thing I was considering here is to run the lookup loop only when the PreserveBaseOverridesAttribute is found on the pParentMD. But I was not sure what is the performance profile of the `MethodDesc::GetCustomAttribute(WellKnownAttribute::PreserveBaseOverridesAttribute, ...)`.

2020-09-10 17:41 UTC, janvorli commented on src/coreclr/src/vm/methodtablebuilder.cpp
> +            for (SLOT_INDEX i = 0; i < idx; i++)
Ah, I haven't realized before that I could call the RequiresCovariantReturnTypeChecking on the pParentMD and that check is cheap.

2020-09-10 17:43 UTC, janvorli commented on src/coreclr/src/vm/methodtablebuilder.cpp
> +            for (SLOT_INDEX i = 0; i < idx; i++)
I've added commit with such a change.

2020-09-10 17:56 UTC, davidwrighton requested changes

2020-09-10 17:56 UTC, davidwrighton commented on src/coreclr/src/vm/methodtablebuilder.cpp
> +
While I believe this is correct, this algorithm is O(n^2) as ChangesImplementationOfVirtualSlot is called for each vtable slot inherited from the parent type. Particular concerns arise from WPF and WinForms scenarios as many of the control classes have >>100 virtual methods.

I believe we either need to 
1. Don't run this algorithm when propagation will not occur. For instance, we have the `HasVTableMethodImpl` check in `PropagateCovariantReturnMethodImplSlots` and checks for PreserveBaseOverridesAttribute before running the secondary loop that makes it O(N^2).
OR 
2. Make the algorithm here not O(N^2)

2020-09-10 19:29 UTC, davidwrighton commented on src/coreclr/src/vm/methodtablebuilder.cpp
> +            if (pParentMD->RequiresCovariantReturnTypeChecking())
This isn't correct. The propagation feature isn't actually tied to covariant return type checking, and I probably should have caught that in the previous change, as the PropagateCovariantReturnMethodImplSlots name isn't really right.

2020-09-10 21:24 UTC, davidwrighton approved these changes

2020-09-11 12:39 UTC, merged

2020-09-14 15:47 UTC, janvorli commented
/backport to release/5.0-rc2