Organize SendReceive tests and isolate non-parallel test collection
dotnet/runtime pull request #44591
Opened 2020-11-12 13:47 UTC by antonfirsov

Some `SendReceive` socket tests may be prone to timing issues on CI. This seems to be the root cause of #1712. We need a reliable way to run such tests to unblock the work on new UDP socket API-s in #33418.

This PR defines a new `SendReceiveNonParallel` test group, moving `SendToRecvFrom_Datagram_UDP` into that group. Since this is already a significant reorganization, it seemed reasonable to also:
- Harmonize naming: all SendReceive test classses are now named either  `SendReceive_[SubVariant]` 
 or `SendReceiveNonParallel_[SubVariant]`
- Split `SendReceive.cs` into multiple files:
    - `SendReceive.cs` for the parallel variants
    - `SendReceiveNonParallel.cs` for the new, non-parallel variants
    - Renamed the non-generic `class SendReceive` to `SendReceiveCommon` (to avoid name collision and confusion with `SendReceive<T>`) and moved it `SendReceiveCommon.cs` 
    - Moved `SendReceiveListener` and `SendReceiveUdpClient` to separate files

Fixes #1712 

/cc @geoffkizer

2020-11-12 16:55 UTC, antonfirsov commented
/azp run runtime-libraries-coreclr outerloop

2020-11-12 17:59 UTC, geoffkizer commented on src/libraries/System.Net.Sockets/tests/FunctionalTests/SendReceive/SendReceiveCommon.cs
> +using System.Collections.Generic;
"Common" is kind of a strange term for this... it seems like it's really just a handful of send/receive related tests that don't fit elsewhere. I'd suggest calling it "SendReceiveMisc.cs" or something like that.

2020-11-12 18:00 UTC, geoffkizer commented on src/libraries/System.Net.Sockets/tests/FunctionalTests/SendReceive/SendReceiveListener.cs
> +using System.Threading.Tasks;
I'd call this file SendReceiveTcpClient to match SendReceiveUdpClient.

2020-11-12 18:02 UTC, geoffkizer requested changes
Generally looks good, but I think we should change a couple class/file names... see above.

2020-11-13 18:42 UTC, antonfirsov commented
/azp run runtime-libraries-coreclr outerloop

2020-11-13 19:54 UTC, geoffkizer approved these changes

2020-11-16 12:47 UTC, antonfirsov commented
The OuterLoop test failures are unrelated (System.Xml, Http and #44015).

2020-11-16 12:50 UTC, merged