BackPorting some of the servicing fixes back into the master
dotnet/runtime pull request #45117
Opened 2020-11-23 18:12 UTC by Anipik

- using the central package version
- fixing the case when no packages are produced 
- Harvesting fix being ported from 3.1

2020-11-23 19:44 UTC, safern requested changes
The conditions related to publish packages to intermediate assets, and to zip package assets to send to helix, and run package tests, should be conditioned to only be true when the target branch is a release branch. So basically it should be an or to run if the target branch is master.

2020-11-24 23:34 UTC, joperezr commented on eng/restore/harvestPackages.targets
> +  <Target Name="AddPackageDownload" DependsOnTargets="_GetBuildingPackageVersions">
```suggestion
  <Target Name="AddPackageDownload" DependsOnTargets="_GetBuildingPackageVersions">
```
NIT: 4 extra spaces

2020-11-24 23:35 UTC, joperezr commented on src/coreclr/dir.common.props
> +    <StableVersion Condition="($(MSBuildProjectName.Contains('Private')) or $(MSBuildProjectName.Contains('Transport'))) and '$(MSBuildProjectExtension)' == '.pkgproj'"></StableVersion>
```suggestion
    <StableVersion Condition="($(MSBuildProjectName.Contains('Private')) or $(MSBuildProjectName.Contains('Transport'))) and '$(MSBuildProjectExtension)' == '.pkgproj'"></StableVersion>
```
NIT: 2 more

2020-11-24 23:36 UTC, joperezr reviewed
Changes related to harvestPackages look good.

2021-01-21 19:44 UTC, ericstj commented
@Anipik what's the state of this PR?

2021-01-21 20:33 UTC, Anipik commented
Some of the changes in this one are already merged. I will take a look if something is left here.

2021-01-22 04:13 UTC, Anipik commented
We can close this one as we wont be using stable version and harvesting fixes going forward.
I have created issue to track the work to fix the servicing path of no packages produced.

2021-01-22 04:13 UTC, closed without merging