Adding support for W3C Baggage header
dotnet/runtime pull request #45839
Opened 2020-12-09 15:10 UTC by jbogard

Preserves backward compatibility for legacy `Correlation-Context` header name;

Addresses #45496

2021-01-04 17:43 UTC, ericstj commented
@tommcdon @karelz it looks like this is touching HttpHandlerDiagnosticListener which was added in https://github.com/dotnet/corefx/pull/18101.  According to comments https://github.com/dotnet/runtime/blob/7ad42b7046751636781689053f810c31144253be/src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/HttpHandlerDiagnosticListener.cs#L17-L25

I think we need someone from both @dotnet/ncl  and @dotnet/dotnet-diag to review this.

2021-01-04 17:47 UTC, tarekgh commented
CC @noahfalk

2021-01-05 16:17 UTC, sdmaclea approved these changes, later dismissed
LGTM

2021-01-05 16:33 UTC, josalem approved these changes
The diagnostics changes look okay to me (maintains the old header name for back-compat and adds a test covering both header names).  I can't comment on the correctness of the header names, etc.

2021-01-07 11:26 UTC, noahfalk requested changes
I want to pump the brakes on this a bit but I do appreciate the PR! A couple thoughts:

1. The .NET team has been burned a bit in the past implementing W3C distributed tracing specs that weren't finalized. We were assured the specs were stable so we took a dependency on the prescribed names and then after our APIs were already released one of the names was changed. Although its water under the bridge, it was also lesson learned... we have to be wary implementing draft specs. I'm fine doing something in an experimental capacity such as a fork, an ifdef, a runtime check, etc, but I am not comfortable emitting the baggage header by default at this time.

2. Preferably I'd like us to decide on a plan that accounts for all versions of .NET where DiagnosticSource.dll runs before we start committing to specific implementations. I expect some differences in design or implementation will be necessary, but I want to make sure we minimizing them as much as possible. There is likely high overlap with the custom propagators request that recently showed up: https://github.com/dotnet/aspnetcore/issues/28642

3. Even if the framework has some default behavior, this seems like a spot where we might want to give the app the final say about which headers, if any, get emitted? Baggage is potentially large and double-encoding it just in case might be problematic for some scenarios. There are also some .NET developers who object to the Http stack adding any header to their request implicitly. If there was an API to opt-in to the new baggage header that also might alleviate the concern in part (1) while allowing early adopters to utilize it.

I think a good next step would be to first make a design proposal in https://github.com/dotnet/runtime/issues/45496 that covers the suggested behavior/API for all versions of .NET. I don't think baggage should start on by default but you are welcome to propose otherwise if you have reasons to disagree. The proposal could also be converged with the [propoagators](https://github.com/dotnet/aspnetcore/issues/28642) work or you could say why you think combining it is a bad idea.

2021-02-23 15:17 UTC, noahfalk commented
I'm going to go ahead and close this PR for now. I'm not at all opposed to having .NET support this in some capacity but there are some issues above that I think need to be addressed first. Thanks @jbogard!

2021-02-23 15:17 UTC, closed without merging

2021-02-24 15:36 UTC, jbogard commented
No worries, thanks for taking a look!