Fix Socket.ReceiveFrom on Unix
dotnet/runtime pull request #46151
Opened 2020-12-16 18:02 UTC by antonfirsov

Fix #45651. The bug happens when a synchronous `ReceiveFrom` is being used after asynchronous `SendToAsync` call(s) on the same socket. As @tmds pointed out in https://github.com/dotnet/runtime/issues/45651#issuecomment-744637362, we did not set `SetReceiveFlags = true` in `SocketAsyncContext.ReceiveFrom`
https://github.com/dotnet/runtime/blob/31062e4ec6b248b709095e13947400b49d507e53/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncContext.Unix.cs#L1510-L1516

which resulted in `BufferedMemoryReceieveOperation` completion attempt with `recv` instead of `recvmsg`:
https://github.com/dotnet/runtime/blob/31062e4ec6b248b709095e13947400b49d507e53/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncContext.Unix.cs#L473-L479

Our existing UDP tests (`SendToRecvFrom_Datagram_UDP`) did not exercise `BufferMemoryReceiveOperation`, because completion of the synchronous `ReceiveFrom` always happened without the use of `_receiveQueue`:

https://github.com/dotnet/runtime/blob/31062e4ec6b248b709095e13947400b49d507e53/src/libraries/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncContext.Unix.cs#L1505-L1508

For reasons I don't understand, this path gets only executed if a synchronous `ReceiveFrom` is being called after an asynchronous operation. The PR adds tests for that case for multiple async variants.
Another weird thing: while my standalone repro resulted in in an assertion failure (https://github.com/dotnet/runtime/issues/45651#issuecomment-744631080), the new tests timeout instead. (But both issues are fixed with `SetReceiveFlags = true`.)

We shall consider adding similar tests for TCP send/receive probably.

2020-12-16 18:02 UTC, antonfirsov commented
@tmds @geoffkizer please take a look. Note: starting from tomorrow, I will be on vacation until the 4th of January, looking at GitHub occasionally.

2020-12-16 18:38 UTC, wfurt approved these changes
LGTM

2020-12-17 00:46 UTC, geoffkizer commented
> For reasons I don't understand, the BufferMemoryReceiveOperation path gets only executed if a synchronous ReceiveFrom is being called after an asynchronous operation. The PR adds tests for that case for multiple async variants.

This is the "sync-over-async" path in SocketAsyncContext.

What happens is this: The OS socket starts out in blocking mode. If you only perform sync IO, it will stay in blocking mode. But as soon as you perform an async IO, we need to switch to nonblocking mode at the OS level. But we still support performing sync operations, even though the underlying OS socket is nonblocking. We do this by simulating sync operations on top of the async infrastructure in SocketAsyncContext. So the sync caller will block on a ManualResetEventSlim that we signal when the operation can proceed, and from the user's point of view this looks and behaves like sync IO, even though under the covers it actually is done using a nonblocking socket and epoll.

We do have a bunch of tests for this. See `SocketHelperSyncForceNonBlocking`. Unfortunately, it seems that these tests only use the sync overloads that take byte[], not the ones that take Memory. We should probably add another case here.

2020-12-17 00:50 UTC, geoffkizer requested changes
The fix itself looks fine. (Edited:) But can we fix the tests as suggested above instead of adding a standalone test?

2021-01-04 17:31 UTC, stephentoub commented on src/libraries/System.Net.Sockets/src/System/Net/Sockets/SocketAsyncContext.Unix.cs
> +                SetReceivedFlags = true,
Product fix LGTM

2021-01-05 17:09 UTC, antonfirsov commented
@geoffkizer `ForceNonBlocking` seems to be sufficient to reproduce the issue. I pushed a change that applies it with the help of `SocketTestHelper`, PTAL.

2021-01-05 17:21 UTC, geoffkizer commented
Are there other UDP tests that should be calling ConfigureNonBlocking? Seems like there must be.

2021-01-05 17:35 UTC, antonfirsov commented
I was able to find only one more among the generic tests utilizing SocketTestHelper infrastructure (`UdpReceiveGetsCanceledByDispose`), pushed a change for that.

2021-01-05 18:29 UTC, geoffkizer approved these changes

2021-01-06 11:39 UTC, antonfirsov commented
I don't know what "runtime-staging" is but it seems to fail because of an iOS build timing out, which is unrelated to this change.

2021-01-06 12:22 UTC, merged

2021-01-06 12:26 UTC, antonfirsov commented
/backport to release/5.0