Update TraceEvent version
dotnet/runtime pull request #46655
Opened 2021-01-06 22:44 UTC by sywhang

We're using 2.0.5 version of TraceEvent for testing which is from 2018.. This PR bumps up the version to the latest release (2.0.64).

2021-01-06 22:47 UTC, stephentoub approved these changes

2021-01-06 22:48 UTC, josalem approved these changes

2021-01-06 22:56 UTC, josalem requested changes
I just noticed this:  we have two different references to TraceEvent.  Can you consolidate them to use the same version?

https://github.com/dotnet/runtime/blob/2f03850bade9930757281f8840b5c6745f3f9a3a/eng/Versions.props#L129

and 

https://github.com/dotnet/runtime/blob/2f03850bade9930757281f8840b5c6745f3f9a3a/eng/Versions.props#L150

The former is used in the `src/tracing/*` tests while the latter is used in the `System.Diagnostics.Tracing*` tests.

2021-01-06 22:58 UTC, sywhang commented
Good idea - I'll update this PR to do that.

2021-01-06 23:14 UTC, josalem approved these changes

2021-01-07 01:59 UTC, sywhang commented
There are some profiler eventpipe tests that are failing in checked builds. I'm investigating what the cause is.

2021-01-13 05:00 UTC, merged