Fix Ilasm Round Trip script by adding retry logic
dotnet/runtime pull request #46765
Opened 2021-01-08 19:59 UTC by briansull

Fixes Issue #44139

2021-01-08 20:10 UTC, briansull commented
/azp run runtime-coreclr jitstress

2021-01-11 17:13 UTC, briansull commented
/azp run runtime-coreclr jitstress

2021-01-11 20:32 UTC, briansull commented
@BruceForstall PTAL

2021-01-11 21:49 UTC, BruceForstall requested changes
looks great with just the one issue

2021-01-11 21:49 UTC, BruceForstall commented on src/tests/Common/CLRTest.Jit.targets
> +    sleep 10
Looks like `ilasm_count` is never incremented.

2021-01-11 21:49 UTC, BruceForstall commented on src/tests/Common/CLRTest.Jit.targets
> +    if [ $ilasm_count -eq 3 ]
Maybe this should be a `>=` instead of `==`? (is that `-ge`?)

2021-01-12 17:29 UTC, BruceForstall approved these changes

2021-01-12 20:33 UTC, briansull commented
Updated with requested fix

2021-01-12 20:33 UTC, merged