My initial changes to fix issue 32972
dotnet/runtime pull request #47089
Opened 2021-01-17 07:00 UTC by mihir-b-shah

#32972

This tries to fix this referenced issue.
It changes to the multiplicative growth, renames a makefile to allow compilation, and removes it from the .gitignore.

I am a newcomer to open source so please tell me if I have not submitted something right, thank you!

2021-01-17 18:48 UTC, lambdageek requested changes
The `Makefile.am.in`->`Makefile.am` file change is not necessary.

In dotnet/runtime MonoVM doesn't use autotools anymore, we use `cmake`.

In mono/mono (where this PR is mirrored), the `Makefile.am.in` file is intentional - it's used by the packaging process when producing official Mono packages.

---

As for the substantive change in this PR, it looks good. We should keep an eye on the perf numbers after we merge this, @CoffeeFlux .

2021-01-17 18:50 UTC, lambdageek commented on src/mono/mono/eglib/garray.c
> +	new_capacity = ((capacity*3 >> 1) + 63) & ~63;
might be better to do this computation as a shift and an add instead.

2021-01-17 19:45 UTC, CoffeeFlux commented
Yep re: perf, cc: @naricc

2021-01-17 20:25 UTC, danmosemsft commented
@mihir-b-shah could you please retitle the PR to suggest what the change is? that makes it easier when browsing PRs.

2021-01-17 21:57 UTC, mihir-b-shah commented
Hi I changed the issue name and changed to a shift and add, I also reversed the makefile change.

2021-01-18 15:37 UTC, lambdageek commented
@mihir-b-shah `Makefile.am` and the change to `.gitignore` looks like it's still in the PR.

You can probably do something like this:
git rm src/mono/mono/mini/Makefile.am
git reset c7fda3b94a50297e6ece9db4ddc79ed039394dd3 -- src/mono/mono/mini/.gitignore
git restore --source=c7fda3b94a50297e6ece9db4ddc79ed039394dd3 -- src/mono/mono/mini/.gitignore
git add -A src/mono/mono/mini
git commit -m "undo changes to mono/mini/Makefile.am"
```

2021-01-18 16:49 UTC, mihir-b-shah commented
Hi I fixed it I think the Makefile.am is gone and it is restored to the gitignore.

2021-01-18 19:45 UTC, lambdageek approved these changes

2021-01-19 04:06 UTC, danmosemsft commented
@mihir-b-shah FYI a tip, if you edit your top comment to change "#32972" to "Fixes #32972" then github will close the issue when this is merged.

2021-01-19 13:20 UTC, CoffeeFlux commented
Just waiting on CI for the mono/mono mirror PR—I've restarted the failing lanes, so hopefully that should be done soon. Thanks for your contribution!

2021-01-19 16:31 UTC, naricc commented
@CoffeeFlux We don't have the capacity to do a full perf run for every change, only the ones we expect to have a wide impact across multiple benchmarks. So I don't plan to do one of this change. I will monitor the weekly runs after this change though.

2021-01-19 17:31 UTC, CoffeeFlux commented
Yeah I don't think we need a separate run for this, just wanted to make sure you're aware it exists since it likely has perf implications. 🙂

2021-01-19 22:56 UTC, merged

2021-01-19 22:57 UTC, lambdageek commented
Thanks for the contribution @mihir-b-shah !