Introducing support for callchain profile-driven optimizations
dotnet/runtime pull request #47664
Opened 2021-01-30 00:12 UTC by trylek

After adding support for calculating callchain profile statistics
as an initial attempt at compile-time measure for code layout
quality, I have implemented an initial algorithm for method
placement based on the statistics. The algorithm is trivial, it
just sorts all caller-callee pairs resolved from the profile
by descending call counts and then goes through the list and
just places methods in the order in which they are found,
putting non-profiled methods last. In the System.Private.CoreLib
compilation using the profile file

simple_new_model_two_apps_1_7.json

(not yet the latest one from Siva with signatures), I'm seeing
the following difference in the statistics:

--callchain-method:none

CHARACTERISTIC            | PAIR COUNT | CALL COUNT | PERCENTAGE
----------------------------------------------------------------
ENTRIES TOTAL             |        291 |     266229 |     100.00
RESOLVED ENTRIES          |        267 |     260172 |      97.72
UNRESOLVED ENTRIES        |         24 |       6057 |       2.28
NEAR (INTRA-PAGE) CALLS   |        145 |     109055 |      40.96
FAR (CROSS-PAGE) CALLS    |        122 |     151117 |      56.76

--callchain-method:sort

CHARACTERISTIC            | PAIR COUNT | CALL COUNT | PERCENTAGE
----------------------------------------------------------------
ENTRIES TOTAL             |        291 |     266229 |     100.00
RESOLVED ENTRIES          |        267 |     260172 |      97.72
UNRESOLVED ENTRIES        |         24 |       6057 |       2.28
NEAR (INTRA-PAGE) CALLS   |        237 |     260110 |      97.70
FAR (CROSS-PAGE) CALLS    |         30 |         62 |       0.02

While the initial results seem encouraging, I guess that's mostly
because the profile used is very small, I guess that with more
complex profiles and / or with composite compilation of the entire
framework things may become substantially more complex.

Thanks

Tomas

/cc @dotnet/crossgen-contrib
/cc @siva-msft

2021-01-30 00:48 UTC, davidwrighton requested changes
@trylek, could you integrate this with the ReadyToRunFileLayoutOptimizer instead of building a parallel structure. It is already capable of re-ordering methods, as well as other parts of the PE file, and has a mechanism for specifying a set of algorithms already.

Also, I misunderstood the work that @nattress had done earlier. We really should be putting the CallChainProfile in with the rest of the ProfileData that comes from mibc processing. The `CallWeights` property of the `MethodProfileData` is intended to correspond to the CallChain profile of an application, although as it hasn't had any real use, it may need further work.

2021-01-30 01:13 UTC, davidwrighton commented
@trylek, I think its reasonable to just address my concern around the `ReadyToRunFileLayoutOptimizer` in this PR. We can unify the `ProfileData` handling later.

2021-02-08 19:42 UTC, trylek commented
@davidwrighton - thanks for your feedback, that actually made the change much simpler (as can be probably expected). As I needed to further beef up the method <code>ApplyProfileGuidedMethodSort</code>, I have slightly refactored it by moving the method ordering into a separate method <code>ApplyMethodSort</code> and I changed the code to use the <code>switch</code> statement. Could you please take another look when you have a chance? The statistics shown at the top of this PR are unchanged, this is a pure code shuffle without functional changes.

2021-02-08 23:38 UTC, davidwrighton approved these changes

2021-02-09 00:27 UTC, merged