Reimplement APM UDP Socket methods on top of task variants and consolidate related tests
dotnet/runtime pull request #47781
Opened 2021-02-02 19:52 UTC by antonfirsov

Contributes to #43845.

- Reimplements `(Begin|End)(SendTo|ReceiveFrom|ReceiveMessageFrom)` on top of the new Task-based variants, and deletes unused code
- Moves all related argument validation tests from `ArgumentValidationTests.cs` to `SendTo.cs`, `ReceiveFrom.cs` and `ReceiveMessageFrom.cs`, and extends coverage. Note that the new test code does not validate `ArgumentException.ParamName`,  since it's very inconsistent across all the overloads.

@geoffkizer PTAL.

2021-02-02 22:02 UTC, gfoidl reviewed
For creating the Memories be consistent and always use the extension method?

2021-02-02 22:02 UTC, gfoidl commented on src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.cs
> +            Task<SocketReceiveFromResult> t = ReceiveFromAsync(new Memory<byte>(buffer, offset, size), socketFlags, remoteEP).AsTask();
```suggestion
            Task<SocketReceiveFromResult> t = ReceiveFromAsync(buffer.AsMemory(offset, size), socketFlags, remoteEP).AsTask();
```

2021-02-04 05:42 UTC, geoffkizer commented on src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.cs
> +            if (t.IsCompletedSuccessfully)
I don't understand why we need to do this. We should at least add a comment explaining this. (Similarly below)

2021-02-04 05:48 UTC, geoffkizer commented
I assume all the deleted ArgumentValidationTests got migrated to tests in the appropriate test file?

Seems like it would be nice to do the same for other tests in ArgumentValidationTests.... not for this PR of course.

2021-02-04 05:49 UTC, geoffkizer requested changes
Just the one issue re remoteEP handling in Begin below... this is probably just a matter of adding a comment, but I'd like to understand it before we merge.

2021-02-04 15:58 UTC, antonfirsov commented
@geoffkizer added some comments. Here is test code checking the mentioned historical behavior, it would fail without the `if (t.IsCompletedSuccessfully)` stuff:
https://github.com/dotnet/runtime/blob/fa5429326ec38b93dd6fa10e0dc3363ea36153be/src/libraries/System.Net.Sockets/tests/FunctionalTests/ReceiveMessageFrom.cs#L317-L327

It wouldn't make sense to pass `remoteEP` by `ref` if we wouldn't update it in case of synchronous completions. Note that this is the vast majority of cases (literally 100% on Windows).

2021-02-04 15:59 UTC, antonfirsov commented on src/libraries/System.Net.Sockets/src/System/Net/Sockets/Socket.cs
> +            Task<int> task = SendToAsync(buffer.AsMemory().Slice(offset, size), socketFlags, remoteEP).AsTask();
Thanks for the suggestion! Applied everywhere.

2021-02-04 16:03 UTC, antonfirsov commented
> I assume all the deleted ArgumentValidationTests got migrated to tests in the appropriate test file?

Yeah, this is the case, I went through existing tests carefully to make sure there is no loss in coverage.

> Seems like it would be nice to do the same for other tests in ArgumentValidationTests.... not for this PR of course.

I have a long One Note document listing Sockets.Tests tech debt (including the existence of `ArgumentValidationTests.cs`. Maybe worth to turn it into an issue?

2021-02-04 16:09 UTC, antonfirsov commented
/azp run runtime-libraries-coreclr outerloop

2021-02-04 16:43 UTC, geoffkizer commented
> I have a One Note document listing Sockets.Tests debt (including the existence of ArgumentValidationTests.cs). Maybe worth to turn it into an issue?

Yeah, that seems good.

2021-02-04 16:48 UTC, geoffkizer commented
> It wouldn't make sense to pass remoteEP by ref if we wouldn't update it in case of synchronous completions. Note that this is the vast majority of cases (literally 100% on Windows).

Yeah, this behavior is pretty weird -- I think this is counter to the standard IAsyncResult pattern. Thanks for clarifying why we need to do this.

2021-02-04 16:48 UTC, geoffkizer approved these changes

2021-02-05 04:07 UTC, geoffkizer commented
A couple of the DualMode SendTo tests are failing, can you look at these?

2021-02-05 11:22 UTC, antonfirsov commented
@geoffkizer it's the same test failing everywhere (I was lazy to run outerloop locally).

The cause is that `Socket_BeginSendToV4IPEndPointToV4Host_Throws` expects the method to fail with a synchronous `SocketException` in case `WSASendTo` returns an error, but our established pattern of wrapping Tasks does not work like this: when a faulted task is returned, we don't throw immediately, but convert it to an `IAsyncResult` that will throw in the corresponding `End***` call instead.

2021-02-08 16:38 UTC, antonfirsov commented
/azp run runtime-libraries-coreclr outerloop

2021-02-08 16:41 UTC, antonfirsov commented
@geoffkizer I pushed a workaround for the test failure (b3e035e55645d15bb8af0f55dd5b255c80d12cfa). Do you think the PR is OK to merge in it's current form?

2021-02-08 20:41 UTC, geoffkizer commented
Yep, LGTM

2021-02-09 11:47 UTC, antonfirsov commented
Outer loop test failures are unrelated: #48049, #41606, #1724, #43877

2021-02-09 16:02 UTC, merged