BOOL -> bool in compiler.h #48317
dotnet/runtime pull request #48563
Opened 2021-02-21 00:11 UTC by JeremyEspresso

This changes `BOOL` to `bool` for all methods that still had `BOOL` as a return type in compiler.h

2021-02-21 23:37 UTC, AndyAyersMS commented
cc @dotnet/jit-contrib 

That looks like it was fairly straightforward.

2021-02-22 21:13 UTC, BruceForstall requested changes
I pointed out a few things.

I think the change needs to be more all-in-one comprehensive, not just changing return types. It also needs to change the use of `BOOL` types in functions, and removing the use of `FALSE`/`TRUE`.

2021-02-22 21:13 UTC, BruceForstall commented on src/coreclr/jit/compiler.h
> +    bool lvaIsOriginalThisReadOnly();           // return TRUE if there is no place in the code
nit: Change `TRUE` (Windows BOOL value) to `true`

2021-02-22 21:13 UTC, BruceForstall commented on src/coreclr/jit/importer.cpp
> +bool Compiler::verMergeEntryStates(BasicBlock* block, bool* changed)
All the `return` statements here need to replace `FALSE` with `false` and `TRUE` with `true`.

The same is the case with other of these functions where the return value was changed.

2021-02-26 00:19 UTC, BruceForstall requested changes
Thanks for the updates. Two more requests.

2021-02-26 00:19 UTC, BruceForstall commented on src/coreclr/jit/typeinfo.cpp
> +bool Compiler::tiCompatibleWith(const typeInfo& child, const typeInfo& parent, bool normalisedForStack) const
below: change `BOOL compatible` => `bool compatible`

2021-02-26 00:19 UTC, BruceForstall commented on src/coreclr/jit/typeinfo.cpp
> +bool Compiler::tiMergeToCommonParent(typeInfo* pDest, const typeInfo* pSrc, bool* changed) const
below: change `BOOL mergeable` => `bool mergeable`

2021-02-26 22:00 UTC, BruceForstall approved these changes
LGTM. Thanks for the contribution.

2021-02-26 23:56 UTC, merged