Fix marshaling in HostFXR API test
dotnet/runtime pull request #49386
Opened 2021-03-09 19:51 UTC by mateoatr

We currently marshal size fields (which are of `size_t` type in native code) as `int`, which is always a 32-bit integer, whereas `size_t` will change its bitness depending on the architecture (it's a little strange that tests pass in every architecture anyway?) Regardless, the correct thing to do here seems to marshal as `UIntPtr` and decide whether to cast it to `uint` or `ulong` depending upon the architecture of the running machine.

2021-03-09 19:59 UTC, jkotas commented on src/installer/tests/Assets/TestProjects/HostApiInvokerApp/HostFXR.cs
> +            [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Auto)]
Can we delete `Utils.OSCharSet` now?

2021-03-09 20:03 UTC, vitek-karas requested changes

2021-03-09 20:03 UTC, vitek-karas commented on src/installer/tests/Assets/TestProjects/HostApiInvokerApp/HostFXR.cs
>              internal struct hostfxr_dotnet_environment_info
The `sdk_count` and `framework_count` are also `size_t` in native, so they should also become `UIntPtr`.

2021-03-09 20:17 UTC, AaronRobinsonMSFT commented on src/installer/tests/Assets/TestProjects/HostApiInvokerApp/HostFXR.cs
> +                internal UIntPtr size;
This should be `nuint` - which is `UIntPtr` but conveys the desired idea of `size_t`.

2021-03-09 20:17 UTC, AaronRobinsonMSFT commented on src/installer/tests/Assets/TestProjects/HostApiInvokerApp/HostFXR.cs
> +                if ((IntPtr.Size == 4 && (env_info_size != (uint)environment_info.size)) ||
`IntPtr.Size == 4` Do we ever run our tests in 32-bit? Also, this is calling into itself, right? If so I don't see why this is needed.

2021-03-10 21:13 UTC, vitek-karas approved these changes

2021-03-10 21:31 UTC, AaronRobinsonMSFT approved these changes

2021-03-11 07:22 UTC, merged