JIT: Don't allocate string literals inside potential BBJ_THROW candidates
dotnet/runtime pull request #50112
Opened 2021-03-23 17:32 UTC by EgorBo

Together with https://github.com/dotnet/runtime/pull/48589, this PR addresses https://github.com/dotnet/runtime/issues/48573#issuecomment-782910710

Example:
```csharp
using System;

class Prog
{
    static void Main(string[] args)
    {
        ThrowIfNull(args, nameof(args));
    }

    private static void ThrowIfNull(object arg, string argName)
    {
        if (arg is null)
            ThrowAE(argName);
    }

    private static void ThrowAE(string arg) => throw new ArgumentNullException(arg);
}
```
Codegen diff for `Main`: https://www.diffchecker.com/tZAYRdBY

As you can see, `nameof(args)` literal is not allocated on heap during JIT compilation, a lazy-allocate helper is emitted instead.

jit-diff (`jit-utils -f --pmi`):
```
PMI CodeSize Diffs for System.Private.CoreLib.dll, framework assemblies for  default jit

Summary of Code Size diffs:
(Lower is better)

Total bytes of base: 52999910
Total bytes of diff: 53058790
Total bytes of delta: 58880 (0.11% of base)
    diff is a regression.

Top file regressions (bytes):
       39746 : System.Collections.Immutable.dasm (3.08% of base)
        3816 : FSharp.Core.dasm (0.10% of base)
        3724 : System.Collections.Concurrent.dasm (0.96% of base)
        1722 : System.Private.DataContractSerialization.dasm (0.23% of base)
        1442 : System.Private.Xml.dasm (0.04% of base)
         985 : System.Speech.dasm (0.23% of base)
         982 : System.DirectoryServices.dasm (0.23% of base)
         929 : System.Data.Common.dasm (0.06% of base)
         796 : CommandLine.dasm (0.16% of base)
         641 : System.DirectoryServices.AccountManagement.dasm (0.17% of base)
         611 : Microsoft.CodeAnalysis.VisualBasic.dasm (0.01% of base)
         428 : System.Data.OleDb.dasm (0.15% of base)
         422 : System.Private.CoreLib.dasm (0.01% of base)
         345 : System.Net.Sockets.dasm (0.20% of base)
         344 : System.IO.Packaging.dasm (0.39% of base)
         276 : Newtonsoft.Json.dasm (0.03% of base)
         271 : System.Net.Http.WinHttpHandler.dasm (0.29% of base)
         165 : System.Configuration.ConfigurationManager.dasm (0.05% of base)
         135 : Microsoft.CodeAnalysis.CSharp.dasm (0.00% of base)
         130 : System.Text.Json.dasm (0.02% of base)

44 total files with Code Size differences (0 improved, 44 regressed), 227 unchanged.

Top method regressions (bytes):
        2025 (16.17% of base) : FSharp.Core.dasm - Array2DModule:CopyTo(ref,int,int,ref,int,int,int,int) (8 methods)
         710 ( 5.09% of base) : System.Collections.Immutable.dasm - ImmutableHashSet`1:SymmetricExcept(IEnumerable`1,MutationInput):MutationResult (8 methods)
         640 (14.24% of base) : System.Collections.Immutable.dasm - ImmutableList`1:ConvertAll(Func`2):ImmutableList`1:this (64 methods)
         640 (14.24% of base) : System.Collections.Immutable.dasm - Builder:ConvertAll(Func`2):ImmutableList`1:this (64 methods)
         580 ( 7.97% of base) : System.Collections.Immutable.dasm - Node:NodeTreeFromList(IOrderedCollection`1,int,int):Node (24 methods)
         504 ( 7.04% of base) : System.Collections.Immutable.dasm - ImmutableHashSet`1:Intersect(IEnumerable`1,MutationInput):MutationResult (8 methods)
         390 ( 4.44% of base) : System.Collections.Immutable.dasm - Builder:AddRange(IEnumerable`1):this (32 methods)
         384 (25.08% of base) : System.Collections.Immutable.dasm - ImmutableSortedDictionary`2:.ctor(Node,int,IComparer`1,IEqualityComparer`1):this (8 methods)
         352 (25.79% of base) : System.Collections.Immutable.dasm - MutationInput:.ctor(SortedInt32KeyNode`1,IEqualityComparer`1,IEqualityComparer`1,int):this (8 methods)
         320 (15.62% of base) : System.Collections.Immutable.dasm - Builder:Sort(int,int,IComparer`1):this (16 methods)
         320 ( 4.75% of base) : System.Collections.Immutable.dasm - Node:CopyTo(ref,int):this (16 methods)
         320 ( 8.36% of base) : System.Collections.Immutable.dasm - Node:CopyTo(int,ref,int,int):this (8 methods)
         320 ( 3.54% of base) : System.Collections.Immutable.dasm - Node:CopyTo(Array,int):this (16 methods)
         310 ( 4.07% of base) : System.Collections.Immutable.dasm - ImmutableHashSet`1:Except(IEnumerable`1,IEqualityComparer`1,IEqualityComparer`1,SortedInt32KeyNode`1):MutationResult (8 methods)
         308 (17.94% of base) : System.Collections.Immutable.dasm - Builder:get_Origin():MutationInput:this (16 methods)
         300 ( 7.18% of base) : System.Collections.Immutable.dasm - Builder:set_KeyComparer(IEqualityComparer`1):this (16 methods)
         296 ( 7.29% of base) : System.Data.Common.dasm - DataTable:DeserializeTableSchema(SerializationInfo,StreamingContext,bool):this
         272 ( 8.80% of base) : System.Collections.Immutable.dasm - ImmutableSortedDictionary`2:WithComparers(IComparer`1,IEqualityComparer`1):ImmutableSortedDictionary`2:this (8 methods)
         261 (39.13% of base) : FSharp.Core.dasm - ListModule:loop@474-29(int,int,FSharpList`1):FSharpList`1 (8 methods)
         256 (12.22% of base) : System.Collections.Immutable.dasm - ImmutableArray:Create(ref,int,int):ImmutableArray`1 (8 methods)

Top method improvements (bytes):
         -41 (-0.59% of base) : System.Private.Xml.dasm - <ParseXmlDeclarationAsync>d__505:MoveNext():this

Top method regressions (percentages):
          18 (100.00% of base) : System.Collections.Concurrent.dasm - ThrowHelper:ThrowKeyNullException()
         261 (39.13% of base) : FSharp.Core.dasm - ListModule:loop@474-29(int,int,FSharpList`1):FSharpList`1 (8 methods)
          23 (35.94% of base) : System.Private.DataContractSerialization.dasm - XmlReaderDelegator:ReadContentAsBoolean():bool:this
          23 (35.94% of base) : System.Private.DataContractSerialization.dasm - XmlReaderDelegator:ReadContentAsSingle():float:this
          23 (35.94% of base) : System.Private.DataContractSerialization.dasm - XmlReaderDelegator:ReadContentAsDouble():double:this
          23 (35.94% of base) : System.Private.DataContractSerialization.dasm - XmlReaderDelegator:ReadContentAsDecimal():Decimal:this
          23 (35.94% of base) : System.Private.DataContractSerialization.dasm - XmlReaderDelegator:ReadContentAsDateTime():DateTime:this
          23 (35.94% of base) : System.Private.DataContractSerialization.dasm - XmlReaderDelegator:ReadContentAsInt():int:this
          23 (35.94% of base) : System.Private.DataContractSerialization.dasm - XmlReaderDelegator:ReadContentAsLong():long:this
          18 (30.51% of base) : System.Runtime.Caching.dasm - MemoryCacheElement:get_Name():String:this
         102 (29.57% of base) : System.Private.Xml.dasm - ReflectionAwareCodeGen:GetStringForArrayMember(String,String,TypeDesc):String:this
          80 (26.76% of base) : System.Collections.Immutable.dasm - ImmutableList:ToImmutableList(Builder):ImmutableList`1 (8 methods)
          80 (26.76% of base) : System.Collections.Immutable.dasm - ImmutableSortedDictionary:ToImmutableSortedDictionary(Builder):ImmutableSortedDictionary`2 (8 methods)
          80 (26.76% of base) : System.Collections.Immutable.dasm - ImmutableSortedSet:ToImmutableSortedSet(Builder):ImmutableSortedSet`1 (8 methods)
          25 (26.32% of base) : Microsoft.CodeAnalysis.CSharp.dasm - CSharpCompiler:ResolveAnalyzersFromArguments(List`1,CommonMessageProvider,TouchedFileLogger):ImmutableArray`1:this
          25 (26.32% of base) : Microsoft.CodeAnalysis.VisualBasic.dasm - VisualBasicCompiler:ResolveAnalyzersFromArguments(List`1,CommonMessageProvider,TouchedFileLogger):ImmutableArray`1:this
         352 (25.79% of base) : System.Collections.Immutable.dasm - MutationInput:.ctor(SortedInt32KeyNode`1,IEqualityComparer`1,IEqualityComparer`1,int):this (8 methods)
          49 (25.65% of base) : System.Drawing.Primitives.dasm - Color:FromArgb(int,int,int,int):Color
          80 (25.56% of base) : System.Collections.Immutable.dasm - ImmutableArray:ToImmutableArray(Builder):ImmutableArray`1 (8 methods)
          80 (25.40% of base) : System.Colle [...]

2021-03-23 21:25 UTC, EgorBo commented
@dotnet/jit-contrib PTAL

2021-03-23 22:16 UTC, AndyAyersMS commented
> 67% of the regression is in System.Collections.Immutable

Is there a pattern to the methods in this assembly that we might want to reconsider?

2021-03-23 22:31 UTC, BruceForstall requested changes

2021-03-23 22:31 UTC, BruceForstall commented on src/coreclr/jit/morph.cpp
> +    if (block->bbJumpKind != BBJ_THROW)
You've introduced a full IR walk just to set this flag. Is it worth it? What's the throughput impact? Can it be done with any existing IR walks?

You've also introduced a new BBF flag. We have space, yes, but every new flag introduces some new complexity. If it's required, then ok.

2021-03-23 22:31 UTC, BruceForstall commented on src/coreclr/jit/morph.cpp
> +                block->bbFlags |= BBF_THROW_CANDIDATE;
Once you've set the flag, you don't need to walk the rest of the statements.

2021-03-23 22:33 UTC, BruceForstall commented on src/coreclr/jit/morph.cpp
> +        // Look for no-return calls inside the current basic block
Should this only be done under `OptimizationEnabled()`?

2021-03-24 12:14 UTC, EgorBo commented
@BruceForstall you're right, I've changed the logic to just scan a top-level node of the current statement in `fgMorphConst` and got almost the same jit-diff with basically zero overhead for JIT.

@AndyAyersMS from my understanding, `System.Collections.Immutable` has a lot of generic types with multiple generic arguments so all diffs are multiplied by some big value.

2021-03-25 23:44 UTC, BruceForstall commented
> @AndyAyersMS from my understanding, System.Collections.Immutable has a lot of generic types with multiple generic arguments so all diffs are multiplied by some big value (PMI mode)

I believe you're correct. However, have you tried crossgen/crossgen2 libraries SuperPMI asm diffs, or using "jit-diff" without "--pmi", to see if that's the case?

2021-03-25 23:45 UTC, BruceForstall approved these changes

2021-03-26 19:21 UTC, EgorBo commented
> > @AndyAyersMS from my understanding, System.Collections.Immutable has a lot of generic types with multiple generic arguments so all diffs are multiplied by some big value (PMI mode)
> 
> I believe you're correct. However, have you tried crossgen/crossgen2 libraries SuperPMI asm diffs, or using "jit-diff" without "--pmi", to see if that's the case?

yeah with crossgen it's 20x smaller:
```
Total bytes of delta: 2241 (0.01% of base)
    diff is a regression.


Top file regressions (bytes):
        1676 : System.Collections.Immutable.dasm (0.74% of base)
         201 : FSharp.Core.dasm (0.02% of base)
         121 : System.Net.Sockets.dasm (0.08% of base)
         102 : System.Collections.Concurrent.dasm (0.22% of base)
          72 : System.Net.Http.WinHttpHandler.dasm (0.11% of base)
          20 : System.Drawing.Primitives.dasm (0.06% of base)
          15 : System.Private.CoreLib.dasm (0.00% of base)
          14 : System.Net.WebSockets.dasm (0.03% of base)
           8 : System.Private.DataContractSerialization.dasm (0.00% of base)
           6 : System.Net.Http.dasm (0.00% of base)
           6 : System.Private.Xml.dasm (0.00% of base)
```

2021-03-26 19:21 UTC, merged