Print reason why EH Var was not enregistered
dotnet/runtime pull request #50215
Opened 2021-03-24 23:14 UTC by kunalspathak

While visiting dumps/disasm, it is valuable to see the reason why EH var didn't get enregistered. In addition to existing reasons, there are are 2 more possibilities:
- It has multiple definition
- It needs explicit zero initialization

2021-03-24 23:14 UTC, kunalspathak commented
@dotnet/jit-contrib , @AndyAyersMS

2021-03-25 23:25 UTC, BruceForstall requested changes

2021-03-25 23:25 UTC, BruceForstall commented on src/coreclr/jit/compiler.h
> +    unsigned char lvDisqualifyEHVarReason = 'H';
Don't put this in the middle of the bitfield declarations; put it after.

2021-03-25 23:54 UTC, BruceForstall approved these changes

2021-03-26 07:26 UTC, merged