Remove unnecessary realpath calls from host probing logic
dotnet/runtime pull request #50671
Opened 2021-04-03 00:55 UTC by mateoatr

In an effort to improve startup time, this PR gets rid of three different file-accessing calls inside the host:

https://github.com/dotnet/runtime/blob/5265305d3121d2fce804948b9250b1b3a5f8a22d/src/native/corehost/hostpolicy/deps_resolver.cpp#L654

Which performs a file existence check on each of the assets inside a deps.json.

And:

https://github.com/dotnet/runtime/blob/8ad1d7d665c9867621193d4f8362cdb983602cae/src/native/corehost/hostpolicy/deps_resolver.cpp#L593

https://github.com/dotnet/runtime/blob/8ad1d7d665c9867621193d4f8362cdb983602cae/src/native/corehost/hostpolicy/deps_resolver.cpp#L48

Which purpose is to unroll the symbolic link of a given path and, in the later case, to later normalize the path.

2021-04-03 13:07 UTC, vitek-karas approved these changes
Basically just some more interesting test cases, otherwise looks good.

2021-04-03 13:07 UTC, vitek-karas commented on src/native/corehost/hostpolicy/deps_resolver.cpp
> +    if (existing->count(path))
We should probably add a comment admitting that in presence of symlinks or non-normalized paths there might be effective duplicates in the output - and that it's OK.

2021-04-03 13:07 UTC, vitek-karas commented on src/installer/tests/Microsoft.NET.HostModel.Tests/Microsoft.NET.HostModel.AppHost.Tests/AppHostUsedWithSymbolicLinks.cs
> +                StandaloneAppFixture_Published = publishFixture;
Couple more tests we might want to add:
* Framework dependent app - run it from a symlink
* Framework dependent app where runtime install location is a symlink (basically `DOTNET_ROOT` points to a symlink)
* Running an app via `dotnet app.dll` where the `dotnet` is a symlink. (I think this is close to the snap scenario)

2021-04-03 13:07 UTC, vitek-karas commented on src/installer/tests/Microsoft.NET.HostModel.Tests/Microsoft.NET.HostModel.AppHost.Tests/AppHostUsedWithSymbolicLinks.cs
> +                StandaloneAppFixture_Published = publishFixture;
Some more
* Make sure we have a test to validate additional probing paths (that they continue to work even after this change)

2021-04-04 17:36 UTC, AaronRobinsonMSFT commented on src/native/corehost/deps_entry.h
> +    bool to_dir_path(const pal::string_t& base, bool look_in_bundle, pal::string_t* str, bool& found_in_bundle, bool check_file_existence) const;
Would strongly recommend keeping the last parameter as the out. In this case we now have "in in out out in". Also, we now have two booleans in these cases which means we are close to warranting an enumeration. At the very least though all of these functions should be updated to keep the outs as the last parameters.

2021-04-05 13:48 UTC, brianrob approved these changes

2021-04-14 23:11 UTC, vitek-karas requested changes

2021-04-14 23:11 UTC, vitek-karas commented on src/native/corehost/hostpolicy/deps_resolver.cpp
> +            search_options |= deps_entry_t::search_options::file_existence;
I think we should change the logic here.
In `setup_probe_config` basically if we end up with anything but app and frameworks in the probes - we should enforce file existence checks. This applies to servicing, shared store, additional probing paths... and whatever else we add in the future.

2021-04-15 17:55 UTC, vitek-karas approved these changes

2021-04-15 23:50 UTC, merged