WIP: runtime changes for static interface method support
dotnet/runtime pull request #50825
Opened 2021-04-07 01:18 UTC by trylek

Apparently I still don't have push request to your fork so for now I'm pushing the commits to my fork. I originally tried to create this PR against your version of the branch but GitHub doesn't let me select it as the base repo, probably due to the fact that I'm not authorized to push. I assume this is a technical detail we'll easily resolve once you're back from vacation; for now I believe this WIP PR to be a useful vehicle for me to publish and comment on my progress and for you to review it when you're back in office.

Thanks

Tomas

2021-04-12 20:39 UTC, davidwrighton requested changes
I have a set of comments on the change in progress, although I'm really happy to see at least 1 test pass. Very exciting.

2021-04-12 20:39 UTC, davidwrighton commented on src/coreclr/vm/methodtablebuilder.cpp
> -                if(IsMdStatic(dwMemberAttrs))
We should not permit static virtual methods on classes/structs. By our ecma design, those should continue to throw.

2021-04-12 20:39 UTC, davidwrighton commented on src/coreclr/vm/methodtablebuilder.cpp
> -    if (IsMdStatic(dwDeclAttrs))
We should not permit static virtual methods on classes/structs. By our ecma design, those should continue to throw.

2021-04-12 20:39 UTC, davidwrighton commented on src/coreclr/vm/methodtablebuilder.cpp
> -
We should not permit static virtual methods on classes/structs. By our ecma design, those should continue to throw.

2021-04-12 20:39 UTC, davidwrighton commented on src/coreclr/vm/methodtablebuilder.cpp
> -        if (!IsMdVirtual(it.Attrs()))
This should only be allowed for static methods

2021-04-12 20:39 UTC, davidwrighton commented on src/coreclr/vm/methodtablebuilder.cpp
> +                /* TODO: what to do about this check
The spec update describes the changes here. This check should be preserved for instance virtuals, but there should be a base check for static virtual overrides.

2021-04-12 20:39 UTC, davidwrighton commented on src/coreclr/vm/clsload.cpp
> +        // TODO: For some reason, the base class BaseScenario1 - DerivedScenario1 inheritance
This is odd. Possibly we just have a ilasm bug.

2021-04-12 20:39 UTC, davidwrighton commented on src/coreclr/vm/contractimpl.cpp
> +                /* TODO: right now it's unclear to me whether the SVMs should go in the method table or not, for now I assume they should.
My initial thought was to store this sort of detail in a parallel table to the existing scheme, but we'll want to take a close look here to see if this is the right approach.

2021-04-12 20:39 UTC, davidwrighton commented on src/coreclr/vm/prestub.cpp
> +        if (!pMD->IsStatic() && pMD->IsVtableMethod())
I don't like the idea that static methods would go in the vtable.

2021-04-20 20:33 UTC, trylek commented
Closing in favor of a new PR against David's private branch.

2021-04-20 20:33 UTC, closed without merging