Fix EventSource EnableEvents(LogAlways)
dotnet/runtime pull request #51227
Opened 2021-04-14 11:55 UTC by MihaZupan

`EventLevel.LogAlways` has a value 0, but is the most verbose option, so it has to be special-cased before the `>` check.
That is done properly in the `IsEnabled` check, but not when updating the level https://github.com/dotnet/runtime/blob/19caa608b9d226d0041d5ed1c7b0d5911fb13d2b/src/libraries/System.Private.CoreLib/src/System/Diagnostics/Tracing/EventSource.cs#L2305

Previously, an already-enabled `EventSource` would ignore an enable command with `EventLevel.LogAlways`.

2021-04-16 15:48 UTC, stephentoub commented
cc: @sywhang

2021-04-16 17:26 UTC, sywhang requested changes
Sorry if this behavior seemed like a bug from the way it is described. 

`LogAlways` is actually not the most "verbose" option in the sense that you might be misled to think. If you specify an event to be *emitted* at `LogAlways` level, it means no filtering will be done and will be logged always given that there is a listener, hence in a way it is the most "verbose" option because it will always get logged. It is *not* the most verbose in the sense that if you enable a session with `LogAlways`, you get all the events. For enabling events, it is the opposite: enabling a session with `LogAlways` should make it only get events that are *always* logged - `LogAlways`.

2021-04-16 21:35 UTC, MihaZupan commented
> For enabling events, it is the opposite: enabling a session with LogAlways should make it only get events that are always logged - LogAlways. 

I can double check, but passing LogAlways to EventListener EnableEvents today means all events **are** logged - regardless of the their level.

2021-04-17 02:31 UTC, noahfalk commented
I think there is bug in the BCL filtering logic here which is probably adding to the confusion on the intended behavior: https://github.com/dotnet/runtime/issues/51429

2021-05-10 21:32 UTC, noahfalk commented
@MihaZupan can we close this? I think the issue we need to fix is #51429

2021-05-10 21:38 UTC, closed without merging

2021-05-10 21:54 UTC, MihaZupan commented
Tests from here would be worthwhile copying over (with minor changes) to whatever fix is used for #51429