Allow mono samples to build and run again
dotnet/runtime pull request #54089
Opened 2021-06-12 01:31 UTC by lambdageek

Copied from src/libraries/Directory.Build.props

Evidently this is sufficient for the console samples to build again:

```
$ make run MONO_CONFIG=Release MONO_ENV_OPTIONS=
../../../.././dotnet.sh publish -c Release -r linux-x64
Microsoft (R) Build Engine version 16.11.0-preview-21254-21+e73d08c28 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  Used runtime pack: /home/aleksey/working/dotnet-runtime/artifacts/bin/microsoft.netcore.app.runtime.linux-x64/Release/
  Used runtime pack: /home/aleksey/.nuget/packages/microsoft.aspnetcore.app.runtime.linux-x64/6.0.0-preview.4.21253.5
  HelloWorld -> /home/aleksey/working/dotnet-runtime/artifacts/bin/HelloWorld/x64/Release/linux-x64/HelloWorld.dll
  HelloWorld -> /home/aleksey/working/dotnet-runtime/artifacts/bin/HelloWorld/x64/Release/linux-x64/publish/
COMPlus_DebugWriteToStdErr=1 \
MONO_ENV_OPTIONS="" \
../../../../artifacts/bin/HelloWorld/x64/Release/linux-x64/publish/HelloWorld
Hello World from Mono!
System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
HelloWorld, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
.NET 6.0.0-dev
```

2021-06-12 01:32 UTC, lambdageek commented
@akoeplinger @ViktorHofer once again I don't _really_ know what I'm doing...  How wrong is this?

2021-06-14 08:53 UTC, akoeplinger approved these changes
LGTM, though we should probably look at moving these properties from src/librares/Directory.Build.props to some common location so we don't need to duplicate them.

2021-06-14 10:27 UTC, ViktorHofer requested changes, later dismissed
Thanks for the fix. Can you please avoid the duplication and move the properties into the root's Directory.Build.props file after the block in which `PackageRID` is defined?

Also when doing so, please remove this block: https://github.com/dotnet/runtime/blob/bc16a7bd2dcca7f1f8ce70e75dc86a3fac3ffcd2/src/libraries/Directory.Build.props#L139-L146.

2021-06-14 13:05 UTC, lambdageek commented
@ViktorHofer Done, thanks!

2021-06-14 13:11 UTC, ViktorHofer commented
I believe this code block is now dead: https://github.com/dotnet/runtime/blob/ccec848395a0b7306d34f6160931a8d8067dd434/src/mono/wasm/build/WasmApp.Native.targets#L33-L36

2021-06-14 13:15 UTC, ViktorHofer commented
And a few more that should also be removed. Would be great if you could do that as well in the PR:
- https://github.com/dotnet/runtime/blob/8818fb0de5662e510de61c20b17c0d9252ad320d/src/mono/wasm/wasm.proj#L10-L12
- https://github.com/dotnet/runtime/blob/b8b3ef137dd729ad8911af294cbecb24c61435bf/src/tests/run.proj#L644
- https://github.com/dotnet/runtime/blob/6722c0b27bc5869bdeef2c5de0f4e9ec38ad748b/src/mono/wasm/build/WasmApp.targets#L85-L88
- https://github.com/dotnet/runtime/blob/8698d0f34506695f38824b5573b8e75bcc80684f/src/mono/sample/Android/AndroidSampleApp.csproj#L9
- https://github.com/dotnet/runtime/blob/8698d0f34506695f38824b5573b8e75bcc80684f/src/mono/sample/iOS/Program.csproj#L8
- https://github.com/dotnet/runtime/blob/8698d0f34506695f38824b5573b8e75bcc80684f/src/mono/sample/mbr/apple/AppleDelta.csproj#L6

2021-06-17 03:06 UTC, radical commented
You can remove https://github.com/dotnet/runtime/blob/main/src/mono/wasm/build/WasmApp.InTree.props#L9 too

2021-06-17 03:07 UTC, radical approved these changes
Other than removing the entry from `src/mono/wasm/build/WasmApp.InTree.props`, LGTM!

2021-06-17 09:32 UTC, ViktorHofer commented
Any idea why tests started failing when removing the properties from the two wasm files? I thought those are dead anyway.

2021-06-17 13:02 UTC, lambdageek commented
> Any idea why tests started failing when removing the properties from the two wasm files? I thought those are dead anyway.

Not sure - I didn't have a chance to look into it yet.  If I had to guess - the wasm runtime build is different from other platforms because there's a step that runs after the libraries are built.  So perhaps the final runtime artifacts for testing are in a slightly different location.

2021-06-17 16:09 UTC, radical commented
> Any idea why tests started failing when removing the properties from the two wasm files? I thought those are dead anyway.

Which files? And where are these failing?

2021-06-17 16:23 UTC, lambdageek commented
@radical `WasmApp.targets` and `WasmApp.Native.targets`

This is what I did initially after adding the properties to the root `Directory.Build.props`: https://github.com/dotnet/runtime/pull/54089/commits/3a6c7bcc8fc0eb69b1c46568fbfdc5de9f3c6f87#diff-9aef04edc740c7aadf146f6890e8316ec4e65030186727ea6286411efea20d02

I don't recall what was failing specifically, but it was the general wasm app building for the libraries tests, I believe.  (don't seem to have AzDO links to the oldest CI runs)

2021-06-17 16:27 UTC, radical commented
> @radical `WasmApp.targets` and `WasmApp.Native.targets`

Those files are used outside the tree too, like in workloads. So, we can't depend on runtime repo's `Directory.Build.props` providing the values.

2021-06-17 16:59 UTC, lambdageek commented
There's one failure still that I can't explain: `"runtime (CoreCLR Pri0 Runtime Tests Run windows arm64 checked)"`

```
##[error].packages\microsoft.dotnet.helix.sdk\6.0.0-beta.21311.3\tools\Microsoft.DotNet.Helix.Sdk.MultiQueue.targets(78,5): error : (NETCORE_ENGINEERING_TELEMETRY=Test) Work item JIT.IL_Conformance in job 54ff2c22-c6df-4b58-8d1b-fe28a368448a has failed.
Failure log: https://helix.dot.net/api/2019-06-17/jobs/54ff2c22-c6df-4b58-8d1b-fe28a368448a/workitems/JIT.IL_Conformance/console
D:\workspace\_work\1\s\.packages\microsoft.dotnet.helix.sdk\6.0.0-beta.21311.3\tools\Microsoft.DotNet.Helix.Sdk.MultiQueue.targets(78,5): error : Work item JIT.jit64 in job 54ff2c22-c6df-4b58-8d1b-fe28a368448a has failed. [D:\workspace\_work\1\s\src\tests\Common\helixpublishwitharcade.proj]
D:\workspace\_work\1\s\.packages\microsoft.dotnet.helix.sdk\6.0.0-beta.21311.3\tools\Microsoft.DotNet.Helix.Sdk.MultiQueue.targets(78,5): error : Failure log: https://helix.dot.net/api/2019-06-17/jobs/54ff2c22-c6df-4b58-8d1b-fe28a368448a/workitems/JIT.jit64/console [D:\workspace\_work\1\s\src\tests\Common\helixpublishwitharcade.proj]
##[error].packages\microsoft.dotnet.helix.sdk\6.0.0-beta.21311.3\tools\Microsoft.DotNet.Helix.Sdk.MultiQueue.targets(78,5): error : (NETCORE_ENGINEERING_TELEMETRY=Test) Work item JIT.jit64 in job 54ff2c22-c6df-4b58-8d1b-fe28a368448a has failed.
Failure log: https://helix.dot.net/api/2019-06-17/jobs/54ff2c22-c6df-4b58-8d1b-fe28a368448a/workitems/JIT.jit64/console
```

The consoles are empty https://helix.dot.net/api/2019-06-17/jobs/54ff2c22-c6df-4b58-8d1b-fe28a368448a/workitems/JIT.IL_Conformance/console 
```
{"Message":"NotFound","ActivityId":"ed4d27eef51d024bb9c5b5a78855025b"}
```

and https://helix.dot.net/api/2019-06-17/jobs/54ff2c22-c6df-4b58-8d1b-fe28a368448a/workitems/JIT.jit64/console
```
{"Message":"NotFound","ActivityId":"6f884237d396f94496fdfcb8581f0336"}
```

Not sure if that could be related to the changes here.

2021-06-21 07:13 UTC, merged