Use XmlWriter.Create instead of XmlTextWriter
dotnet/runtime pull request #54949
Opened 2021-06-30 06:01 UTC by StephenMolloy

Use XmlReader/Writer.Create instead of XmlTextReader/Writer.

XmlTextWriter is not strict about some of the things it writes. Like
the null character, which is technically illegal in XML 1.0 and 1.1.
(The way we used the XmlTextReader counterpart, we would end
up successfully serializing a null character, and then hit an exception
when trying to deserialize what we just serialized. This inability to
round trip breaks a core tenet of serialization.)

Since the long ago days of .Net 2.0, Microsoft has been
recommending people to use XmlReader/Writer.Create()
instead of directly instantiating XmlTextReader/Writer. This PR
will bring us in line with those recommendations from long ago.

Fixes #1411

2021-06-30 17:24 UTC, stephentoub commented on src/libraries/System.Private.Xml/src/System/Xml/Serialization/XmlSerializer.cs
> +            //xmlWriter.Indentation = 2;
```suggestion
```

2021-06-30 17:24 UTC, stephentoub commented on src/libraries/System.Private.Xml/src/System/Xml/Serialization/XmlSerializer.cs
> +            //xmlWriter.Indentation = 2;
```suggestion
```

2021-06-30 17:24 UTC, stephentoub commented on src/libraries/System.Private.Xml/src/System/Xml/Serialization/XmlSerializer.cs
> +            //xmlReader.XmlResolver = null;
```suggestion
```

2021-06-30 17:25 UTC, stephentoub approved these changes

2021-07-06 23:37 UTC, HongGit approved these changes

2021-07-12 20:20 UTC, HongGit approved these changes

2021-07-13 00:52 UTC, mconnew commented on src/libraries/System.Private.Xml/src/System/Xml/Serialization/XmlSerializer.cs
>              Serialize(xmlWriter, o, namespaces);
Why explicitly set CheckCharacters and IndentChars? You are seeting them to their default values. `Indent` is the only property which you are changing from the default.

2021-07-13 00:53 UTC, mconnew commented on src/libraries/System.Private.Xml/src/System/Xml/Serialization/XmlSerializer.cs
>              Serialize(xmlWriter, o, namespaces);
Same for this, skip setting values to the defaults.

2021-07-13 00:59 UTC, mconnew requested changes
Remove the extra XmlWriterSettings property setting where you are setting the default

2021-07-13 23:31 UTC, HongGit approved these changes

2021-07-15 00:22 UTC, mconnew approved these changes

2021-07-15 01:01 UTC, merged