Avoid nullref while trying to throw a more helpful exception.
dotnet/runtime pull request #55316
Opened 2021-07-08 06:27 UTC by StephenMolloy

Avoid nullref while trying to throw a more helpful exception.

The method checking for referential surrogates during deserialization
(`ReplaceDeserializedObject`) wants to throw a helpful exception when
it can't fix up references post-type-substitution. In order to actually be
helpful, avoid nullref-ing when one of the objects involved in the
replacement is null. Simply use the term "unknown type" instead.

Fixes #41465

2021-07-08 17:18 UTC, stephentoub commented on src/libraries/System.Private.DataContractSerialization/src/System/Runtime/Serialization/XmlObjectSerializerReadContext.cs
> +                    var newType = (newObj != null) ? DataContract.GetClrTypeFullName(newObj.GetType()) : "unknown type";
Nit:
```suggestion
                    string oldType = (oldObj != null) ? DataContract.GetClrTypeFullName(oldObj.GetType()) : "unknown type";
                    string newType = (newObj != null) ? DataContract.GetClrTypeFullName(newObj.GetType()) : "unknown type";
```
Also, does "unknown type" need to come from a resx?

2021-07-12 20:14 UTC, HongGit approved these changes

2021-07-12 23:36 UTC, mconnew requested changes
Please make the changes that @stephentoub requested. "Unknown Type" should be a string resource so that it gets translated.

2021-07-15 00:14 UTC, mconnew approved these changes

2021-07-15 06:59 UTC, merged