Handle early wakeup of counter loop
dotnet/runtime pull request #57170
Opened 2021-08-10 20:50 UTC by josalem

Fix #56695
* prevent a negative delta value

Copy of comment from #56695:

> I think I've worked out what happened.
> 
> The new logic:
> 
> ```cs
> TimeSpan delta = now - _nextPollingTimeStamp;
> if (delta > TimeSpan.Zero && _pollingIntervalInMilliseconds > 0)
> 	_nextPollingTimeStamp += TimeSpan.FromMilliseconds(_pollingIntervalInMilliseconds * Math.Ceiling(delta.TotalMilliseconds / _pollingIntervalInMilliseconds));
> ```
> 
> can have wonky behavior if the sleep in `CounterGroup.PollForValues` wakes up early.
> 
> `delta` can be negative, which will result in `_nextPollingTimeStamp` not being updated. This means that `sleepDurationInMilliseconds` will be set to `1` and the counter will fire again on the next loop because `_nextPollingTimeStamp < now + new TimeSpan.FromMilliseconds(1)` will be true.
> 
> https://github.com/dotnet/runtime/blob/4d26112c07391f563cb0ca46af1993635399007e/src/libraries/System.Private.CoreLib/src/System/Diagnostics/Tracing/CounterGroup.cs#L267-L306
> 
> A fix would be to switch to the following:
> 
> ```cs
> private const TimeSpan MinimumPollingInterval = TimeSpan.FromSeconds(1);
> 
> // ...
> 
> TimeSpan delta = now - _nextPollingTimeStamp;
> delta = MinimumPollingInterval > delta ? MinimumPollingInterval : delta;
> if (_pollingIntervalInMilliseconds > 0)
> 	_nextPollingTimeStamp += TimeSpan.FromMilliseconds(_pollingIntervalInMilliseconds * Math.Ceiling(delta.TotalMilliseconds / _pollingIntervalInMilliseconds));
> ```
> 
> The `now - _nextPollingTimeStamp` is calculating the difference between when the counter woke up (`now`) and when it was _supposed_ to wake up (`_nextPollingTimeStamp`). This is supposed to then increment `_nextPollingTimeStamp` to the next discrete increment of `_pollingIntervalInMillseconds` from the origin time. This prevents the interval from sliding if counters take sufficiently long amounts of time to calculate. This updated logic without the loop, however, only increments if `now > _nextPollingTimeStamp` (if the counter woke up _after_ the intended timestamp).

We'll need to backport these changes to 3.1 and 5.0 if they are approved.

2021-08-12 17:26 UTC, mikem8361 approved these changes

2021-08-12 20:51 UTC, hoyosjs requested changes

2021-08-12 20:51 UTC, hoyosjs commented on src/libraries/System.Private.CoreLib/src/System/Diagnostics/Tracing/CounterGroup.cs
> +                    delta = s_minimumPollingInterval > delta ? s_minimumPollingInterval : delta;
delta = _pollingIntervalInMilliseconds > delta ? _pollingIntervalInMilliseconds  : delta

2021-08-12 20:53 UTC, hoyosjs commented on src/libraries/System.Private.CoreLib/src/System/Diagnostics/Tracing/CounterGroup.cs
> +        private static readonly TimeSpan s_minimumPollingInterval = TimeSpan.FromSeconds(1);
```suggestion
```

2021-08-12 23:42 UTC, hoyosjs approved these changes

2021-08-13 00:13 UTC, josalem commented
CI doesn't seem to be starting for some reason...

2021-08-13 00:13 UTC, josalem commented
/azp run runtime

2021-08-13 03:10 UTC, davmason approved these changes

2021-08-13 21:05 UTC, hoyosjs commented
Failuer is not unique to this PR (see #57174)

2021-08-13 21:07 UTC, hoyosjs commented
Created 
https://github.com/dotnet/runtime/issues/57375

2021-08-13 21:07 UTC, merged