Fix thread pool completed work item counter to remove finalized nodes
dotnet/runtime pull request #57305
Opened 2021-08-12 18:02 UTC by kouvel

- New nodes are being added to the set but finalized ones were not being removed
- This would result in double-counting the completed work item count for a thread that exits, and memory would grow over time

2021-08-12 18:25 UTC, davidwrighton requested changes
I don't think this change addresses the problem at all. Since there is a reference path from PortableThreadPool through the ThreadInt64PersistentCounter to each ThreadLocalNode, I don't see any way for the finalizer on `ThreadLocalNode` to ever execute. I recently learned about `ThreadLocal<T>` and I think creative use of that api would likely be a more effective way to fix this issue. In particular, remove the finalizer from `ThreadLocalNode`, and use `ThreadLocal<T>` to setup a finalizer that when a thread exits will call a Dispose function on `ThreadLocalNode`.

2021-08-12 18:39 UTC, kouvel commented
Yep missed that, will need a better fix

2021-08-12 21:25 UTC, davidwrighton approved these changes
This should work nicely.

2021-08-12 21:25 UTC, davidwrighton commented on src/libraries/System.Private.CoreLib/src/System/Threading/ThreadInt64PersistentCounter.cs
> +        private sealed class ThreadLocalNode : IDisposable
IDisposable here isn't necessary.

2021-08-13 14:27 UTC, stephentoub commented on src/libraries/System.Private.CoreLib/src/System/Threading/ThreadInt64PersistentCounter.cs
> +            }
```suggestion
            List<ThreadLocalNodeFinalizationHelper>? nodeFinalizationHelpers = t_nodeFinalizationHelpers ??= new List<ThreadLocalNodeFinalizationHelper>(1);
```

2021-08-13 14:28 UTC, stephentoub approved these changes

2021-08-14 04:52 UTC, danmoseley commented
Failure was the xunit crash. 😢

2021-08-14 04:52 UTC, merged