Add handling of generic attributes to CustomAttributeDecoder
dotnet/runtime pull request #57466
Opened 2021-08-16 03:41 UTC by MichalStrehovsky

If the attribute constructor refers to the generic T in its signature, we would throw `BadImageFormatException`. This adds handling by capturing the generic context and interpreting the signature variables when needed.

I've hit this in the src\tests\reflection\GenericAttribute tests with NativeAOT since the NativeAOT compiler uses S.R.Metadata to read custom attributes.

No tests yet because I would like to discuss testing strategy.

* There's notes about pre-existing test debt in `CustomAttributeDecoderTests`.
* I don't want to write an IL test for this because they're a maintenance nightmare.
* We crosstarget (and test?) on .NET Framework. I don't know the support plans for generic attributes when targeting net461 with Roslyn. I don't know the support status of generic attributes in this repo.

I tested it with the `src\tests\reflection\GenericAttribute` test and NativeAOT, but that test is not much more than a smoke test, really.

Cc @tmat @RikkiGibson

2021-08-16 18:31 UTC, tmat commented on src/libraries/System.Reflection.Metadata/src/System/Reflection/Metadata/Ecma335/CustomAttributeDecoder.cs
> +                if (genericContextReader.ReadSignatureTypeCode() == SignatureTypeCode.GenericTypeInstance)
>if (genericContextReader.ReadSignatureTypeCode() == SignatureTypeCode.GenericTypeInstance [](http://example.com/codeflow?start=16&length=89)

Shouldn't this set attributeOwningTypeSpec to nil if the type code is not GenericTypeInstance?

2021-08-16 18:35 UTC, tmat commented
>         private ArgumentTypeInfo DecodeNamedArgumentType(ref BlobReader valueReader, bool isElementType = false)

Named argument can't by of generic type parameter type?

---
Refers to: src/libraries/System.Reflection.Metadata/src/System/Reflection/Metadata/Ecma335/CustomAttributeDecoder.cs:230 in 5204378. [](commit_id = 5204378fc7cccb204ae28f638935bdb4f43b3c76, deletion_comment = False)

2021-08-16 18:43 UTC, tmat requested changes
We should definitely add unit tests for this. 

You can use MetadataBuilder to construct the metadata image in the test that has generic attributes and then read them back.

2021-08-16 22:02 UTC, MichalStrehovsky commented
> Named argument can't by of generic type argument type?

Named arguments encode their type inline - we don't need to resolve the members to find their signature.

2021-08-16 22:24 UTC, tmat commented
> Named arguments encode their type inline - we don't need to resolve the members to find their signature.

So `DecodeNamedArgumentType` does not need to handle `SignatureTypeCode.GenericTypeParameter`? Seems odd

2021-08-24 08:54 UTC, krwq commented on src/libraries/System.Reflection.Metadata/src/System/Reflection/Metadata/Ecma335/CustomAttributeDecoder.cs
> +                    if (parameterIndex >= numGenericParameters)
consider also checking for negative index

2021-08-24 08:57 UTC, krwq commented on src/libraries/System.Reflection.Metadata/src/System/Reflection/Metadata/Ecma335/CustomAttributeDecoder.cs
> +                case (int)SignatureTypeCode.Boolean:
isn't there any existing subroutine for checking simple types?

2021-08-24 09:00 UTC, krwq approved these changes
considering it's not valid in C# to create generic attributes I'm ok with no extra tests and just unblocking scenarios for problematic assemblies. If they're ever supported then we should add more tests and fix any rough edges if there are any

2021-08-24 16:46 UTC, tmat commented
@krwq Generic attributes are going to be supported in C# 10 or 11. We need tests.

2021-08-24 17:27 UTC, RikkiGibson commented
Generic attributes are shipping in preview in .NET 6/C# 10, and will hopefully ship stable in C# 11.

2021-08-24 22:36 UTC, MichalStrehovsky commented
I thought I would be able to get to the tests, but it probably won't happen anytime soon. I filed #58073. It's better if it's handled by someone else. The fix I have works and I can just fork the file where I need this. I have test coverage through other CoreCLR tests from that.

2021-08-24 22:36 UTC, closed without merging

2021-08-25 08:14 UTC, krwq commented
@tmat @RikkiGibson if that's the case then agreed we need tests