Fix AddEventLog: EventLogSettings not added
dotnet/runtime pull request #57567
Opened 2021-08-17 12:52 UTC by wrzucher

TryAddEnumerable do not add second provider to service collection

Closes #51899

2021-08-17 12:52 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=57567) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=57567) before we can accept your contribution.<br/><br/>:x: wrzucher [sign now](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=57567)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/runtime?pullRequest=57567) it.</sub>

2021-12-04 01:04 UTC, maryamariyan approved these changes

2021-12-04 01:04 UTC, maryamariyan commented on src/libraries/Microsoft.Extensions.Logging.EventLog/src/EventLoggerFactoryExtensions.cs
> -            builder.Services.TryAddEnumerable(ServiceDescriptor.Singleton<ILoggerProvider>(new EventLogLoggerProvider(settings)));
I agree, I prefer the other two overloads to `AddEventLog(this ILoggingBuilder builder, EventLogSettings settings)`. If we wanted to add event log with settings we should be using the overload taking `Action<EventLogSettings>`.

Looked at the PR again I think it looks good as-is. Just added a nit review comment.

Thanks

2021-12-04 01:04 UTC, maryamariyan commented on src/libraries/Microsoft.Extensions.Logging/tests/Common/EventLogLoggerTest.cs
> +            serviceCollection.AddLogging(builder => builder.AddEventLog());
This line can be removed

2021-12-16 08:39 UTC, deeprobin requested changes

2021-12-16 08:39 UTC, deeprobin commented on src/libraries/Microsoft.Extensions.Logging/tests/Common/EventLogLoggerTest.cs
> +            var services = serviceCollection.BuildServiceProvider();
Usage explicit type
```suggestion
            IServiceProvider services = serviceCollection.BuildServiceProvider();
```

2021-12-21 20:49 UTC, deeprobin approved these changes
LGTM. If CI passes, I think its ready to merge.

2021-12-30 07:24 UTC, wrzucher commented
@maryamariyan please, confirm that you take a look at my concerns about this PR in the original issue
https://github.com/dotnet/runtime/issues/51899#issuecomment-900804993

2022-01-17 22:22 UTC, maryamariyan commented
Thanks for the note @wrzucher. I also believe the proper overload to use in general is the one below:

```c#
public static ILoggingBuilder AddEventLog(this ILoggingBuilder builder, Action<EventLogSettings> configure)
```

And I think the usage to the overload being fixed in this PR should be discouraged. (Note that `AddConsole` for example does not have such an overload, we take `Action` instead.)
I think it's better to close this PR rather than merge because there is not much value-add in fixing this API overload. Also since the current fix is not without risks.

2022-01-17 22:22 UTC, closed without merging