Validate CompressionLevel value is defined in BrotliStream ctor
dotnet/runtime pull request #57561
Opened 2021-08-17 10:22 UTC by i3arnon

Fix #46595

2021-08-19 10:12 UTC, i3arnon commented
> 2\. Ask a committer to mail the `.NET Breaking Change Notification` DL.

@stephentoub Can you please send the breaking change suggestion to the DL? dotnet/docs#25665

2021-08-19 10:20 UTC, stephentoub commented
_if_ it's merged

2021-10-05 00:06 UTC, carlossanlop commented
The CI results are already deleted. I want to make sure we don't have unit test failures. Closing and reopening to re-trigger the CI (same with the other related PR).

2021-10-21 22:47 UTC, jeffhandley requested changes
Please see the comment from @scalablecory here: https://github.com/dotnet/runtime/pull/57561#discussion_r723748527

2021-11-01 17:42 UTC, carlossanlop commented on src/libraries/System.IO.Compression.Brotli/src/System/IO/Compression/enc/BrotliStream.Compress.cs
> +            switch (compressionLevel)
@i3arnon hope you don't mind - I pushed the proposed change to your branch and I added tests to validate it.

2021-11-01 17:42 UTC, carlossanlop commented on src/libraries/System.IO.Compression.Brotli/src/System/IO/Compression/enc/BrotliStream.Compress.cs
> +            switch (compressionLevel)
@i3arnon hope you don't mind - I pushed the proposed change to your branch and I added tests to validate it.

2021-11-01 17:49 UTC, carlossanlop approved these changes
I'm signing off, although I added the last commits to address the suggestion and to add tests. @Jozkee @adamsitnik @jeffhandley @stephentoub would you mind giving us an additional sign-off if you agree with the change?

2021-11-01 20:56 UTC, jeffhandley approved these changes

2021-11-01 23:15 UTC, merged

2022-10-04 20:12 UTC, ericstj commented
@carlossanlop were you planning to create a breaking change document for this?

2022-10-27 21:48 UTC, eerhardt commented
We should also consider updating this blog: https://devblogs.microsoft.com/dotnet/introducing-support-for-brotli-compression/

It explicitly calls out this behavior as a feature:

> As mentioned earlier, Brotli supports 11 levels of compression quality aside from the standard Optimal, Fastest and NoCompression levels. You can pass in the level to the constructor by casting the desired level directly to CompressionLevel, like this:
```C#
BrotliStream brotli = new BrotliStream(baseStream,
                                       CompressionMode.Compress,
                                       leaveOpen,
                                       bufferSize,
                                       (CompressionLevel)5); // Use level 5
```

I stumbled on it from searching for "brotli compression kestrel".

2022-10-27 21:51 UTC, stephentoub commented
I've removed it.

2022-11-16 16:01 UTC, Jozkee commented
breaking change doc created https://github.com/dotnet/docs/issues/32620.