Nullable annotation for System.Windows.Extensions
dotnet/runtime pull request #57896
Opened 2021-08-22 11:05 UTC by huoyaoyuan

Part of #41720

2021-08-25 12:37 UTC, huoyaoyuan commented
How to verify the ref source? I tried `/t:GenerateReferenceAssemblySource` but it has no effect.

2021-09-07 08:25 UTC, ViktorHofer commented
cc @Anipik @ericstj (for some reason, the bot doesn't do anything).

2021-09-07 14:46 UTC, stephentoub requested changes

2021-09-07 14:46 UTC, stephentoub commented on src/libraries/System.Windows.Extensions/ref/System.Windows.Extensions.cs
> +        public SoundPlayer(string? soundLocation) { }
This should not be nullable.  Passing null will throw an exception.

2021-09-07 14:46 UTC, stephentoub commented on src/libraries/System.Windows.Extensions/ref/System.Windows.Extensions.cs
> +        [System.Diagnostics.CodeAnalysis.AllowNullAttribute]
Ditto; this should be removed.  Setting SoundLocation to null will throw an exception.

2021-09-07 14:46 UTC, stephentoub commented on src/libraries/System.Windows.Extensions/src/System/Media/SoundPlayer.cs
> +        public SoundPlayer(string? soundLocation) : this()
This shouldn't be nullable.

2021-09-07 14:46 UTC, stephentoub commented on src/libraries/System.Windows.Extensions/src/System/Media/SoundPlayer.cs
>          }
`public SoundPlayer(Stream stream)` below should be `public SoundPlayer(Stream? stream)`

2021-09-07 14:46 UTC, stephentoub commented on src/libraries/System.Windows.Extensions/ref/System.Windows.Extensions.cs
>          public SoundPlayer(System.IO.Stream stream) { }
The `stream` parameter should be nullable.

2021-09-07 14:46 UTC, stephentoub commented on src/libraries/System.Windows.Extensions/src/System/Media/SoundPlayer.cs
> +        [AllowNull]
This should be removed.

2021-09-07 14:46 UTC, stephentoub commented on src/libraries/System.Windows.Extensions/src/System/Media/SoundPlayer.cs
> +            // See SoundPlayerTests.Load_NullStream_ThrowsNullReferenceException
It'd be worth opening an issue for this to decide separately whether we should throw a better exception in that case.

2021-09-07 14:46 UTC, stephentoub commented on src/libraries/System.Windows.Extensions/ref/System.Windows.Extensions.cs
> +        public event System.EventHandler? StreamChanged { add { } remove { } }
GitHub won't let me comment on it, but below for X509Certificate2UI.SelectFromCollection, both title and message should be nullable.

2021-09-27 09:36 UTC, huoyaoyuan commented
@stephentoub Is this now ready?

2021-10-06 04:40 UTC, stephentoub approved these changes
LGTM. Thanks!

2021-11-24 04:26 UTC, huoyaoyuan commented
@stephentoub ping on this

2021-11-24 11:54 UTC, stephentoub approved these changes

2021-11-24 13:52 UTC, merged