roll r2r jobs into crossgen2-outerloop
dotnet/runtime pull request #58282
Opened 2021-08-27 18:31 UTC by mangod9

With crossgen1 now defunct merging R2R and crossgen2 outerloops runs into a single CI. This should help with reducing duplication of CI runs. 

Contributes to https://github.com/dotnet/runtime/issues/58120

2021-08-27 19:39 UTC, trylek approved these changes
LGTM, thank you!

2021-08-28 01:32 UTC, BruceForstall requested changes
You need to remove the `# Limited outerloop testing in non-composite mode` comment, right?

Are you going to adjust the schedule to be daily, like r2r.yml?

There is still cg2 R2R testing in "outerloop" (ci.yml), that is batch run. Should you remove any testing here that is already done in ci.yml? (Is there any overlap?) Presumably, we do want that batch test R2R testing preferably to this daily "cg2 outerloop" testing.

I'm not sure we need to test on Windows arm(32). We do minimal testing in outerloop to keep it alive, but it is not supported. Maybe it's still useful to keep it alive for R2R?

It might be possible/easier to use `platformGroup: all` instead of listing all the platforms; I'm not sure if your platform set is equivalent to that (but note that `platformGroup: all` includes windows_arm).

2021-08-30 19:00 UTC, mangod9 commented
yeah makes sense to remove arm, though I copied the it over from r2r. Will get that removed. Will check ci.yml as to what is run there. Some duplication is ok unless its easy to separate.

2021-08-30 20:33 UTC, BruceForstall commented on eng/pipelines/coreclr/crossgen2-outerloop.yml
>    displayName: Sun, Tue, Thu at 11:00 PM (UTC-8:00)
Update this comment

2021-08-30 20:53 UTC, mangod9 commented on eng/pipelines/coreclr/crossgen2-outerloop.yml
>    displayName: Sun, Tue, Thu at 11:00 PM (UTC-8:00)
yup thanks for noticing.

2021-08-30 20:56 UTC, BruceForstall approved these changes

2021-08-31 04:37 UTC, mangod9 commented on eng/pipelines/coreclr/crossgen2-outerloop.yml
>        testGroup: outerloop
will update in a subsequent PR. @davidwrighton any specific reason comparison jobs require Release builds?

2021-08-31 04:38 UTC, merged