removed argument requestId from loopbackserver.cs
dotnet/runtime pull request #58678
Opened 2021-09-04 08:57 UTC by AnudeepGunukula

Closes #58239 

i had removed the requestId arguement from the loopbackserver.cs
i removed at the places where argument is not necessary.

This pr will solve the above issue.

2021-09-06 11:58 UTC, ManickaP commented
Thanks for the contribution!
I see that there are some compilation issues. You can see them if you look at the CI pipelines. Could you please make sure everything compiles?

2021-09-06 12:14 UTC, AnudeepGunukula commented
i will remove the argument requestId in the abstract methods in GenericLoopbackServer.cs 
and will make a new commit. so that errors will be not there.

2021-09-07 05:52 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=58678) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=58678) before we can accept your contribution.<br/><br/>:x: AnudeepGunukula [sign now](https://cla.dotnetfoundation.org/dotnet/runtime?pullRequest=58678)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/runtime?pullRequest=58678) it.</sub>

2021-09-07 14:29 UTC, karelz requested changes
All inherited classes need similar changes.

2021-09-07 14:29 UTC, karelz commented on src/libraries/Common/tests/System/Net/Http/GenericLoopbackServer.cs
>          public async Task SendResponseBodyAsync(string content, bool isFinal = true, int requestId = 0)
```suggestion
        public async Task SendResponseBodyAsync(string content, bool isFinal = true)
```

2021-09-07 14:29 UTC, karelz commented on src/libraries/Common/tests/System/Net/Http/GenericLoopbackServer.cs
>          public async Task SendResponseBodyAsync(string content, bool isFinal = true, int requestId = 0)
You forgot this method -- that is what the compilation error says.
Can you please ensure it compiles locally before updating PR?

2021-09-07 14:56 UTC, AnudeepGunukula commented
yes @karelz . i will make similar changes in all inherited classes and then test locally and will make a commit soon
Thankyou for your inputs

2021-09-14 14:50 UTC, karelz commented
@AnudeepGunukula just curious if you were able to make further progress, or if you got stuck somewhere ...

2021-09-14 15:00 UTC, AnudeepGunukula commented
Hi @karelz i am working on it and will make commit soon
Thankyou for asking i will post here if i got any doubt

2021-09-18 14:36 UTC, AnudeepGunukula commented
`
        public override Task SendResponseAsync(HttpStatusCode statusCode = HttpStatusCode.OK, IList<HttpHeaderData> headers = null, string content = "", bool isFinal = true, **int requestId = 0**)
        {
            return GetOpenRequest(**requestId**).SendResponseAsync(statusCode, headers, content, isFinal);
        }

`
hi @karelz . i got a doubt here Http3LoopbackConnection.cs
the requestId is passing from SendResponseAsync() to GetOpendRequest() method .
this is an implemented method of genericloopbackserver.cs only.
is there be any problem if i remove requestId from here as well.
kindly let me know.

`public Http3LoopbackStream GetOpenRequest(**int requestId = 0**)
        {
            return requestId == 0 ? _currentStream : _openStreams[requestId - 1];
        }
`

2021-09-20 05:13 UTC, AnudeepGunukula commented
hi @karelz . i had removed requestId argument from all the Inherited classes
kindly let me know why some checks are failing .

2021-09-27 14:51 UTC, AnudeepGunukula commented
Hi @ManickaP 
kindly review the code and please let me know the changes.

2021-09-29 13:32 UTC, ManickaP commented
Hi @AnudeepGunukula,

I see in the checks that there are failing tests due to the change:
https://dev.azure.com/dnceng/public/_build/results?buildId=1371361&view=ms.vss-test-web.build-test-results-tab&runId=40011952&resultId=155973&paneView=debug
```
System.Net.Http.HttpRequestException : An error occurred while sending the request.
---- System.IO.IOException : The request was aborted.
-------- System.Net.Http.Http2ConnectionException : The HTTP/2 server sent invalid data on the connection. HTTP/2 error code 'PROTOCOL_ERROR' (0x1).
```

They need to be resolved as well.

You can run the tests for System.Net.Http locally like this: https://github.com/dotnet/runtime/blob/main/docs/workflow/testing/libraries/testing.md#running-tests-for-a-single-library

From the quick look, it seems like the change in HttpClientHandlerTest.Http2.cs is not correct. Since the test is not reading request via `ReadRequestDataAsync`, `_lastStreamId` won't get updated and the response data are thus probably sent with stream id 0.

In this particular case, you need to somehow pass the stream id to the loopback connection.

2021-11-01 13:07 UTC, ManickaP reviewed
You need to add a new method, not add the `requestId` back to the overriding one.

2021-11-04 13:58 UTC, AnudeepGunukula commented
Hi @ManickaP . I had created new function in http2 but still some checks are failing.
Kindly let me know why some checks are failing

2021-11-04 15:02 UTC, karelz commented
@AnudeepGunukula did you look at all the failed legs?

From a cursory look at couple of failed legs are failing on test `System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http2.Http2SendAsync_LargeHeaders_CorrectlyWritten`:
```
    System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Http2.Http2SendAsync_LargeHeaders_CorrectlyWritten(continuationCount: 0) [FAIL]
      System.Net.Http.HttpRequestException : An error occurred while sending the request.
      ---- System.IO.IOException : The request was aborted.
      -------- System.Net.Http.Http2ConnectionException : The HTTP/2 server sent invalid data on the connection. HTTP/2 error code 'PROTOCOL_ERROR' (0x1).
      Stack Trace:
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Connection.cs(1974,0): at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs(975,0): at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/RedirectHandler.cs(30,0): at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/HttpClient.cs(527,0): at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
        /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http2.cs(3330,0): at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http2.<>c__DisplayClass99_0.<<Http2SendAsync_LargeHeaders_CorrectlyWritten>b__0>d.MoveNext()
        --- End of stack trace from previous location ---
        /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(120,0): at System.Threading.Tasks.TaskTimeoutExtensions.GetRealException(Task task)
        --- End of stack trace from previous location ---
        /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(90,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks)
        /_/src/libraries/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(55,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout)
        /_/src/libraries/Common/tests/System/Net/Http/Http2LoopbackServer.cs(173,0): at System.Net.Test.Common.Http2LoopbackServer.CreateClientAndServerAsync(Func`2 clientFunc, Func`2 serverFunc, Http2Options http2Options, Int32 timeout)
        /_/src/libraries/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Http2.cs(3321,0): at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Http2.Http2SendAsync_LargeHeaders_CorrectlyWritten(Int32 continuationCount)
        --- End of stack trace from previous location ---
        ----- Inner Stack Trace -----
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Connection.cs(2081,0): at System.Net.Http.Http2Connection.ThrowRequestAborted(Exception innerException)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Stream.cs(954,0): at System.Net.Http.Http2Connection.Http2Stream.CheckResponseBodyState()
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Stream.cs(969,0): at System.Net.Http.Http2Connection.Http2Stream.TryEnsureHeaders()
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Stream.cs(1006,0): at System.Net.Http.Http2Connection.Http2Stream.ReadResponseHeadersAsync(CancellationToken cancellationToken)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Connection.cs(1963,0): at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
        ----- Inner Stack Trace -----
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Connection.cs(2089,0): at System.Net.Http.Http2Connection.ThrowProtocolError(Http2ProtocolErrorCode errorCode)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Connection.cs(2085,0): at System.Net.Http.Http2Connection.ThrowProtocolError()
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Connection.cs(582,0): at System.Net.Http.Http2Connection.GetStream(Int32 streamId)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Connection.cs(604,0): at System.Net.Http.Http2Connection.ProcessHeadersFrame(FrameHeader frameHeader)
        /_/src/libraries/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Connection.cs(523,0): at System.Net.Http.Http2Connection.ProcessIncomingFramesAsync()
```

Did you try to reproduce the failure on your machine and debug it?

2021-11-22 18:49 UTC, greenEkatherine commented on src/libraries/Common/tests/System/Net/Http/Http2LoopbackConnection.cs
> +            int streamId = _lastStreamId;
```suggestion
            int streamId = requestId == 0 ? _lastStreamId : requestId;
```

2021-11-22 18:50 UTC, greenEkatherine requested changes
please try to revert the line where `_lastStreamId` was passed before

2021-11-23 08:55 UTC, karelz requested changes
Looks like we are almost done with the change. I added 2 nits with extra space and 1 deduplication of code.

2021-11-23 08:55 UTC, karelz commented on src/libraries/Common/tests/System/Net/Http/Http2LoopbackConnection.cs
> +            }
Why do we need exactly the same copy as the method above? Can we just invoke it instead with `requestId = 0`?

```suggestion
            SendResponseAsync(statusCode, headers, content, isFinal, requestId: 0);
```

2021-11-23 08:55 UTC, karelz commented on src/libraries/Common/tests/System/Net/Http/Http2LoopbackConnection.cs
> +            int streamId =  _lastStreamId;
```suggestion
            int streamId = _lastStreamId;
```

2021-11-23 08:55 UTC, karelz commented on src/libraries/Common/tests/System/Net/Http/Http2LoopbackConnection.cs
> +            int streamId =  _lastStreamId;
```suggestion
            int streamId = _lastStreamId;
```

2021-11-23 09:00 UTC, karelz commented on src/libraries/Common/tests/System/Net/Http/Http2LoopbackConnection.cs
> +            }
It might need to be paired with `async` removal from method signature to compile.

2021-11-23 10:57 UTC, AnudeepGunukula commented
Hi , i had commited the suggested changes .
Thankyou for reviewing.

2021-11-23 11:44 UTC, karelz commented
@AnudeepGunukula I think you missed my comment to remove 'async' from the method: https://github.com/dotnet/runtime/pull/58678#discussion_r754910805

@greenEkatherine can you please help here to move this further? Thank you!

2021-11-23 14:04 UTC, greenEkatherine commented
@AnudeepGunukula thank you for your contribution! Kindly let me take over this PR and add the necessary change

2021-11-23 14:31 UTC, karelz approved these changes

2021-11-23 14:38 UTC, greenEkatherine approved these changes

2021-11-23 18:20 UTC, merged

2021-11-23 18:29 UTC, karelz commented
Thanks @AnudeepGunukula for your contribution!
Thanks @greenEkatherine for helping to finish it here!