JIT: update debug dumping for loop hoisting
dotnet/runtime pull request #59287
Opened 2021-09-17 22:27 UTC by AndyAyersMS

I kept adding stuff like this whenever I wanted to understand why hosting was
doing what it was doing, so figured it likely had lasting value.

2021-09-17 22:31 UTC, AndyAyersMS commented
@BruceForstall PTAL
cc @dotnet/jit-contrib 

Sample jit dump fragment
```
BB02 [0001]  2       BB01,BB04             4     0 [006..00A)-> BB04 ( cond )                     i Loop Loop0 bwd bwd-target 
BB03 [0002]  2       BB02,BB03            16     1 [00A..01B)-> BB03 ( cond )                     i Loop Loop0 bwd bwd-target align 
BB04 [0004]  2       BB02,BB03             4     0 [01B..024)-> BB02 ( cond )                     i bwd 

Loop Nest L00
optHoistLoopCode for loop L00 <BB02..BB04>:
  Loop body does not contain a call
  Loop has single exit

  USEDEF  (5)={V03 V00 V01 V04 V02}
  INOUT   (4)={V03 V00 V01 V02}
  LOOPVARS(4)={V03 V00 V01 V02}
  Only considering hosting in blocks that dominate exit block BB04

    optHoistLoopBlocks BB02 (weight=  4   ) of loop L00 <BB02..BB04>, firstBlock is true
      [000012] not hoistable: variant child
      [000043] not hoistable: variant child

    optHoistLoopBlocks BB04 (weight=  4   ) of loop L00 <BB02..BB04>, firstBlock is false
      [000036] not hoistable: variant child
      [000009] not hoistable: variant child
```
Note we skip hosting from the inner loop block BB03 because it is conditionally executed. Added todos to the code for this (echoing some of what's over in #35735).

2021-09-17 22:49 UTC, BruceForstall requested changes
Thanks for doing this!

2021-09-17 22:49 UTC, BruceForstall commented on src/coreclr/jit/optimizer.cpp
> +            JITDUMP("\nLoop L%02u was removed\n", lnum);
We now have `FMT_LP`

2021-09-17 22:49 UTC, BruceForstall commented on src/coreclr/jit/optimizer.cpp
> +    JITDUMP("\n%s L%02u\n", optLoopTable[lnum].lpParent == BasicBlock::NOT_IN_LOOP ? "Loop Nest" : "Nested Loop", lnum);
same

2021-09-17 22:49 UTC, BruceForstall commented on src/coreclr/jit/optimizer.cpp
> +        JITDUMP("  Only considering hosting in blocks that dominate exit block " FMT_BB "\n", pLoopDsc->lpExit->bbNum);
typo: hosting

2021-09-17 22:49 UTC, BruceForstall commented on src/coreclr/jit/optimizer.cpp
> +            JITDUMP("  -- odd, we didn't reach entry from exit via dominators. Only considering hosting in entry "
typo: hosting

2021-09-17 22:49 UTC, BruceForstall commented on src/coreclr/jit/optimizer.cpp
> +        JITDUMP("  only considering hosting in entry block " FMT_BB "\n", pLoopDsc->lpEntry->bbNum);
typo: hosting

2021-09-17 22:49 UTC, BruceForstall commented on src/coreclr/jit/optimizer.cpp
> +            JITDUMP("    tree cost too low: %d < %d (lvc %u >= arc %u)\n", tree->GetCostEx(), 2 * IND_COST_EX,
IMO, spelling out the variables here would be better. (same below)

2021-09-17 22:49 UTC, BruceForstall commented on src/coreclr/jit/optimizer.cpp
> +                    INDEBUG(failReason = "variant child";);
nit: I presume you only need one of the semicolons (here and below)

2021-09-18 00:05 UTC, BruceForstall approved these changes

2021-09-18 01:42 UTC, merged

2021-09-19 16:06 UTC, EgorBo commented
Oh, I was going to use "Loop Hoisting" as an example of a jit area that needs more diagnostic info in my write-up 😐