Loop Alignment support for Arm64
dotnet/runtime pull request #60135
Opened 2021-10-07 18:35 UTC by kunalspathak

Add support for loop alignment for Arm64. This is an extension of adaptive loop alignment work done for xarch in #44370 .

The loop alignment is adaptive and the padding amount will be adjusted based on the number of blocks needed to fit the loop. Since the instruction encoding size for Arm64 is 4 bytes, 4 `NOP` will be added for a loop that can fit in single chunk of 32 bytes, and the padding amount will reduce as the loop size increases.

| Max Pad (bytes) | Minimum 32B blocks needed to fit the loop |
|-----------------|-------------------------------------------|
| 16              | 1 (32 bytes)                              |
| 12              | 2 (64 bytes)                              |
| 8               | 3 (96 bytes)                              |
| 4               | 4 (128 bytes)                             |

Benchmarks windows/arm64 diffs:
```

Summary of Code Size diffs:
(Lower is better)

Total bytes of base: 221276
Total bytes of diff: 223752
Total bytes of delta: 2476 (1.12% of base)
Total relative delta: 9.88
    diff is a regression.
    relative diff is a regression.
```
<details>

<summary>Detail diffs</summary>

```

Top file regressions (bytes):
          48 : 12587.dasm (3.28% of base)
          32 : 2381.dasm (8.89% of base)
          32 : 2757.dasm (2.69% of base)
          24 : 1201.dasm (2.37% of base)
          24 : 18571.dasm (1.14% of base)
          20 : 9146.dasm (1.71% of base)
          16 : 11289.dasm (19.05% of base)
          16 : 13071.dasm (4.17% of base)
          16 : 14407.dasm (4.71% of base)
          16 : 11879.dasm (4.71% of base)
          16 : 21920.dasm (4.71% of base)
          16 : 265.dasm (1.38% of base)
          16 : 12059.dasm (1.02% of base)
          16 : 4135.dasm (2.41% of base)
          16 : 13231.dasm (5.80% of base)
          16 : 17237.dasm (5.80% of base)
          16 : 19061.dasm (4.71% of base)
          16 : 1602.dasm (2.48% of base)
          16 : 21369.dasm (4.71% of base)
          16 : 22459.dasm (4.88% of base)

293 total files with Code Size differences (0 improved, 293 regressed), 1 unchanged.

Top method regressions (bytes):
          48 ( 3.28% of base) : 12587.dasm - BenchmarksGame.FannkuchRedux_9:Run(int,int)
          32 ( 2.69% of base) : 2757.dasm - System.Number:TryParseInt64IntegerStyle(System.ReadOnlySpan`1[Char],int,System.Globalization.NumberFormatInfo,byref):int
          32 ( 8.89% of base) : 2381.dasm - System.Xml.XmlStreamNodeWriter:UnsafeGetUTF8Chars(long,int,System.Byte[],int):int:this
          24 ( 2.37% of base) : 1201.dasm - System.Text.RegularExpressions.RegexBoyerMoore:.ctor(System.String,bool,bool,System.Globalization.CultureInfo):this
          24 ( 1.14% of base) : 18571.dasm - System.Threading.ReaderWriterLockSlim:TryEnterWriteLockCore(TimeoutTracker):bool:this
          20 ( 1.71% of base) : 9146.dasm - System.Number:TryParseUInt64IntegerStyle(System.ReadOnlySpan`1[Char],int,System.Globalization.NumberFormatInfo,byref):int
          16 ( 1.02% of base) : 12059.dasm - BenchmarksGame.FannkuchRedux_5:run(int,int,int)
          16 ( 2.37% of base) : 21241.dasm - BenchmarksGame.SpectralNorm_1:Bench(int):double:this
          16 ( 0.76% of base) : 23328.dasm - Benchstone.BenchI.Puzzle:DoIt():bool:this
          16 ( 1.47% of base) : 10517.dasm - DecCalc:VarDecMul(byref,byref)
          16 ( 5.80% of base) : 13231.dasm - System.Buffers.Text.Utf8Parser:TryParseByteD(System.ReadOnlySpan`1[Byte],byref,byref):bool
          16 ( 4.17% of base) : 13071.dasm - System.Buffers.Text.Utf8Parser:TryParseUInt16D(System.ReadOnlySpan`1[Byte],byref,byref):bool
          16 ( 2.41% of base) : 4135.dasm - System.Buffers.Text.Utf8Parser:TryParseUInt32D(System.ReadOnlySpan`1[Byte],byref,byref):bool
          16 (19.05% of base) : 11289.dasm - System.Collections.IndexerSet`1[Int32][System.Int32]:Span():int:this
          16 ( 4.71% of base) : 14822.dasm - System.MathBenchmarks.Double:AbsTest()
          16 ( 4.71% of base) : 21369.dasm - System.MathBenchmarks.Double:CeilingTest()
          16 ( 4.71% of base) : 21920.dasm - System.MathBenchmarks.Double:FloorTest()
          16 ( 4.88% of base) : 22459.dasm - System.MathBenchmarks.Double:ILogBTest()
          16 ( 4.71% of base) : 11879.dasm - System.MathBenchmarks.Double:RoundTest()
          16 ( 4.71% of base) : 13485.dasm - System.MathBenchmarks.Double:SqrtTest()

Top method regressions (percentages):
          12 (21.43% of base) : 18878.dasm - System.Diagnostics.Tracing.EventSource:GetDispatcher(System.Diagnostics.Tracing.EventListener):System.Diagnostics.Tracing.EventDispatcher:this
          16 (19.05% of base) : 11289.dasm - System.Collections.IndexerSet`1[Int32][System.Int32]:Span():int:this
          12 (17.65% of base) : 12576.dasm - System.Xml.Linq.XElement:Attribute(System.Xml.Linq.XName):System.Xml.Linq.XAttribute:this
           8 (16.67% of base) : 19693.dasm - System.Collections.Concurrent.ConcurrentStack`1[__Canon][System.__Canon]:get_Count():int:this
           8 (16.67% of base) : 14274.dasm - System.Collections.Concurrent.ConcurrentStack`1[Int32][System.Int32]:get_Count():int:this
          12 (13.64% of base) : 22676.dasm - System.Collections.IterateFor`1[Int32][System.Int32]:ReadOnlySpan():int:this
          12 (13.64% of base) : 22412.dasm - System.Collections.IterateFor`1[Int32][System.Int32]:Span():int:this
          12 (13.64% of base) : 19362.dasm - System.Collections.IterateForEach`1[Int32][System.Int32]:ReadOnlySpan():int:this
          12 (13.64% of base) : 18995.dasm - System.Collections.IterateForEach`1[Int32][System.Int32]:Span():int:this
           8 (13.33% of base) : 22034.dasm - Benchstone.BenchF.DMath:Fact(double):double
           8 (13.33% of base) : 22035.dasm - Benchstone.BenchF.DMath:Power(double,double):double
          12 (13.04% of base) : 17238.dasm - System.Reflection.BlobUtilities:WriteBytes(System.Byte[],int,ubyte,int)
           8 (12.50% of base) : 12681.dasm - Span.IndexerBench:TestIndexer1(System.Span`1[Byte]):ubyte
           8 (12.50% of base) : 13060.dasm - Span.IndexerBench:TestIndexer2(System.Span`1[Byte]):ubyte
           8 (12.50% of base) : 13330.dasm - Span.IndexerBench:TestIndexer3(System.Span`1[Byte]):ubyte
           8 (12.50% of base) : 18057.dasm - Span.IndexerBench:TestReadOnlyIndexer1(System.ReadOnlySpan`1[Byte]):ubyte
           8 (12.50% of base) : 18954.dasm - Span.IndexerBench:TestReadOnlyIndexer2(System.ReadOnlySpan`1[Byte]):ubyte
           8 (12.50% of base) : 11224.dasm - Span.IndexerBench:TestRef(System.Span`1[Byte]):ubyte
           8 (11.76% of base) : 14723.dasm - Span.IndexerBench:TestIndexer6(System.Span`1[Byte],Span.Sink):ubyte
          12 (11.54% of base) : 21117.dasm - System.Collections.IndexerSetReverse`1[Int32][System.Int32]:Span():int:this

293 total methods with Code Size differences (0 improved, 293 regressed), 1 unchanged.

```

</details>

--------------------------------------------------------------------------------

Libraries windows/arm64 diffs:

```

Summary of Code Size diffs:
(Lower is better)

Total bytes of base: 547924
Total bytes of diff: 555328
Total bytes of delta: 7404 (1.35% of base)
Total relative delta: 41.93
    diff is a regression.
    relative diff is a regression.
```
<details>

<summary>Detail diffs</summary>

```

Top file regressions (bytes):
          64 : 6462.dasm (1.75% of base)
          32 : 116552.dasm (8.89% of base)
          32 : 145813.dasm (7.92% of base)
          28 : 213124.dasm (1.77% of base)
          28 : 110271.dasm (6.14% of base)
          28 : 204842.dasm (7.69% of base)
          24 : 100302.dasm (1.50% of base)
          24 : 98371.dasm (9.68% of base)
          24 : 100294.dasm (8.57% of base)
          24 : 99802.dasm (10.71% of base)
          24 : 90757.dasm (0.93% of base)
          24 : 92581.dasm (9.38% of base)
          24 : 98133.dasm (9.68% of base)
          24 : 99568.dasm (10.71% of base)
          24 : 101605.dasm (1.32% of base)
          24 : 222436.dasm (2.37%  [...]

2021-10-18 17:32 UTC, kunalspathak commented
From the private perf run (thanks to @DrewScoggins), all the benchmarks flagged are noisy and there is not an obvious regression from this work. Once this PR is merged, we will continue monitoring the stability of benchmarks.

Windows/arm64 - https://pvscmdupload.blob.core.windows.net/drewtest/reports/report_Default_ca%3DARM64_cb%3Drefs-heads-loopaligntest_co%3DWindows1019041_cr%3Ddotnetruntime_cc%3DCompilationMode%3Dtiered-RunKind%3Dmicro_bb%3Drefs-heads-main_2021-10-18.html

Ubuntu/arm64 - https://pvscmdupload.blob.core.windows.net/drewtest/reports/report_Default_ca%3DARM64_cb%3Drefs-heads-loopaligntest_co%3DUbuntu1804ARM_cr%3Ddotnetruntime_cc%3DCompilationMode%3Dtiered-RunKind%3Dmicro_bb%3Drefs-heads-main_2021-10-18.html

2021-10-19 00:24 UTC, BruceForstall requested changes

2021-10-20 06:12 UTC, kunalspathak commented
Addressed all your feedback. Please take another look.

2021-10-20 06:14 UTC, BruceForstall approved these changes

2021-10-20 15:11 UTC, merged