Add API entry for JsonDocument converter
dotnet/runtime pull request #60236
Opened 2021-10-10 21:51 UTC by strobelt

Fixes #59954 by adding an API entry for JsonDocument converter in the JsonMetadataServices

2021-10-11 11:25 UTC, eiriktsarpalis requested changes
I think more work is needed to wire the converter into the source generator implementation. Could you add a few tests as well?

2021-10-11 16:14 UTC, layomia commented
> I think more work is needed to wire the converter into the source generator implementation. Could you add a few tests as well?

👍 

Ideally, we want to abstract the [`JsonDocument`](https://github.com/dotnet/runtime/blob/71e324fa72e31928d39e8e2f375bdca4c0a11957/src/libraries/System.Text.Json/tests/System.Text.Json.Tests/Serialization/JsonDocumentTests.cs) serializer tests (and possibly the [`JsonElement`](https://github.com/dotnet/runtime/blob/71e324fa72e31928d39e8e2f375bdca4c0a11957/src/libraries/System.Text.Json/tests/System.Text.Json.Tests/Serialization/JsonElementTests.cs) tests) to be shared between the reflection and src-gen implementations of the serializer.  You can use the `ExtensionDataTests.cs`-related diffs in https://github.com/dotnet/runtime/pull/58912 as an example.

2021-10-13 03:19 UTC, strobelt commented
I fixed the naming conventions and added `JsonDocument` to the src-gen implementation.

But I am having a very hard time creating the tests needed. I read the changes on the PR #58912 and from what I understood there were two main changes: 
- The `System.Text.Json.SourceGeneration.Tests/Serialization/ExtensionDataTests.cs` file was created with tests for the JsonExtensionDataAttribute
- The `System.Text.Json/tests/Common/ExtensionDataTests.cs` file was moved to Common and was made dependent on the SerializerTests

If I understood correctly the idea was to abstract the JsonDocument tests from `Serialization\JsonDocumentTests.cs` and `\Serialization\DomTests.cs` into a structure similar to what we have in both the `ExtensionDataTests` files. Is this correct? And if so, could you help me do this correctly? 

Sorry for not being of more help with this, and thanks for all the help!

2021-11-15 09:31 UTC, eiriktsarpalis commented
Hi @strobelt, we haven't had a chance to take a look at this yet. If you don't mind I will close this PR for now but we will revisit once we find the time to work on it.

2022-04-20 15:13 UTC, eiriktsarpalis commented
I've rebased the changes and added a couple of simple unit tests. Rather than abstracting the existing JsonDocument/JsonElement suite, I included a couple of simple acceptance tests in the `RealWorldContextTests` class. We shouldn't need to replicate the full suite just to make sure we're wiring things correctly in the source generator.

2022-04-20 15:13 UTC, eiriktsarpalis approved these changes

2022-04-20 21:47 UTC, eiriktsarpalis commented
Test failures unrelated, cf. https://github.com/dotnet/runtime/issues/68293

2022-04-20 21:47 UTC, merged

2022-04-20 21:48 UTC, eiriktsarpalis commented
Thank you for your contribution @strobelt!