JIT: "Scaled" addressing mode on ARM
dotnet/runtime pull request #60808
Opened 2021-10-24 13:52 UTC by EgorBo

Addressing modes on ARM are tricky, it only supports:
```
[reg]
[reg  + icon]
[reg1 + reg2]
[reg1 + reg2 * natural-scale]
```
while on x64 we can do things like `[reg1 + 8 * reg2 + icon]`

Codegen improvement example:
```csharp
void GetSet(int* data, int i, int j) 
    => data[i] = data[j];
```
diff:
```diff
; Method Prog:GetSet(long,int,int):this
G_M13801_IG01:
            stp     fp, lr, [sp,#-16]!
            mov     fp, sp
G_M13801_IG02:
            sxtw    x0, w3
-           lsl     x0, x0, #2
-           ldr     w0, [x1, x0]
+           ldr     w0, [x1, x0, LSL #2]
            sxtw    x2, w2
-           lsl     x2, x2, #2
-           str     w0, [x1, x2]
+           str     w0, [x1, x2, LSL #2]
G_M13801_IG03:
            ldp     fp, lr, [sp],#16
            ret     lr
; Total bytes of code: 40
```

Also, I removed `SCALED_ADDR_MODES` - it's always defined for all targets and I don't think it simplifies porting to new platforms as before this PR this flag was set but scaled addr modes were disabled anyway.

## coreclr_tests.pmi.Linux.arm64.checked.mch:

```

Summary of Code Size diffs:
(Lower is better)

Total bytes of base: 109454980 (overridden on cmd)
Total bytes of diff: 109451052 (overridden on cmd)
Total bytes of delta: -3928 (-0.00 % of base)
    diff is an improvement.
    relative diff is an improvement.
```
<details>

<summary>Detail diffs</summary>

```

Top file regressions (bytes):
           4 : 2482.dasm (0.71% of base)
           4 : 240122.dasm (1.85% of base)
           4 : 240128.dasm (1.18% of base)

Top file improvements (bytes):
        -324 : 105.dasm (-4.11% of base)
         -52 : 248472.dasm (-6.88% of base)
         -52 : 246408.dasm (-2.92% of base)
         -44 : 240496.dasm (-2.23% of base)
         -32 : 242403.dasm (-0.20% of base)
         -32 : 232908.dasm (-0.20% of base)
         -28 : 237005.dasm (-1.89% of base)
         -28 : 124.dasm (-1.31% of base)
         -24 : 216037.dasm (-5.22% of base)
         -20 : 2477.dasm (-1.79% of base)
         -20 : 103.dasm (-1.09% of base)
         -20 : 237004.dasm (-1.59% of base)
         -16 : 176880.dasm (-1.15% of base)
         -16 : 180145.dasm (-1.15% of base)
         -16 : 247725.dasm (-0.92% of base)
         -16 : 229727.dasm (-1.32% of base)
         -16 : 168580.dasm (-1.15% of base)
         -16 : 179906.dasm (-1.19% of base)
         -16 : 155761.dasm (-1.15% of base)
         -16 : 197830.dasm (-1.15% of base)

703 total files with Code Size differences (700 improved, 3 regressed), 5 unchanged.

Top method regressions (bytes):
           4 ( 1.18% of base) : 240128.dasm - <>c__DisplayClass4_0:<DoBench>b__0(int):this
           4 ( 1.85% of base) : 240122.dasm - BenchmarksGame.MandelBrot_7:GetByte(long,double,int,int):ubyte
           4 ( 0.71% of base) : 2482.dasm - Sys:AllocNullTerminatedArray(System.String[],byref)

Top method improvements (bytes):
        -324 (-4.11% of base) : 105.dasm - System.Text.RegularExpressions.RegexWriter:EmitFragment(int,System.Text.RegularExpressions.RegexNode,int):this
         -52 (-6.88% of base) : 248472.dasm - GitHub_23159:BytesOrdinalEqualsStringAndAscii(System.String,System.Span`1[Byte]):bool
         -52 (-2.92% of base) : 246408.dasm - ImplicitByrefTailCalls:Main():int
         -44 (-2.23% of base) : 240496.dasm - ImplicitByrefTailCalls:Main():int
         -32 (-0.20% of base) : 242403.dasm - StrAccess2:Main():int
         -32 (-0.20% of base) : 232908.dasm - StrAccess2:Main():int
         -28 (-1.89% of base) : 237005.dasm - Runtime_31615:Check(V4,float,float,float,float,int)
         -28 (-1.31% of base) : 124.dasm - System.Text.RegularExpressions.RegexReplacement:.ctor(System.String,System.Text.RegularExpressions.RegexNode,System.Collections.Hashtable):this
         -24 (-5.22% of base) : 216037.dasm - Span.SpanBench:TestQuickSortSpan(System.Span`1[Int32])
         -20 (-1.59% of base) : 237004.dasm - Runtime_31615:Check(V3,float,float,float,int)
         -20 (-1.79% of base) : 2477.dasm - System.Diagnostics.Process:GetNextArgument(System.String,byref):System.String
         -20 (-1.09% of base) : 103.dasm - System.Text.RegularExpressions.RegexWriter:RegexCodeFromRegexTree(System.Text.RegularExpressions.RegexTree):System.Text.RegularExpressions.RegexCode:this
         -16 (-0.92% of base) : 247725.dasm - GitHub_21915:Main():int
         -16 (-1.32% of base) : 229727.dasm - IntelHardwareIntrinsicTest.Program:Main(System.String[]):int
         -16 (-1.15% of base) : 176880.dasm - IntelHardwareIntrinsicTest.Program:PrintErrorHeaderTuv(System.String,System.String)
         -16 (-1.15% of base) : 180145.dasm - IntelHardwareIntrinsicTest.Program:PrintErrorHeaderTuv(System.String,System.String)
         -16 (-1.15% of base) : 168580.dasm - IntelHardwareIntrinsicTest.Program:PrintErrorHeaderTuv(System.String,System.String)
         -16 (-1.19% of base) : 179906.dasm - IntelHardwareIntrinsicTest.Program:PrintErrorHeaderTuv(System.String,System.String)
         -16 (-1.15% of base) : 155761.dasm - IntelHardwareIntrinsicTest.Program:PrintErrorHeaderTuv(System.String,System.String)
         -16 (-1.15% of base) : 197830.dasm - IntelHardwareIntrinsicTest.Program:PrintErrorHeaderTuv(System.String,System.String)

Top method regressions (percentages):
           4 ( 1.85% of base) : 240122.dasm - BenchmarksGame.MandelBrot_7:GetByte(long,double,int,int):ubyte
           4 ( 1.18% of base) : 240128.dasm - <>c__DisplayClass4_0:<DoBench>b__0(int):this
           4 ( 0.71% of base) : 2482.dasm - Sys:AllocNullTerminatedArray(System.String[],byref)

Top method improvements (percentages):
          -4 (-16.67% of base) : 224135.dasm - TestApp:test_116(long,long):long
          -4 (-16.67% of base) : 232140.dasm - TestApp:test_134(long,long):long
          -4 (-16.67% of base) : 231052.dasm - TestApp:test_155(long,long):long
          -4 (-16.67% of base) : 240284.dasm - TestApp:test_173(long,long):long
          -4 (-16.67% of base) : 240286.dasm - TestApp:test_194(long,long):long
          -4 (-16.67% of base) : 243157.dasm - TestApp:test_290(long,long):long
          -4 (-16.67% of base) : 229406.dasm - TestApp:test_311(long,long):long
          -4 (-16.67% of base) : 229422.dasm - TestApp:test_38(long,long):long
          -4 (-16.67% of base) : 232610.dasm - TestApp:test_56(long,long):long
          -4 (-16.67% of base) : 241744.dasm - TestApp:test_95(long,long):long
          -4 (-14.29% of base) : 229435.dasm - TestApp:test_136(long,long):long
          -4 (-14.29% of base) : 232624.dasm - TestApp:test_175(long,long):long
          -4 (-14.29% of base) : 240254.dasm - TestApp:test_292(long,long):long
          -4 (-14.29% of base) : 226381.dasm - TestApp:test_58(long,long):long
          -4 (-14.29% of base) : 237885.dasm - TestApp:test_97(long,long):long
          -4 (-14.29% of base) : 252747.dasm - X:E(byref,int):float
          -4 (-12.50% of base) : 250762.dasm - float4:get_Item(int):float:this
          -4 (-11.11% of base) : 250763.dasm - float4:set_Item(int,float):this
          -4 (-8.33% of base) : 243180.dasm - TestApp:test_212(long,long):long
          -4 (-8.33% of base) : 226348.dasm - TestApp:test_233(long,long):long

703 total methods with Code Size differences (700 improved, 3 regressed), 5 unchanged.

```

</details>

--------------------------------------------------------------------------------

## libraries.crossgen2.Linux.arm64.checked.mch:

```

Summary of Code Size diffs:
(Lower is better)

Total bytes of base: 48207596 (overridden on cmd)
Total bytes of diff: 48200580 (overridden on cmd)
Total bytes of delta: -7016 (-0.01 % of base)
    diff is an improvement.
    relative diff is an improvement.
```
<details>

<summary>Detail diffs</summary>

```

Top file regressions (bytes):
          56 : 124427.dasm (5.19% of base)
          28 : 145076.dasm (3.30% of base)
          24 : 145080.dasm (5.26% of base)
          24 : 124430.dasm (4.48% of base)
           8 : 144854.dasm (3.77% of base)
           8 [...]

2021-10-25 11:22 UTC, jakobbotsch approved these changes
LGTM.

2021-10-26 00:47 UTC, BruceForstall requested changes

2021-10-28 22:47 UTC, BruceForstall approved these changes
LGTM

Long-term, I'm worried about one comment you added:

"For now we only handle MUL and LSH because
 arm doesn't support both scale and offset at the same. Offset is handled
 at the emitter as a peephole optimization."

There's been controversy over the years about what GenTreeAddrMode should represent; it is a fully general x86 addressing mode, as the comments seem to indicate? Or is it "target-specific" as the comments also say? Should it be extended to include the arm64 "sxt/uxt" shifters, for arm? It seems like handling "offset as a peephole optimization" is the wrong place for that; the full address mode should be properly represented in the GenTree.

2021-10-29 11:47 UTC, merged

2021-11-02 10:25 UTC, krwq commented
@EgorBo I think this has regressed rolling builds. See i.e.:
- https://dev.azure.com/dnceng/public/_build/results?buildId=1446655&view=results

essentially every rolling build since then is consistently failing with that assert. If fix is unclear please consider temporarily reverting.

Note: I'm not 100% sure this PR is responsible but looking at the list of commits: https://dev.azure.com/dnceng/public/_traceability/runview/changes?currentRunId=1446655 this looks most probable.

2021-11-04 15:17 UTC, EgorBo commented
improvements in linux-arm64 https://github.com/dotnet/perf-autofiling-issues/issues/2148