Upload checked JITs for Release branches and introduce jitmap.txt
dotnet/runtime pull request #61597
Opened 2021-11-15 14:56 UTC by EgorBo

This PR does two things:
1) It enables jitrollingbuilds for `Release/*.*` branches (in order to produce & publish checked JITs for every commit that touches jit sources in Release branches too - currently it's only done for Main branch -- single-line change in `jitrollingbuild.yml`
2) Introduces a `jitmap.txt` file that can be used to quickly get commit of `dotnet/runtime` that triggered `jitrollingbuild.yml` and produced checked JIT that will be friendly for input `dotnet/runtime` hash.

That will allow end-users (without local `dotnet/runtime` repos and git) to easily download checked jit that matches their own .NET installed in the system (release or daily build - it doesn't matter).

So the algorithm is bit dump currently I just want to check that I'm moving in the right direction: Every non-PR commit `update-checkedjit-map-job.yml` is triggered and invokes `python jitrollingbuild.py updatejitmap` script that only calculates two things: current-git-hash and last-good-checked-jit hash and append them both to AzureStorage's `jitmap.txt` file by re-uploading it. Its content is basically a list:
```
hash1:hash_with_checked_jit_1
hash2:hash_with_checked_jit_1
hash3:hash_with_checked_jit_1
hash4:hash_with_checked_jit_2
hash5:hash_with_checked_jit_2
hash6:hash_with_checked_jit_3
```
The format or type of storage can be improved - it's just a draft, perhaps, you have better ideas how to handle it:
@dotnet/jit-contrib @BruceForstall @kunalspathak

2021-11-15 21:03 UTC, kunalspathak commented
> That will allow end-users (without local dotnet/runtime repos and git) to easily download checked jit that matches their own .NET installed in the system (release or daily build - it doesn't matter).

Can you elaborate how end-users will access `jitMap.txt`?

2021-11-15 21:04 UTC, kunalspathak commented on src/coreclr/scripts/jitrollingbuild.py
> +updatejitmap_parser.add_argument("-az_storage_key", help="Key for the clrjit Azure Storage location. Default: use the value of the CLRJIT_AZ_KEY environment variable.")
Perhaps make this a common key so both `upload` and `updatejitmap` can share? Then you can remove the new code you added specifically for `updatejitmap`?

2021-11-15 21:06 UTC, kunalspathak commented on eng/pipelines/coreclr/update-checkedjit-map.yml
> +    - windows_arm64
Why do we want to run this on all possible configurations? One `windows_x64` machine is good enough to update the git hash, right?

2021-11-16 06:59 UTC, kunalspathak commented on eng/pipelines/coreclr/update-checkedjit-map.yml
> +    - windows_arm64
Also, can we do this as part of `jitrollingbuild` pipeline itself?

2021-11-16 23:56 UTC, BruceForstall requested changes
I have some questions and comments about this:

1. What is the end-to-end scenario here? I.e., how will the newly created `jitmap.txt` file be used? Where will the hash be found to map to the JIT hash that you want to download from the rolling build?
2. What should the retention policy be for the JITs built for the release builds? Currently, we don't have a strong requirement to keep the JITs in Azure Storage except for our own purposes as SPMI asm diffs baseline compilers. Does this new system imply we need to have stronger retention policies for JITs coming from different builds?
3. Should the Azure Storage builds have a new top-level directory named for the branch? Currently, the directory is `builds/git_hash/OS/arch/build_type`; maybe it should be `builds/branch/git_hash/OS/arch/build_type`, with branch like `main` or `release_6.0`. This might not be strictly required since the git hashes would be unique, but it might make it easier to manage (e.g., retention/purge/archive).
4. The proposed `jitmap.txt` file: does it really need to be created for every dotnet/runtime merge? Does it have to be that up-to-date? Can't it be completely created from scratch by looking at the `git` history? Could it be updated once a week, say, instead of on every merge?
5. Doesn't there need to be one jitmap.txt per branch?
6. `process_git_hash_arg` uses `git merge-base <git_hash> origin/main` to find the baseline hash. Doesn't it need to use the release branch (e.g., `release/6.0`) instead of `origin/main` when looking for the baseline in a release branch?
7. If the jitmap.txt update happens for every merge, there will be a race for JIT changes; it might try to update the map before the JIT build completes.
8. Does the JIT need to be signed?
9. We might want to put the jitmap.txt in a new Azure Storage location.

2022-02-15 23:00 UTC, closed without merging