Add path information to INotifyInstanceUserLimitExceeded
dotnet/runtime pull request #62096
Opened 2021-11-27 12:22 UTC by yecril71pl

When you are a .NET developer, chances are you do not know what `inotify` is,, why it is needed and how it is configured, so when you get this error, you are helpless.  I added the configuration file path to the error message to make your life a bit easier.

2021-11-27 15:27 UTC, kasperk81 commented
> why it is needed and how it is configured, so when you get this error, you are helpless.

it is optional and you can use polling over inotify. did _you_ actually got into the situation where you were "helpless" and couldn't find anything related on google, stackoverflow or github? this is unlikely and hypothetical at best...

2021-11-27 16:13 UTC, yecril71pl commented
> > why it is needed and how it is configured, so when you get this error, you are helpless.
> 
> it is optional and you can use polling over inotify. did _you_ actually got into the situation where you were "helpless" and couldn't find anything related on google, stackoverflow or github? this is unlikely and hypothetical at best...

I do not subscribe to the very convenient view that documentation for our products should be provided by third-party services.  The documentation is missing and I have reported it.  If it gets fixed, it will be possible to find relevant information where it should be.  But having the path at hand would save developer&rsquo;s time anyway.

If you share that view, I continue to feel helpless because that is not what quality software should look like.

2021-11-29 13:42 UTC, adamsitnik approved these changes
I am OK with extending the error message to contain the config file path. 

@carlossanlop @tmds thoughts?

@yecril71pl thank you for your contribution!

2021-11-29 13:57 UTC, tmds commented
> @carlossanlop @tmds thoughts?

The resulting message is still not actionable, so I don't think it helps.

A user still has to google and find something like https://stackoverflow.com/questions/43469400/asp-net-core-the-configured-user-limit-128-on-the-number-of-inotify-instance.

2021-11-29 14:03 UTC, tmds commented
> I open the offending file in editor, multiply the value by 2 and save. Tada!

That isn't persisted. So when you reboot the system, the error comes back.

2021-11-29 14:05 UTC, yecril71pl commented
> > I open the offending file in editor, multiply the value by 2 and save. Tada!
> 
> That isn't persisted. So when you reboot the system, the error comes back.

Fortunately, I do not code in .NET every day.  A persistent solution may be mentioned by referring the reader to the corresponding manual page for `inotify` in the documentation for the exception when it finally appears.  But mentioning it in the error message would be an overkill.

2021-11-29 14:19 UTC, tmds commented
I think we may be leading users in the wrong direction by including the file path.

2021-11-29 14:23 UTC, yecril71pl commented
> I think we may be leading users in the wrong direction by including the file path.

I am not sure what you mean.  The path is hardcoded and the message contains the path that has been used to examine the limit, not some path I fancied would be appropriate.  If it stops working because of a change in the kernel, we shall have to change that in the code anyway, and the path in the message will change accordingly.

2021-11-29 14:28 UTC, tmds commented
In your initial message you said:

>  I added the configuration file

This path isn't a configuration file. It is the running kernel setting.
I think in most cases a users will want to update a configuration file (like `/etc/sysctl.conf`) which causes the setting to persist.

2021-11-29 14:32 UTC, yecril71pl commented
> In your initial message you said:
> 
> > I added the configuration file
> 
> This path isn't a configuration file. It is the running kernel setting. I think in most cases a users will want to update a configuration file (like `/etc/sysctl.conf`) which causes the setting to persist.

Running kernel settings are stored in configuration files.  Users who wants to update a persistent configuration file will hopefully find the relevant information in the documentation.  It does not prevent them from reconfiguring the running kernel to get a quick fix.

2022-01-15 17:48 UTC, yecril71pl commented
So here is what the affected application needs to do:
1. Add special syntax to the command line to update the configuration file.
2. Capture and understand the exception where it occurs.  This is fragile because it is not a separate type.
3. Handle the exception by increasing the value.
4. If access denied, execute itself elevated with a special command line.

```C#
// MUI_PATH should preferably be read from the error message instead of being a constant
const string
  MUI_PATH = "/proc/sys/fs/inotify/max_user_instances",
  MUI_MESSAGE = "The configured user limit (",
  EMERGENCY_SYNTAX = "set inotify max user instances to";
static void HandleUserLimitExceeded (IOException ex)
{
  var message = ex .Message;
  if (message .StartsWith (MUI_MESSAGE))
  {
    var imui = int .Parse (File .ReadAllText (MUI_PATH));
    if (message .Substring (MUI_MESSAGE .Length) .StartsWith ($"{ imui })"))
    try { File .WriteAllText (MUI_PATH, (imui <<= 0X1) .ToString ()); }
    catch (UnauthorizedAccessException badAccess)
    {
       using
       (
         var p =
         Process .Start
         (
           "pkexec",
           string .Format
           (
             "\"{0}\" \"{1}\" {2} {3}",
            Environment .ProcessPath,
            Environment .GetCommandLineArgs () [0X0], EMERGENCY_SYNTAX,  imui))
            {
              p .WaitForExit ();
              throw
              new InvalidOperationException
              (
                string .Format
                (
                  "Current user is {0}, run {{ {1};}} AS ROOT!",
                  Environment .UserName,
                  p .StartInfo .Arguments), badAccess); }}} throw; }
static bool HandleEmergencyCommandLine (string[] args)
{
  if (args .SkipLast (0X1) .SequenceEqual(EMERGENCY_SYNTAX .Split ()))
  { File .WriteAllText (MUI_PATH, args [0X6]); return true; } return default; }

```

2022-01-24 08:37 UTC, adamsitnik requested changes
As pointed by @tmds, these settings are not persisted between system reboots. Since this might be surprising to our users (I was also not aware of that when I've initially accepted this PR), this should be well explained and **documented**. In my opinion it's too much information for exception message which needs to be concise. That is why I've created a new issue in our docs repo: https://github.com/dotnet/dotnet-api-docs/issues/7625.

@yecril71pl thank you for your contribution! Is there any chance you would like to contribute to our docs? It's also a GH repository.

2022-01-24 08:37 UTC, closed without merging