[wasm] more emscripten asserts for debug build of runtime
dotnet/runtime pull request #62254
Opened 2021-12-01 22:19 UTC by pavelsavara

`-s ASSERTIONS=1` for debug build of runtime. It emits asserts to C and JS, it helps with debugging.

> ASSERTIONS=1 is used to enable runtime checks for common memory allocation errors (e.g. writing more memory than was allocated). It also defines how Emscripten should handle errors in program flow. The value can be set to ASSERTIONS=2 in order to run additional  #tests.

See https://emscripten.org/docs/porting/Debugging.html

2021-12-01 22:32 UTC, radical commented
Related question - would it help, or make sense to enable this for AOT/library tests?

2021-12-01 23:28 UTC, kg approved these changes
Makes sense to me. I agree that we might want to enable it for AOT and/or library tests.

2021-12-02 02:24 UTC, lewing requested changes
Not until this doesn't break blazor

2021-12-02 02:26 UTC, lewing commented
see https://github.com/dotnet/aspnetcore/issues/37690

2021-12-30 12:00 UTC, closed without merging