Increase count of bit for emitAddrMode::amScale
dotnet/runtime pull request #62782
Opened 2021-12-14 15:34 UTC by kant2002

Currently emitter::opSize hold values form 0 to 6, and as such require 3 bits

2021-12-14 15:36 UTC, kant2002 commented
Link existing code for reference

https://github.com/dotnet/runtime/blob/663e7b4aad00c34bbb9a98310a56433160682078/src/coreclr/jit/emit.h#L457-L471

2021-12-14 16:29 UTC, EgorBo commented
I'm not against adding a bit for correctness but it sounds like 1 bit will cause +31 bits-long padding for this struct?

2021-12-14 16:29 UTC, EgorBo commented
@dotnet/jit-contrib

2021-12-14 16:41 UTC, SingleAccretion commented
I believe so.

For reference, here are layouts of the relevant data structures on x86:
```c
struct emitter::instrDesc /* size 12 @ C:\Users\Accretion\source\dotnet\runtime\src\coreclr\jit\emit.h:577 */
{
/* 0000:04 */ instruction _idIns;
/* 0000:04 */ emitter::insFormat _idInsFmt;
/* 0000:04 */ uint32_t _idCodeSize;
/* 0000:04 */ emitter::opSize _idOpSize;
/* 0000:04 */ GCtype _idGCref;
/* 0000:04 */ _regNumber_enum _idReg1;
/* 0004:04 */ uint32_t _idDspReloc;
/* 0004:04 */ uint32_t _idCnsReloc;
/* 0004:04 */ uint32_t _idNoGC;
/* 0004:04 */ uint32_t _idCallAddr;
/* 0004:04 */ uint32_t _idCallRegPtr;
/* 0004:04 */ uint32_t _idLargeDsp;
/* 0004:04 */ uint32_t _idLargeCall;
/* 0004:04 */ uint32_t _idSmallCns;
/* 0004:04 */ uint32_t _idLargeCns;
/* 0004:04 */ uint32_t _idSmallDsc;
/* 0004:04 */ _regNumber_enum _idReg2;
/* 0004:04 */ uint32_t _idBound;
/* 0008:04 */ emitter::instrDesc::idAddrUnion _idAddrUnion;
};

struct emitter::instrDesc::idAddrUnion /* size 4 @ C:\Users\Accretion\source\dotnet\runtime\src\coreclr\jit\emit.h:809 */
{
/* 0000:04 */ emitLclVarAddr iiaLclVar;
/* 0000:04 */ BasicBlock* iiaBBlabel;
/* 0000:04 */ insGroup* iiaIGlabel;
/* 0000:04 */ uint8_t* iiaAddr;
/* 0000:04 */ emitter::emitAddrMode iiaAddrMode;
/* 0000:04 */ CORINFO_FIELD_STRUCT_* iiaFieldHnd;
/* 0000:04 */ int32_t iiaEncodedInstrCount;
/* 0000:04 */ _regNumber_enum _idReg3;
/* 0000:04 */ _regNumber_enum _idReg4;
};

struct emitter::emitAddrMode /* size 4 @ C:\Users\Accretion\source\dotnet\runtime\src\coreclr\jit\emit.h:532 */
{
/* 0000:04 */ _regNumber_enum amBaseReg;
/* 0000:04 */ _regNumber_enum amIndxReg;
/* 0000:04 */ emitter::opSize amScale;
/* 0000:04 */ int32_t amDisp;
};
```

2021-12-14 16:47 UTC, am11 commented
Yup, that's correct @EgorBo. We never assign larger than two-bit value, otherwise clang would have raised `-Wbitfield-constant-conversion` and gcc `-Woverflow` (both are fatal build time errors). ref: https://github.com/dotnet/runtime/issues/33541#issuecomment-754285791

2021-12-14 17:12 UTC, kant2002 commented
> but it sounds like 1 bit will cause +31 bits-long padding for this struct

I probably again miss something, previously struct was declared like this
```
struct emitAddrMode
    {
        regNumber       amBaseReg : 7;
        regNumber       amIndxReg : 7;
        emitter::opSize amScale : 2;
        int             amDisp : 16;
    };
```

REGNUM_BITS  is consistently == 6 everywhere.

with this change it would be 
```
struct emitAddrMode
    {
        regNumber       amBaseReg : 7;
        regNumber       amIndxReg : 7;
        emitter::opSize amScale : 3;
        int             amDisp : 15;
    };
```
Not sure if it reducing size of `amDisp` was too optimistic on my side.

2021-12-14 17:16 UTC, EgorBo commented
@kant2002 ah, sorry, I didn't notice you were reducing `amDisp` and the fact it even had explicit size

2021-12-14 18:18 UTC, EgorBo commented
CI failures are related

2021-12-14 18:49 UTC, BruceForstall commented
Presumably x86/x64 only uses 0-3, but arm64 can use 4 and maybe 5?

It seems like OPSZ16 / OPSZ32 should be ifdef'ed out for x86/x64. It's surprising that arm64 wouldn't have had bugs here, but it is only for certain hwintrinsics ops that it would apply. @echesakovMSFT ?

2021-12-14 19:21 UTC, EgorBo commented
> It seems like OPSZ16 / OPSZ32 should be ifdef'ed out for x86/x64. 

From my understanding this enum is not only for scales but also for sizes so these values are needed there

2021-12-14 19:52 UTC, EgorBo commented
>  but it is only for certain hwintrinsics ops that it would apply

Here is an example where 4 could be used: https://godbolt.org/z/dvs97GMdT
JIT emits:
```
00000000          add     x0, x0, x1, LSL #4
00000000          ldr     q16, [x0]
```
so for this one it's fine so far but I see your point

2021-12-15 01:10 UTC, BruceForstall commented
> add     x0, x0, x1, LSL #4

That case allows a shift of 0-63 in an immediate, so it doesn't use the opSize mechanism.

2021-12-15 01:47 UTC, EgorBo commented
> > add     x0, x0, x1, LSL #4
> 
> That case allows a shift of 0-63 in an immediate, so it doesn't use the opSize mechanism.

Yes, that's what I meant by "it's fine" - we don't use scale there

2021-12-15 01:50 UTC, BruceForstall requested changes
I don't think we want this change.

`amScale` is only used on x86/x64, and there, for addressing modes, it can only be 0-3 (representing scales of 1, 2, 4, 8).

I PR'ed a change to put this under #ifdef to make that explicit: https://github.com/dotnet/runtime/pull/62830

One thing that might be useful is to make these fields (including `amScale`) private, and add "set" functions that assert the values being set are in range.

2021-12-15 02:24 UTC, closed without merging