Allow empty IGs when allocating unwind info for a fragment
dotnet/runtime pull request #62862
Opened 2021-12-15 21:00 UTC by kunalspathak

The empty IGs are sometimes created before the loop that we are trying to align to ensure the loop size calculation is correct.

Fixes: #62250

2021-12-15 21:00 UTC, kunalspathak commented
@dotnet/jit-contrib

2021-12-16 05:20 UTC, BruceForstall requested changes
I apologize, since I suggested to you to loosen the assert, but after looking at the test case for a while, I think this is the wrong fix. I think there's a bug in the split algorithm (emitSplit) for zero sized IGs. Do you mind if I take the issue?

2021-12-16 07:08 UTC, kunalspathak commented
Now that I was able to debug the issue with your minimum repro, I think the problem is that we should not report the candidate if it has size zero. So, may be something like this? I verified and it fixes the issue. Were you thinking similar fix?

```diff
@@ -2764,6 +2764,10 @@ void emitter::emitSplit(emitLocation*         startLoc,
         {
             // We can't update the candidate
         }
+        else if (ig->igSize == 0)
+        {
+            // We can't update the candiate because it is empty.
+        }
         else
         {
             igLastCandidate = ig;
```

2021-12-16 22:52 UTC, BruceForstall commented
@kunalspathak Almost; here's my proposal: https://github.com/dotnet/runtime/pull/62931

2021-12-16 22:57 UTC, kunalspathak commented
https://github.com/dotnet/runtime/pull/62931 will take care of this.

2021-12-16 22:57 UTC, closed without merging