[wasm] Socket tests on NodeJS
dotnet/runtime pull request #63441
Opened 2022-01-06 11:35 UTC by maraf

Enable WebSocket tests on NodeJS.

- [x] Install `ws` npm package.
- [x] Load installed packages in `test-main.js`.
- [ ] Enable WebSocket tests on NodeJS.

2022-01-07 14:00 UTC, pavelsavara commented on src/libraries/System.Net.WebSockets.Client/tests/WebSocketHelper.cs
> +            if (PlatformDetection.IsBrowser && PlatformDetection.Host == "v8")
spidermonkey ?

2022-01-07 14:04 UTC, pavelsavara commented on eng/testing/WasmRunnerTemplate.cmd
> +if exist "%EXECUTION_DIR%\package-lock.json" (
Could we do with flag from specific csproj instead of file sniffing ?
Possibly also via <RunScriptCommands> instead of adding it here.

2022-01-07 14:05 UTC, pavelsavara commented on src/libraries/System.Net.WebSockets.Client/tests/System.Net.WebSockets.Client.Tests.csproj
> +    <SetScriptCommands Condition="'$(Scenario)' != ''" Include="export NODE_TLS_REJECT_UNAUTHORIZED=0" />
Please add comment on why

2022-01-11 10:47 UTC, maraf commented
/azp run runtime-manual

2022-01-11 10:57 UTC, maraf commented
/azp run runtime-manual

2022-01-12 10:03 UTC, maraf commented
/azp run runtime-manual

2022-01-12 11:55 UTC, pavelsavara commented on src/libraries/System.Net.WebSockets.Client/tests/System.Net.WebSockets.Client.Tests.csproj
> +    <WasmExtraFilesToDeploy Include="package.json" />
Are these files available for all projects ?

2022-01-12 11:58 UTC, pavelsavara commented on src/libraries/System.Net.WebSockets.Client/tests/ConnectTest.cs
> +        [ActiveIssue("TBD", TestPlatforms.Browser)]
one more

2022-01-12 12:05 UTC, pavelsavara approved these changes
One more active issue link and we good to go

2022-01-12 12:06 UTC, pavelsavara commented
/azp run runtime-manual

2022-01-12 12:55 UTC, maraf commented on src/libraries/System.Net.WebSockets.Client/tests/System.Net.WebSockets.Client.Tests.csproj
> +  <PropertyGroup Condition="'$(Scenario)' == 'WasmTestOnNodeJS'">
Locally I'm passing a `-p:Scenario=WasmTestOnNodeJS` and it works.

2022-01-12 13:19 UTC, pavelsavara commented on src/libraries/System.Net.WebSockets.Client/tests/System.Net.WebSockets.Client.Tests.csproj
> +  <PropertyGroup Condition="'$(Scenario)' == 'WasmTestOnNodeJS'">
I think it would not work on helix

2022-01-13 12:31 UTC, maraf commented
/azp run runtime-manual

2022-01-13 14:07 UTC, maraf commented
/azp run runtime-manual

2022-01-13 14:10 UTC, pavelsavara requested changes
I think that HelixPreCommand will not run from inside sendtohelix. At that point build is already done and we are dealing with zip files. You have to do it inside sendtohelix, I thnik

2022-01-14 10:49 UTC, maraf commented
/azp run runtime-manual

2022-01-14 12:39 UTC, pavelsavara approved these changes

2022-01-14 13:00 UTC, maraf commented
/azp run runtime-manual

2022-01-14 15:40 UTC, maraf commented
/azp run runtime-manual

2022-01-19 16:10 UTC, maraf commented
/azp run runtime-manual

2022-01-20 12:58 UTC, merged