Fix NullabilityInfoContext.Create to properly analyze types with nested generic types
dotnet/runtime pull request #63556
Opened 2022-01-09 18:33 UTC by Shane32

Consider the following method signature:

```cs
public static Tuple<Tuple<string?, string?>, string> Field2() { }
```

Attempting to interpret the nullability attributes of `Field2`, it will report that the final `string` is nullable when in fact it is not.  For a complete demonstration, please view this file:

https://github.com/graphql-dotnet/graphql-dotnet/blob/f190a1566f61f29e1909fe6b7dcbb7140c404908/src/GraphQL.Tests/NRTTests.cs

The problem is that when enumerating the generic type definitions of `Tuple<Tuple<string?, string?>, string>`, and specifically the first generic type `Tuple<string?, string?>`, the code does not increment the index of the nullability byte in the metadata by 3 (non-null, nullable, nullable) but instead only increments it by 1.  So it reads the wrong byte value from the attribute.

I have changed the `GetNullabilityInfo` private method to accept a `ref` index argument so that it can update the index properly based on the number of nested types (and whether or not those nested types utilize a nullability byte, since non-generic value types do not).

I would be happy to add tests, but I'm not sure where in the codebase to do so.

2022-01-09 19:18 UTC, Shane32 commented on src/libraries/System.Private.CoreLib/src/System/Reflection/NullabilityInfoContext.cs
> +                    }
```suggestion
                        {
                            state = TranslateByte(elementB);
                            return true;
                        }
```

2022-01-12 05:52 UTC, buyaa-n requested changes
@Shane32, thanks for your contribution, the fix LGTM, please add corresponding test [here ](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Runtime/tests/System/Reflection/NullabilityInfoContextTests.cs)

2022-01-12 11:05 UTC, Shane32 commented
I will do so - thanks!

2022-01-17 07:44 UTC, Shane32 commented
@buyaa-n I wrote a simple test.  Please review, let me know if you'd like additional variations, how many, etc.  Thanks!

2022-01-18 04:31 UTC, buyaa-n approved these changes
>  let me know if you'd like additional variations, how many (many or few), etc. Thanks!

Thanks @Shane32, LGTM, the tests looks enough for the fix, I would add test for generics but as you know there is a bug needs to be fixed.

2022-01-18 18:55 UTC, buyaa-n commented
Failures unrelated and filed an [issue ](https://github.com/dotnet/runtime/issues/63946) for one and there is existing [issue](https://github.com/dotnet/runtime/issues/63439) for other, merging

2022-01-18 18:56 UTC, merged

2022-01-18 18:57 UTC, Shane32 commented
Thanks @buyaa-n !