Fixes #66141: ConfigurationBinder and ISet
dotnet/runtime pull request #66151
Opened 2022-03-03 18:04 UTC by xakep139

This is to fix #66141 
I didn't add all the tests, this is just to illustrate an idea (although all added tests are passing).
I also fixed some existing tests (few `Bind` and `Get` ones duplicate each other)

2022-03-04 09:59 UTC, xakep139 commented
Test failures seem unrelated

2022-03-22 22:42 UTC, maryamariyan commented
> I didn't add all the tests, this is just to illustrate an idea (although all added tests are passing).

what other tests would need to be included?

2022-03-22 23:27 UTC, maryamariyan requested changes

2022-03-22 23:27 UTC, maryamariyan commented on src/libraries/Microsoft.Extensions.Configuration.Binder/src/ConfigurationBinder.cs
> +            Type genericType = typeof(HashSet<>).MakeGenericType(type.GenericTypeArguments[0]);
I'd assume this would change based on the comment by @halter73 in https://github.com/dotnet/runtime/issues/66141#issuecomment-1075743040

2022-03-23 16:41 UTC, xakep139 commented
> > I didn't add all the tests, this is just to illustrate an idea (although all added tests are passing).
> 
> what other tests would need to be included?

@maryamariyan, I didn't add all possible variations/use-cases of `IDictoinary<>`, `IReadOnlyDictoinary<>`, `ISet<>` and `IReadOnlySet<>` in tests. Will add those when approach that [Stephen Halter](https://github.com/halter73) proposed is implemented.

2022-04-05 23:40 UTC, maryamariyan commented
Closing this PR pending feedback in https://github.com/dotnet/runtime/issues/66141#issuecomment-1075743040

2022-04-05 23:40 UTC, closed without merging