Perform reachability analysis before codegen
dotnet/runtime pull request #66967
Opened 2022-03-22 00:12 UTC by kunalspathak

Perform reachability analysis one last time before doing code gen to eliminate unreachable blocks.

2022-03-22 20:55 UTC, kunalspathak commented
@dotnet/jit-contrib

2022-03-22 21:08 UTC, AndyAyersMS reviewed
Are you actually removing the blocks anywhere?

`fgComputeReachability` is not particularly efficient (it blindly unions all preds instead of just the ones with updates).

It is overkill for what I think you are looking for here -- you only want to know if a block A is reachable from method entry, not whether block A is reachable from block B.

`fgComputeReachability` also updates the gc safe block flags, which, while likely harmless is probably not something we want to be doing.

So I think you can get this information more cheaply and with less collateral impact.

2022-03-22 21:08 UTC, AndyAyersMS commented on src/coreclr/jit/compiler.cpp
> +    DoPhase(this, PHASE_COMPUTE_REACHABILITY, computeReachability);
I would use a different local name and a different phase name (reusing a phase name likely messes up some stats computations).

2022-03-22 21:50 UTC, BruceForstall requested changes

2022-03-22 21:50 UTC, BruceForstall commented on src/coreclr/jit/compiler.cpp
> -        DoPhase(this, PHASE_COMPUTE_REACHABILITY, &Compiler::fgComputeReachability);
Why does this need to change?

2022-03-22 21:50 UTC, BruceForstall commented on src/coreclr/jit/emit.cpp
> +            printf("\t\t\t\t\t\t;;  size=%d   bbWeight=%s PerfScore %.2f", ig->igSize, refCntWtd2str(ig->igWeight),
nit: why so much whitespace?

2022-03-22 21:50 UTC, BruceForstall commented on src/coreclr/jit/fgopt.cpp
> +void Compiler::fgComputeEnterBlocksSet(DEBUG_ARG1(const bool renumberingDone))
This is kind of annoying (adding an arg just for this). Why not just remove the offending assert instead? Doesn't seem like it has much value anyway.

2022-03-22 21:50 UTC, BruceForstall commented on src/coreclr/jit/fgopt.cpp
> +//       computeDoms - Whether to compute doms or not.
It would be useful to understand (and add to this comment block) when renumbering is required, and why. And when it is not. Same for creating doms.

2022-03-22 22:51 UTC, kunalspathak commented
> Are you actually removing the blocks anywhere?

Yes, after it tracks the `bbReach` it uses it to determine (by referring the `fgEnterBlks`) whether to remove it or not, but I agree with you. I can do `bbReach` or equivalent calculation cheaper. Let me work on it.

https://github.com/dotnet/runtime/blob/8b42dffa5f37762caddbe949ebc2fc348cca5121/src/coreclr/jit/fgopt.cpp#L455-L464

2022-03-22 23:02 UTC, kunalspathak commented
@AndyAyersMS - Just to answer your original question, yes it does remove block in that method as seen [in asmdiffs](https://dev.azure.com/dnceng/public/_build/results?buildId=1675329&view=ms.vss-build-web.run-extensions-tab).

2022-03-23 07:18 UTC, kunalspathak commented
I have verified the diffs between the new implementation and previous (exhaustive) implementation and there is no diff.

2022-03-24 19:05 UTC, AndyAyersMS reviewed
I think the approach is good.

I have one question and also wondered if you had new TP measurements.

2022-03-24 22:14 UTC, kunalspathak commented on src/coreclr/jit/fgopt.cpp
> +    do
I need to double check. I was trying to be conservative and reuse the same logic we have in reachability, but may be the way I am calling reachability here, another iteration might not be needed.

2022-03-24 22:14 UTC, kunalspathak commented
I guess there are superpmi replay for linux-arm failures that I need to look into.

https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-66967-merge-88ab271474c44ff7ab/unix-arm-1/1/console.33965e13.log?sv=2019-07-07&se=2022-04-12T07%3A25%3A15Z&sr=c&sp=rl&sig=K9oClcSFxxSXGc4cuE6aKs4EUpOU9DzkcMyRZ6OKLWM%3D

2022-03-25 18:01 UTC, BruceForstall commented on src/coreclr/jit/fgopt.cpp
> +    do
Since you aren't recomputing reachability each loop, it seems that iterating won't have an effect anyway.

2022-03-28 23:26 UTC, kunalspathak commented
Latest pin numbers on superpmi libraries_pmi collection:

```
Before: 327744184719
After: 328136546105
Diff: 0.12%
```

2022-03-28 23:59 UTC, BruceForstall approved these changes

2022-03-28 23:59 UTC, BruceForstall commented on src/coreclr/jit/fgopt.cpp
> +            worklist.insert(worklist.end(), block->bbNext);
this could also be:
```suggestion
            worklist.push_back(block->bbNext);
```
?

2022-03-29 02:22 UTC, kunalspathak commented on src/coreclr/jit/fgopt.cpp
> +            worklist.insert(worklist.end(), block->bbNext);
ah missed this one.

2022-03-29 02:24 UTC, kunalspathak commented
failure related to https://github.com/dotnet/runtime/issues/59542

2022-03-29 16:19 UTC, merged

2022-04-07 17:00 UTC, EgorBo commented
Improvements in System.Text.Json.Tests.Perf_Booleans https://github.com/dotnet/perf-autofiling-issues/issues/4364 on x64