JIT: add standard range enable for register stress
dotnet/runtime pull request #68574
Opened 2022-04-26 22:01 UTC by AndyAyersMS

Add `COMPlus_JitStressRegsRange` to specify a subset of methods that should be
subjected to register stress. The range is the standard method hash range,
for example:

```
COMPlus_JitStressRegsRange=FD400000-FD4FFFFF
```

Remove the older non-standard bits that did something similar, along with the
version based on method number, which tends to be less useful with modern tests like
libraries tests where jit order is never fully deterministic.

2022-04-26 22:01 UTC, AndyAyersMS commented
@kunalspathak PTAL
cc @dotnet/jit-contrib

2022-04-26 22:40 UTC, BruceForstall requested changes

2022-04-26 22:40 UTC, BruceForstall commented on src/coreclr/jit/lsra.cpp
> +            JITDUMP("*** JitStressRegs = 0x%x -- disabled by JitStressRegsRange\n");
No replacement for %x

2022-04-26 22:40 UTC, BruceForstall commented on src/coreclr/jit/lsra.cpp
> +            JITDUMP("*** JitStressRegs = 0x%x\n");
no replacement for %x

2022-04-26 22:40 UTC, BruceForstall commented on src/coreclr/jit/jitconfigvalues.h
> +CONFIG_STRING(JitStressRegsRange, W("JitStressRegsRange"))
Add a minimal comment?

2022-04-27 01:32 UTC, BruceForstall approved these changes

2022-04-27 01:34 UTC, kunalspathak approved these changes

2022-04-27 15:31 UTC, AndyAyersMS commented
Failure looks similar to #67816.

2022-04-27 15:32 UTC, merged