[release/6.0] Use x64 directory if running x64 process on arm64 apphost
dotnet/runtime pull request #68583
Opened 2022-04-27 03:12 UTC by elinor-fung

Backport of #59890

## Customer Impact

## Testing

## Risk

2022-04-27 09:07 UTC, vitek-karas approved these changes

2022-04-29 18:13 UTC, vitek-karas approved these changes

2022-04-29 18:59 UTC, jeffschwMSFT approved these changes
Approved.  We will take for consideration in 6.0.x

2022-05-03 23:33 UTC, carlossanlop requested changes
@elinor-fung @vitek-karas the CI has failures. Can you confirm if the errors are related to this change? If not, let me know so I can merge this.

2022-05-04 00:19 UTC, elinor-fung commented
The failures are unrelated:
- https://github.com/dotnet/runtime/issues/67946
- https://github.com/dotnet/runtime/issues/68293
- Failure to connect to Android device (`Unexpected response from adb devices -l`), which this change would not affect

2022-05-04 02:28 UTC, carlossanlop approved these changes

2022-05-04 02:29 UTC, merged