Fix VSTest and dotnet test broken on .NETFramework
dotnet/runtime pull request #68863
Opened 2022-05-04 17:09 UTC by ViktorHofer

Fixes https://github.com/dotnet/runtime/issues/68384

For a detailed explanation why updating the xunit.runner.visualstudio fixes .NETFramework dotnet test and VSTest invocation please see the above linked issue.

2022-05-04 17:56 UTC, eiriktsarpalis commented
Getting the following error when testing your branch locally:
```C#
C:\Users\eitsarpa\devel\dotnet\runtime\src\libraries\System.Text.Json\tests\System.Text.Json.Tests\System.Text.Json.Tests.csproj : error NU1202: Package xunit.runner.visualstudio 2.4.4 is not compatible with net462 (.NETFramework,Version=v4.6.2). Package xunit.runner.visualstudio 2.4.4 supports: [C:\Users\eitsarpa\devel\dotnet\runtime\src\libraries\System.Text.Json\System.Text.Json.sln]
C:\Users\eitsarpa\devel\dotnet\runtime\src\libraries\System.Text.Json\tests\System.Text.Json.Tests\System.Text.Json.Tests.csproj : error NU1202:   - net472 (.NETFramework,Version=v4.7.2) [C:\Users\eitsarpa\devel\dotnet\runtime\src\libraries\System.Text.Json\System.Text.Json.sln]
C:\Users\eitsarpa\devel\dotnet\runtime\src\libraries\System.Text.Json\tests\System.Text.Json.Tests\System.Text.Json.Tests.csproj : error NU1202:   - netcoreapp3.1 (.NETCoreApp,Version=v3.1) [C:\Users\eitsarpa\devel\dotnet\runtime\src\libraries\System.Text.Json\System.Text.Json.sln]
C:\Users\eitsarpa\devel\dotnet\runtime\src\libraries\System.Text.Json\tests\System.Text.Json.Tests\System.Text.Json.Tests.csproj : error NU1202:   - uap10.0.16299 (UAP,Version=v10.0.16299) [C:\Users\eitsarpa\devel\dotnet\runtime\src\libraries\System.Text.Json\System.Text.Json.sln]
```
Would this change require increasing `NetFrameworkMinimum` to `net472` perhaps?

2022-05-04 20:51 UTC, stephentoub approved these changes

2022-05-05 11:12 UTC, eiriktsarpalis requested changes
I'd hold off from merging until we either bump the minimum framework version or revert https://github.com/xunit/visualstudio.xunit/commit/d0447cf1d347c09180681b9201075acf2fdc3e20. Tests might work in CI but this change would break the dev loop.

2022-05-05 17:57 UTC, eiriktsarpalis approved these changes
Latest change works like a charm. Thanks!

2022-05-05 19:27 UTC, merged