Fix tracking for if a type has auto-layout fields for the managed type system.
dotnet/runtime pull request #69451
Opened 2022-05-17 18:21 UTC by jkoritzinsky

cc:@davidwrighton

2022-05-17 18:54 UTC, davidwrighton requested changes
Looks good except for the extra debugging code.

2022-05-17 18:54 UTC, davidwrighton commented on src/coreclr/tools/Common/TypeSystem/Common/MetadataFieldLayoutAlgorithm.cs
> +            if (type.Name == "ObjectHandleOnStack") System.Diagnostics.Debugger.Break();
Remove this.

2022-05-17 18:55 UTC, jkoritzinsky commented on src/coreclr/tools/Common/TypeSystem/Common/MetadataFieldLayoutAlgorithm.cs
> +            if (type.Name == "ObjectHandleOnStack") System.Diagnostics.Debugger.Break();
```suggestion
```

2022-05-17 18:55 UTC, jkoritzinsky commented
Removed the debugging code

2022-05-17 20:30 UTC, davidwrighton approved these changes

2022-05-17 20:57 UTC, stephentoub approved these changes

2022-05-24 21:46 UTC, jkoritzinsky commented
Only failure is #69476. Merging in

2022-05-24 21:46 UTC, merged