Issue 71386
dotnet/runtime pull request #72041
Opened 2022-07-12 17:58 UTC by turnyanszki

#if NET5_0_OR_GREATER is needed beacuse the project is targeting .net framwork for some reason (analyzers maybe).
All project should be refactored at some point in my opinion.

2022-07-12 19:35 UTC, radical commented
@turnyanszki In the PR description, could you please describe the issue that you are fixing here? Also, add a short title for the PR. And reference any link for the issue, if there is one.

2022-09-06 02:22 UTC, danmoseley commented
@Jozkee  could you please give an idea when you will be able to review? This change seems small.

2022-09-06 15:28 UTC, eerhardt commented
@turnyanszki - looks like the new test you added to verify the bug fix is failing on .NET Framework. This is because you are only adding code for `#if NET5_0_OR_GREATER`. You need to also fix the bug for .NET Framework.

2022-09-06 15:29 UTC, eerhardt commented on src/libraries/Microsoft.Extensions.FileProviders.Physical/src/PhysicalFilesWatcher.cs
> +#if NET5_0_OR_GREATER
```suggestion
#if NETCOREAPP
```

We only build this library on .NET Core for net6.0+. So the if can be simplified (we don't use lower version checks than what we build for).

2022-09-10 18:56 UTC, turnyanszki commented
> @turnyanszki - looks like the new test you added to verify the bug fix is failing on .NET Framework. This is because you are only adding code for `#if NET5_0_OR_GREATER`. You need to also fix the bug for .NET Framework.

I dont want to implement the whole Path.GetFullPath method myself, and it does not exists in .NET Framework.
Any suggestions?

2022-09-12 15:01 UTC, eerhardt commented
> I dont want to implement the whole Path.GetFullPath method myself, and it does not exists in .NET Framework.
Any suggestions?

Looking at `Path.GetFullPath`, the trickiest part is the `if (IsPathFullyQualified(path))` method:

https://github.com/dotnet/runtime/blob/878354a9d2c159cec527edc94bffdd3324570feb/src/libraries/System.Private.CoreLib/src/System/IO/Path.Unix.cs#L36-L51

This method is available on `netstandard2.0` or .NET Framework. However, looking at the callers of this method, it call comes from `CreateFileChildToken` here:

https://github.com/dotnet/runtime/blob/878354a9d2c159cec527edc94bffdd3324570feb/src/libraries/Microsoft.Extensions.FileProviders.Physical/src/PhysicalFilesWatcher.cs#L134-L146

Which verifies that the `filter` string isn't a rooted path. So I believe you can just Combine the two paths, and call GetFullPath on the result. That _should_ be the same on .NET Framework.

2022-10-10 21:45 UTC, Jozkee requested changes

2022-10-10 21:45 UTC, Jozkee commented on src/libraries/Microsoft.Extensions.FileProviders.Physical/src/PhysicalFilesWatcher.cs
> +#endif
@eerhardt suggestion, this should work for .NET Framework too:

```suggestion
#if NETCOREAPP
            string absolutePath = Path.GetFullPath(filePath, _root);
#else
            string absolutePath = Path.GetFullPath(Path.Combine(_root, filePath));
#endif
            filePath = absolutePath.Substring(_root.Length);
```

2022-10-10 21:45 UTC, Jozkee commented on src/libraries/Microsoft.Extensions.Configuration/tests/FunctionalTests/ConfigurationTests.cs
> +        public async Task ReloadingFileFiresOnChangeEvent()
This test should be a `Theory` and you should put `./reload.json` and `reload.json` as `InlineData`.

2022-11-08 06:02 UTC, closed without merging