Remove Mono LLVM tools from Darc subscription
dotnet/runtime pull request #72212
Opened 2022-07-14 19:36 UTC by agocke

Someone disabled the llvm-project -> runtime subscription, presumably
to disable the update of the Mono llvm tools. But NativeAOT also gets
the objwriter from that subscription. That needs to stay. This change
just removes the Mono LLVM items from the subscription.

2022-07-14 19:37 UTC, agocke commented
FYI @MichalStrehovsky

2022-07-14 22:26 UTC, agocke commented
@directhex @akoeplinger @steveisok @lewing for review

2022-07-15 01:16 UTC, lewing requested changes
this is not the fix

2022-07-15 02:39 UTC, steveisok commented
I'm confused.  Why is this needed?

2022-07-15 04:28 UTC, MichalStrehovsky commented
The Mono bits in the channel are broken - see the Darc update attempt here: https://github.com/dotnet/runtime/pull/72150

It looked like whoever disabled the subscription did so to avoid the failures. Darc updates for both Mono's LLVM stuff and NativeAOT LLVM stuff stopped flowing 2 months ago. Noticed because a fix for objwriter we made in LLVM repo didn't make it to this repo.

2022-07-16 21:10 UTC, agocke commented
Sounds like Mono still wants to update using this subscription.

2022-07-16 21:10 UTC, closed without merging