[wasm][debugger] Fix "command is not pending"
dotnet/runtime pull request #72953
Opened 2022-07-27 17:50 UTC by thaystg

Session id can be different if there is a redirect, but the message id is kept.

I mean, even if the sessionID number is changed the sequential number that answers the message is the same, so we only need to compare the sequential number.
For example:
We send -> messageID = 1 to sessionID = aaa
We receive -> messageID = 1 sessionID = bbb because there was a redirect
So it was not finding in the dictionary because we were expecting SessionID and MessageId to be the same.
`other.sessionId == sessionId && other.id == id;`

I have no idea how to create a test case for it.

2022-07-27 19:18 UTC, lewing commented
are the message-ids really unique across all sessions?

2022-07-27 19:19 UTC, thaystg commented
> are the message-ids really unique across all sessions?

It looks like yes.

2022-07-27 19:21 UTC, lewing commented
is that true for our ids?

2022-07-27 19:26 UTC, thaystg commented
That is exactly the case that we are getting the message error described in the issue, we are sending messageID=259, and the session does not exist anymore, so we receive an answer with messageID=259 and another sessionID, that is why we weren't find it.

Where we increment:
https://github.com/dotnet/runtime/blob/6b3ea401ca20c26dbb5497b0fbbf77b3afc73374/src/mono/wasm/debugger/BrowserDebugProxy/DevToolsProxy.cs#L38

Where we use it:
https://github.com/dotnet/runtime/blob/6b3ea401ca20c26dbb5497b0fbbf77b3afc73374/src/mono/wasm/debugger/BrowserDebugProxy/DevToolsProxy.cs#L165

2022-07-27 23:56 UTC, radical commented
> Session id can be different if there is a redirect, but the message id is kept.

What do you mean by a "redirect" here?

2022-07-28 10:41 UTC, ilonatommy commented
> I have no idea how to create a test case for it.

When it was observed? This link to issue does not work, could you check it?

2022-07-28 13:15 UTC, thaystg commented
> > I have no idea how to create a test case for it.
> 
> When it was observed? This link to issue does not work, could you check it?

It looks like you don't have rights to see it, I already asked for, let's wait.

2022-07-28 13:16 UTC, thaystg commented
> > Session id can be different if there is a redirect, but the message id is kept.
> 
> What do you mean by a "redirect" here?

Something like go to a login page and login.

2022-07-28 23:00 UTC, lewing commented
This still doesn't seem correct to me (not to mention we'd need to change the hash computation) based on the error in the linked issue my guess is that we're comparing one message with a string.Empty sessionId to another with a null one.  Can you changing the MessageId constructor to do:

            this.sessionId = string.IsNullOrEmpty (sessionId) ? null : sessionId;

2022-07-29 00:03 UTC, lewing requested changes
I don't see how this would fix the dictionary lookup in the general case.  We need to make sure the hash code and Equals use the same logic

2022-07-29 01:35 UTC, thaystg commented
> This still doesn't seem correct to me (not to mention we'd need to change the hash computation) based on the error in the linked issue my guess is that we're comparing one message with a string.Empty sessionId to another with a null one. Can you changing the MessageId constructor to do:
> 
> ```
>         this.sessionId = string.IsNullOrEmpty (sessionId) ? null : sessionId;
> ```

This is exactly what we are comparing:

```
see the pending_cmds
SessionId = FD9F77A4C958D595651B0F5D39AC75AC - CommandId = 277
SessionId = 469F7AE3DF255CC5FC81CF5BEF2B7523 - CommandId = 278
SessionId = FD9F77A4C958D595651B0F5D39AC75AC - CommandId = 276
SessionId = FD9F77A4C958D595651B0F5D39AC75AC - CommandId = 275
I was looking for: SessionId =  - CommandId = 276
see the pending_cmds
SessionId = FD9F77A4C958D595651B0F5D39AC75AC - CommandId = 277
SessionId = 469F7AE3DF255CC5FC81CF5BEF2B7523 - CommandId = 278
SessionId = FD9F77A4C958D595651B0F5D39AC75AC - CommandId = 276
SessionId = FD9F77A4C958D595651B0F5D39AC75AC - CommandId = 275
I was looking for: SessionId =  - CommandId = 277
```

So to be clear, we are sending command 276 from sessionID FD9F77A4C958D595651B0F5D39AC75AC  and receiving the answer from SessionId = "";
We are sending command 277 from sessionID FD9F77A4C958D595651B0F5D39AC75AC and also receiving the answer from SessionId = "";

So I agree we need to change the hash, but I don't think that considering an empty string as NULL will fix it.

2022-07-29 02:11 UTC, thaystg commented
> I don't see how this would fix the dictionary lookup in the general case. We need to make sure the hash code and Equals use the same logic

After testing more and more, I detected that this is not always happening, it only happens sometimes, but I'm confident that the fix works because I added a message in the code like this:
![image](https://user-images.githubusercontent.com/4503299/181668160-8d5b9314-3455-4a51-93bb-fe3e2a68b68c.png)

And I run a lot of times until see the "we would get the error" message.

Also after a lot of tests I got and error when we send the Debugger.Enabled message, same error "Session with given id not found", so I also protected that message.

2022-07-29 16:40 UTC, lewing commented
iirc a missing sessionId means it applies to all sessions so it makes more sense than a different sessionId.  The updates look fine although it might make sense to warn if the sessions have a value and are different because I don't think that should ever happen.  What command is the response to?

2022-07-29 16:49 UTC, thaystg commented
> iirc a missing sessionId means it applies to all sessions so it makes more sense than a different sessionId. The updates look fine although it might make sense to warn if the sessions have a value and are different because I don't think that should ever happen. What command is the response to?

```
{
  "id": 536,
  "method": "Debugger.enable",
  "params": {},
  "sessionId": "EDA0856A52259CB6A25FDCB8A6282422"
}

``````
{
  "id": 537,
  "method": "Runtime.evaluate",
  "params": {
    "expression": "getDotnetRuntime(0).INTERNAL.mono_wasm_runtime_is_ready",
    "objectGroup": "mono-debugger",
    "includeCommandLineAPI": false,
    "silent": false,
    "returnByValue": true
  },
  "sessionId": "EDA0856A52259CB6A25FDCB8A6282422"
}
```

2022-08-14 19:57 UTC, lewing approved these changes

2022-08-15 01:24 UTC, merged