[wip][wasm] deprecate legacy JS API and propose new
dotnet/runtime pull request #73068
Opened 2022-07-29 15:52 UTC by pavelsavara

- separated legacy API into `dotnet-legacy.d.ts`
- renamed `snake_case` to `camelCase` names in the `mono-config.json` type `MonoConfig`
    - the idea is that this type/file was added to Net7 and we have still chance to fix it without backward compatibility shim. The shim could be done, if truly necessary.
    - `assembly_root` -> `assemblyRootFolder`
    - `debug_level` -> `debugLevel`
    - `enable_debugging` - removed in favor of `debugLevel`
    - `isError` - removed, we throw exceptions as necessary
    - `globalization_mode` -> `globalizationMode`
    - `diagnostic_tracing` -> `diagnosticTracing`
    - `remote_sources` -> `remoteSources`
    - `environment_variables` -> `environmentVariables`
    - `runtime_options` -> `runtimeOptions`
    - `aot_profiler_options` -> `aotProfilerOptions` with `writeAt` & `sendTo`
    - `coverage_profiler_options` -> `coverageProfilerOptions` with `writeAt` & `sendTo`
    - `diagnostic_options` -> `diagnosticOptions`
    - `ignore_pdb_load_errors` -> `ignorePdbLoadErrors`
    - `wait_for_debugger` -> `waitForDebugger`
- renamed `snake_case` to `camelCase` names in `DiagnosticServerOptions`
    - `virtual_path` -> `virtualPath`
    - `load_remote` -> `loadRemote`
    - `is_optional` -> `isOptional`
    - we are producing it in `src\tasks\WasmAppBuilder\WasmAppBuilder.cs`
- renamed `snake_case` to `camelCase` names in `AssetEntry`
    - `connect_url` -> `connectUrl`
- renamed `snake_case` to `camelCase` names in `UnnamedProviderConfiguration`
    - `keyword_mask` -> `keywordMask`
- renamed names in `Diagnostics`
    - `EventLevel` -> `eventLevel`
- Added new `API` next to `MONO` and `BINDING` namespaces
    - `runMain`, `runMainAndExit`, `setEnvironmentVariable`, `getAssemblyExports` are just renamed existing API
    - `getConfig` will return `mono-config.json` type `MonoConfig`
    - `applyConfig`, or merge-in `MonoConfig` via shalow merge
- marked `MONO` and `BINDING` namespaces obsolete
- updated samples and templates

2022-08-01 19:03 UTC, pavelsavara commented
/azp run runtime-wasm

2022-08-02 11:59 UTC, pavelsavara commented on src/mono/sample/wasm/browser/main.js
> -function wasm_exit(exit_code, reason) {
okay, reverted.

2022-08-02 13:10 UTC, pavelsavara commented on src/mono/wasm/runtime/export-api.ts
> +    const api: APIType = {
there are only few methods right now and it's hard to find good category names.

2022-08-02 13:23 UTC, maraf approved these changes

2022-08-02 18:13 UTC, maraf requested changes
I think we could remove `EXPORTS` and `IMPORTS`. I like the API for getting assembly exports (`getAssemblyExports`) and as imports are similar feature, we could provide a similar API for it, eg. `setAssemblyImports(assembly: string, imports: any)`.
With this API we can remove `EXPORTS` and `IMPORTS`.

I'm still not sure if flatten `API` object is the right choice. I know than by now we have only few functions, but it seems to me that adding more structure is good for future enhancements.

2022-08-02 20:09 UTC, pavelsavara commented
/azp run runtime-wasm

2022-08-02 20:44 UTC, pavelsavara commented
/azp run runtime-wasm

2022-08-03 08:07 UTC, pavelsavara commented
/azp run runtime-wasm

2022-08-03 10:00 UTC, pavelsavara commented
/azp run runtime-wasm

2022-08-03 10:30 UTC, maraf commented
After a discussion we have chosen a 100% flat API in root object returned from the `createDotnetRuntime`.

2022-08-03 10:37 UTC, maraf commented on src/mono/wasm/runtime/es6/dotnet.es6.lib.js
> +    { api:API, mono:MONO, binding:BINDING, internal:INTERNAL, module:Module, marshaled_imports: IMPORTS },
This needs a change, as the API object doesn't exist anymore, right?

2022-08-03 10:37 UTC, maraf commented on src/mono/wasm/runtime/es6/dotnet.es6.pre.js
> +const API = {}, MONO = {}, BINDING = {}, INTERNAL = {}, IMPORTS = {};
This needs a change, as the API object doesn't exist anymore, right?

2022-08-03 10:49 UTC, pavelsavara commented
/azp run runtime-wasm

2022-08-03 10:51 UTC, maraf approved these changes

2022-08-03 13:00 UTC, ilonatommy approved these changes

2022-08-03 13:45 UTC, pavelsavara commented on src/mono/sample/wasm/browser/main.js
> +                // Module.FS.chdir("/");
Yes, this is just sample code we would not like to run

2022-08-03 13:46 UTC, pavelsavara commented on src/mono/wasm/runtime/types.ts
> +    marshaled_imports: any,
I only changed the public identifiers. We could re-format the rest of typeScript codebase in Net8

2022-08-03 13:48 UTC, pavelsavara commented
/azp run runtime-wasm

2022-08-03 17:56 UTC, lambdageek approved these changes

2022-08-03 20:06 UTC, pavelsavara commented
/azp run runtime-wasm

2022-08-03 22:48 UTC, pavelsavara commented
/azp run runtime-wasm

2022-08-04 06:01 UTC, pavelsavara commented
`System.NotSupportedException : The deserialization constructor for type 'System.Tuple`1[System.Int32]' contains parameters with null names.` is https://github.com/dotnet/runtime/issues/73347

Debugger failures are https://github.com/dotnet/runtime/issues/73342

2022-08-04 06:19 UTC, merged