Add guard word before local var CMiniColDef[9]
dotnet/runtime pull request #73736
Opened 2022-08-11 00:20 UTC by RobertHenry6bev

Initialize the guard word so it does not pass the UsesAllocatedMemory
test.

Found running output of clang14 -fsanitize=address, then inspection

Fixes https://github.com/dotnet/runtime/issues/73718

2022-08-11 22:20 UTC, AntonLapounov requested changes
Please use something like below for consistency with other places:
```C++
    const int MaxCols = 9;
    BYTE tempCols[MaxCols * sizeof(CMiniColDef) + 1];

    _ASSERTE(MaxCols >= pTable->m_cCols);
    // Mark the array of columns as not allocated (not ALLOCATED_MEMORY_MARKER) for SetNewColumnDefinition call bellow
    tempCols[0] = 0;
    CMiniColDef *pCols = BYTEARRAY_TO_COLDES(tempCols);
```

2022-08-12 00:41 UTC, AntonLapounov commented on src/coreclr/md/runtime/metamodel.cpp
> +    BYTE tempCols[sizeof(markword_t) + MaxCols * sizeof(CMiniColDef)]; // keep aligned
We use a single-byte marker everywhere in this code.  I see no reason to use four bytes just at this particular place.  This array contains 3-byte structures, so you cannot align them.

2022-08-12 00:44 UTC, AntonLapounov commented on src/coreclr/md/runtime/metamodel.cpp
> +    // Mark the array of columns as not allocated (eg, not ALLOCATED_MEMORY_MARKER)
E.g. means “for example”. Did you actually mean "i.e."?

2022-08-12 00:48 UTC, AntonLapounov commented on src/coreclr/md/runtime/metamodel.cpp
> +    BYTE tempCols[sizeof(markword_t) + MaxCols * sizeof(CMiniColDef)]; // keep aligned
Here is similar code in another function: https://github.com/dotnet/runtime/blob/2201016c1e13bdb9abf49e2e38cadf4ee0568df2/src/coreclr/md/enc/metamodelrw.cpp#L3635-L3638

2022-08-12 00:50 UTC, AntonLapounov commented on src/coreclr/md/runtime/metamodel.cpp
> +    BYTE tempCols[sizeof(markword_t) + MaxCols * sizeof(CMiniColDef)]; // keep aligned
And here: https://github.com/dotnet/runtime/blob/4710133ea0ed60c96ea77e66aee461eadc6c6f78/src/coreclr/md/runtime/metamodel.cpp#L880-L889

2022-09-12 17:30 UTC, tommcdon commented
Hi @RobertHenry6bev, I've moved this PR to draft mode.  Once it is ready for review, please feel free to move out of draft mode.  Thanks for your contributions!

2022-10-12 23:02 UTC, closed without merging