Disable ConnectWithRevocation_WithCallback test
dotnet/runtime pull request #74168
Opened 2022-08-18 18:53 UTC by rzikm

Contributes to #74034.

2022-08-18 18:57 UTC, CarnaViire approved these changes
LGTM, thanks!

2022-08-18 20:25 UTC, CarnaViire requested changes
Note Jeremy's comment on the issue:

> I only see the failures occurring on OSX, so it should only be disabled on OSX, not all Unixes. (The Linuxes are passing stably)

2022-08-21 17:56 UTC, danmoseley commented on src/libraries/System.Net.Security/tests/FunctionalTests/CertificateValidationRemoteServer.cs
> +        [ActiveIssue("https://github.com/dotnet/runtime/issues/74034", TestPlatforms.AnyUnix)]
```suggestion
        [ActiveIssue("https://github.com/dotnet/runtime/issues/74034", TestPlatforms.OSX)]
```

2022-08-21 17:57 UTC, danmoseley commented
I edited to OSX so validation could rerun. note that doesn't include iOS and tvOS, not sure whether those are relevant.

2022-08-21 18:01 UTC, danmoseley commented
/azp run runtime-libraries-coreclr outerloop

2022-08-22 10:00 UTC, rzikm commented
> I edited to OSX so validation could rerun. note that doesn't include iOS and tvOS, not sure whether those are relevant.

I am not aware of any failures on those, so it either works there or is disabled by some other means.

2022-08-22 10:02 UTC, rzikm commented
/azp run runtime

2022-08-22 10:02 UTC, rzikm commented
/azp run runtime-libraries-coreclr outerloop

2022-08-22 10:04 UTC, CarnaViire approved these changes

2022-08-22 14:55 UTC, rzikm commented
CI failures are weird, but build succeeded and the test itself is actually not outerloop so any failures are not result of this change.

2022-08-22 14:55 UTC, merged

2022-08-24 07:51 UTC, rzikm commented
/backport to release/7.0