Draft of optimizing a series of divisions (#74020)
dotnet/runtime pull request #74314
Opened 2022-08-21 22:11 UTC by SkiFoD

A draft to figure out if I'm on a right way.

2022-08-23 05:57 UTC, SkiFoD commented
/azp run runtime

2022-08-24 07:17 UTC, SkiFoD commented
@jakobbotsch Hey, could you please review this PR?

2022-08-24 09:23 UTC, EgorBo commented on src/coreclr/jit/morph.cpp
> +        div->gtOp1->SetVNsFromNode(op1);
isn't gtOp2 already chOp1 so you don't need to change that?

2022-08-24 09:24 UTC, EgorBo commented on src/coreclr/jit/morph.cpp
> +    if (gtTreeHasSideEffects(div, GTF_SIDE_EFFECT))
you only need to take side effects into account for the case where you fold to 0, and i guess you need to check op1 there

2022-08-24 09:25 UTC, EgorBo commented on src/coreclr/jit/morph.cpp
> +        div->gtOp2->SetVNsFromNode(op2);
this looks like it sets VN that does not correspond to the new constant value

2022-08-24 09:45 UTC, EgorBo commented on src/coreclr/jit/morph.cpp
> +        div->gtOp2->SetVNsFromNode(op2);
Also, since your opt is guarded with fgGlobalMorph you don't need to care about it all I guess (or enable it for all phases)

2022-09-03 06:43 UTC, SkiFoD commented
@EgorBo Hey, could you please check the PR?

2022-09-05 22:20 UTC, danmoseley commented
> The same happens with MUL 

@SkiFoD Do you want to open an issue for that too?

2022-09-11 12:20 UTC, SkiFoD commented
> > The same happens with MUL
> 
> @SkiFoD Do you want to open an issue for that too?

@danmoseley Hey. Created an issue https://github.com/dotnet/runtime/issues/75413 for the bug.

2022-10-03 20:50 UTC, JulieLeeMSFT commented
@EgorBo, this community PR is ready for another review.

> @EgorBo Hey, could you please check the PR?

2022-10-12 17:52 UTC, SkiFoD commented
@EgorBo I updated the PR.

2022-10-15 00:08 UTC, BruceForstall commented
@EgorBo PTAL

2022-10-24 02:03 UTC, EgorBo commented
Oops, sorry for the delay, will review tomorrow

2022-12-19 18:38 UTC, BruceForstall commented
@EgorBo ping

2023-01-04 15:55 UTC, EgorBo commented on src/coreclr/jit/morph.cpp
> +#if defined(TARGET_XARCH)
Why it's limited to xarch only?

2023-01-04 15:55 UTC, EgorBo commented on src/coreclr/jit/morph.cpp
> +                    if (tree->IsIntegralConst())
it doesn't look like this condition can possibly be true?

2023-01-04 15:56 UTC, EgorBo commented on src/coreclr/jit/morph.cpp
> +        if ((upperBound / child_val) < root_val)
potential division by zero in jit code if `child_val` is 0

2023-01-04 15:56 UTC, EgorBo commented on src/coreclr/jit/morph.cpp
> +        int64_t       upperBound = IntegralRange::SymbolicToRealValue(boundRange.GetUpperBound());
it's not clear to me why IntegralRange is used here - you already have child_val and root_val, don't you?

2023-01-04 15:58 UTC, EgorBo commented
From what I see locally this PR only hits a single diff across all collections so it needs unit tests at least, e.g. the division by zero case. e.g. this code:
```csharp
uint foo() => 0;

uint ff(uint u2) => u2 / foo() / 4;
```
crashes jit in this PR

2023-02-13 17:50 UTC, JulieLeeMSFT commented
CC @TIHan will look into this.

2023-02-14 22:47 UTC, TIHan requested changes
Overall, this looks fine. There is an outstanding @EgorBo comment regarding the IntegralRange and why we need it.

I would suggest that we add a few disasm check tests, see [here](https://github.com/dotnet/runtime/blob/main/docs/workflow/testing/coreclr/disasm-checks.md) for detail on how to do this.

2023-03-06 07:03 UTC, SkiFoD commented
> Overall, this looks fine. There is an outstanding @EgorBo comment regarding the IntegralRange and why we need it.
> 
> I would suggest that we add a few disasm check tests, see [here](https://github.com/dotnet/runtime/blob/main/docs/workflow/testing/coreclr/disasm-checks.md) for details on how to do this.

The code changes produce too small diffs, so I'm not sure if it is worth it to keep the code or it is just better to reject the PR.

2023-03-27 07:40 UTC, EgorBo commented
Let's focus on a more impactful optimization (in DM)

2023-03-27 07:40 UTC, closed without merging