Add custom comparer to use incremental generator caching for LoggerMessageGenerator and JsonSourceGenerator
dotnet/runtime pull request #74558
Opened 2022-08-25 09:00 UTC by 3schwartz

Related to issue https://github.com/dotnet/runtime/issues/74557, this is a proposed solution how to add caching to `LoggerMessageGenerator` and `JsonSourceGenerator`.

2022-08-25 10:03 UTC, teo-tsirpanis requested changes
Ignoring the `Compilation` when comparing the tuples is not correct according to https://github.com/dotnet/runtime/pull/64579#discussion_r800952586.

2022-08-25 14:16 UTC, eerhardt commented
@CyrusNajmabadi @chsienki - are changes still needed here with the latest changes using the new Roslyn Attribute API?

2022-08-25 18:19 UTC, 3schwartz commented
> @CyrusNajmabadi @chsienki - are changes still needed here with the latest changes using the new Roslyn Attribute API?

Hi @eerhardt 
Could you help share which changes you are talking about? Like a link to some issue. I would very much like to read up upon it.

2022-08-25 18:25 UTC, eerhardt commented
> Could you help share which changes you are talking about? Like a link to some issue. I would very much like to read up upon it.

No problem. Check out:

https://github.com/dotnet/roslyn/issues/54725
https://github.com/dotnet/runtime/issues/70754
https://github.com/dotnet/runtime/pull/70911

2022-08-25 18:28 UTC, 3schwartz commented
> Ignoring the `Compilation` when comparing the tuples is not correct according to [#64579 (comment)](https://github.com/dotnet/runtime/pull/64579#discussion_r800952586).

Thanks for your reply.

Looking at the PR you linked, it seems like you moved a lot of the logic within the ´GetSemanticTargetForGeneration´ instead of having this executed after `RegisterSourceOutput` is called.

If you think it could help and changes would be accepted, I could give it a try with the above two generators and move the logic executed after `RegisterSourceOutput` to the predicate, such that optimal caching is used.

Please let me know if help is appreciated :-)

2022-08-26 12:04 UTC, eiriktsarpalis commented
See https://github.com/dotnet/runtime/issues/68353#issuecomment-1112504534:

> > It also employs a custom equality comparer that ignores the Compilation component
> 
> _Never do this_. This action instructs the command line compiler that it is allowed to produce inaccurate outputs in an actual .dll or .exe, and will allow a production machine to publish/sign/ship that invalid output.

cc @sharwell

2022-08-27 05:42 UTC, 3schwartz commented
> > Could you help share which changes you are talking about? Like a link to some issue. I would very much like to read up upon it.
> 
> No problem. Check out:
> 
> [dotnet/roslyn#54725](https://github.com/dotnet/roslyn/issues/54725) #70754 #70911

Hi @eerhardt 

After reading through the links you send I understand it as the API `ForAttributeWithMetadataName` now does the correct filtering in the predicate and avoid people doing the logic after register the incremental values (hope it is correct understood).

It also seems like some are working on updating the generators. I will close the PR and issue then - thanks clarifying I’m looking forward to the API is out 😊

2022-08-29 15:01 UTC, closed without merging