Remove deprecated WebRequest from SoundPlayer.cs
dotnet/runtime pull request #76136
Opened 2022-09-24 20:12 UTC by AtariDreams

Use HttpClient instead

2022-09-24 20:21 UTC, teo-tsirpanis requested changes

2022-09-24 20:21 UTC, teo-tsirpanis commented on src/libraries/System.Windows.Extensions/src/System/Media/SoundPlayer.cs
> +                    _stream = Task.Run(response.Content.ReadAsStreamAsync()).Result;
```suggestion
                    var response = client.Send(message, HttpCompletionOption.ResponseHeadersRead);
                    _stream = response.Content.ReadAsStream();
```

2022-09-24 20:21 UTC, teo-tsirpanis commented on src/libraries/System.Windows.Extensions/src/System/Media/SoundPlayer.cs
> +                        var response = await client.SendAsync(message, HttpCompletionOption.ResponseHeadersRead);
```suggestion
                        var response = await client.SendAsync(message, HttpCompletionOption.ResponseHeadersRead, cancellationToken);
```

2022-09-25 05:03 UTC, hez2010 commented
I don't think HttpClient should be used as transient, instead an IHttpClientFactory should be used to avoid socket exhaustion.

2022-09-25 16:52 UTC, AtariDreams commented
How can I do this when I need to have default credentials

2022-09-25 18:29 UTC, AtariDreams commented
@stephentoub Is this an appropriate use of HttpClient and its properties/methods?

2022-09-25 19:49 UTC, jkotas commented
HttpClient handles http: and https: protocols only. WebRequest handles file: and ftp: protocols as well. So this change will break callers that pass urls that use these additional protocols. I would be concerned about file: in particular.

The libraries that you are changing are provided for compatibility with .NET Framework. We are not investing in them and it is fine for them to use use WebRequest in them since that is only provided for compatibility with .NET Framework. We plan to document which libraries are actively maintained vs. libraries are in sustained engineering mode to create clarity about this. cc @jeffhandley

2022-09-25 20:55 UTC, stephentoub commented
@AtariDreams, thanks for working on this.  I agree with Jan; while in theory it'd be nice to get rid of the use of WebRequest, replacing it with HttpClient is a breaking change, and these libraries are primarily in maintenance mode.  Given that, I'm going to close this, and also https://github.com/dotnet/runtime/issues/41516, which may have steered you wrong (apologies).  Thanks for your interest in contributing.

2022-09-25 20:55 UTC, closed without merging