Quick disasm check CI JitStress fix
dotnet/runtime pull request #76417
Opened 2022-09-30 02:07 UTC by TIHan

Runtime_33972 was failing in ARM64 in JitStress because it turns off HWIntrinsic - so I force the test to enable it.

2022-09-30 02:07 UTC, TIHan commented
@dotnet/jit-contrib This is ready.

2022-09-30 03:37 UTC, BruceForstall requested changes
Is this the fix for https://github.com/dotnet/runtime/issues/76352?

Why is this the fix, instead of disabling FileCheck if `COMPlus_EnableHWIntrinsic=0`?

In general, it seems like we should not be forcing certain JIT modes in the disasm tests, we should have FileCheck give up instead.

2022-09-30 06:43 UTC, markples commented
> In general, it seems like we should not be forcing certain JIT modes in the disasm tests, we should have FileCheck give up instead.

This is a good conversation to have.  We have other test modes and test specifics that clash.  Some are direct - testenvironment and test(s) both set the same variable such as GCStress, JitStress, TieredCompilation, etc.  If I understand correctly, a lot of those will work like this PR.  Other tests set things like JitOptimizationSensitive or XXXIncompatible, which turns the test off.

disasm tests are an interesting mode because in some ways, the disasm check -is- the test, not just a mode for the test.  For example, the purpose of Runtime_33972 is to test the intrinsics.  That clashes with the other strategy of "we have a bunch of test code, so let's run it in multiple configurations" (but so do the things in the previous paragraph, so we might want to reconsider those as well).

Disabling disasm tests in general for JitStress (or any mode) would unblock things.  Two potential problems with this are (1) disasm tests could just as easily be written for the mode, and (2) any COMPlus_ flag can potentially break a disasm test (kind of by definition), so a global list could get large.

This gets into a major difference we have from LLVM's use of FileCheck.  LLVM uses `RUN:` lines in each test to specify various modes for that test, and those `RUN:` lines also specify the check prefixes for FileCheck.  My guess is that a similar LLVM test would only have an intrinsics=on execution, though it could also easily have two `RUN:` lines with different patterns for intrinsics being on vs off.  Maybe we need to replicate that concept.  Imagine if this test specified `complus_hwintrinsics=1 --> add prefix INTRIN`, which updated our command line to specify `ARM64-INTRIN` (instead of or in addition to ARM64) *only when* `complus_hwintrinsics=1`.  It could then have no checks for `complus_hwintrinsics=0` or it could specify `NO_INTRIN` and provide a list of `ARM64-NO_INTRIN` checks.

2022-09-30 18:19 UTC, BruceForstall commented
@markples One general question I have is: is a disasm test _only_ a disasm test, or will we have tests which run and test correctness (so must return our conventional "100" exit code from some execution) _as well as_ get FileCheck disasm checking and thus must both return 100 as well as have the FileCheck succeed?

If disasm tests are disasm specific, then it seems we should run them at all in configuration scenarios where they aren't compatible (e.g., JitStress). After all, we do have default configuration runs and will get test coverage in those runs. We don't need a JitStress run to also run the test by disabling JitStress. We also don't want to distribute the code to disable all the possible configurations that could negatively affect a test to all the possibly affected tests -- we should centralize that code in one place.

If disasm tests are not disasm specific, we should disable the FileCheck functionality in affected configurations, but still run the test in those configurations (but not alter the configuration settings we're attempting to test). Perhaps this could be achieved by a set of `<JitAsmTestRequired_HWIntrinsics>` kind of tags for the configurations that are required.

2022-09-30 19:37 UTC, TIHan commented
@BruceForstall 
Ideally, I think we do want these tests to run in all the different configurations, but only run the FileCheck test if it matches the compatible configuration and/or contains the right prefixes like @markples mentioned. Right now, this PR unblocks CI JitStress. We already have plans to improve test mode configurability with disasm checks.

2022-09-30 19:38 UTC, TIHan commented
I think we should also figure out what we want the default configuration to be for DisasmChecks.

2022-09-30 20:04 UTC, TIHan commented
@BruceForstall how do you want to move forward with this?

2022-09-30 20:07 UTC, BruceForstall approved these changes

2022-09-30 20:08 UTC, merged

2022-09-30 20:08 UTC, BruceForstall commented
I went ahead and approved to unblock fixing the stress job failure. But as I've described, I think this area needs more thinking and possibly a different approach.

2022-10-01 03:20 UTC, JulieLeeMSFT commented
@TIHan Please open an issue to track how we will handle executing a test and FileChecking based on the various configurations.