Update mask for `ComWrappers` CCW lookup
dotnet/runtime pull request #77302
Opened 2022-10-21 04:14 UTC by AaronRobinsonMSFT

We use a mask to control how many vtable entries we can map to a single `this` instance. Since .NET 5, the mapping has been 3:1 for 32-bit and 1:1 for 64-bit. This change keeps the 32-bit 3:1 but changes the 64-bit to 7:1. The end result is that managed objects that have lots of projected interfaces will see a memory improvement, but those with few interfaces will see a modest increase.

/cc @manodasanW @scottj1s

2022-10-24 20:51 UTC, AaronRobinsonMSFT commented
/cc @dotnet/interop-contrib

2022-11-01 18:07 UTC, jkoritzinsky approved these changes

2022-11-01 18:08 UTC, jkoritzinsky requested changes
Make sure to account for NativeAOT's ComWrappers support in the shared ComWrappers.cs file

2022-11-01 18:26 UTC, AaronRobinsonMSFT commented
@jkoritzinsky Thanks for calling that out. It seems NativeAOT is written in a naive way so it is good. I've created https://github.com/dotnet/runtime/issues/77738 to track updating that and moving CoreCLR to reuse the NativeAOT work.

https://github.com/dotnet/runtime/blob/0e6fa6287022ef1d660c377daf3ca27a9694eea5/src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/ComWrappers.NativeAot.cs#L40-L58

https://github.com/dotnet/runtime/blob/0e6fa6287022ef1d660c377daf3ca27a9694eea5/src/coreclr/nativeaot/System.Private.CoreLib/src/System/Runtime/InteropServices/ComWrappers.NativeAot.cs#L376-L382

2022-11-01 18:40 UTC, jkoritzinsky approved these changes

2022-11-01 18:41 UTC, merged