[wasm][debugger] Variables with same name in different scopes in async method
dotnet/runtime pull request #78651
Opened 2022-11-21 19:55 UTC by thaystg

Fixing 2 variables with same names in different scopes in an async method.

Before this PR it was always showing the value of the last variable declared.

Fixes #77031

2022-11-23 15:44 UTC, ilonatommy approved these changes

2022-11-29 11:58 UTC, radical requested changes

2022-11-29 12:00 UTC, radical commented
I pushed the changes that I suggested to https://github.com/radical/runtime/commits/aj-thays_fix_77031 .

2022-11-29 16:56 UTC, radical commented on src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs
>                      asyncLocalsFull.Add(asyncLocal);
Should this be unconditional? It seems to be common, for the cases we don't `continue` earlier.

2022-11-29 16:56 UTC, radical commented on src/mono/wasm/debugger/BrowserDebugProxy/MonoSDBHelper.cs
> +                            ret = ret.Insert(0, match.Groups[2].Value);
Check `match.Success` .

2022-11-29 16:57 UTC, radical approved these changes
Other than the comments, LGTM 👍

2022-11-29 17:34 UTC, radical approved these changes

2022-11-29 19:47 UTC, merged