Fixing assert on variable live range for simd12 LCL / STORE_LCL
dotnet/runtime pull request #79182
Opened 2022-12-03 02:09 UTC by BrianBohe

Intend to fix [78898](https://github.com/dotnet/runtime/issues/78898).

Op GT_STORE_LCL_VAR for target type SIMD12 always stores the result on the stack when FEATURE_SIMD is on. Liveness and the variable descriptor were updated after emitting this operation. This PR updates the tree's variable descriptor and liveness.

Having said that, LSRA assigned a target register for GT_STORE_LCL_VAR is assigned a target register in LSRA although the result (v01 arg0) is stored on the stack. For that reason, the tree target reg is being updated inside our specific case. LSRA already has the information about the available registers, then might be better to add this SIMD12 information there and avoid changing the tree after. I am opening this PR to see if this is triggering other problems.

The same behavior may be happening for GT_STOREIND for the same target type but I cannot get an example.

2022-12-05 20:47 UTC, BrianBohe commented
/azp run runtime-coreclr jitstress

2022-12-06 02:28 UTC, BruceForstall commented
I wonder why the arm64 `genStoreLclTypeSIMD12` code supports reg/reg `mov` but the x64 code doesn't.

2022-12-06 02:44 UTC, BruceForstall requested changes

2022-12-06 02:44 UTC, BruceForstall commented on src/coreclr/jit/simdcodegenxarch.cpp
> +    treeNode->SetRegNum(REG_STK); // we always store the result on stack
It seems odd to call this. Isn't the problem that LSRA shouldn't be assigning a register to this node at all?

2022-12-08 06:20 UTC, kunalspathak commented
`genStoreLclTypeSIMD12()` was just missing a case for a scenario where `targetReg` (the destination register for `STORE_LCL_VAR`) is not `REG_NA`. In this case, it is `xmm1` and for such, we should just do the move and no need to store the variable on stack. Of course, if we are doing a `mov`, we need to also `genProduceReg()` which will update the life of `V01`.

2022-12-08 16:02 UTC, kunalspathak commented
/azp run runtime-coreclr jitstress

2022-12-08 16:03 UTC, kunalspathak commented
Pushed fixes at other places where we were not tracking the liveness of `treeNode` during `genCodeForStoreLclVar()` and `genCodeForStoreLclFld()` on both x64 and arm64.

2022-12-08 16:04 UTC, kunalspathak commented
If jitstress looks ok, we should also kick off gcstress @BrianBohe

2022-12-08 20:20 UTC, BrianBohe commented
/azp run runtime-coreclr jitstress

2022-12-08 21:10 UTC, BrianBohe commented
/azp run runtime-coreclr jitstress

2022-12-08 22:18 UTC, BruceForstall approved these changes
LGTM.

Are there any asm diffs? It would be nice to summarize interesting examples here.

2022-12-09 05:47 UTC, kunalspathak commented
> LGTM.
> 
> Are there any asm diffs? It would be nice to summarize interesting examples here.

The only difference is in coreclr_tests for the test case that was failing.

![image](https://user-images.githubusercontent.com/12488060/206632967-00b74396-0109-4758-8bfb-b47a380cdd55.png)

Here is the diff which removes the extra store on stack.

![image](https://user-images.githubusercontent.com/12488060/206633143-d2f9ed3d-dfb9-4662-9386-f7512f7f285d.png)

2022-12-09 18:11 UTC, BrianBohe commented
Errors are CI infrastructure related (timeouts) or unrelated

2022-12-09 19:57 UTC, merged