Decommit mark array when decommitting region
dotnet/runtime pull request #79912
Opened 2022-12-22 18:54 UTC by cshung

2023-01-05 04:31 UTC, Maoni0 commented on src/coreclr/gc/gc.cpp
> +        virtual_decommit(heap_segment_mem (region), size, oh, h_number);
you shouldn't be decommitting regions if large pages are enabled though in `init_table_for_region`. I suggest to refactor what `decommit_step` is doing and call that instead.

2023-01-05 04:31 UTC, Maoni0 commented on src/coreclr/gc/gc.cpp
> +            0;
`heap_number` is already defined as 0 for WKS GC

2023-01-05 04:32 UTC, Maoni0 commented on src/coreclr/gc/gc.cpp
> +        virtual_decommit(heap_segment_mem (region), size, oh, h_number);
nit - you have inconsistent space in these 3 lines of code. please try to stick to having a space to the left of '(`.

2023-01-05 04:33 UTC, Maoni0 commented on src/coreclr/gc/gc.cpp
> +                gc_heap* hp = __this;
nit - conventional way is to do

`gc_heap* hp = pGenGCHeap;`

for WKS GC

2023-01-05 04:34 UTC, Maoni0 commented on src/coreclr/gc/gc.cpp
> +                hp->decommit_mark_array_by_seg (region);
why are we not doing the mark array decommit for the large pages case? wouldn't you hit the same problem with double counting mark array committed bytes?

2023-01-05 04:35 UTC, Maoni0 requested changes
also it would be nice to add a comment to `delete_region` to specify the invariant which is when you return a region to the global region allocator, memory should be decommitted (unless it's large pages) and mark array (if committed).

2023-01-10 11:07 UTC, PeterSolMS commented
Looks good to me.

Regarding Maoni's comment, I wonder if we can add an assert to `delete_region` to actually enforce the invariant. To make that work, `decommit_region` would need to set `heap_segment_committed` for the region, so we know its memory is decommitted.

2023-01-11 20:48 UTC, Maoni0 approved these changes
LGTM!

2023-01-11 23:25 UTC, merged

2023-01-13 19:40 UTC, sebastienros commented
With these commits (https://github.com/dotnet/runtime/compare/2ca7cf7...6aaaaaa) aspnet apps crash at runtime in the benchmarks CI. I am flagging the PR which had the potential to explain it.

Crank command if you can run with and without this PR changes:

```
crank --config https://raw.githubusercontent.com/aspnet/Benchmarks/main/src/BenchmarksApps/Mvc/benchmarks.certapi.yml  --config https://raw.githubusercontent.com/aspnet/Benchmarks/main/build/ci.profile.yml --scenario NoMvcAuth --profile intel-win-app --profile intel-load2-load --profile intel-db-db --application.framework net8.0 --application.aspNetCoreVersion 8.0.0-alpha.1.23062.23 --application.runtimeVersion 8.0.0-alpha.1.23061.12 --application.sdkVersion 8.0.100-alpha.1.23061.8
```