Add additional IG assertion checking
dotnet/runtime pull request #80599
Opened 2023-01-13 05:37 UTC by BruceForstall

Especially, check various IG flags to ensure illegal combinations do not occur.

2023-01-13 05:39 UTC, BruceForstall commented
I'd like to change the JIT so that an IG and all its EXTEND IGs (if any) have the same NOGC flag. I think it would simplify the mental model, and possibly reduce the chance of GC holes when peephole optimizations reach across IG boundaries. However, that requires further changes.

2023-01-13 17:38 UTC, BruceForstall commented
[No diffs](https://dev.azure.com/dnceng-public/public/_build/results?buildId=136343&view=ms.vss-build-web.run-extensions-tab), of course.

2023-01-13 17:38 UTC, BruceForstall commented
@kunalspathak @dotnet/jit-contrib PTAL

2023-01-13 18:42 UTC, kunalspathak requested changes

2023-01-13 18:42 UTC, kunalspathak commented on src/coreclr/jit/emit.cpp
> +    for (insGroup *tempIG = emitIGlist, *prevIG = nullptr; tempIG != nullptr; prevIG = tempIG, tempIG = tempIG->igNext)
rename `tempIG` to `currIG`?

2023-01-13 18:42 UTC, kunalspathak commented on src/coreclr/jit/emit.cpp
> +        assert(emitPrologIG != nullptr);
This doesn't have to be inside the loop.

2023-01-13 21:11 UTC, BruceForstall commented
@kunalspathak updated

2023-01-14 00:52 UTC, BruceForstall commented
diffs failure was infra:
```
git --config-env=http.extraheader=env_var_http.extraheader fetch --force --tags --prune --prune-tags --progress --no-recurse-submodules origin --depth=20 +3f93a90fc6171f75c303289c686b29b336f181bf:refs/remotes/origin/3f93a90fc6171f75c303289c686b29b336f181bf
##[error]The operation was canceled.
Unhandled exception. System.IO.IOException: The parameter is incorrect.
   at System.ConsolePal.ControlCHandlerRegistrar.Unregister()
   at System.Console.remove_CancelKeyPress(ConsoleCancelEventHandler value)
   at Agent.PluginHost.Program.Main(String[] args) in D:\a\1\s\src\Agent.PluginHost\Program.cs:line 202
```

2023-01-14 06:07 UTC, kunalspathak approved these changes

2023-01-14 06:08 UTC, merged