Generate StandardOptimizationData uncompressed
dotnet/runtime pull request #81623
Opened 2023-02-03 23:56 UTC by hoyosjs

#76467 changed the default value of mibc merged data to compressed. Our tools handle this properly, but our signing service doesn't. Set our usage of it to uncompressed.

2023-02-03 23:58 UTC, hoyosjs commented
/backport to release/8.0-preview1

2023-02-04 00:01 UTC, jakobbotsch approved these changes

2023-02-04 00:02 UTC, EgorBo approved these changes
Perhaps it should be "false" always by default in the dotnet-pgo tool itself?

2023-02-04 04:58 UTC, merged

2023-02-04 14:19 UTC, hassan13-deep requested changes
No