Make area-owners.json true source for all area like labels dependencies
dotnet/runtime pull request #82534
Opened 2023-02-23 16:52 UTC by marek-safar

2023-03-03 16:33 UTC, jeffschwMSFT approved these changes
The owner updates look good to me.  @jeffhandley for the fabricbot updates.

2023-03-08 11:51 UTC, jeffhandley requested changes
I left comments in https://github.com/dotnet/fabricbot-config/pull/69#pullrequestreview-1330436620, but this is currently resulting in an undesired change to mentionees in the issue routing where `@dotnet/area-` team members are expanded and mentioned specifically as well.

_Thanks for your patience awaiting my review_.

2023-03-08 11:51 UTC, jeffhandley commented on docs/area-owners.md
> -| area-System.Linq.Parallel                      | @jeffhandley         | @dotnet/area-system-linq-parallel                   | Consultants: @stephentoub @kouvel
We're losing "Consultants" notes in a few rows, but I think that's OK.

2023-03-08 11:51 UTC, jeffhandley commented on docs/area-owners.md
> +* Manually update `mentionees` sections in both [`fabricbot.json`](fabricbot.json) and [`.github/fabricbot.json`](../.github/fabricbot.json) files
I suspect you meant to refer to `area-owners.json` and `fabricbot.json` here.

2023-04-05 18:02 UTC, closed without merging