Add Ubuntu 22.10 kinetic kudu RIDs for .NET 7
dotnet/runtime pull request #84984
Opened 2023-04-18 15:19 UTC by dviererbe

Related to https://github.com/dotnet/runtime/issues/84974

2023-04-18 15:31 UTC, dviererbe commented
@dotnet-policy-service agree company="Canonical"

2023-04-24 19:23 UTC, carlossanlop commented
@dviererbe please retarget your PR to release/7.0-staging, per these instructions: https://github.com/dotnet/runtime/blob/release/7.0-staging/docs/project/library-servicing.md

2023-05-03 17:39 UTC, wfurt commented
do we have  PR for main? We usually start with that. 
Also it seems like 23.10 is also announced https://www.omgubuntu.co.uk/2023/04/ubuntu-23-10-codename-revealed 
I'm wondering we we could/should do them together (don't need to)

2023-05-04 18:29 UTC, carlossanlop requested changes
Needs a PR merged in main first.

2023-05-05 05:59 UTC, dviererbe commented
Sorry for the long delay. 

@wfurt I think we can add mantic too I will prepare this. 
@carlossanlop I thought this change is an exception, because Microsoft plans to step away from RIDs. See https://github.com/dotnet/runtime/issues/83246 I will prepare a PR for main.

Same applies for the .NET 6 PR https://github.com/dotnet/runtime/pull/84983

2023-05-15 20:22 UTC, carlossanlop approved these changes
Thanks for submitting the main change.

2023-05-15 20:30 UTC, carlossanlop commented
@dviererbe FYI I added a missing change in the Microsoft.NETCore.Platforms.csproj file that ensures it gets built for servicing.

2023-05-15 20:37 UTC, wfurt approved these changes
LGTM

2023-05-16 01:29 UTC, merged