Don't re-scan previously visited blocks in helperexpansion.cpp
dotnet/runtime pull request #85201
Opened 2023-04-22 17:30 UTC by EgorBo

2023-04-22 20:12 UTC, EgorBo commented
@kunalspathak PTAL, that change I proposed for the helper expansion. Currently it is quite fragile and relies on a fact that expansion will put a call into a cold block or manually clear some flag. This PR skips all internal blocks added during expansion. Diffs: https://dev.azure.com/dnceng-public/public/_build/results?buildId=248685&view=results I expected to see some small TP improvement but I guess we don't expand helper calls that much.

2023-04-24 14:08 UTC, kunalspathak requested changes

2023-04-24 14:08 UTC, kunalspathak commented on src/coreclr/jit/helperexpansion.cpp
> +bool Compiler::fgExpandRuntimeLookupsForCall(BasicBlock** pBlock, Statement* stmt, GenTreeCall* call)
Can you add method summary for this method?

2023-04-24 14:08 UTC, kunalspathak commented on src/coreclr/jit/helperexpansion.cpp
> +//    pBlock - Block containing the helper call to expand (may be updated in case of block splitting)
```suggestion
//    pBlock - Block containing the helper call to expand. If expansion is performed, this is updated to the new block that was an outcome of block splitting.
```

Likewise at other places.

2023-04-24 14:08 UTC, kunalspathak commented on src/coreclr/jit/helperexpansion.cpp
> +        while (fgExpandHelperForBlock<ExpansionFunction>(&block))
I would make sure that we indeed get an updated block if `fgExpandHelperForBlock()` returned `true.`

```c++
INDEBUG(BasicBlock* origBlock = block);
while (fgExpandHelperForBlock<ExpansionFunction>(&block))
{
   result = PhaseStatus::MODIFIED_EVERYTHING; 
#ifdef DEBUG
   assert(origBlock != block);
   origBlock = block;   
#endif
}
```

2023-04-25 23:40 UTC, EgorBo commented
@kunalspathak thanks for the feedback, I believe I've addressed all comments

2023-04-25 23:45 UTC, kunalspathak approved these changes
LGTM

2023-04-26 05:33 UTC, EgorBo commented
failure is https://github.com/dotnet/runtime/issues/76454

2023-04-26 05:34 UTC, merged