[release/6.0] Fix HTTTP/2 header decoder buffer allocation
dotnet/runtime pull request #85341
Opened 2023-04-25 17:01 UTC by ManickaP

Fixes #78516

Backports #78862

## Customer impact

Reliability problem in HTTP/2, where some requests/responses with large headers that should be accepted might end up throwing exception.
- In HPack case (HTTP/2 scenarios), the issue is much less likely to be hit as it requires 4KB of headers.

This is a shared code with Kestrel so this affects server side as well - expect follow up PR in ASP.NET.

## Testing

Added tests for the root cause and similar scenarios, increasing test coverage. All of those are ran in CI.

## Risk

Low, as this affects only HPack in (rare) case of 4KB+ sized headers data buffers.

2023-04-27 13:47 UTC, MihaZupan approved these changes

2023-04-27 15:30 UTC, ManickaP commented
Failures look like #76454, timeouts with machine provisioning and/or test execution.

2023-04-28 11:06 UTC, karelz commented
Approved by Tactics (@SteveMCarroll) on 4/27 via email. Marking as servicing-approved.

2023-05-04 18:23 UTC, carlossanlop requested changes
Same request [as in the 7.0 PR](https://github.com/dotnet/runtime/pull/85337#pullrequestreview-1413664552) - Rebase to release/6.0-staging, and make sure to merge before May 15th (code complete) if you intend to include this fix in the June Release.

2023-05-09 14:12 UTC, ManickaP commented
Closed in favor of https://github.com/dotnet/runtime/pull/85976

2023-05-09 14:12 UTC, closed without merging