Prefer lld in NativeAot when using clang
dotnet/runtime pull request #85478
Opened 2023-04-27 18:32 UTC by sbomer

This detects availability of lld and prefers it, when using clang. If not found, falls back on bfd as before, as discussed in https://github.com/dotnet/runtime/issues/84794. Fixes https://github.com/dotnet/runtime/issues/84934.

2023-04-28 14:10 UTC, jkotas approved these changes

2023-04-28 14:11 UTC, jkotas requested changes
Build is failing with `invalid linker name in argument '-fuse-ld=bfd'`

2023-04-28 15:58 UTC, jkotas approved these changes

2023-04-28 18:25 UTC, am11 reviewed
Otherwise LGTM, assuming we will add `lld` to the prerequisite docs: https://learn.microsoft.com/en-us/dotnet/core/deploying/native-aot/#prerequisites

2023-04-28 18:25 UTC, am11 commented on src/coreclr/nativeaot/BuildIntegration/Microsoft.NETCore.Native.Unix.targets
> +    <Exec Command="&quot;$(CppLinker)&quot; -fuse-ld=lld -Wl,--version" Condition="'$(LinkerFlavor)' == 'lld' or ('$(LinkerFlavor)' == '' and $(CppCompilerAndLinker.Contains('clang')))"
```suggestion
    <Exec Command="&quot;$(CppLinker)&quot; -fuse-ld=lld -Wl,--version" Condition="'$(LinkerFlavor)' == 'lld'" IgnoreExitCode="true" StandardOutputImportance="Low" ConsoleToMSBuild="true">
```

Revert this line: this is not correct. Before we were checking the --version regardless of LinkerFlavor emptiness. Which means FreeBSD and user-supplied -p:LinkkerFlavor was also considered.

2023-04-28 18:25 UTC, am11 commented on src/coreclr/nativeaot/BuildIntegration/Microsoft.NETCore.Native.targets
Same as above, revert changes in this file.

2023-04-28 18:30 UTC, jkotas commented
> Otherwise LGTM, assuming we will add lld to the prerequisite docs: https://learn.microsoft.com/en-us/dotnet/core/deploying/native-aot/#prerequisites

My assumption was that it comes by default with clang, no?

2023-04-28 18:34 UTC, am11 commented
> My assumption was that it comes by default with clang, no?

Nope, `lld` is a separate package on distros such as Ubuntu, Fedora and Alpine Linux.

2023-04-28 19:44 UTC, jkotas commented
> I would prefer the approach of defining our preferred tools, and requiring some explicit user action to take a different path - it makes things more predictable.

Yes, especially given that there are 3 different packages that one has to install to get the preferred tools for out-of-the-box experience. It was just one package (`clang`) in .NET 7.

2023-04-28 19:44 UTC, am11 commented
> Including both lld and llvm-objdump in the instructions would make sense then.

Yes, they have similarities. The difference is that `fuse-ld=lld` will select the exact matching version (clang-13 -> lld-13, clang-14 -> lld-14..), it does not depend on PATH. Whereas, llvm-objcopy is picked off of the PATH by default. In runtime builds, we don't have this problem because we use a cmake-based function to find the components (objcopy, objdump, ar, nm, readelf) matching the current toolchain flavor & version: https://github.com/dotnet/runtime/blob/47195755314c2e834d232442863a72fe8c7cea59/eng/native/configuretools.cmake#L24-L71 

That is quite robust but implementing that in MSBuild without cmake dependency is non-trivial work.

2023-04-28 20:00 UTC, jkotas commented
If you can "apt-get install llvm" that will add version-less alias for llvm-objdump.

2023-04-28 20:07 UTC, am11 commented
On Alpine, `clang` doesn't install `llvm-objcopy`, it requires `llvm-dev` package. Then `llvm-dev` doesn't install `lldb`, it requires explicit `lldb`. The toolchain prefix and version suffix support is something we are not supporting. We discussed previously that if someone needs that, we should have properties to customize the desired toolchain; so we added `<ObjCopyName>llvm-objcopy-#` to match `<CppCompilerAndLinker>clang-#`.

2023-04-28 20:13 UTC, jkotas commented
This sounds like a very complicated matrix. Do we really want to change these defaults?

2023-04-28 20:15 UTC, am11 commented on src/coreclr/nativeaot/BuildIntegration/Microsoft.NETCore.Native.Unix.targets
> +    <Exec Command="&quot;$(CppLinker)&quot; -fuse-ld=lld -Wl,--version" Condition="'$(LinkerFlavor)' == 'lld' or ('$(LinkerFlavor)' == '' and $(CppCompilerAndLinker.Contains('clang')))"
You are right about this one. We do not need to revert it.

When `LinkerFlavor` is `lld`, we will always check the version. Which means `_LinkerVersion` can't be empty if `lld` exists and changes made in `src/coreclr/nativeaot/BuildIntegration/Microsoft.NETCore.Native.targets` are not needed, right?

2023-04-28 20:25 UTC, jkotas commented
> This sounds like a very complicated matrix. Do we really want to change these defaults?

Hmm, we are exposed to it already. So trying to auto-detected what is on the box is about the best that we can do.

2023-04-28 20:51 UTC, am11 commented on src/coreclr/nativeaot/BuildIntegration/Microsoft.NETCore.Native.Unix.targets
> +    <Exec Command="&quot;$(CppLinker)&quot; -fuse-ld=lld -Wl,--version" Condition="'$(LinkerFlavor)' == 'lld' or ('$(LinkerFlavor)' == '' and $(CppCompilerAndLinker.Contains('clang')))"
Then it will result in error one way or the other. We shouldn't be checking for emptiness.

2023-04-28 21:15 UTC, am11 commented
For compiler/linker-driver, we can pack `init-compiler.sh` (it's a standalone script) and call it like this in BuildIntegration targets: https://github.com/dotnet/runtime/blob/02b8071c7212f409384c153c62f85a00b05edfb1/src/coreclr/tools/aot/crossgen2/crossgen2.csproj#L96

After that, we can parse out version from `$(CppLinker) --version` and try to prefer `llvm-objcopy-{ThatVersion}` over `llvm-objcopy` (unversioned) and then `objcopy` (from binutils).

2023-04-29 00:19 UTC, jkotas commented
> init-compiler.sh 

init-compiler.sh is tied to dotnet/runtime engineering infrastructure. It lives in arcade repo and it is not meant to be a shipping artifact.

I would hope that we can land on something simpler for the linker detection than hundred lines shell script. I like the default experience today: Install clang, the rest just works, the implementation is not that complicated. It feels we are trying to complicate it quite a bit.

2023-04-29 00:33 UTC, jkotas commented
To address the problem with bfd linker not being available in our cross-build containers, can we set `LinkerFlavor=bfd` in the build container to make it just work?

2023-05-01 19:51 UTC, jkotas commented
> you were on board with making lld/llvm-objcopy the default, even if it means users need to install two extra packages, until we realized that it's problematic on Ubuntu 18.04

Yes, I have not realized that it will require installing additional packages and expose us to potential version mismatches. I think it is likely problematic on more than just Ubuntu 18. Every other distro seems to have their own tweaks on how the explicitly versioned binaries are setup, and it varies over time. With these insights, I think it is better to lean on the standard config by default that should be simple, and allow people to manually override when it does not work.

2023-05-02 16:32 UTC, agocke commented
Hmm, I thought I commented on this issue, but I don't see it. I must have forgot to submit.

I've been thinking about the matrix here and it seems like, no matter what, we're going to have to be compatible with a variety of different linkers. Even if we ignore lld/bfd, we have to support ld64, the Mac linker. That means we're always going to be in a bit of a passive position of adapting to the system requirements.

Given that, it seems like we should roll with whatever the user has on the machine. Preference for one linker over another seems mostly academic, since it's unlikely that we'll get the exact same version of a linker we test with, regardless of which linker we choose. This also seems to be necessary since we want to be on the latest linker version in our official builds for fixes and patches, but most Linux distros ship with very old versions of the linkers.

So, no matter what we choose we probably won't be running on something we explicitly tested. In that case, I wouldn't provide a warning if we run with something other than our preferred linker, I would at most produce some sort of diagnostic message, like the "Generating native code" message that's output during Native AOT publish.

2023-05-03 00:59 UTC, closed without merging