[browser] introduce sourcemaps
dotnet/runtime pull request #86152
Opened 2023-05-12 14:10 UTC by pavelsavara

For `dotnet.runtime.js` and `dotnet.js`, which are built from our typescript.
- It will link `file:///C:/Dev/runtime/src/mono/wasm/runtime/loader/logging.ts` while running on local machine. 
    - This doesn't work on FF, but it does on Chrome.
- It will link `https://raw.githubusercontent.com/dotnet/runtime/a146e4e3a58e7287fe831164b3ee273b83c52758/gging.ts` when built on CI, with the correct git hash.

2023-05-18 08:48 UTC, ilonatommy approved these changes

2023-05-18 08:48 UTC, ilonatommy commented on src/mono/wasm/runtime/rollup.config.js
> +function sourcemapPathTransform(relativeSourcePath, sourcemapPath) {
How/where is this function called?

2023-05-18 08:57 UTC, maraf requested changes
It should have build time configuration for propagation to the build output folder (I believe off by default, or at least for publish)

2023-05-18 09:23 UTC, pavelsavara commented on src/mono/wasm/runtime/rollup.config.js
> +function sourcemapPathTransform(relativeSourcePath, sourcemapPath) {
Line 133, it's a rollup plugin

2023-06-28 09:38 UTC, pavelsavara commented
> It should have build time configuration for propagation to the build output folder (I believe off by default, or at least for publish)

Done via `WasmEmitSourceMap`

2023-06-28 11:41 UTC, maraf approved these changes
Looks good to me 👍

2023-06-28 11:43 UTC, merged