Disable mark list optimization if we hit a per region mark list overflow
dotnet/runtime pull request #86508
Opened 2023-05-19 16:36 UTC by cshung

Fixes https://github.com/microsoft/FASTER/issues/835

In case the mark list is overflowed when we `get_region_mark_list`, we have to disable the optimization, otherwise, we will miss marking live objects and cause heap corruption.

2023-05-23 02:35 UTC, Maoni0 requested changes
fix looks fine but please consider not duplicating code in `plan_phase`.

2023-05-23 14:12 UTC, PeterSolMS reviewed
Looks good to me.

Your solution has the property that once we hit a mark list overflow for one region, we will not use the mark list for any other region, even if it is possible. Given that this is such a rare case anyway, it doesn't seem worthwhile fixing.

2023-05-26 22:10 UTC, Maoni0 commented
this actually compiles? `use_mark_list` is not defined in this method or as a per heap/global member.

2023-06-01 21:08 UTC, Maoni0 approved these changes
LGTM!

2023-06-05 18:46 UTC, merged