Email addresses in same domain not equal
dotnet/runtime pull request #87721
Opened 2023-06-17 06:28 UTC by feiyun0112

#87564 

The user information in the URI for email addresses in same domain be ignored when comparing equality.

2023-06-17 11:33 UTC, gfoidl commented on src/libraries/System.Private.Uri/src/System/Uri.cs
> +                return this.ToString().Equals(obj.ToString());
Can the string allocations be avoided?

2023-06-17 13:28 UTC, danmoseley commented
Is this behavior the same in .NET Framework? 
Would this change break existing code?

2023-06-17 15:03 UTC, filipnavara commented
> Is this behavior the same in .NET Framework? Would this change break existing code?

No, it is not. It is a breaking change (in a good direction though). We had a workaround for this for years...

2023-06-18 03:49 UTC, feiyun0112 commented on src/libraries/System.Private.Uri/src/System/Uri.cs
> +                return this.ToString().Equals(obj.ToString());
> Can the string allocations be avoided?

how to avoid? please give some advice.

2023-06-19 12:12 UTC, karelz approved these changes

2023-06-19 12:12 UTC, karelz commented
Agreed, this is a good technical breaking change. @stephentoub any thoughts here?

2023-06-20 01:22 UTC, stephentoub commented
> Agreed, this is a good technical breaking change. @stephentoub any thoughts here?

Without passing judgement on this specific fix, this just seems like a bug, and a bug that's worth fixing.  Like most functional bugs, fixing it could break someone depending on the buggy behavior, but I wouldn't deem this a "breaking change" unless we get a lot of feedback that it's causing problems.

2023-06-20 01:45 UTC, danmoseley commented
@marklio  is it possible to say how much usage this api has in nuget?

2023-06-20 01:47 UTC, stephentoub commented
> @marklio is it possible to say how much usage this api has in nuget?

It's not just about the API (Equals), which would both almost certainly "a ton" and impossible to measure well because we're talking about an override of object.Equals.  It's more specifically about when the Uri's being compared later are constructed with "mailto" schemas.

2023-06-20 19:25 UTC, MihaZupan commented
FWIW, the current behavior [is documented](https://learn.microsoft.com/dotnet/api/system.uri.equals#remarks):

> The [Equals](https://learn.microsoft.com/en-us/dotnet/api/system.uri.equals?view=net-7.0) method compares the two instances without regard to user information ([UserInfo](https://learn.microsoft.com/en-us/dotnet/api/system.uri.userinfo?view=net-7.0)) and fragment ([Fragment](https://learn.microsoft.com/en-us/dotnet/api/system.uri.fragment?view=net-7.0)) parts that they might contain. For example, given the URIs http://www.contoso.com/index.htm#search and http://user:password@www.contoso.com/index.htm, the [Equals](https://learn.microsoft.com/en-us/dotnet/api/system.uri.equals?view=net-7.0) method would return true.

Why this behavior was chosen though, I don't know 🤷‍♂️
While someone out there is likely depending on this being the case for "normal" Uris (e.g. http), I doubt that's the case for `mailto`.

`System.Uri`'s support of the `mailto` scheme is [_limited_](https://github.com/dotnet/runtime/issues/80799#issuecomment-1396083913), such that checking `Equals` on two semantically equivalent mailto addresses may still return false. I doubt we'll ever change that, but this change feels like a good step in the right direction to at least handle the common case better.

2023-06-20 19:32 UTC, MihaZupan commented on src/libraries/System.Private.Uri/src/System/Uri.cs
> +                return this.ToString().Equals(obj.ToString());
This condition is skipping a bunch of edge cases and fast paths.
Can you please move this down to before https://github.com/dotnet/runtime/blob/3fc0f5fd610f73f0397cf40f68bf6e13787a8f2c/src/libraries/System.Private.Uri/src/System/Uri.cs#L1732C9-L1734
and alter which `UriComponents` are selected for comparison.

Something along the lines of
```c#
UriComponents components = UriComponents.HttpRequestUrl;

if (_syntax.InFact(UriSyntaxFlags.MailToLikeUri))
{
    if (!obj._syntax.InFact(UriSyntaxFlags.MailToLikeUri))
        return false;

    components |= UriComponents.UserInfo;
}

string selfUrl = selfInfo.RemoteUrl ??= GetParts(components, UriFormat.SafeUnescaped);
string otherUrl = otherInfo.RemoteUrl ??= obj.GetParts(components, UriFormat.SafeUnescaped);
```

`GetHashCode` should also be updated to include the UserInfo when hashing.

2023-06-21 00:13 UTC, marklio commented
Agree with @stephentoub. We can maybe come up with how often Uris are constructed with strings composed with "mailto:" schemes and later compared, but that's not likely to give a picture of what's really going on. Generating "mailto:" Uris is typically done as part of hypertext generation, and not typically used as "data". It seems unlikely that there's alot of code relying on the super odd behavior of "all email addresses from the same domain are equal", because that's not terribly meaningful in a world where gmail and other "large email providers" share the same domain without any other meaningful connection. I'd say we're just as likely to uncover bugs where apps are doing improper equality. That said, I'm happy to try to dig into the data if we think there's value.

2023-06-21 00:14 UTC, marklio commented
...although I disagree with not documenting it as a breaking change. :) I think we should.

2023-07-03 20:19 UTC, karelz requested changes

2023-07-03 20:19 UTC, karelz commented on src/libraries/System.Private.Uri/src/System/Uri.cs
>              // Fragment AND UserInfo are ignored
```suggestion
            // Fragment AND UserInfo (for non-mailto URIs) are ignored
```
And move it to the `components` definition above

2023-07-04 10:24 UTC, karelz approved these changes

2023-07-04 10:26 UTC, merged

2023-07-04 10:26 UTC, karelz commented
Thanks @feiyun0112 for your PR!