[System.Numerics] Cross Product for Vector2 and Vector4
dotnet/runtime pull request #87968
Opened 2023-06-23 14:10 UTC by AlexRadch

Close https://github.com/dotnet/runtime/issues/28731 Issue.

2023-06-23 15:03 UTC, EgorBo commented
Can you post codegen examples for these functions you added? Presumably, the API proposal implies JIT support for these which is not done as part of this PR

2023-06-23 16:37 UTC, AlexRadch commented
> Can you post codegen examples for these functions you added? Presumably, the API proposal implies JIT support for these which is not done as part of this PR

Is there any instruction on how to get generated code?

2023-06-23 21:34 UTC, EgorBo commented
I assume we can handle this separately in JIT once this merged

2023-06-25 06:07 UTC, huoyaoyuan commented
Are there any corner cases we need to consider, like +0/-0? I assume we should avoid this to achieve best performance, but hardware intrinsic may provide different result.

2023-06-25 09:51 UTC, AlexRadch commented
> Are there any corner cases we need to consider, like +0/-0? I assume we should avoid this to achieve best performance, but hardware intrinsic may provide different result.

`Vector2.Cross` have the same code as `Vector2.Dot` but with a rotated second vector.
`Vector4.Cross` has a similar code as `Vector3.Cross` and W components multiplication.

I think we do not need to consider any corner cases there.

2023-10-27 11:08 UTC, adamsitnik requested changes
Overall it LGTM, but we need to apply some minor cleanup before merging.

@AlexRadch thank you for your contribution!

2023-10-27 11:08 UTC, adamsitnik commented on src/libraries/System.Private.CoreLib/src/System/Numerics/Vector2.cs
> +        [Intrinsic]
my understanding is that as long as you don't contribute a JIT change, then it won't get replaced by JIT with more optimal codegen

@tannergooding please confirm

```suggestion
```

2023-10-27 11:08 UTC, adamsitnik commented on src/libraries/System.Numerics.Vectors/tests/Vector2Tests.cs
> +        // A test for Cross (Vector2f, Vector2f)
I am aware of the fact that other tests in this class use similar comments, but I don't believe they add any value.

```suggestion
```

2023-10-27 11:08 UTC, adamsitnik commented on src/libraries/System.Numerics.Vectors/tests/Vector2Tests.cs
> +            actual = Vector2.Cross(a, b);
```suggestion
            float actual = Vector2.Cross(a, b);
```

2023-10-27 11:08 UTC, adamsitnik commented on src/libraries/System.Numerics.Vectors/tests/Vector2Tests.cs
> +        // Cross test for parallel vector
```suggestion
```

2023-10-27 11:08 UTC, adamsitnik commented on src/libraries/System.Numerics.Vectors/tests/Vector2Tests.cs
> +        // Cross test with specail float values
```suggestion
```

2023-10-27 11:08 UTC, adamsitnik commented on src/libraries/System.Numerics.Vectors/tests/Vector4Tests.cs
> +        // A test for Cross (Vector4f, Vector4f)
```suggestion
```

2023-10-27 11:08 UTC, adamsitnik commented on src/libraries/System.Numerics.Vectors/tests/Vector4Tests.cs
> +        // Cross test of the same vector
```suggestion
```

2023-11-18 12:00 UTC, PavielKraskouski commented
I'm keeping this pull request active.

2023-12-16 18:01 UTC, closed without merging