[wasm][debugger] Set TasksConfiguration=RuntimeConfiguration for debugger tests
dotnet/runtime pull request #90611
Opened 2023-08-15 17:09 UTC by thaystg

2023-08-15 17:29 UTC, lewing submitted a review, later dismissed

2023-08-15 17:43 UTC, radical approved these changes, later dismissed

2023-08-16 15:26 UTC, ViktorHofer requested changes
It doesn't make sense for the task configuration to default to the runtime configuration.

2023-08-16 15:29 UTC, ViktorHofer commented
cc @elinor-fung

2023-08-16 20:34 UTC, thaystg commented
After discuss a lot their suggestion is to build whatever project we want passing as a parameter TasksConfiguration=Debug or Release depending on the runtime configuration.

2023-08-16 20:34 UTC, closed without merging