Implement StoreVector128x2 for Arm64
dotnet/runtime pull request #92109
Opened 2023-09-15 09:11 UTC by SwapnilGaikwad

Contribute towards #84510.

Implements the following API calls
```csharp
// ST2 (multiple structures)
public static unsafe void StoreVector128x2(byte*   address, (Vector128<byte>   Value1, Vector128<byte>   Value2) value);
public static unsafe void StoreVector128x2(sbyte*  address, (Vector128<sbyte>  Value1, Vector128<sbyte>  Value2) value);
public static unsafe void StoreVector128x2(short*  address, (Vector128<short>  Value1, Vector128<short>  Value2) value);
public static unsafe void StoreVector128x2(ushort* address, (Vector128<ushort> Value1, Vector128<ushort> Value2) value);
public static unsafe void StoreVector128x2(int*    address, (Vector128<int>    Value1, Vector128<int>    Value2) value);
public static unsafe void StoreVector128x2(uint*   address, (Vector128<uint>   Value1, Vector128<uint>   Value2) value);
public static unsafe void StoreVector128x2(long*   address, (Vector128<long>   Value1, Vector128<long>   Value2) value);
public static unsafe void StoreVector128x2(ulong*  address, (Vector128<ulong>  Value1, Vector128<ulong>  Value2) value);
public static unsafe void StoreVector128x2(float*  address, (Vector128<float>  Value1, Vector128<float>  Value2) value);
public static unsafe void StoreVector128x2(double* address, (Vector128<double> Value1, Vector128<double> Value2) value);
```

2023-09-15 13:56 UTC, SwapnilGaikwad commented
Hi @kunalspathak , rest of the store APIs will follow this! 🙂 

CC:@a74nh

2023-09-18 10:19 UTC, SwapnilGaikwad commented
> Can you please share the sample codegen for these?

Sure, following is the relevant snippet from the test program. Full source is available [here](https://gist.github.com/SwapnilGaikwad/552b5f51c343248db178cf1274bfeb55).
```csharp
[MethodImpl(MethodImplOptions.NoInlining)]
public void RunTestScenario()
{
    AdvSimd.Arm64.StoreVector128x2((Int32*)_dataTable.outArrayPtr, (_fld1, _fld2));

}
```

The generates the following assembly.
```
; Assembly listing for method JIT.HardwareIntrinsics.Arm.StoreVector128x2Test:RunTestScenario():this (FullOpts)
; Emitting BLENDED_CODE for generic ARM64 - Unix
; FullOpts code
; optimized code
; fp based frame
; partially interruptible
; No PGO data
; 0 inlinees with PGO data; 4 single block inlinees; 0 inlinees without PGO data
; Final local variable assignments
;
;  V00 this         [V00,T01] (  5,  5   )     ref  ->  x19         this class-hnd single-def <JIT.HardwareIntrinsics.Arm.StoreVector128x2Test>
;# V01 OutArgs      [V01    ] (  1,  1   )  struct ( 0) [sp+0x00]  do-not-enreg[XS] addr-exposed "OutgoingArgSpace"
;* V02 tmp1         [V02    ] (  0,  0   )  struct (32) zero-ref    HFA(simd16)  ld-addr-op "NewObj constructor temp" <System.ValueTuple`2[System.Runtime.Intrinsics.Vector128`1[int],System.Runtime.Intrinsics.Vector128`1[int]]>
;* V03 tmp2         [V03    ] (  0,  0   )    long  ->  zero-ref    "impAppendStmt"
;  V04 tmp3         [V04,T00] (  4,  8   )   byref  ->  x20         single-def "Inlining Arg"
;* V05 tmp4         [V05    ] (  0,  0   )    long  ->  zero-ref    ld-addr-op "Inline stloc first use temp"
;  V06 tmp5         [V06,T03] (  2,  4   )    long  ->   x0         "Inlining Arg"
;  V07 tmp6         [V07,T02] (  3,  6   )    long  ->   x1         "Inlining Arg"
;* V08 tmp7         [V08    ] (  0,  0   )  simd16  ->  zero-ref    HFA(simd16)  "Inlining Arg" <System.Runtime.Intrinsics.Vector128`1[int]>
;* V09 tmp8         [V09    ] (  0,  0   )  simd16  ->  zero-ref    HFA(simd16)  "Inlining Arg" <System.Runtime.Intrinsics.Vector128`1[int]>
;* V10 tmp9         [V10    ] (  0,  0   )  simd16  ->  zero-ref    HFA(simd16)  "field V02.Item1 (fldOffset=0x0)" P-INDEP
;* V11 tmp10        [V11    ] (  0,  0   )  simd16  ->  zero-ref    HFA(simd16)  "field V02.Item2 (fldOffset=0x10)" P-INDEP
;
; Lcl frame size = 0

G_M27384_IG01:  ;; offset=0x0000
            stp     fp, lr, [sp, #-0x20]!
            stp     x19, x20, [sp, #0x10]
            mov     fp, sp
            mov     x19, x0
						;; size=16 bbWeight=1 PerfScore 3.00
G_M27384_IG02:  ;; offset=0x0010
            add     x20, x19, #40
            ldrsb   wzr, [x20]
            add     x0, x20, #48
            movz    x1, #0x5368      // code for System.Runtime.InteropServices.GCHandle:AddrOfPinnedObject():long:this
            movk    x1, #0x4993 LSL #16
            movk    x1, #0xFFFF LSL #32
            ldr     x1, [x1]
            blr     x1
            ldr     x1, [x20, #0x18]
            add     x0, x0, x1
            sub     x0, x0, #1
            sub     x1, x1, #1
            bic     x0, x0, x1
            ldr     q16, [x19, #0x08]
            ldr     q17, [x19, #0x18]
            st2     {v16.4s, v17.4s}, [x0]
						;; size=64 bbWeight=1 PerfScore 22.50
G_M27384_IG03:  ;; offset=0x0050
            ldp     x19, x20, [sp, #0x10]
            ldp     fp, lr, [sp], #0x20
            ret     lr
						;; size=12 bbWeight=1 PerfScore 3.00

; Total bytes of code 92, prolog size 12, PerfScore 37.70, instruction count 23, allocated bytes for code 92 (MethodHash=55539507) for method JIT.HardwareIntrinsics.Arm.StoreVector128x2Test:RunTestScenario():this (FullOpts)
; ============================================================
```

Also added StoreVector64x2 variants to the patch as it's mainly the boilerplate change.

2023-09-25 21:08 UTC, kunalspathak commented
/azp run runtime-coreclr jitstress

2023-09-25 21:08 UTC, kunalspathak commented
/azp run runtime-coreclr libraries-jitstress

2023-09-25 21:10 UTC, kunalspathak requested changes
Started some jitstress jobs.

2023-09-25 21:10 UTC, kunalspathak commented on src/libraries/System.Private.CoreLib/src/System/Runtime/Intrinsics/Arm/AdvSimd.cs
> +            public static unsafe void StoreVector128x2(byte* address, (Vector128<byte> Value1, Vector128<byte> Value2) value) => StoreVector128x2(address, value);
Can you also add the following as part of this PR?

```c#
namespace System.Runtime.Intrinsics.Arm
{
    public static class AdvSimd
    {
        public partial class Arm
        {
            // ST2 (multiple structures)
            public static unsafe void StoreVector64x2(byte*   address, (Vector64<byte> Value1,    Vector64<byte> Value2));
            public static unsafe void StoreVector64x2(sbyte*  address, (Vector64<sbyte> Value1,   Vector64<sbyte> Value2));
            public static unsafe void StoreVector64x2(short*  address, (Vector64<short> Value1,   Vector64<short> Value2));
            public static unsafe void StoreVector64x2(ushort* address, (Vector64<ushort> Value1,  Vector64<ushort> Value2));
            public static unsafe void StoreVector64x2(int*    address, (Vector64<int> Value1,     Vector64<int> Value2));
            public static unsafe void StoreVector64x2(uint*   address, (Vector64<uint> Value1,    Vector64<uint> Value2));
            public static unsafe void StoreVector64x2(float*  address, (Vector64<float> Value1,   Vector64<float> Value2));
        }
    }
}
```

2023-09-26 16:04 UTC, kunalspathak commented on src/libraries/System.Private.CoreLib/src/System/Runtime/Intrinsics/Arm/AdvSimd.cs
> +            public static unsafe void StoreVector128x2(byte* address, (Vector128<byte> Value1, Vector128<byte> Value2) value) => StoreVector128x2(address, value);
Sure, that was just a thought because it shouldn't be any different than what you are already doing in this PR except to handle 64 bits in some code.

2023-09-26 16:05 UTC, kunalspathak commented
Failure is https://github.com/dotnet/runtime/issues/92236

2023-09-26 16:06 UTC, kunalspathak commented
The PR looks good modulo my comment in https://github.com/dotnet/runtime/pull/92109#discussion_r1336376769. Once that is addressed, we can merge this one.

2023-09-28 19:42 UTC, kunalspathak commented on src/libraries/System.Private.CoreLib/src/System/Runtime/Intrinsics/Arm/AdvSimd.cs
> +            public static unsafe void StoreVector128x2(byte* address, (Vector128<byte> Value1, Vector128<byte> Value2) value) => StoreVector128x2(address, value);
Implemented and pushed with the changes.

2023-09-28 19:42 UTC, kunalspathak commented
@BruceForstall @dotnet/jit-contrib

2023-09-29 04:01 UTC, BruceForstall approved these changes

2023-09-29 13:50 UTC, kunalspathak approved these changes

2023-09-29 13:50 UTC, merged