Add an additional length check to FrozenDictionary and FrozenSet
dotnet/runtime pull request #92546
Opened 2023-09-24 00:08 UTC by andrewjsaid

On construction of the collection, we compute an unsigned long which is effectively 64 boolean flags, each representing the presence of a key string of a particular length (mod 64) in the set of keys.
When reading from the collection, we can exit early if the key being tested does not map to a bit which has been switched on by the original computation. I believe this has similarities to how Bloom Filters work.
This adds a relatively small cost on creation of the collection as well as a small cost to each read operation. However it can speed up reads with certain data patterns especially when the difference between the maximum and minimum key length is large but there aren't many different lengths.

Tested via the following benchmark
```c#
using System.Collections.Frozen;
using System.Collections.Generic;
using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;

BenchmarkSwitcher
    .FromAssembly(typeof(Program).Assembly)
    .Run(new[] { "-i" });

public class FrozenSetBenchmarks
{
    private FrozenSet<string> _hashSet = new HashSet<string>
    {
        "cddafs", "cd9660", "iso", "isofs", "iso9660", "fuseiso", "fuseiso9660", "udf", "umview-mod-umfuseiso9660", "aafs", "adfs", "affs", "anoninode", "anon-inode FS", "apfs", "balloon-kvm-fs", "bdevfs", "befs", "bfs", "bootfs", "bpf_fs",
        "btrfs", "btrfs_test", "coh", "daxfs", "drvfs", "efivarfs", "efs", "exfat", "exofs", "ext", "ext2", "ext2_old", "ext3", "ext2/ext3", "ext4", "ext4dev", "f2fs", "fat", "fuseext2", "fusefat", "hfs", "hfs+", "hfsplus", "hfsx", "hostfs",
        "hpfs", "inodefs", "inotifyfs", "jbd", "jbd2", "jffs", "jffs2", "jfs", "lofs", "logfs", "lxfs", "minix (30 char.)", "minix v2 (30 char.)", "minix v2", "minix", "minix_old", "minix2", "minix2v2", "minix2 v2", "minix3", "mlfs", "msdos",
        "nilfs", "nsfs", "ntfs", "ntfs-3g", "ocfs2", "omfs", "overlay", "overlayfs", "pstorefs", "qnx4", "qnx6", "reiserfs", "rpc_pipefs", "sffs", "smackfs", "squashfs", "swap", "sysv", "sysv2", "sysv4", "tracefs", "ubifs", "ufs", "ufscigam",
        "ufs2", "umsdos", "umview-mod-umfuseext2", "v9fs", "vagrant", "vboxfs", "vxfs", "vxfs_olt", "vzfs", "wslfs", "xenix", "xfs", "xia", "xiafs", "xmount", "zfs", "zfs-fuse", "zsmallocfs", "9p", "acfs", "afp", "afpfs", "afs", "aufs", "autofs",
        "autofs4", "beaglefs", "ceph", "cifs", "coda", "coherent", "curlftpfs", "davfs2", "dlm", "eCryptfs", "fhgfs", "flickrfs", "ftp", "fuse", "fuseblk", "fusedav", "fusesmb", "gfsgfs2", "gfs/gfs2", "gfs2", "glusterfs-client",
        "gmailfs", "gpfs", "ibrix", "k-afs", "kafs", "kbfuse", "ltspfs", "lustre", "ncp", "ncpfs", "nfs", "nfs4", "nfsd", "novell", "obexfs", "panfs", "prl_fs", "s3ql", "samba", "smb", "smb2", "smbfs", "snfs", "sshfs", "vmhgfs", "webdav", "wikipediafs",
        "xenfs", "anon_inode", "anon_inodefs", "aptfs", "avfs", "bdev", "binfmt_misc", "cgroup", "cgroupfs", "cgroup2fs", "configfs", "cpuset", "cramfs", "cramfs-wend", "cryptkeeper", "ctfs", "debugfs", "dev", "devfs", "devpts", "devtmpfs", "encfs", "fd",
        "fdesc", "fuse.gvfsd-fuse", "fusectl", "futexfs", "hugetlbfs", "libpam-encfs", "ibpam-mount", "mntfs", "mqueue", "mtpfs", "mythtvfs", "objfs", "openprom", "openpromfs", "pipefs", "plptools", "proc", "pstore", "pytagsfs", "ramfs", "rofs", "romfs",
        "rootfs", "securityfs", "selinux", "selinuxfs", "sharefs", "sockfs", "sysfs", "tmpfs", "udev", "usbdev", "usbdevfs", "gphotofs", "sdcardfs", "usbfs", "usbdevice", "vfat",
    }.ToFrozenSet();

    // No entry has length 17 so the optimization occurs (and hash code is not calculated)
    [Benchmark]
    public void Caught_By_LengthFilter() => _hashSet.Contains("some_drive_name_2");

    // As some entries have length 14 then the length filter does not help
    [Benchmark]
    public void Missed_By_LengthFilter() => _hashSet.Contains("somedrivename2");

}
```

Results before (control)
| Method                 | Mean     | Error     | StdDev    |
|----------------------- |---------:|----------:|----------:|
| Caught_By_LengthFilter | 6.262 ns | 0.0730 ns | 0.0683 ns |
| Missed_By_LengthFilter | 6.154 ns | 0.0571 ns | 0.0534 ns |

Results after
| Method                 | Mean     | Error     | StdDev    |
|----------------------- |---------:|----------:|----------:|
| Caught_By_LengthFilter | 1.957 ns | 0.0198 ns | 0.0185 ns |
| Missed_By_LengthFilter | 6.215 ns | 0.0505 ns | 0.0422 ns |

2023-10-09 08:57 UTC, andrewjsaid commented
@stephentoub @adamsitnik I would greatly appreciate feedback on this PR. Thanks

2023-10-20 16:56 UTC, adamsitnik reviewed
I like the idea, but we need to make sure that such misses will be common in real life scenarios (with the micro benchmarks from dotnet/performance repo they are not)

2023-10-21 02:07 UTC, andrewjsaid commented
Side note: I've changed from `% 64` to `& 0x3F` and that seems to have given a significant bump in perf. Would this be a good suggestion for a JIT optimization for mod powers of 2? My understanding doesn't go **that** deep...

2023-10-21 02:10 UTC, MichalPetryka commented
> Would this be a good suggestion for a JIT optimization for mod powers of 2?

I think the JIT already does it for unsigned integers.

2023-10-21 02:37 UTC, andrewjsaid commented
Thank you for your review and for pointing me to the resource on how to properly run the benchmarks.

# Additional Test

To obtain an interesting discussion I added a new microbenchmark designed to showcase the existing length bounds as well as the proposed length filter in this PR. This can be seen in my results as the Count = 20 case. The implementation is a bimodal distribution of lengths and a testing ("notfound") array uniformly distributed over a larger bounds.
```
Count == 20 ? ValuesGenerator.ArrayOfUniqueStrings(10, minLength: 10, maxLength: 12)
              .Concat(ValuesGenerator.ArrayOfUniqueStrings(10, minLength: 18, maxLength: 20))
              .Concat(ValuesGenerator.ArrayOfUniqueStrings(10 * 2, minLength: 5, maxLength: 25)).ToArray()
```

# Benchmark Results: TryGetValue_*_FrozenDictionary

`dotnet run -c Release -f net8.0 --filter System.Collections.Perf_*FrozenDictionary*TryGetValue_*_FrozenDictionary --corerun D:\Code\_forks\dotnet-runtime-main\artifacts\bin\testhost\net9.0-windows-Release-x64\shared\Microsoft.NETCore.App\9.0.0\corerun.exe D:\Code\_forks\dotnet-runtime-pr92546\artifacts\bin\testhost\net9.0-windows-Release-x64\shared\Microsoft.NETCore.App\9.0.0\corerun.exe`

## DefaultFrozenDictionary
```
// * Summary *

BenchmarkDotNet v0.13.7-nightly.20230717.35, Windows 11 (10.0.22621.2428/22H2/2022Update/SunValley2)
AMD Ryzen 9 5950X, 1 CPU, 32 logical and 16 physical cores
.NET SDK 8.0.100-rc.1.23463.5
  [Host]     : .NET 8.0.0 (8.0.23.41904), X64 RyuJIT AVX2
  Job-YITQJR : .NET 9.0.0 (42.42.42.42424), X64 RyuJIT AVX2
  Job-LPACKA : .NET 9.0.0 (42.42.42.42424), X64 RyuJIT AVX2

PowerPlanMode=00000000-0000-0000-0000-000000000000  Arguments=/p:EnableUnsafeBinaryFormatterSerialization=true  IterationTime=250.0000 ms  
MaxIterationCount=20  MinIterationCount=15  WarmupCount=1  

|                             Method |        Job |                         ...   Toolchain | Count |          Mean |        Error |       StdDev |        Median |           Min |           Max | Ratio | RatioSD | Allocated | Alloc Ratio |
|----------------------------------- |----------- |-------------------------...------------ |------ |--------------:|-------------:|-------------:|--------------:|--------------:|--------------:|------:|--------:|----------:|------------:|
|  TryGetValue_True_FrozenDictionary | Job-YITQJR |     \dotnet-runtime-main...\corerun.exe |    10 |      24.97 ns |     0.160 ns |     0.150 ns |      24.95 ns |      24.62 ns |      25.17 ns |  1.00 |    0.00 |         - |          NA |
|  TryGetValue_True_FrozenDictionary | Job-LPACKA |  \dotnet-runtime-pr92546...\corerun.exe |    10 |      25.83 ns |     0.116 ns |     0.108 ns |      25.80 ns |      25.70 ns |      26.07 ns |  1.03 |    0.01 |         - |          NA |
|                                    |            |                         ...             |       |               |              |              |               |               |               |       |         |           |             |
| TryGetValue_False_FrozenDictionary | Job-YITQJR |     \dotnet-runtime-main...\corerun.exe |    10 |      22.64 ns |     0.082 ns |     0.072 ns |      22.64 ns |      22.47 ns |      22.75 ns |  1.00 |    0.00 |         - |          NA |
| TryGetValue_False_FrozenDictionary | Job-LPACKA |  \dotnet-runtime-pr92546...\corerun.exe |    10 |      25.28 ns |     0.826 ns |     0.951 ns |      25.36 ns |      24.00 ns |      26.94 ns |  1.12 |    0.03 |         - |          NA |
|                                    |            |                         ...             |       |               |              |              |               |               |               |       |         |           |             |
|  TryGetValue_True_FrozenDictionary | Job-YITQJR |     \dotnet-runtime-main...\corerun.exe |    20 |      89.82 ns |     0.593 ns |     0.555 ns |      89.69 ns |      89.18 ns |      90.85 ns |  1.00 |    0.00 |         - |          NA |
|  TryGetValue_True_FrozenDictionary | Job-LPACKA |  \dotnet-runtime-pr92546...\corerun.exe |    20 |     100.14 ns |     0.752 ns |     0.667 ns |     100.31 ns |      97.87 ns |     100.61 ns |  1.11 |    0.01 |         - |          NA |
|                                    |            |                         ...             |       |               |              |              |               |               |               |       |         |           |             |
| TryGetValue_False_FrozenDictionary | Job-YITQJR |     \dotnet-runtime-main...\corerun.exe |    20 |      36.55 ns |     0.237 ns |     0.210 ns |      36.45 ns |      36.38 ns |      37.01 ns |  1.00 |    0.00 |         - |          NA |
| TryGetValue_False_FrozenDictionary | Job-LPACKA |  \dotnet-runtime-pr92546...\corerun.exe |    20 |      20.19 ns |     0.186 ns |     0.174 ns |      20.09 ns |      20.03 ns |      20.54 ns |  0.55 |    0.01 |         - |          NA |
|                                    |            |                         ...             |       |               |              |              |               |               |               |       |         |           |             |
|  TryGetValue_True_FrozenDictionary | Job-YITQJR |     \dotnet-runtime-main...\corerun.exe |   100 |     805.90 ns |     6.611 ns |     5.861 ns |     804.30 ns |     799.51 ns |     818.56 ns |  1.00 |    0.00 |         - |          NA |
|  TryGetValue_True_FrozenDictionary | Job-LPACKA |  \dotnet-runtime-pr92546...\corerun.exe |   100 |     804.85 ns |     4.217 ns |     3.944 ns |     804.65 ns |     797.32 ns |     812.49 ns |  1.00 |    0.01 |         - |          NA |
|                                    |            |                         ...             |       |               |              |              |               |               |               |       |         |           |             |
| TryGetValue_False_FrozenDictionary | Job-YITQJR |     \dotnet-runtime-main...\corerun.exe |   100 |     705.79 ns |     3.174 ns |     2.969 ns |     705.63 ns |     700.79 ns |     711.30 ns |  1.00 |    0.00 |         - |          NA |
| TryGetValue_False_FrozenDictionary | Job-LPACKA |  \dotnet-runtime-pr92546...\corerun.exe |   100 |     551.45 ns |     2.837 ns |     2.369 ns |     550.76 ns |     549.34 ns |     557.81 ns |  0.78 |    0.01 |         - |          NA |
|                                    |            |                         ...             |       |               |              |              |               |               |               |       |         |           |             |
|  TryGetValue_True_FrozenDictionary | Job-YITQJR |     \dotnet-runtime-main...\corerun.exe |  1000 |   8,292.91 ns |    17.361 ns |    14.497 ns |   8,291.58 ns |   8,268.44 ns |   8,318.85 ns |  1.00 |    0.00 |         - |          NA |
|  TryGetValue_True_FrozenDictionary | Job-LPACKA |  \dotnet-runtime-pr92546...\corerun.exe |  1000 |   8,503.81 ns |    87.401 ns |    81.755 ns |   8,447.35 ns |   8,421.88 ns |   8,625.60 ns |  1.02 |    0.01 |         - |          NA |
|                                    |            |                         ...             |       |               |              |              |               |               |               |       |         |           |             |
| TryGetValue_False_FrozenDictionary | Job-YITQJR |     \dotnet-runtime-main...\corerun.exe |  1000 |   7,807.82 ns |    48.572 ns |    43.058 ns |   7,796.98 ns |   7,765.43 ns |   7,910.40 ns |  1.00 |    0.00 |         - |          NA |
| TryGetValue_False_FrozenDictionary | Job-LPACKA |  \dotnet-runtime-pr92546...\corerun.exe |  1000 |   7,833.96 ns |     9.129 ns |     7.128 ns |   7,834.54 ns |   7,819.31 ns |   7,847.11 ns |  1.00 |    0.01 |         - |          NA |
|                                    |            |                         ...             |       |               |              |              |               |       [...]

2023-10-21 02:43 UTC, danmoseley commented
This seems like a good cost/benefit to me. (But I'm not area owner)

Should any of your tests go into dotnet/performance? We don't aim to be exhaustive there, so it would only be if there was a clear gap in coverage.

2023-10-21 10:29 UTC, andrewjsaid commented
>Should any of your tests go into dotnet/performance?

https://github.com/dotnet/performance/pull/3432/files#r1367705797

Added as a suggestion to @adamsitnik 's PR which importantly adds coverage for the `TryGetValue = false` scenario.

2023-10-21 11:04 UTC, andrewjsaid commented
One possible realistic scenario where this PR might come in useful is in [aspnetcore's DictionaryJumpTable.cs](https://github.com/dotnet/aspnetcore/blob/main/src/Http/Routing/src/Matching/DictionaryJumpTable.cs)

One can imagine some routes like the following
```
POST /api/orders/{id}/add/{item-id}
POST /api/orders/{id}/mark-as-deleted
POST /api/orders/{id}/reset
... (enough other endpoints to avoid `LinearSearchJumpTable`)
POST /api/orders/{id}/{item-id}/quantity
```

In the above example the frozen dictionary would contain `add`, `mark-as-deleted`, `reset` but potentially many requests would come in for `{item-id}`.
If `{item-id}` has a length which none of the other paths have, then the optimisation occurs.

I got the following results by constructing an example data showcasing the above
```
// * Summary *

BenchmarkDotNet v0.13.7-nightly.20230717.35, Windows 11 (10.0.22621.2428/22H2/2022Update/SunValley2)
AMD Ryzen 9 5950X, 1 CPU, 32 logical and 16 physical cores
.NET SDK 8.0.100-rc.1.23463.5
  [Host]     : .NET 8.0.0 (8.0.23.41904), X64 RyuJIT AVX2
  Job-YRQHWN : .NET 9.0.0 (42.42.42.42424), X64 RyuJIT AVX2
  Job-JIMCXL : .NET 9.0.0 (42.42.42.42424), X64 RyuJIT AVX2

PowerPlanMode=00000000-0000-0000-0000-000000000000  Arguments=/p:EnableUnsafeBinaryFormatterSerialization=true  IterationTime=250.0000 ms  
MaxIterationCount=20  MinIterationCount=15  WarmupCount=1  

|                             Method |        Job |                         ...   Toolchain | Count |     Mean |    Error |   StdDev |   Median |      Min |      Max | Ratio | Allocated | Alloc Ratio |
|----------------------------------- |----------- |-------------------------...------------ |------ |---------:|---------:|---------:|---------:|---------:|---------:|------:|----------:|------------:|
| TryGetValue_False_FrozenDictionary | Job-YRQHWN |    \dotnet-runtime-main\...\corerun.exe |    11 | 45.61 ns | 0.215 ns | 0.180 ns | 45.56 ns | 45.42 ns | 45.97 ns |  1.00 |         - |          NA |
| TryGetValue_False_FrozenDictionary | Job-JIMCXL | \dotnet-runtime-pr92546\...\corerun.exe |    11 | 11.68 ns | 0.142 ns | 0.133 ns | 11.65 ns | 11.45 ns | 11.89 ns |  0.26 |         - |          NA |
```

2023-10-21 14:43 UTC, danmoseley commented
Cc @BrennanConroy  for that.

2023-11-17 19:23 UTC, adamsitnik requested changes
Hi @andrewjsaid 

Thank you for applying my suggestion! I've re run all the frozen collection benchmarks we have with `--launchCount 3` argument (each benchmark run in 3 dedicated processes, helps to lower side effects of memory randomization and other similar factors).

## Perf_LengthBucketsFrozenDictionary

The `TryGetValue_True_FrozenDictionary` and `TryGetValue_False_FrozenDictionary` show no difference (ratio 1.00 or 0.99), which confirms that we can trust the results: there were no changes made to this particular code path and performance is the same.

But the creation of frozen dictionaries has regressed up to 7% for small inputs. I know that my suggestion is the reason for that.

<details>

```
BenchmarkDotNet v0.13.7-nightly.20230717.35, Windows 11 (10.0.22621.2715/22H2/2022Update/SunValley2)
AMD Ryzen Threadripper PRO 3945WX 12-Cores, 1 CPU, 24 logical and 12 physical cores
.NET SDK 9.0.100-alpha.1.23531.2
  [Host]     : .NET 8.0.0 (8.0.23.47906), X64 RyuJIT AVX2
          PR : .NET 9.0.0 (42.42.42.42424), X64 RyuJIT AVX2
        main : .NET 9.0.0 (42.42.42.42424), X64 RyuJIT AVX2

PowerPlanMode=00000000-0000-0000-0000-000000000000  Arguments=/p:EnableUnsafeBinaryFormatterSerialization=true  IterationTime=250.0000 ms  
LaunchCount=3  MaxIterationCount=20  MinIterationCount=15  
WarmupCount=1  
```
|                             Method |        Job | Count | ItemsPerBucket |          Mean | Ratio | Allocated |
|----------------------------------- |----------- |------ |--------------- |--------------:|------:|----------:|
|                 ToFrozenDictionary |         PR |    10 |              1 |     234.39 ns |  1.06 |     488 B |
|                 ToFrozenDictionary |       main |    10 |              1 |     220.88 ns |  1.00 |     488 B |
|                                    |            |       |                |               |       |           |
|  TryGetValue_True_FrozenDictionary |         PR |    10 |              1 |      22.31 ns |  1.00 |         - |
|  TryGetValue_True_FrozenDictionary |       main |    10 |              1 |      22.20 ns |  1.00 |         - |
|                                    |            |       |                |               |       |           |
| TryGetValue_False_FrozenDictionary |         PR |    10 |              1 |      12.49 ns |  1.00 |         - |
| TryGetValue_False_FrozenDictionary |       main |    10 |              1 |      12.49 ns |  1.00 |         - |
|                                    |            |       |                |               |       |           |
|                 ToFrozenDictionary |         PR |    10 |              5 |     231.01 ns |  1.02 |     328 B |
|                 ToFrozenDictionary |       main |    10 |              5 |     225.83 ns |  1.00 |     328 B |
|                                    |            |       |                |               |       |           |
|  TryGetValue_True_FrozenDictionary |         PR |    10 |              5 |      80.77 ns |  1.02 |         - |
|  TryGetValue_True_FrozenDictionary |       main |    10 |              5 |      78.98 ns |  1.00 |         - |
|                                    |            |       |                |               |       |           |
| TryGetValue_False_FrozenDictionary |         PR |    10 |              5 |      12.47 ns |  1.00 |         - |
| TryGetValue_False_FrozenDictionary |       main |    10 |              5 |      12.47 ns |  1.00 |         - |
|                                    |            |       |                |               |       |           |
|                 ToFrozenDictionary |         PR |   100 |              1 |   1,110.68 ns |  1.06 |    3728 B |
|                 ToFrozenDictionary |       main |   100 |              1 |   1,045.52 ns |  1.00 |    3728 B |
|                                    |            |       |                |               |       |           |
|  TryGetValue_True_FrozenDictionary |         PR |   100 |              1 |     206.33 ns |  1.00 |         - |
|  TryGetValue_True_FrozenDictionary |       main |   100 |              1 |     206.37 ns |  1.00 |         - |
|                                    |            |       |                |               |       |           |
| TryGetValue_False_FrozenDictionary |         PR |   100 |              1 |     102.75 ns |  1.00 |         - |
| TryGetValue_False_FrozenDictionary |       main |   100 |              1 |     102.44 ns |  1.00 |         - |
|                                    |            |       |                |               |       |           |
|                 ToFrozenDictionary |         PR |   100 |              5 |   1,131.40 ns |  1.07 |    2128 B |
|                 ToFrozenDictionary |       main |   100 |              5 |   1,055.68 ns |  1.00 |    2128 B |
|                                    |            |       |                |               |       |           |
|  TryGetValue_True_FrozenDictionary |         PR |   100 |              5 |     902.55 ns |  1.00 |         - |
|  TryGetValue_True_FrozenDictionary |       main |   100 |              5 |     903.75 ns |  1.00 |         - |
|                                    |            |       |                |               |       |           |
| TryGetValue_False_FrozenDictionary |         PR |   100 |              5 |     102.68 ns |  1.00 |         - |
| TryGetValue_False_FrozenDictionary |       main |   100 |              5 |     102.40 ns |  1.00 |         - |
|                                    |            |       |                |               |       |           |
|                 ToFrozenDictionary |         PR |  1000 |              1 |   9,514.12 ns |  1.04 |   36128 B |
|                 ToFrozenDictionary |       main |  1000 |              1 |   9,178.91 ns |  1.00 |   36128 B |
|                                    |            |       |                |               |       |           |
|  TryGetValue_True_FrozenDictionary |         PR |  1000 |              1 |   2,362.08 ns |  1.00 |         - |
|  TryGetValue_True_FrozenDictionary |       main |  1000 |              1 |   2,361.07 ns |  1.00 |         - |
|                                    |            |       |                |               |       |           |
| TryGetValue_False_FrozenDictionary |         PR |  1000 |              1 |   1,253.38 ns |  1.00 |         - |
| TryGetValue_False_FrozenDictionary |       main |  1000 |              1 |   1,251.53 ns |  1.00 |         - |
|                                    |            |       |                |               |       |           |
|                 ToFrozenDictionary |         PR |  1000 |              5 |   9,501.18 ns |  1.02 |   20128 B |
|                 ToFrozenDictionary |       main |  1000 |              5 |   9,360.78 ns |  1.00 |   20128 B |
|                                    |            |       |                |               |       |           |
|  TryGetValue_True_FrozenDictionary |         PR |  1000 |              5 |   8,324.55 ns |  1.00 |         - |
|  TryGetValue_True_FrozenDictionary |       main |  1000 |              5 |   8,301.55 ns |  1.00 |         - |
|                                    |            |       |                |               |       |           |
| TryGetValue_False_FrozenDictionary |         PR |  1000 |              5 |   1,172.01 ns |  1.00 |         - |
| TryGetValue_False_FrozenDictionary |       main |  1000 |              5 |   1,168.92 ns |  1.00 |         - |
|                                    |            |       |                |               |       |           |
|                 ToFrozenDictionary |         PR | 10000 |              1 | 239,837.56 ns |  0.99 |  360129 B |
|                 ToFrozenDictionary |       main | 10000 |              1 | 241,305.99 ns |  1.00 |  360129 B |
|                                    |            |       |                |               |       |           |
|  T [...]

2023-11-18 02:46 UTC, andrewjsaid commented
Thank you for your feedback. I take your point; with the minimal cost of hashing a single char or a few chars, there's not much benefit to be had from filtering early when a few instructions later we will be testing equality which early on compares string lengths anyway.

I've implemented the change to only apply when no hashable substring was found by KeyAnalyzer. Benchmark results below showing what you would expect. Luckily the concrete classes already had been optimized for customized codegen based on overridden methods Equals and GetHashCode.

### Perf_DefaultFrozenDictionary

Improvement has remained (~20% in the relevant case).

<details>

```
|                             Method |               Toolchain | Count |          Mean | Ratio | RatioSD |
|----------------------------------- |------------------------ |------ |--------------:|------:|--------:|
|  TryGetValue_True_FrozenDictionary |    \dotnet-runtime-main |    10 |      24.92 ns |  1.00 |    0.00 |
|  TryGetValue_True_FrozenDictionary | \dotnet-runtime-pr92546 |    10 |      24.93 ns |  1.00 |    0.02 |
|                                    |                         |       |               |       |         |
| TryGetValue_False_FrozenDictionary |    \dotnet-runtime-main |    10 |      22.50 ns |  1.00 |    0.00 |
| TryGetValue_False_FrozenDictionary | \dotnet-runtime-pr92546 |    10 |      21.87 ns |  0.97 |    0.05 |
|                                    |                         |       |               |       |         |
|  TryGetValue_True_FrozenDictionary |    \dotnet-runtime-main |   100 |     765.10 ns |  1.00 |    0.00 |
|  TryGetValue_True_FrozenDictionary | \dotnet-runtime-pr92546 |   100 |     775.43 ns |  1.01 |    0.02 |
|                                    |                         |       |               |       |         |
| TryGetValue_False_FrozenDictionary |    \dotnet-runtime-main |   100 |     667.79 ns |  1.00 |    0.00 |
| TryGetValue_False_FrozenDictionary | \dotnet-runtime-pr92546 |   100 |     539.15 ns |  0.81 |    0.02 |
|                                    |                         |       |               |       |         |
|  TryGetValue_True_FrozenDictionary |    \dotnet-runtime-main |  1000 |   8,060.49 ns |  1.00 |    0.00 |
|  TryGetValue_True_FrozenDictionary | \dotnet-runtime-pr92546 |  1000 |   8,062.08 ns |  1.00 |    0.02 |
|                                    |                         |       |               |       |         |
| TryGetValue_False_FrozenDictionary |    \dotnet-runtime-main |  1000 |   7,501.04 ns |  1.00 |    0.00 |
| TryGetValue_False_FrozenDictionary | \dotnet-runtime-pr92546 |  1000 |   7,542.41 ns |  1.01 |    0.01 |
|                                    |                         |       |               |       |         |
|  TryGetValue_True_FrozenDictionary |    \dotnet-runtime-main | 10000 | 162,555.61 ns |  1.00 |    0.00 |
|  TryGetValue_True_FrozenDictionary | \dotnet-runtime-pr92546 | 10000 | 165,447.62 ns |  1.02 |    0.01 |
|                                    |                         |       |               |       |         |
| TryGetValue_False_FrozenDictionary |    \dotnet-runtime-main | 10000 | 137,994.69 ns |  1.00 |    0.00 |
| TryGetValue_False_FrozenDictionary | \dotnet-runtime-pr92546 | 10000 | 138,603.15 ns |  1.00 |    0.02 |
```

</details>

### Perf_LengthBucketsFrozenDictionary

Still no change (just noise)

<details>

```
|                             Method |               Toolchain | Count | ItemsPerBucket |           Mean | Ratio | RatioSD |
|----------------------------------- |------------------------ |------ |--------------- |---------------:|------:|--------:|
|  TryGetValue_True_FrozenDictionary |    \dotnet-runtime-main |    10 |              1 |      17.022 ns |  1.00 |    0.00 |
|  TryGetValue_True_FrozenDictionary | \dotnet-runtime-pr92546 |    10 |              1 |      17.167 ns |  1.01 |    0.02 |
|                                    |                         |       |                |                |       |         |
| TryGetValue_False_FrozenDictionary |    \dotnet-runtime-main |    10 |              1 |       8.611 ns |  1.00 |    0.00 |
| TryGetValue_False_FrozenDictionary | \dotnet-runtime-pr92546 |    10 |              1 |       8.583 ns |  1.00 |    0.02 |
|                                    |                         |       |                |                |       |         |
|  TryGetValue_True_FrozenDictionary |    \dotnet-runtime-main |    10 |              5 |      56.041 ns |  1.00 |    0.00 |
|  TryGetValue_True_FrozenDictionary | \dotnet-runtime-pr92546 |    10 |              5 |      56.575 ns |  1.01 |    0.01 |
|                                    |                         |       |                |                |       |         |
| TryGetValue_False_FrozenDictionary |    \dotnet-runtime-main |    10 |              5 |       8.638 ns |  1.00 |    0.00 |
| TryGetValue_False_FrozenDictionary | \dotnet-runtime-pr92546 |    10 |              5 |       8.599 ns |  1.00 |    0.03 |
|                                    |                         |       |                |                |       |         |
|  TryGetValue_True_FrozenDictionary |    \dotnet-runtime-main |   100 |              1 |     156.655 ns |  1.00 |    0.00 |
|  TryGetValue_True_FrozenDictionary | \dotnet-runtime-pr92546 |   100 |              1 |     157.464 ns |  1.01 |    0.02 |
|                                    |                         |       |                |                |       |         |
| TryGetValue_False_FrozenDictionary |    \dotnet-runtime-main |   100 |              1 |      78.636 ns |  1.00 |    0.00 |
| TryGetValue_False_FrozenDictionary | \dotnet-runtime-pr92546 |   100 |              1 |      78.647 ns |  1.00 |    0.01 |
|                                    |                         |       |                |                |       |         |
|  TryGetValue_True_FrozenDictionary |    \dotnet-runtime-main |   100 |              5 |     652.883 ns |  1.00 |    0.00 |
|  TryGetValue_True_FrozenDictionary | \dotnet-runtime-pr92546 |   100 |              5 |     671.718 ns |  1.03 |    0.04 |
|                                    |                         |       |                |                |       |         |
| TryGetValue_False_FrozenDictionary |    \dotnet-runtime-main |   100 |              5 |      79.549 ns |  1.00 |    0.00 |
| TryGetValue_False_FrozenDictionary | \dotnet-runtime-pr92546 |   100 |              5 |      79.696 ns |  1.00 |    0.01 |
|                                    |                         |       |                |                |       |         |
|  TryGetValue_True_FrozenDictionary |    \dotnet-runtime-main |  1000 |              1 |   1,880.296 ns |  1.00 |    0.00 |
|  TryGetValue_True_FrozenDictionary | \dotnet-runtime-pr92546 |  1000 |              1 |   1,888.283 ns |  1.00 |    0.01 |
|                                    |                         |       |                |                |       |         |
| TryGetValue_False_FrozenDictionary |    \dotnet-runtime-main |  1000 |              1 |     919.183 ns |  1.00 |    0.00 |
| TryGetValue_False_FrozenDictionary | \dotnet-runtime-pr92546 |  1000 |              1 |     917.314 ns |  1.00 |    0.00 |
|                                    |                         |       |                |                |       |         |
|  TryGetValue_True_FrozenDictionary |    \dotnet-runtime-main |  1000 |              5 |   6,538.792 ns |  1.00 |    0.00 |
|  TryGetValue_True_FrozenDictionary | \dotnet-runtime-pr92546 |  1000 |              5 |   6,373.152 ns |  0.98 |    0.06 |
|                                    |                         |       |                |                |       |         |
| TryGetValue_False_FrozenDictionary |    \dotnet-runtime-main |  1000 |              5 |     824.639 ns |  1.00 |    0.00 |
| TryGetValue_False_FrozenDictionary | \dotnet-runtime-pr92546 | [...]

2023-12-11 08:54 UTC, adamsitnik approved these changes
LGTM, big thanks for your contribution @andrewjsaid !

2023-12-11 08:56 UTC, merged