[linux-bionic] Skip failing NTLM tests
dotnet/runtime pull request #92830
Opened 2023-09-29 18:45 UTC by steveisok

Some NTLM tests are still running and failing even though libSystem.Net.Security.Native isn't being built for linux-bionic. This PR skips them all.

2023-09-29 18:46 UTC, steveisok commented
/azp run runtime-linuxbionic

2023-09-29 20:13 UTC, wfurt commented
should we include the managed implementation? That should just work without GSSAP AFAIK.
cc: @filipnavara

2023-09-29 20:34 UTC, steveisok commented
> should we include the managed implementation? That should just work without GSSAP AFAIK. cc: @filipnavara

Ah, yes, I think we should.

2023-09-29 21:52 UTC, filipnavara commented
We should but there was not any product-level check that we are running on linux-bionic.

2023-09-29 23:14 UTC, am11 commented
> We should but there was not any product-level check that we are running on linux-bionic.

It is possible to test:
```c#
if (RuntimeInformation.RuntimeIdentifier.StartsWith("linux-bionic")) ForBionic();
else if (RuntimeInformation.RuntimeIdentifier.StartsWith("linux-musl")) ForMusl();
else ForGlibC();
```

2023-09-30 18:17 UTC, filipnavara commented
> It is possible to test:

Hmm. I though there's a reason why the [test check](https://github.com/dotnet/runtime/blob/8dad137b7a51adba94c7224768a4c5c76b017f4d/src/libraries/Common/tests/TestUtilities/System/PlatformDetection.Unix.cs#L171-L184) is implemented differently. If `RuntimeInformation.RuntimeIdentifier` returns the correct information then we likely just need to modify this condition:

https://github.com/dotnet/runtime/blob/8dad137b7a51adba94c7224768a4c5c76b017f4d/src/libraries/System.Net.Security/src/System/Net/NegotiateAuthenticationPal.Unix.cs#L25

and add `|| (OperationSystem.IsLinux() && RuntimeInformation.RuntimeIdentifier.StartsWith("linux-bionic")`.

2023-11-03 08:12 UTC, adamsitnik requested changes
Please solve the merge conflict.

I am requesting changes mostly so this PR does not show up at the next Stale PRs email ;)

2023-11-06 14:51 UTC, steveisok commented
For whatever reason, this doesn't appear to be failing in CI any longer.

2023-11-06 14:51 UTC, closed without merging