[MT][browser] Allow CI failures on library MT tests
dotnet/runtime pull request #93224
Opened 2023-10-09 14:17 UTC by ilonatommy

- We were planning to switch off `shouldContinueOnError` after a few weeks from merging https://github.com/dotnet/runtime/pull/91536 if it will not be failing after disabling.
- Fixing ```fail: [out of order message from the browser]: http://127.0.0.1:33323/_framework/dotnet.js 2 WebSocket connection to 'ws://127.0.0.1:33323/_framework/dotnet.native.worker.js/console' failed: Error during WebSocket handshake: Unexpected response code: 404``` [log](https://helixre107v0xdcypoyl9e7f.blob.core.windows.net/dotnet-runtime-refs-pull-92226-merge-a992e6d52f8f410ebe/WasmTestOnBrowser-System.Transactions.Local.Tests/1/console.cec4fb69.log?helixlogtype=result)

2023-10-09 14:18 UTC, pavelsavara commented
/azp run runtime-wasm

2023-10-09 15:49 UTC, radical commented
How often has this run recently, and how often has it failed?

2023-10-09 15:54 UTC, pavelsavara commented
> How often has this run recently, and how often has it failed?

It failed "silently" for me. I have not noticed that there is "organge" lane. I want it to really fail when I do `/azp run runtime-wasm`

2023-10-09 15:57 UTC, radical commented
'runtime-wasm' will be red then.

2023-10-09 15:59 UTC, pavelsavara commented
> 'runtime-wasm' will be red then.

Right, that's what we want to anything that was not already marked active issue by Ilona in https://github.com/dotnet/runtime/pull/91536.

Am I missing something ?

2023-10-09 17:01 UTC, radical commented
> > 'runtime-wasm' will be red then.
> 
> 
> 
> Right, that's what we want to anything that was not already marked active issue by Ilona in https://github.com/dotnet/runtime/pull/91536.
> 
> 
> 
> Am I missing something ?

Has the job been green for few weeks when there were no PR introduced mt failures? That's what I'm talking about. It shouldn't randomly fail, else we would start getting merges on red and failures getting ignored because users aren't sure whether the failures are expected. A red pipeline on PRs that did not introduce mt failures would be counterproductive.

2023-10-09 17:02 UTC, radical commented
> This PR needs adding a blocking for `Wasm.Browser.Threads.Minimal.Sample` and `Microsoft.Extensions.DependencyInjection.Tests`, they might have been overlooked in the big blocking PR (I will add it). Beyond that, nothing else failed. If a new failure will arise, we will at least notice it thanks to this change.

Then it hasn't been green/stable for few weeks.

2023-10-09 18:16 UTC, ilonatommy commented
/azp run runtime-wasm

2023-10-09 18:21 UTC, ilonatommy commented on src/libraries/tests.proj
> +
Whitespace (when the CI finishes).

2023-10-09 18:23 UTC, radical requested changes
Please don't merge this yet. We should have couple of weeks worth of builds where the job has been green, before we merge.

2023-10-09 18:27 UTC, ilonatommy commented on eng/pipelines/extra-platforms/runtime-extra-platforms-wasm.yml
> -      shouldContinueOnError: true
To be reverted because not 100% of tests were disabled.

2023-10-10 09:06 UTC, ilonatommy commented
/azp run runtime-wasm

2023-10-10 09:23 UTC, pavelsavara commented
> Please don't merge this yet. We should have couple of weeks worth of builds where the job has been green, before we merge.

In that case we need to make the test run much more often. What we have now is useless waiting without any observability. Do you have any proposal @radical  ?

2023-10-11 16:36 UTC, radical commented
> > Please don't merge this yet. We should have couple of weeks worth of builds where the job has been green, before we merge.
> 
> In that case we need to make the test run much more often. What we have now is useless waiting without any observability. Do you have any proposal @radical ?

The test failures are observable, just that they won't show up as failures in github. Open the azdo build and you can see the failures, and all the details.

2023-10-11 16:51 UTC, ilonatommy commented
Let's merge at least these fixes for now. Failures are unrelated.

2023-10-11 16:54 UTC, radical commented
> Let's merge at least these fixes for now.

👍 Please update the PR title, and description to match.

2023-10-11 16:55 UTC, radical commented
Also, please open an issue for the error that is unrelated, and isn't being flagged by `build analysis`.

2023-10-11 17:11 UTC, radical approved these changes

2023-10-11 17:24 UTC, merged