[wasm] Disable failing runtime tests
dotnet/runtime pull request #93712
Opened 2023-10-19 07:06 UTC by radical

2023-10-19 21:03 UTC, radical commented
@jkoritzinsky @trylek IIUC, excluding tests uses the paths specified in `issues.targets`. For a test like `Interop/PInvoke/Vector2_3_4`, a `BasicTestMethod` is used which uses the full method name to the filter's `ShouldRunTest`, and that won't match the path from `issues.targets`. If that is correct, then what is the recommended way of excluding such tests?
I see there is support for a dotnet-test like filter expression, but is that for manual runs?

There are existing exclusions for this like https://github.com/dotnet/runtime/blob/a40db0207101780e6b8d5ad261428d8d954f6df2/src/tests/issues.targets#L2630-L2632

.. but these do not work any more, AFAIU!

2023-10-19 21:05 UTC, radical commented
cc @lewing

2023-10-19 21:50 UTC, jkoritzinsky requested changes
Please use the `PlatformSpecific` attribute or one of the other xunit/XunitExtensions attributes instead of issues.targets for merged tests like this.

2023-10-20 00:12 UTC, jkoritzinsky approved these changes
We should probably also disable these tests on the mobile platforms (all xharness platforms currently have the same infra limitations).

2023-10-20 00:18 UTC, radical commented
> We should probably also disable these tests on the mobile platforms (all xharness platforms currently have the same infra limitations).

@steveisok @SamMonoRT do you know if these tests fail for ios, and other platforms? Look for `Interop/PInvoke/Vector2_3_4/Vector2_3_4/**` in `src/tests/issues.targets`, it is disabled for a few combinations.
If these tests are not failing on those platforms, then we can simply remove the exclusion. If they are failing, then we can add to the `ActiveIssue` for these.

This can be done in a follow up PR.

2023-10-20 04:17 UTC, merged