Remove Explicit Deletion of CMake `/GR` Flag as 3.20's *CMP0117* by Default Doesn't Add It
dotnet/runtime pull request #96814
Opened 2024-01-10 21:45 UTC by ivdiazsa

Completes #94354. CMake Version 3.20+ implements a new version of Policy CMP0117. This new version does not add the `/GR` flag by default to `CMAKE_CXX_FLAGS`. And this is the behavior we want. However, previous versions of CMake did add it, so we had to manually remove it. This PR removes that deletion as part of the efforts to simplify our CMake build in general.

2024-01-16 22:18 UTC, ivdiazsa commented on src/coreclr/CMakeLists.txt
> +cmake_policy(SET CMP0117 NEW)
The Ninja files were the same, so indeed not specifying = set by default. I've sent a new commit with the change removing it.

2024-01-16 22:43 UTC, jkoritzinsky requested changes

2024-01-16 22:43 UTC, jkoritzinsky commented on eng/native/configurecompiler.cmake
> -  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /GR-")
We still want to add `/GR-` as the default is equivalent to specifying `/GR` (which is what prompted the CMake policy).

2024-01-16 23:47 UTC, jkoritzinsky commented on eng/native/configurecompiler.cmake
> -  # disable C++ RTTI
Let's keep this comment

2024-01-16 23:47 UTC, jkoritzinsky approved these changes
LGTM with one nit

2024-01-17 23:22 UTC, ivdiazsa commented
Failure is unrelated and is being tracked in issue #97103, so we can merge this now.

2024-01-17 23:22 UTC, merged