Remove helperframe marshal
dotnet/runtime pull request #96860
Opened 2024-01-11 20:12 UTC by AaronRobinsonMSFT

Convert `Marshal` API FCalls with `HelperMethodFrames` into QCalls.

2024-01-11 21:31 UTC, davidwrighton requested changes
OffsetOfInternal shouldn't take a field object, it should just be implemented as taking a FieldDesc* as input. Then it won't need anything to do with wonking around with the GC state at all, and can operate entirely in preemptive mode

2024-01-11 22:01 UTC, AaronRobinsonMSFT commented
> OffsetOfInternal shouldn't take a field object, it should just be implemented as taking a FieldDesc* as input. Then it won't need anything to do with wonking around with the GC state at all, and can operate entirely in preemptive mode

@davidwrighton Done.

2024-01-11 22:17 UTC, jkotas commented on src/coreclr/System.Private.CoreLib/src/System/Runtime/InteropServices/Marshal.CoreCLR.cs
> +        private static partial nint OffsetOfInternal(IntPtr pFD);
```suggestion
        private static partial nint OffsetOf(IntPtr pFD);
```
Nit: The internal suffix is not necessary. The signature is sufficient to make the internal entrypoint distinct.

2024-01-11 22:18 UTC, jkotas commented on src/coreclr/System.Private.CoreLib/src/System/Runtime/InteropServices/Marshal.CoreCLR.cs
> +        private static partial void GetExceptionForHRWorker(int errorCode, IntPtr errorInfo, ObjectHandleOnStack exception);
Similar here: it can be `GetExceptionForHRInternal`

2024-01-11 22:20 UTC, jkotas commented on src/coreclr/vm/marshalnative.cpp
> +    GCPROTECT_END();
```suggestion
    hr = SetupErrorInfo(obj.Get());
```
GCPROTECT is unnecessary

2024-01-11 23:17 UTC, davidwrighton approved these changes
Just one more nit... around unnecessary GCX_PREEMP();

2024-01-11 23:17 UTC, davidwrighton commented on src/coreclr/vm/marshalnative.cpp
>          GCX_PREEMP();
You shouldn't need GCX_PREEMP() here. QCalls are preemptible code.

2024-01-11 23:20 UTC, elinor-fung approved these changes

2024-01-12 01:40 UTC, jkotas commented on src/coreclr/System.Private.CoreLib/src/System/Runtime/InteropServices/Marshal.CoreCLR.cs
> +        private static partial int GetHRForExceptionInternal(ObjectHandleOnStack exception);
```suggestion
            => GetHRForException(ObjectHandleOnStack.Create(ref e));

        [LibraryImport(RuntimeHelpers.QCall, EntryPoint = "MarshalNative_GetHRForException")]
        private static partial int GetHRForException(ObjectHandleOnStack exception);
```

2024-01-12 01:42 UTC, jkotas commented on src/coreclr/vm/marshalnative.cpp
>              StackSString strTypeName;
```suggestion
            SString strTypeName;
```
We do not need stack-allocated buffer for exception throwing.

2024-01-12 01:44 UTC, jkotas approved these changes
LGTM. Thanks!

2024-01-12 04:41 UTC, merged