Provide System.IO.Pipelines package readme
dotnet/runtime pull request #99666
Opened 2024-03-13 05:38 UTC by eNeRGy164

Fill out details for the `System.IO.Pipelines` NuGet package readme.

See #99358

2024-03-20 09:21 UTC, ViktorHofer commented
ping @adityamandaleeka @davidfowl @halter73

2024-04-15 16:07 UTC, ViktorHofer commented
@adityamandaleeka @davidfowl @halter73 please review the package readme changes

2024-05-06 16:55 UTC, adityamandaleeka approved these changes

2024-05-06 16:55 UTC, adityamandaleeka commented
Sorry I missed this earlier. Thanks @eNeRGy164

2024-05-06 16:59 UTC, adityamandaleeka commented on src/libraries/System.IO.Pipelines/src/PACKAGE.md
> +```csharp
Actually, can we please remove the sample code from here and instead just link to the docs, which have samples already? Trying to keep the number of samples in different places down.

2024-05-06 16:59 UTC, adityamandaleeka requested changes
Please remove the sample code from here

2024-05-09 20:59 UTC, adityamandaleeka approved these changes

2024-05-10 06:06 UTC, merged